/**
 * Region 12 — こころの谷, the Valley of Hearts. A valley village in autumn,
 * getting ready for its kagura festival, where masked dancers act out the
 * old tales. The dragon's hunger is eating the valley's feelings: every
 * face has frozen like a Noh mask, nobody can say how they feel, friends
 * quarrel and can't make up, and the dancers can't put feeling into the
 * masks. The last stop before the Tower.
 *
 * Words: feeling words, feeling verbs, nouns of the heart, the sound-
 * feelings (ドキドキ, わくわく…) and the little reactions of real talk
 * (よかった, まさか, うそ…). Grammar: the cause of a feeling (〜て), reading
 * other people (〜そう, 〜がる, 〜みたい), wishes and regrets (〜てほしい,
 * 〜てしまった, 〜のに, 〜ばよかった) and thanks (〜てくれて ありがとう).
 */
import type { RegionData } from '../types'

export const DATA: RegionData = {
  region: {
    id: 12,
    name: 'The Valley of Hearts',
    jp: 'こころの谷',
    reading: 'こころのたに',
    tagline: 'Every face has frozen. Name the feeling, and it thaws.',
    teaches: ['Feeling words and sound-feelings (ドキドキ, わくわく)', 'Why you feel: 〜て, 〜のに, 〜てよかった, 〜ばよかった', 'Reading others: 〜そう, 〜がる, 〜みたい'],
    color: '#f2789f',
    emoji: '🎭',
    pos: { x: 30, y: 18 },
    map: 'kokoro',
  },

  words: [
    // ── How It Feels: feeling words
    ['shiawase', '幸せ', 'しあわせ', 'happiness', 'na-adj', '🍀', { alt: ['happy', 'blessed', 'fortunate', 'happy (deep down)'] }],
    ['hazukashii', '恥ずかしい', 'はずかしい', 'embarrassed', 'i-adj', '😳', { alt: ['embarrassing', 'shy', 'ashamed'] }],
    ['kuyashii', '悔しい', 'くやしい', 'frustrated', 'i-adj', '😤', { alt: ['vexed', 'mortified', 'galling', 'bitter (at losing)'] }],
    ['natsukashii', '懐かしい', 'なつかしい', 'nostalgic', 'i-adj', '📼', { alt: ['dear old', 'fondly remembered', 'bittersweet', 'brings back memories'] }],
    ['urayamashii', '羨ましい', 'うらやましい', 'envious', 'i-adj', '👀', { alt: ['jealous', 'enviable'] }],
    ['iya', '嫌', 'いや', 'unpleasant', 'na-adj', '🙅‍♀️', { alt: ['disagreeable', 'hateful', 'no way', 'I don’t want to'] }],
    ['shinpai', '心配', 'しんぱい', 'worry', 'na-adj', '😟', { alt: ['worried', 'concern', 'anxiety (worry)'] }],
    ['anshin', '安心', 'あんしん', 'relief', 'na-adj', '😌', { alt: ['peace of mind', 'reassured', 'feeling safe'] }],
    ['zannen', '残念', 'ざんねん', 'too bad', 'na-adj', '😞', { alt: ['a pity', 'what a shame', 'disappointing', 'regrettable'] }],
    ['fuan', '不安', 'ふあん', 'uneasy', 'na-adj', '😰', { alt: ['anxious', 'anxiety', 'insecure', 'uneasiness'] }],
    ['taikutsu', '退屈', 'たいくつ', 'bored', 'na-adj', '🥱', { alt: ['boring', 'boredom', 'dull'] }],
    ['kawaisou', '可哀想', 'かわいそう', 'poor thing', 'na-adj', '😿', { alt: ['pitiful', 'pitiable', 'pitiful (poor thing)'] }],
    ['subarashii', '素晴らしい', 'すばらしい', 'wonderful', 'i-adj', '🌟', { alt: ['splendid', 'magnificent', 'marvellous', 'marvelous'] }],
    ['sugoi', 'すごい', 'すごい', 'amazing', 'i-adj', '🤩', { alt: ['great', 'incredible', 'awesome', 'terrific'] }],
    ['hidoi', 'ひどい', 'ひどい', 'terrible', 'i-adj', '💢', { alt: ['awful', 'cruel', 'harsh', 'mean'] }],

    // ── Laughing and Crying: feeling verbs
    ['warau', '笑う', 'わらう', 'laugh', 'verb', '😆', { masu: '笑います', alt: ['to laugh', 'smile', 'to smile'] }],
    ['naku', '泣く', 'なく', 'cry', 'verb', '😭', { masu: '泣きます', alt: ['to cry', 'weep', 'to weep'] }],
    ['okoru', '怒る', 'おこる', 'get angry', 'verb', '😠', { masu: '怒ります', alt: ['to get angry', 'be angry', 'get mad', 'to be angry'] }],
    ['odoroku', '驚く', 'おどろく', 'be surprised', 'verb', '😲', { masu: '驚きます', alt: ['to be surprised', 'be amazed', 'be startled'] }],
    ['yorokobu', '喜ぶ', 'よろこぶ', 'be delighted', 'verb', '🥳', { masu: '喜びます', alt: ['to be delighted', 'rejoice', 'be glad', 'to rejoice'] }],
    ['komaru', '困る', 'こまる', 'be troubled', 'verb', '😥', { masu: '困ります', alt: ['to be troubled', 'be in trouble', 'be at a loss', 'be stuck'] }],
    ['kinchou-suru', '緊張する', 'きんちょうする', 'get nervous', 'verb', '😬', { masu: '緊張します', alt: ['to get nervous', 'be nervous', 'be tense'] }],
    ['kandou-suru', '感動する', 'かんどうする', 'be moved', 'verb', '🥹', { masu: '感動します', alt: ['to be moved', 'be touched', 'be deeply moved'] }],
    ['ochikomu', '落ち込む', 'おちこむ', 'feel down', 'verb', '😔', { masu: '落ち込みます', alt: ['to feel down', 'be depressed', 'be down', 'get depressed'] }],
    ['ayamaru', '謝る', 'あやまる', 'apologise', 'verb', '🙇', { masu: '謝ります', alt: ['to apologise', 'apologize', 'to apologize', 'say sorry'] }],
    ['yurusu', '許す', 'ゆるす', 'forgive', 'verb', '🕊️', { masu: '許します', alt: ['to forgive', 'pardon'] }],
    ['nagusameru', '慰める', 'なぐさめる', 'comfort', 'verb', '🫂', { masu: '慰めます', alt: ['to comfort', 'console', 'to console'] }],
    ['hagemasu', '励ます', 'はげます', 'encourage', 'verb', '📣', { masu: '励まします', alt: ['to encourage', 'cheer up (someone)', 'buoy up'] }],
    ['gaman-suru', '我慢する', 'がまんする', 'put up with', 'verb', '🤐', { masu: '我慢します', alt: ['to put up with', 'endure', 'hold back', 'bear it', 'be patient'] }],
    ['ouen-suru', '応援する', 'おうえんする', 'cheer for', 'verb', '🙌', { masu: '応援します', alt: ['to cheer for', 'support', 'root for', 'to support'] }],

    // ── Things of the Heart: nouns
    ['namida', '涙', 'なみだ', 'tears', 'noun', '🥲', { alt: ['tear', 'teardrop'] }],
    ['egao', '笑顔', 'えがお', 'smile', 'noun', '☺️', { alt: ['smiling face', 'a smile'] }],
    ['ai', '愛', 'あい', 'love', 'noun', '❤️', { alt: ['affection'] }],
    ['koi', '恋', 'こい', 'romantic love', 'noun', '💘', { alt: ['love (romantic)', 'being in love', 'a crush', 'crush'] }],
    ['kenka', '喧嘩', 'けんか', 'quarrel', 'noun', '🥊', { alt: ['fight', 'argument', 'squabble'] }],
    ['nakanaori', '仲直り', 'なかなおり', 'making up', 'noun', '🤝', { alt: ['make up', 'reconciliation', 'making peace'] }],
    ['kansha', '感謝', 'かんしゃ', 'gratitude', 'noun', '💐', { alt: ['thanks', 'appreciation', 'thankfulness'] }],
    ['kitai', '期待', 'きたい', 'expectation', 'noun', '🌠', { alt: ['hope', 'expectations', 'high hopes'] }],
    ['koukai', '後悔', 'こうかい', 'regret', 'noun', '😩', { alt: ['remorse', 'regrets'] }],
    ['himitsu', '秘密', 'ひみつ', 'secret', 'noun', '🤫', { alt: ['a secret'] }],
    ['jishin', '自信', 'じしん', 'confidence', 'noun', '😎', { alt: ['self-confidence', 'self-belief'] }],
    ['ikari', '怒り', 'いかり', 'anger', 'noun', '🌋', { alt: ['rage', 'fury', 'wrath'] }],
    ['tanoshimi', '楽しみ', 'たのしみ', 'something to look forward to', 'noun', '🎁', { alt: ['looking forward to', 'can’t wait', 'pleasure', 'anticipation'] }],
    ['omoiyari', '思いやり', 'おもいやり', 'kindness', 'noun', '💞', { alt: ['consideration', 'compassion', 'thoughtfulness'] }],
    ['kibun', '気分', 'きぶん', 'mood', 'noun', '🌡️', { alt: ['feeling', 'how one feels', 'spirits'] }],

    // ── Sound-Feelings: onomatopoeia of the heart
    ['dokidoki', 'ドキドキ', 'どきどき', 'heart pounding', 'adverb', '💓', { alt: ['pounding heart', 'heart racing', 'thump-thump', 'nervous'] }],
    ['wakuwaku', 'わくわく', 'わくわく', 'excited', 'adverb', '🎆', { alt: ['thrilled', 'excitedly', 'tingling with excitement'] }],
    ['iraira', 'イライラ', 'いらいら', 'irritated', 'adverb', '😾', { alt: ['annoyed', 'irritation', 'on edge'] }],
    ['nikoniko', 'ニコニコ', 'にこにこ', 'smiling', 'adverb', '😁', { alt: ['beaming', 'all smiles', 'smiling happily'] }],
    ['niyaniya', 'にやにや', 'にやにや', 'smirking', 'adverb', '😏', { alt: ['grinning slyly', 'smirk', 'sly grin'] }],
    ['shikushiku', 'しくしく', 'しくしく', 'sobbing quietly', 'adverb', '🥀', { alt: ['sniffling', 'weeping softly', 'sobbing'] }],
    ['mesomeso', 'めそめそ', 'めそめそ', 'whimpering', 'adverb', '☔', { alt: ['snivelling', 'sniveling', 'weepy', 'whiny crying'] }],
    ['gakkari', 'がっかり', 'がっかり', 'disappointed', 'adverb', '🫠', { alt: ['let down', 'disheartened', 'disappointment'] }],
    ['hotto', 'ほっと', 'ほっと', 'relieved', 'adverb', '😮‍💨', { alt: ['with a sigh of relief', 'phew', 'feeling relieved'] }],
    ['bikkuri', 'びっくり', 'びっくり', 'startled', 'adverb', '😱', { alt: ['surprised', 'shocked', 'taken aback'] }],
    ['ukiuki', 'うきうき', 'うきうき', 'cheerful', 'adverb', '🎈', { alt: ['buoyant', 'in high spirits', 'light-hearted'] }],
    ['moyamoya', 'もやもや', 'もやもや', 'vague unease', 'adverb', '😶‍🌫️', { alt: ['unsettled', 'murky feeling', 'foggy feeling', 'gloomy'] }],
    ['zotto', 'ぞっと', 'ぞっと', 'shivers', 'adverb', '🥶', { alt: ['chills', 'a shiver', 'shudder', 'creeped out'] }],
    ['punpun', 'ぷんぷん', 'ぷんぷん', 'in a huff', 'adverb', '😡', { alt: ['huffy', 'fuming', 'pouting angrily'] }],
    ['sowasowa', 'そわそわ', 'そわそわ', 'restless', 'adverb', '🐜', { alt: ['fidgety', 'jittery', 'can’t sit still'] }],

    // ── Real Reactions: what people really say
    ['yokatta', 'よかった', 'よかった', 'thank goodness', 'expression', '😅', { alt: ['I’m glad', 'that’s good', 'what a relief', 'phew, good'] }],
    ['saikou', '最高', 'さいこう', 'the best', 'na-adj', '🏆', { alt: ['best', 'awesome', 'supreme'] }],
    ['saiaku', '最悪', 'さいあく', 'the worst', 'na-adj', '👎', { alt: ['worst', 'awful (the worst)'] }],
    ['taihen', '大変', 'たいへん', 'tough', 'na-adj', '😵', { alt: ['hard', 'difficult', 'serious', 'a big deal', 'very'] }],
    ['mendoukusai', '面倒くさい', 'めんどうくさい', 'what a hassle', 'i-adj', '🙄', { alt: ['bothersome', 'a pain', 'tedious', 'troublesome'] }],
    ['heiki', '平気', 'へいき', 'fine', 'na-adj', '👌', { alt: ['okay', 'all right', 'unbothered', 'no problem'] }],
    ['kawaii', '可愛い', 'かわいい', 'cute', 'i-adj', '🐣', { alt: ['adorable', 'sweet', 'lovely'] }],
    ['ki-ni-naru', '気になる', 'きになる', 'be on one’s mind', 'verb', '🧐', { masu: '気になります', alt: ['to be curious', 'be curious about', 'bother', 'weigh on one’s mind'] }],
    ['ki-wo-tsukeru', '気をつける', 'きをつける', 'be careful', 'verb', '⚠️', { masu: '気をつけます', alt: ['to be careful', 'take care', 'watch out'] }],
    ['omedetou', 'おめでとう', 'おめでとう', 'congratulations', 'expression', '🎊', { alt: ['congrats', 'well done'] }],
    ['uso', 'うそ', 'うそ', 'lie', 'noun', '🤥', { alt: ['a lie', 'no way', 'you’re kidding', 'untruth'] }],
    ['masaka', 'まさか', 'まさか', 'no way', 'expression', '😮', { alt: ['surely not', 'it can’t be', 'impossible'] }],
    ['honki', '本気', 'ほんき', 'serious', 'na-adj', '🎯', { alt: ['for real', 'in earnest', 'seriousness'] }],
    ['tereru', '照れる', 'てれる', 'be bashful', 'verb', '🫣', { masu: '照れます', alt: ['to be bashful', 'be shy', 'blush', 'get embarrassed'] }],
    ['raku', '楽', 'らく', 'easy', 'na-adj', '🛋️', { alt: ['comfortable', 'relaxed', 'at ease'] }],
  ],

  grammar: [
    { id: 'te-feeling', region: 12, jp: '〜て／〜くて ＋ きもち', say: 'te / kute + feeling', en: 'the cause of a feeling: て-form (verbs, な-words) or 〜くて (い-adjectives), then how you feel', example: { jp: 'また 会えて うれしい！', en: 'I’m so happy to see you again!' } },
    { id: 'feeling-ga', region: 12, jp: 'わたしは 〜が こわい', say: 'ga + feeling', en: 'feelings take が for what you feel about (〜が すき, 〜が こわい); say your own feelings straight out, but other people’s with 〜そう, 〜がる or 〜みたい', example: { jp: 'わたしは かみなりが こわい。でも、ホタルは こわがって いない。', en: 'I’m scared of thunder. But Hotaru isn’t scared.' } },
    { id: 'sou-looks', region: 12, jp: '〜そう', say: 'sō', en: 'looks ~ (from what you see): drop い or な and add そう (かなしい → かなしそう, げんき → げんきそう, いい → よさそう)', example: { jp: 'レンさんは かなしそうです。', en: 'Ren looks sad.' } },
    { id: 'garu', region: 12, jp: '〜がる', say: 'garu', en: 'someone else shows a feeling: い-adjective stem + がる, usually as がって いる (こわい → こわがる, ほしい → ほしがる)', example: { jp: 'こどもは おにの めんを こわがって います。', en: 'The child is scared of the demon mask.' } },
    { id: 'mitai', region: 12, jp: '〜みたい', say: 'mitai', en: 'seems like ~ (from what you see or hear): plain form or noun + みたい', example: { jp: 'ホタルちゃん、ねむい みたい。', en: 'Hotaru seems sleepy.' } },
    { id: 'tagaru', region: 12, jp: '〜たがる', say: 'tagaru', en: 'someone else wants to ~: ます-stem + たがる (いく → いきたがる), usually as たがって いる', example: { jp: 'タロウくんは まつりに 行きたがって います。', en: 'Taro is dying to go to the festival.' } },
    { id: 'te-hoshii', region: 12, jp: '〜てほしい', say: 'te hoshii', en: 'I want you (someone else) to ~: て-form + ほしい', example: { jp: 'まつりで おどって ほしい。', en: 'I want you to dance at the festival.' } },
    { id: 'ki-ga-suru', region: 12, jp: '〜ような 気が する', say: 'yō na ki ga suru', en: 'I have a feeling that ~: plain form + ような 気が する', example: { jp: 'だれかが ないて いる ような 気が する。', en: 'I have a feeling someone is crying.' } },
    { id: 'te-shimatta', region: 12, jp: '〜てしまった', say: 'te shimatta', en: 'did ~ and wish you hadn’t, or “oops”: て-form + しまった', example: { jp: 'めんを わって しまった…', en: 'Oh no, I broke the mask…' } },
    { id: 'noni', region: 12, jp: '〜のに', say: 'noni', en: 'even though ~ (disappointment, frustration): plain form + のに (な-words and nouns: 〜なのに)', example: { jp: 'れんしゅうしたのに、まけた。', en: 'Even though I practised, I lost.' } },
    { id: 'ba-yokatta', region: 12, jp: '〜ば よかった', say: 'ba yokatta', en: 'I wish I had ~ (regret): ば-form + よかった', example: { jp: 'もっと はやく あやまれば よかった。', en: 'I wish I had apologised sooner.' } },
    { id: 'te-yokatta', region: 12, jp: '〜て よかった', say: 'te yokatta', en: 'I’m glad that ~ (relief, gladness): て-form + よかった', example: { jp: 'この 谷に 来て よかった。', en: 'I’m glad I came to this valley.' } },
    { id: 'nante', region: 12, jp: '〜なんて', say: 'nante', en: 'surprise or disbelief, “to think that ~!” (also “something like ~”): plain form + なんて', example: { jp: 'はんにゃが ないて いる なんて…', en: 'To think that Hannya is crying…' } },
    { id: 'te-kurete-arigatou', region: 12, jp: '〜てくれて ありがとう', say: 'te kurete arigatō', en: 'thank you for ~ (doing something for me): て-form + くれて ありがとう', example: { jp: 'たすけて くれて ありがとう。', en: 'Thank you for helping me.' } },
  ],

  sentences: [
    { id: 'kk1', en: 'I’m glad I could meet you.', tokens: ['あなた', 'に', '会えて', 'うれしい', 'です'], distractors: ['を', '会う'], region: 12, hint: 'The cause of the feeling comes first, in て-form: 会えて (being able to meet) → うれしい.' },
    { id: 'kk2', en: 'Ren looks sad today.', tokens: ['レン', 'さん', 'は', '今日', '悲しそう', 'です'], distractors: ['悲しい', 'を'], region: 12, hint: 'For someone else’s feeling, say how they look: 悲しい → 悲しそう.' },
    { id: 'kk3', en: 'The child is scared of the demon mask.', tokens: ['子ども', 'は', '鬼', 'の', '面', 'を', '怖がって', 'います'], distractors: ['が', '怖い'], region: 12, hint: 'Someone else’s fear: 怖がって います, and the thing they fear takes を.' },
    { id: 'kk4', en: 'I want you to dance at the festival.', tokens: ['祭り', 'で', '踊って', 'ほしい'], distractors: ['を', '踊りたい'], region: 12, hint: 'て-form + ほしい: I want *you* to do it. 踊りたい would be “I want to dance”.' },
    { id: 'kk5', en: 'I have a feeling it will rain tomorrow.', tokens: ['明日', 'は', '雨', 'が', '降る', 'ような', '気が', 'します'], distractors: ['降って', 'を'], region: 12, hint: 'Plain form + ような 気が します: 降る ような 気が します.' },
    { id: 'kk6', en: 'Oh no, I broke the mask.', tokens: ['面', 'を', '割って', 'しまった'], distractors: ['が', '割った'], region: 12, hint: 'て-form + しまった for something you wish hadn’t happened: 割って しまった.' },
    { id: 'kk7', en: 'Even though I practised, I lost.', tokens: ['練習した', 'のに', '負けた'], distractors: ['から', 'ので'], region: 12, hint: 'のに joins two things that clash: I practised, and still I lost.' },
    { id: 'kk8', en: 'I wish I had apologised sooner.', tokens: ['もっと', '早く', '謝れば', 'よかった'], distractors: ['謝って', 'から'], region: 12, hint: 'ば-form + よかった for regret: 謝る → 謝れば よかった.' },
    { id: 'kk9', en: 'I’m glad I came to this valley.', tokens: ['この', '谷', 'に', '来て', 'よかった'], alts: [['この', '谷', 'へ', '来て', 'よかった']], distractors: ['を', '来た'], region: 12, hint: 'て-form + よかった: 来て よかった (I’m glad I came).' },
    { id: 'kk10', en: 'Thank you for comforting me.', tokens: ['慰めて', 'くれて', 'ありがとう'], distractors: ['あげて', 'を'], region: 12, hint: 'Something done for you: て-form + くれて ありがとう.' },
    { id: 'kk11', en: 'Hannya seems to be lonely.', tokens: ['はんにゃ', 'は', '寂しい', 'みたい', 'です'], distractors: ['を', 'たい'], region: 12, hint: 'Plain form + みたい: 寂しい みたい (seems lonely).' },
    { id: 'kk12', en: 'I’m scared of dark places.', tokens: ['わたし', 'は', '暗い', 'ところ', 'が', '怖い'], distractors: ['を', '怖がる'], region: 12, hint: 'Your own feeling, straight out: the thing you fear takes が, then 怖い.' },
    { id: 'kk13', en: 'My heart is pounding.', tokens: ['胸', 'が', 'ドキドキ', 'して', 'いる'], distractors: ['を', 'わくわく'], region: 12, hint: 'Sound-feelings work with する: 胸が ドキドキ して いる.' },
    { id: 'kk14', en: 'To think that Hannya would cry!', tokens: ['はんにゃ', 'が', '泣く', 'なんて'], distractors: ['を', 'のに'], region: 12, hint: 'Plain form + なんて: surprise, “to think that…!”' },
    { id: 'kk15', en: 'Taro is dying to go to the festival.', tokens: ['タロウ', 'は', '祭り', 'に', '行きたがって', 'います'], distractors: ['を', '行きたい'], region: 12, hint: 'Someone else’s want: 行きたい → 行きたがって います.' },
  ],

  runes: [
    { id: 'kk-r1', jp: '会えてうれしいです', reading: 'あえてうれしいです', answer: 'I’m happy to see you.', wrong: ['I was sad not to see you.', 'Please come and see me.'], region: 12 },
    { id: 'kk-r2', jp: 'レンさんは悲しそうです', reading: 'れんさんはかなしそうです', answer: 'Ren looks sad.', wrong: ['Ren is very happy.', 'Ren wants to be sad.'], region: 12 },
    { id: 'kk-r3', jp: '子どもは面を怖がっています', reading: 'こどもはめんをこわがっています', answer: 'The child is afraid of the mask.', wrong: ['The child is wearing a scary mask.', 'The child wants a mask.'], region: 12 },
    { id: 'kk-r4', jp: '練習したのに負けました', reading: 'れんしゅうしたのにまけました', answer: 'Even though I practised, I lost.', wrong: ['I practised, so I won.', 'I lost because I didn’t practise.'], region: 12 },
    { id: 'kk-r5', jp: 'もっと早く謝ればよかった', reading: 'もっとはやくあやまればよかった', answer: 'I wish I had apologised sooner.', wrong: ['I apologised right away.', 'You should apologise later.'], region: 12 },
    { id: 'kk-r6', jp: '慰めてくれてありがとう', reading: 'なぐさめてくれてありがとう', answer: 'Thank you for comforting me.', wrong: ['Please comfort me.', 'I comforted you, you’re welcome.'], region: 12 },
    { id: 'kk-r7', jp: '明日は雨が降るような気がする', reading: 'あしたはあめがふるようなきがする', answer: 'I have a feeling it will rain tomorrow.', wrong: ['It rained yesterday, I think.', 'I don’t like rainy days.'], region: 12 },
    { id: 'kk-r8', jp: '祭りで踊ってほしい', reading: 'まつりでおどってほしい', answer: 'I want you to dance at the festival.', wrong: ['I want to dance at the festival.', 'I danced at the festival.'], region: 12 },
  ],

  readings: {
    会えて: 'あえて',
    会う: 'あう',
    今日: 'きょう',
    悲しそう: 'かなしそう',
    子ども: 'こども',
    鬼: 'おに',
    面: 'めん',
    怖がって: 'こわがって',
    怖がる: 'こわがる',
    祭り: 'まつり',
    踊って: 'おどって',
    踊りたい: 'おどりたい',
    明日: 'あした',
    雨: 'あめ',
    降る: 'ふる',
    降って: 'ふって',
    気が: 'きが',
    割って: 'わって',
    割った: 'わった',
    練習した: 'れんしゅうした',
    負けた: 'まけた',
    早く: 'はやく',
    謝れば: 'あやまれば',
    謝って: 'あやまって',
    谷: 'たに',
    来て: 'きて',
    来た: 'きた',
    慰めて: 'なぐさめて',
    暗い: 'くらい',
    胸: 'むね',
    行きたがって: 'いきたがって',
    行きたい: 'いきたい',
  },

  npcs: [
    {
      id: 'dancer-ren',
      name: 'Ren the Kagura Dancer',
      jp: 'かぐらの まいて レン',
      emoji: '🪭',
      region: 12,
      personality: 'The valley’s best young kagura dancer, bright and proud, who has danced the lead every autumn since she was nine. Since the faces froze she can’t put any feeling into the masks, she flubbed the dress rehearsal in front of everyone, and now she thinks she should give up. Speaks casually, like a friend.',
      politeness: 'casual',
      color: '#f2789f',
      interests: ['kagura dance', 'the old tales', 'masks', 'the autumn festival'],
      greeting: { jp: 'あ… 見て たの？ さっきの しっぱい…', en: 'Oh… did you see? That mess just now…' },
    },
    {
      id: 'ameya-sora',
      name: 'Sora the Candy-Apple Seller',
      jp: 'りんごあめやの ソラ',
      emoji: '🍎',
      region: 12,
      personality: 'Quick-tempered, warm-hearted girl who runs the candy-apple stall on the festival street. She spent all night dipping apples. Fiery when wronged, but forgives quickly when someone says sorry properly. Casual speech.',
      politeness: 'casual',
      color: '#e2432f',
      interests: ['candy apples', 'the festival', 'her best friend Ren', 'saying what you mean'],
      greeting: { jp: 'いらっしゃい！ りんごあめ、どう？', en: 'Welcome! Fancy a candy apple?' },
    },
    {
      id: 'farmer-mamoru',
      name: 'Mamoru the Rice Farmer',
      jp: 'こめづくりの マモル',
      emoji: '🌾',
      region: 12,
      personality: 'Shy, hard-working young farmer of the rice terraces. Last year a storm flattened his whole field; this year he worked every day, and his rice has just won first prize at the harvest show. He doesn’t know how to take praise and goes red at once.',
      politeness: 'casual',
      color: '#d9a441',
      interests: ['rice', 'the weather', 'the terraces', 'his grandmother'],
      greeting: { jp: 'あ、こんにちは… きょうは いい 天気ですね。', en: 'Oh, hello… lovely weather today.' },
    },
  ],

  scenarios: [
    // ── 1. Cheering up a friend who failed ───────────────────────────
    {
      id: 'kokoro-cheer',
      npcId: 'dancer-ren',
      region: 12,
      translations: 'always',
      start: 'open',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Ren slipped in the middle of the dress rehearsal, in front of the whole valley. Now she sits backstage with her mask in her lap.',
        'Listen to her, name what she feels, and cheer her up: 〜そう, 〜のに, 〜て よかった, 〜てほしい, 〜てくれて ありがとう.',
        'Pick the kind reply that fits. Wrong answers cost a ❤️.',
      ],
      nodes: {
        open: {
          id: 'open',
          line: { jp: '…あ、見て たの？ さっきの しっぱい。', en: '…Oh, did you see? That mess just now.' },
          kana: 'あ、みて たの？ さっきの しっぱい。',
          wordIds: ['ochikomu'],
          hint: 'She looks down. Say how she *looks*: 〜そう.',
          next: 'why',
          options: [
            { jp: 'うん… だいじょうぶ？ おちこんで いる みたいだね。', en: 'Yeah… are you okay? You seem down.', correct: true, wordIds: ['ochikomu'], reply: { jp: '…うん。すごく おちこんでる。', en: '…Yeah. I’m really down.' }, effects: { trust: 1 } },
            { jp: 'うん、見た！ おもしろかった！', kana: 'うん、みた！ おもしろかった！', en: 'Yep, I saw! It was hilarious!', correct: false, reply: { jp: '…ひどい。', en: '…That’s mean.' }, note: 'Laughing at a friend’s failure hurts. Show you noticed how she feels: おちこんで いる みたい.' },
            { jp: 'レンさんは おちこんで います。', en: 'Ren is depressed. (stated as a fact)', correct: false, reply: { jp: 'え… なんで あなたが きめるの？', en: 'Huh… since when do you decide how I feel?' }, note: 'You can’t state someone else’s feelings as fact. Soften it: おちこんで いる みたい / かなしそう.' },
          ],
        },
        why: {
          id: 'why',
          line: { jp: 'まいにち れんしゅうしたのに… みんなの まえで ころんじゃった。', en: 'I practised every single day… and I still fell flat in front of everyone.' },
          wordIds: ['kuyashii'],
          hint: 'She practised and still failed. That feeling is くやしい.',
          next: 'scared',
          options: [
            { jp: 'れんしゅうしたのに… くやしいね。', en: 'You practised so hard, and still… that’s so frustrating.', correct: true, wordIds: ['kuyashii'], reply: { jp: 'うん… くやしい。すごく くやしい！', en: 'Yeah… it’s frustrating. SO frustrating!' }, effects: { trust: 1 } },
            { jp: 'れんしゅうしたから、うれしいね。', en: 'You practised, so you must be happy.', correct: false, reply: { jp: 'うれしい？ いまの どこが？', en: 'Happy? Which part of this is happy?' }, note: 'のに shows the clash (practised, still failed). The feeling is くやしい (frustrated), not うれしい.' },
            { jp: 'うらやましいね。', en: 'How enviable.', correct: false, reply: { jp: '…なにが？', en: '…Of what?' }, note: 'うらやましい is envy. When your effort didn’t pay off, the word is くやしい.' },
          ],
        },
        scared: {
          id: 'scared',
          line: { jp: 'あしたが ほんばん。また ころんだら… こわい。もう おどりたく ない。', en: 'Tomorrow’s the real thing. What if I fall again… I’m scared. I don’t want to dance anymore.' },
          wordIds: ['fuan', 'kinchou-suru'],
          hint: 'Don’t push her. First say it’s normal to feel nervous.',
          next: 'remember',
          options: [
            { jp: 'ふあんに なるのは ふつうだよ。だれでも きんちょうする。', en: 'Feeling uneasy is normal. Everyone gets nervous.', correct: true, wordIds: ['fuan', 'kinchou-suru'], reply: { jp: '…だれでも？ あなたも？', en: '…Everyone? You too?' }, effects: { trust: 1 } },
            { jp: 'じゃあ、やめれば？ らくだよ。', en: 'Then why not quit? It’s easier.', correct: false, wordIds: ['raku'], reply: { jp: '…そう だよね。やめた ほうが らくだよね。', en: '…Yeah, you’re right. Quitting would be easier.' }, note: 'That agrees with her worst fear. Encourage (はげます) instead: it’s normal to be nervous.' },
            { jp: 'こわがらないで！ がまんして！', en: 'Don’t be scared! Just put up with it!', correct: false, wordIds: ['gaman-suru'], reply: { jp: 'がまんなんて、もう できないよ…', en: 'I can’t put up with it anymore…' }, note: 'Telling someone to bottle it up (がまん) rarely helps. Accept the feeling first.' },
          ],
        },
        remember: {
          id: 'remember',
          line: { jp: 'あなたは… どうして わたしの おどりが 見たいの？', en: 'Why do you… even want to see me dance?' },
          kana: 'あなたは… どうして わたしの おどりが みたいの？',
          wordIds: ['kandou-suru'],
          hint: 'Tell her what her dance did to you: 感動した.',
          next: 'wish',
          options: [
            { jp: 'きのう れんしゅうを 見て、感動したから。', kana: 'きのう れんしゅうを みて、かんどうしたから。', en: 'Because I saw you practise yesterday, and it moved me.', correct: true, wordIds: ['kandou-suru'], reply: { jp: '…感動？ わたしの おどりで？', en: '…Moved? By my dancing?' }, effects: { trust: 1 } },
            { jp: 'たいくつだから。', en: 'Because I’m bored.', correct: false, wordIds: ['taikutsu'], reply: { jp: 'ひまつぶし？ ……。', en: 'To kill time? ……' }, note: 'たいくつ (bored) makes her dance sound like filler. Say it moved you: 感動した.' },
            { jp: 'めんどうくさいけど。', en: 'Even though it’s a hassle.', correct: false, wordIds: ['mendoukusai'], reply: { jp: 'めんどうくさいなら、見なくて いいよ。', en: 'If it’s a hassle, you don’t have to watch.' }, note: 'めんどうくさい (what a hassle) is the opposite of encouragement.' },
          ],
        },
        wish: {
          id: 'wish',
          line: { jp: 'ほんとうに… わたしに おどって ほしい？', en: 'Do you really… want me to dance?' },
          wordIds: ['ouen-suru'],
          hint: 'Say what you want *her* to do: おどって ほしい.',
          next: 'thanks',
          options: [
            { jp: 'うん。レンに おどって ほしい。おうえんするよ！', en: 'Yes. I want you to dance, Ren. I’ll be cheering for you!', correct: true, wordIds: ['ouen-suru'], reply: { jp: 'おうえん… してくれるんだ。', en: 'You’ll… cheer for me.' }, effects: { trust: 1 } },
            { jp: 'うん。わたしが おどりたい。', en: 'Yes. I want to dance.', correct: false, reply: { jp: 'え、あなたが おどるの？', en: 'Huh, *you’re* going to dance?' }, note: 'おどりたい is what *you* want to do. For what you want someone else to do: おどって ほしい.' },
            { jp: 'うん。レンが おどりたがって いる。', en: 'Yes. Ren is eager to dance.', correct: false, reply: { jp: 'わたしの きもちを、わたしに せつめいしないで…', en: 'Don’t explain my own feelings to me…' }, note: '〜たがって いる describes a third person. Talking to Ren about your own wish: おどって ほしい.' },
          ],
        },
        thanks: {
          id: 'thanks',
          line: { jp: '…へんだね。さっきより、むねが かるい。', en: '…Funny. My chest feels lighter than before.' },
          wordIds: ['anshin'],
          hint: 'She thanks you for listening: きいて くれて ありがとう. Type it as Ren would say it.',
          next: 'bye',
          input: {
            accepted: ['きいてくれてありがとう', '聞いてくれてありがとう', 'はなしをきいてくれてありがとう', '話を聞いてくれてありがとう', 'きいてくれて、ありがとう'],
            model: '聞いてくれて ありがとう',
            modelKana: 'きいてくれて ありがとう',
            wrongReply: { jp: 'えっと… なんて いえば いいんだっけ。', en: 'Um… how do I say it again?' },
            wrongNote: 'Thanking someone for doing something for you: て-form + くれて ありがとう → きいて くれて ありがとう.',
            reply: { jp: 'きいて くれて ありがとう。…あした、おどるよ。こわいけど、おどる！', en: 'Thank you for listening. …Tomorrow, I’ll dance. I’m scared, but I’ll dance!' },
          },
        },
        bye: { id: 'bye', line: { jp: 'あなたに 話して よかった。ほんばん、見に きてね！', en: 'I’m glad I talked to you. Come and watch the real thing!' }, kana: 'あなたに はなして よかった。ほんばん、みに きてね！', end: true },
      },
    },

    // ── 2. Apologising after a quarrel ───────────────────────────────
    {
      id: 'kokoro-sorry',
      npcId: 'ameya-sora',
      region: 12,
      translations: 'always',
      start: 'crash',
      hearts: 4,
      startTrust: 1,
      trustMax: 6,
      intro: [
        'Hurrying down the festival street, you bump Sora’s stall. A whole tray of candy apples rolls into the dust.',
        'She is furious, and she has a right to be. Apologise properly and make up: 〜てしまった, 〜ば よかった, ゆるす, なかなおり.',
        'Pick what you would really say. Wrong answers cost a ❤️.',
      ],
      nodes: {
        crash: {
          id: 'crash',
          line: { jp: 'ああっ！ りんごあめが！ ぜんぶ おちた！', en: 'Aaah! My candy apples! They all fell!' },
          kana: 'ああっ！ りんごあめが！ ぜんぶ おちた！',
          wordIds: ['ayamaru'],
          hint: 'Say sorry first, and own it: 〜てしまった.',
          next: 'angry',
          options: [
            { jp: 'ごめんなさい！ ぶつかって しまった！', en: 'I’m so sorry! I bumped into it!', correct: true, wordIds: ['ayamaru'], reply: { jp: 'ごめんなさい、じゃ ないよ！', en: '“Sorry” doesn’t cut it!' }, effects: { trust: 1 } },
            { jp: 'あ、おちたね。', en: 'Oh, they fell.', correct: false, reply: { jp: '「おちたね」？！ あなたが おとしたの！', en: '“They fell”?! YOU knocked them over!' }, note: 'Describing it like it just happened by itself sounds cold. Own it: ぶつかって しまった, ごめんなさい.' },
            { jp: 'へいき、へいき！', en: 'It’s fine, it’s fine!', correct: false, wordIds: ['heiki'], reply: { jp: 'へいきじゃ ない！ わたしが きめる！', en: 'It is NOT fine! I get to decide that!' }, note: 'へいき (it’s fine) is for the person who was hurt to say, not the one who caused it.' },
          ],
        },
        angry: {
          id: 'angry',
          line: { jp: 'ひと晩じゅう つくったのに！ ほんとうに イライラする！', en: 'I made them all night long! I’m so irritated!' },
          kana: 'ひとばんじゅう つくったのに！ ほんとうに いらいらする！',
          wordIds: ['iraira', 'okoru'],
          hint: 'Don’t argue. Accept that she is angry, and that it’s your fault.',
          next: 'regret',
          options: [
            { jp: 'おこるのは あたりまえだよ。わたしが わるかった。', en: 'Of course you’re angry. It was my fault.', correct: true, wordIds: ['okoru'], reply: { jp: '……そう だよ。あなたが わるい。', en: '……Yeah. It was your fault.' }, effects: { trust: 1 } },
            { jp: 'そんなに おこらないでよ。めんどうくさいなあ。', en: 'Don’t get so angry. What a hassle.', correct: false, wordIds: ['mendoukusai'], reply: { jp: 'めんどうくさい？！ もう ぷんぷんだよ！', en: 'A HASSLE?! Now I’m really fuming!' }, note: 'Calling her anger a hassle makes the quarrel worse. Accept it: おこるのは あたりまえ.' },
            { jp: 'でも、ソラの みせが みちに でて いたから…', kana: 'でも、ソラの みせが みちに でて いたから…', en: 'But your stall was sticking out into the road, so…', correct: false, reply: { jp: 'わたしの せい？！', en: 'So it’s MY fault?!' }, note: 'Excuses (でも…から) turn an apology into a quarrel (けんか). Take the blame first.' },
          ],
        },
        regret: {
          id: 'regret',
          line: { jp: 'どうして はしって いたの？', en: 'Why were you running, anyway?' },
          wordIds: ['ki-wo-tsukeru'],
          hint: 'Regret: 〜ば よかった (I wish I had…).',
          next: 'offer',
          options: [
            { jp: 'いそいで いたんだ。もっと 気を つければ よかった。', kana: 'いそいで いたんだ。もっと きを つければ よかった。', en: 'I was in a hurry. I wish I’d been more careful.', correct: true, wordIds: ['ki-wo-tsukeru'], reply: { jp: '…うん。つぎは 気を つけてね。', en: '…Mm. Be careful next time.' }, effects: { trust: 1 } },
            { jp: 'いそいで いたんだ。もっと 気を つけるば よかった。', kana: 'いそいで いたんだ。もっと きを つけるば よかった。', en: '(I wish I had be-careful-ba…)', correct: false, wordIds: ['ki-wo-tsukeru'], reply: { jp: '「つけるば」？', en: '“Tsukeru-ba”?' }, note: 'The ば-form of つける is つければ: 気を つければ よかった.' },
            { jp: 'いそいで いたから、しかたない。', en: 'I was in a hurry, so it couldn’t be helped.', correct: false, reply: { jp: 'しかたなく ないよ！', en: 'It could TOTALLY have been helped!' }, note: 'しかたない (it can’t be helped) sounds like dodging. Show regret: 気を つければ よかった.' },
          ],
        },
        offer: {
          id: 'offer',
          line: { jp: 'でも、あしたの まつりまでに、もう 一回 つくるのは たいへんだよ…', en: 'But making them all over again before tomorrow’s festival… that’s a lot of work…' },
          kana: 'でも、あしたの まつりまでに、もう いっかい つくるのは たいへんだよ…',
          wordIds: ['taihen'],
          hint: 'Make amends: offer to help.',
          next: 'forgive',
          options: [
            { jp: 'てつだわせて！ いっしょに つくろう。', en: 'Let me help! Let’s make them together.', correct: true, reply: { jp: '…ほんとに？ りんごあめ、むずかしいよ？', en: '…Really? Candy apples are tricky, you know?' }, effects: { trust: 1 } },
            { jp: 'たいへんだね。がんばって！', en: 'That’s rough. Good luck!', correct: false, wordIds: ['taihen'], reply: { jp: '…あなたは てつだわないんだ。', en: '…So you’re not going to help.' }, note: '“Good luck” leaves her alone with the mess you made. Offer to help: てつだわせて.' },
            { jp: 'りんごあめは きらいだから、いいよ。', kana: 'りんごあめは きらいだから、いいよ。', en: 'I don’t like candy apples anyway, so it’s fine.', correct: false, reply: { jp: 'そういう もんだいじゃ ない！', en: 'That is NOT the point!' }, note: 'Whether you like them doesn’t matter. Make amends: てつだわせて.' },
          ],
        },
        forgive: {
          id: 'forgive',
          line: { jp: '…わかった。ゆるして あげる。', en: '…Okay. I forgive you.' },
          wordIds: ['yurusu', 'nakanaori'],
          hint: 'Thank her for forgiving you: ゆるして くれて ありがとう.',
          next: 'end',
          options: [
            { jp: 'ゆるして くれて ありがとう。なかなおり しよう。', en: 'Thank you for forgiving me. Let’s make up.', correct: true, wordIds: ['yurusu', 'nakanaori'], reply: { jp: 'うん、なかなおり！ …わたしも、どなって ごめんね。', en: 'Yeah, let’s make up! …And sorry for yelling at you, too.' }, effects: { trust: 1 } },
            { jp: 'ゆるして あげて ありがとう。', en: '(Thank you for forgiving-for-someone-else.)', correct: false, wordIds: ['yurusu'], reply: { jp: 'だれを ゆるすの？', en: 'Forgive who?' }, note: 'あげる is giving to someone else. When she does something for *you*: ゆるして くれて ありがとう.' },
            { jp: 'よかった。じゃ、さよなら！', en: 'Great. Okay, bye!', correct: false, wordIds: ['yokatta'], reply: { jp: 'え、てつだうって いったよね？！', en: 'Wait, you said you’d help, didn’t you?!' }, note: 'Running off right after being forgiven undoes it. Thank her, and make up properly.' },
          ],
        },
        end: { id: 'end', line: { jp: 'けんかの あとの りんごあめは、いつもより あまいね！', en: 'Candy apples taste sweeter after making up!' }, end: true },
      },
    },

    // ── 3. Congratulating someone ────────────────────────────────────
    {
      id: 'kokoro-congrats',
      npcId: 'farmer-mamoru',
      region: 12,
      translations: 'hint',
      start: 'news',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Last year a storm flattened Mamoru’s rice. This year his rice won first prize at the valley’s harvest show, but he is too shy to celebrate.',
        'Congratulate him, react with real feeling, and help him say how he feels: おめでとう, すごい, 〜て よかった, 〜なんて.',
        'English only comes with a hint this time. Listen to the feeling in his words.',
      ],
      nodes: {
        news: {
          id: 'news',
          line: { jp: 'あの… ぼくの おこめが、いちばんに なったんです。', en: 'Um… my rice came first.' },
          wordIds: ['omedetou'],
          hint: 'Good news! The first thing to say is おめでとう.',
          next: 'react',
          options: [
            { jp: 'おめでとう！', en: 'Congratulations!', correct: true, wordIds: ['omedetou'], reply: { jp: 'あ… ありがとう ございます。', en: 'Oh… thank you.' }, effects: { trust: 1 } },
            { jp: 'ざんねんですね。', en: 'What a shame.', correct: false, wordIds: ['zannen'], reply: { jp: 'えっ… ざんねん…？', en: 'Huh… a shame…?' }, note: 'ざんねん is for bad news. Good news gets おめでとう!' },
            { jp: 'ごめんなさい。', en: 'I’m sorry.', correct: false, reply: { jp: 'え、なにが ですか？', en: 'Huh, sorry for what?' }, note: 'Apologising makes no sense here. Celebrate: おめでとう!' },
          ],
        },
        react: {
          id: 'react',
          line: { jp: 'きょねんは あらしで、ぜんぶ だめに なったのに…', en: 'Even though last year the storm ruined everything…' },
          wordIds: ['sugoi', 'masaka'],
          hint: 'From ruin to first prize: show you are amazed. すごい!',
          next: 'shy',
          options: [
            { jp: 'きょねん ぜんぶ だめだったのに、ことしは いちばん なんて… すごい！', en: 'Everything was ruined last year, and this year first prize… amazing!', correct: true, wordIds: ['sugoi'], reply: { jp: 'え、えへへ…', en: 'Eh, ehehe…' }, effects: { trust: 1 } },
            { jp: 'へえ。たいくつですね。', en: 'Huh. How boring.', correct: false, wordIds: ['taikutsu'], reply: { jp: '…たいくつ、ですか。', en: '…Boring, is it.' }, note: 'たいくつ (boring) crushes good news. React with feeling: すごい!' },
            { jp: 'うそ。しんじない。', en: 'Liar. I don’t believe you.', correct: false, wordIds: ['uso'], reply: { jp: 'ほ、ほんとうです…', en: 'I-it’s true…' }, note: 'A light うそ！ (no way!) can be a happy reaction, but しんじない (I don’t believe you) is hurtful.' },
          ],
        },
        shy: {
          id: 'shy',
          line: { jp: 'みんなが ほめて くれるんですけど… なんだか 顔が あつくて。', en: 'Everyone keeps praising me, but… my face goes all hot.' },
          kana: 'みんなが ほめて くれるんですけど… なんだか かおが あつくて。',
          wordIds: ['tereru'],
          hint: 'He is shy about being praised: てれて いる. Say how he seems: 〜みたい.',
          next: 'glad',
          options: [
            { jp: 'マモルさん、てれて いる みたいですね。', en: 'You seem bashful, Mamoru.', correct: true, wordIds: ['tereru'], reply: { jp: 'て、てれて ないです！ …てれて ます。', en: 'I-I’m not bashful! …Okay, I am.' }, effects: { trust: 1 } },
            { jp: 'マモルさん、おこって いる みたいですね。', en: 'You seem angry, Mamoru.', correct: false, wordIds: ['okoru'], reply: { jp: 'おこって ないです！', en: 'I’m not angry!' }, note: 'A hot face when praised is てれる (bashful), not おこる (angry).' },
            { jp: 'マモルさんは てれたいです。', en: '(Mamoru wants to be bashful.)', correct: false, wordIds: ['tereru'], reply: { jp: '…え？', en: '…Huh?' }, note: 'For how someone seems, use 〜みたい: てれて いる みたい.' },
          ],
        },
        glad: {
          id: 'glad',
          line: { jp: 'でも… あきらめないで よかった、と 思います。', en: 'But… I think I’m glad I didn’t give up.' },
          kana: 'でも… あきらめないで よかった、と おもいます。',
          wordIds: ['yokatta'],
          hint: 'Share his gladness: 〜て よかった.',
          next: 'end',
          options: [
            { jp: 'ほんとうに、がんばって よかったですね！', en: 'You really are glad you kept going!', correct: true, wordIds: ['yokatta'], reply: { jp: 'はい！ …ことしの おまつりは、さいこうに なりそうです。', en: 'Yes! …This year’s festival is going to be the best.' }, effects: { trust: 1 } },
            { jp: 'がんばれば よかったですね。', en: 'You should have tried harder.', correct: false, reply: { jp: 'え… がんばりましたけど…', en: 'Huh… but I did try…' }, note: '〜ば よかった is regret (“I wish I had”). For gladness: がんばって よかった.' },
            { jp: 'がんばったのに、ざんねんですね。', en: 'You worked hard, and yet, what a pity.', correct: false, wordIds: ['zannen'], reply: { jp: 'いちばんに なったんですよ…？', en: 'But I came first…?' }, note: 'のに and ざんねん are for disappointment. This is good news: がんばって よかった.' },
          ],
        },
        end: { id: 'end', line: { jp: 'ありがとう。こんなに よろこんで もらえるなんて… しあわせです。', en: 'Thank you. To think someone would be this happy for me… I’m so happy.' }, end: true },
      },
    },
  ],
}
