import type { Locus } from '../types'

/**
 * Room 12: the Valley of Hearts. In at the west gate (Hotaru) and the
 * teahouse, up to Kaede's workshop among the maples, the hill shrine, down
 * to the river steps (Taro) and the lantern bridge (Gen), across to the
 * festival street (Sora's stall, Pon's drum, Kiyo's corner), up to the
 * kagura hall's backstage room (Ren), back down to the rice terraces
 * (Mamoru) and finally through the bamboo to Grandma Chiyo's hearth.
 */
export const ROOM: Locus[] = [
  {
    id: 'p12-gate',
    room: 12,
    map: 'kokoro',
    anchor: 'ko-hotaru',
    name: { jp: 'ほたるの もん', en: 'Firefly Gate' },
    emoji: '🏮',
    memories: [
      { item: 'w:shiawase', story: 'Hotaru twirls in the gateway singing “SHE, AH, WAH, SAY!” With every twirl a four-leaf clover drops from the sky, and a deep, quiet glow spreads through you: happiness.', image: 'a firefly child twirls singing “SHE, AH, WAH, SAY!” as four-leaf clovers drop from the sky, and a deep quiet glow of happiness spreads through you' },
      { item: 'w:hazukashii', story: 'A traveller sits on a HAZY, CUSHY cushion by the signpost. PFFFT! Everyone at the gate turns to stare, and her face goes red right up to the ears: embarrassed.', image: 'someone sits on a HAZY, CUSHY cushion that goes PFFFT, everyone turns to stare, and their face goes red to the ears: embarrassed' },
      { item: 'w:kuyashii', story: 'A pigeon loses a race to a snail right through the gate. “COO! YA… SHE beat me!” it stamps, wings shaking. All that practice for nothing: frustrated.', image: 'a pigeon loses a race to a snail and stamps its feet — “COO! YA… SHE beat me!” — wings shaking with frustration' },
      { item: 'w:natsukashii', story: 'Hotaru digs up an old tin of NUTS and CASH beside the gatepost. “EE, I hid that when I was little!” She smiles and sighs at the same time: nostalgic.', image: 'someone digs up an old tin of NUTS and CASH — “EE, I hid that when I was little!” — and smiles and sighs at once: nostalgic' },
      { item: 'w:urayamashii', story: 'A monkey on the gate roof stares at another monkey’s bowl. “OO-RAY! YAMA-SHE gets the MASH and I don’t!” Its eyes turn green: envious.', image: 'a monkey stares at another’s bowl — “OO-RAY! YAMA-SHE gets the MASH!” — and its eyes turn green with envy' },
      { item: 'w:iya', story: 'At the gate a boy is handed a cup of bitter medicine. “EE-YAH!” he squeals, shoving it away with both hands. Unpleasant: no, no, no.', image: 'a boy is handed bitter medicine, squeals “EE-YAH!” and shoves it away with both hands: unpleasant, no thank you' },
      { item: 'w:shinpai', story: 'Hotaru balances a PIE on her SHIN and hops through the gate. SHIN-PIE, SHIN-PIE… will it fall? She can’t stop worrying.', image: 'a child balances a PIE on her SHIN and hops along — SHIN-PIE, SHIN-PIE — unable to stop worrying it will fall' },
    ],
  },
  {
    id: 'p12-teahouse',
    room: 12,
    map: 'kokoro',
    anchor: 'ko-teahouse',
    name: { jp: 'ハナエの ちゃみせ', en: 'Hanae’s Teahouse' },
    emoji: '🍵',
    memories: [
      { item: 'w:anshin', story: 'Before a hockey match a girl at Hanae’s counter straps on AN extra SHIN guard. With AN SHIN pad on each leg, her shoulders finally drop: relief, peace of mind.', image: 'a hockey player straps on AN extra SHIN guard, and with the pad in place her shoulders finally drop: relief, peace of mind' },
      { item: 'w:zannen', story: 'Your last dumpling rolls off the teahouse bench into the SAND. “SAND IN it?” sighs Hanae, shaking her head. Too bad, what a pity.', image: 'your last dumpling rolls into the SAND — “SAND IN it?” — and someone shakes their head: too bad, what a pity' },
      { item: 'w:fuan', story: 'From the empty kettle on Hanae’s stove comes a ghostly “FOO… AHN…” Nobody is there. Every hair on your neck prickles: uneasy, anxious.', image: 'an empty kettle breathes a ghostly “FOO… AHN…” and every hair on your neck prickles: uneasy, anxious' },
      { item: 'w:taikutsu', story: 'SUE sits at a teahouse table with nothing to do, so she snips her TIE into strips: TIE, CUT, SUE. Snip. Yawn. Snip. Bored.', image: 'a girl named SUE has nothing to do, so she snips her necktie into strips — TIE, CUT, SUE — snip, yawn, snip: bored' },
      { item: 'w:kawaisou', story: 'A soaked kitten shivers under a CAR outside the teahouse. “WHY SO wet, you poor thing?” Hanae coos, wrapping it in her apron. CAR, WHY SO: poor thing.', image: 'a soaked kitten shivers under a CAR — “WHY SO wet, you poor thing?” — and gets wrapped in a warm apron' },
      { item: 'w:subarashii', story: 'A chef ladles SOUP from a BARREL, and SHE bows as fireworks burst over the teahouse: SOUP, BARRA, SHE! Everyone cries out: wonderful!', image: 'a chef ladles SOUP from a BARREL and SHE bows as fireworks burst overhead — SOUP, BARRA, SHE! — wonderful' },
      { item: 'w:sugoi', story: 'SUE walks past Hanae’s counter with twelve teacups stacked on her head. “SUE, GO-EE!” the customers yell. Amazing!', image: 'a girl walks with twelve teacups stacked on her head while a crowd yells “SUE, GO-EE!”: amazing' },
      { item: 'w:hidoi', story: 'Someone tips salt into Hanae’s best tea. “HE DID… OY!” she splutters, spitting it out. Terrible! Mean!', image: 'someone tips salt into the best tea, and the drinker splutters “HE DID… OY!”: terrible, mean' },
    ],
  },
  {
    id: 'p12-workshop',
    room: 12,
    map: 'kokoro-workshop',
    anchor: 'kw-kaede',
    name: { jp: 'カエデの こうぼう', en: 'Kaede’s Workshop' },
    emoji: '🎭',
    memories: [
      { item: 'g:te-feeling', story: 'Kaede carves a mask that giggles “TEH-he!” Its line is “I met you, TEH-he, so I’m happy!” The reason goes first, in TEH-form, then the feeling.', image: 'a mask giggles “TEH-he! I met you, so I’m happy!”: the reason comes first in TEH-form, then the feeling' },
      { item: 'g:feeling-ga', story: 'A spider drops onto Kaede’s bench. “GAH!” she gasps. The thing you feel about takes GAH: spiders, GAH, scary. Your own feelings, say straight; others’, say how they look.', image: 'a spider drops down and someone gasps “GAH!”: the thing you feel about takes GAH; say your own feelings straight, others’ by how they look' },
      { item: 'g:sou-looks', story: 'Kaede holds up a mask with drooping eyes. “It looks SOH sad,” you say: you only see the outside. Chop the end off the feeling word and add SOH: looks ~.', image: 'someone holds up a mask with drooping eyes — “it looks SOH sad” — chop the end off the feeling word and add SOH: looks ~' },
      { item: 'g:garu', story: 'A child peeks at the oni mask on the wall and GARGLES with fright. You can’t feel her fear, only see it: stem + GAH-ROO, “shows signs of ~”.', image: 'a child sees a red demon mask and GARGLES with fright: stem + GAH-ROO, someone shows signs of a feeling' },
      { item: 'g:mitai', story: 'One of Kaede’s masks is wearing a necktie. “ME TIE? Seems like it’s off to a party,” she laughs. Plain form or noun + ME-TIE: seems like ~.', image: 'a mask wearing a necktie — “ME TIE? Seems like it’s off to a party” — plain form or noun + ME-TIE: seems like' },
      { item: 'g:tagaru', story: 'A kangaroo hops into the workshop and keeps grabbing the price TAG on a mask: TAG-A-ROO wants to try it on! Stem + TAH-GAH-ROO: someone else wants to ~.', image: 'a kangaroo keeps grabbing the price TAG on a mask — TAG-A-ROO wants to try it on — stem + TAH-GAH-ROO: someone else wants to' },
    ],
  },
  {
    id: 'p12-shrine',
    room: 12,
    map: 'kokoro',
    anchor: 'ko-priest',
    name: { jp: 'やまの おみや', en: 'Hill Shrine' },
    emoji: '⛩️',
    memories: [
      { item: 'w:ai', story: 'A huge painted EYE on the shrine curtain blinks slowly, and pink hearts float out of it and drift over the valley. EYE: love.', image: 'a huge painted EYE blinks slowly and pink hearts float out of it, drifting away on the breeze: love' },
      { item: 'w:koi', story: 'In the shrine pond two KOY carp swim round and round in the shape of a heart, blushing pink to the fins: romantic love.', image: 'two KOY carp swim round and round in the shape of a heart, blushing pink to the fins: romantic love' },
      { item: 'w:kansha', story: 'A Persian SHAH climbs the shrine steps and offers Shinobu a CAN of peaches. “CAN, SHAH thank you enough?” Deep gratitude.', image: 'a Persian SHAH bows low and offers a CAN of peaches — “CAN, SHAH thank you enough?” — deep gratitude' },
      { item: 'w:kitai', story: 'A KITE with a painted EYE rises over the shrine roof. The whole village holds its breath, waiting for it to climb higher: KITE-EYE, expectation, high hopes.', image: 'a KITE with a painted EYE rises, and a whole crowd holds its breath waiting for it to climb higher: expectation, high hopes' },
      { item: 'w:koukai', story: 'A boy drank a whole bottle of COKE before bed, and now he sits on the shrine steps at dawn with a twitching EYE. COKE, EYE: regret.', image: 'a boy who drank a whole bottle of COKE before bed sits awake at dawn with a twitching EYE: regret' },
      { item: 'w:himitsu', story: 'Behind the shrine hall, HE MEETS SUE, and they both put a finger to their lips. HE MEETS SUE: a secret.', image: 'behind a wall, HE MEETS SUE, and both put a finger to their lips: a secret' },
      { item: 'w:jishin', story: 'A runner on the shrine steps slaps her SHIN and shouts “GEE, SHIN, we can do this!” Chest out, chin up: confidence.', image: 'a runner slaps her SHIN and shouts “GEE, SHIN, we can do this!” with her chest out and chin up: confidence' },
    ],
  },
  {
    id: 'p12-river',
    room: 12,
    map: 'kokoro',
    anchor: 'ko-taro',
    name: { jp: 'かわの いしだん', en: 'River Steps' },
    emoji: '🏞️',
    memories: [
      { item: 'w:warau', story: 'Taro and a crab have a tickle WAR on the steps. “WAR! OW! WAR!” They laugh so hard they both topple into the river.', image: 'a boy and a crab have a tickle WAR — “WAR! OW!” — and laugh so hard they both topple into the water' },
      { item: 'w:naku', story: 'A pigeon on the river steps loses its bread to the current. “NAH… COO…” it sobs, and big tears plop into the water: cry.', image: 'a pigeon watches its bread float away — “NAH… COO…” — and big tears plop into the water: cry' },
      { item: 'w:okoru', story: 'Someone tosses an apple CORE at Taro. “OH! CORE?!” His face goes red and steam whistles from his ears: he gets angry.', image: 'an apple CORE bounces off a boy’s head — “OH! CORE?!” — his face goes red and steam whistles out: getting angry' },
      { item: 'w:odoroku', story: 'A wooden DOOR pops up out of the river. “OH! DOOR! OH-KOO!” Taro jumps a whole metre in the air: surprised.', image: 'a wooden DOOR pops up out of the water — “OH! DOOR! OH-KOO!” — and a boy jumps a metre in the air: surprised' },
      { item: 'w:yorokobu', story: 'Taro fishes out a ROCK shaped exactly like a corn COB. “YO! ROCK-COB!” He dances up and down the steps, delighted.', image: 'a boy fishes out a ROCK shaped like a corn COB — “YO! ROCK-COB!” — and dances up and down, delighted' },
      { item: 'w:komaru', story: 'Taro’s homework blew into the river and came back with a COMMA after every word. He’ll RUE this: COMMA-RUE. He’s stuck, at a loss, in trouble.', image: 'homework comes back with a COMMA after every word, and its owner will RUE it — COMMA-RUE — stuck, at a loss' },
      { item: 'w:kinchou-suru', story: 'Taro has to eat his CHOW in front of all his KIN at the riverside feast, and his chopsticks rattle in his hand: KIN-CHOW, nervous.', image: 'a boy must eat his CHOW in front of all his KIN, and his chopsticks rattle in his hand: KIN-CHOW, nervous' },
      { item: 'w:kandou-suru', story: 'Grandma brings Taro a heart she baked from CANNED DOUGH. He’s so moved his eyes fill up: CAN-DOUGH, deeply touched.', image: 'a grandma brings a heart baked from CANNED DOUGH, and the boy is so moved his eyes fill up: deeply touched' },
    ],
  },
  {
    id: 'p12-bridge',
    room: 12,
    map: 'kokoro',
    anchor: 'ko-gen',
    name: { jp: 'ちょうちんの はし', en: 'Lantern Bridge' },
    emoji: '🌉',
    memories: [
      { item: 'g:te-hoshii', story: 'Gen points his walking stick at Ren across the bridge: “TEH… HO! SHE should dance!” TEH-form + HO-SHE-EE: I want you (someone else) to do it.', image: 'an old storyteller points his stick: “TEH… HO! SHE should dance!” — TEH-form + HO-SHE-EE: I want someone else to do it' },
      { item: 'g:ki-ga-suru', story: 'Gen sniffs a rusty KEY on the bridge rail. “KEY… GAS… SOO-ROO… I have a feeling something’s burning.” Plain form + YOH-NAH KEY-GAH SOO-ROO: I have a feeling that ~.', image: 'an old man sniffs a rusty KEY — “KEY, GAS… I have a feeling something’s burning” — plain form + YOH-NAH KEY-GAH SOO-ROO' },
      { item: 'g:te-shimatta', story: 'Gen’s best lantern slips off the bridge into the river. “Oops, SHE MATTA’d!” TEH-form + SHE-MAT-TAH: did it, and wish it hadn’t happened.', image: 'a lantern slips into the water — “oops, SHE MATTA’d!” — TEH-form + SHE-MAT-TAH: it happened, and you wish it hadn’t' },
      { item: 'g:noni', story: 'A runner trained on the bridge every day for a year, then tripped on the start line. “I trained… and NO KNEE!” NO-NEE: even though ~, the two halves clash.', image: 'a runner trained all year, then tripped on the start line — “I trained… and NO KNEE!” — NO-NEE: even though' },
      { item: 'g:ba-yokatta', story: 'Gen stares at his scraggly beard in the river. “BAH! YO, should’ve CUT-TA it!” BAH-form + YOH-KAT-TAH: I wish I had ~.', image: 'an old man stares at his scraggly beard in the water — “BAH! YO, should’ve CUT-TA it!” — BAH-form + YOH-KAT-TAH: I wish I had' },
      { item: 'g:te-yokatta', story: 'Gen sips his TEA as a falling CAT lands safely on the bridge: “TEH, YO, CAT-TAH… I’m glad it made it.” TEH-form + YOH-KAT-TAH: glad that ~.', image: 'someone sips TEA as a falling CAT lands safely — “TEH, YO, CAT-TAH, I’m glad” — TEH-form + YOH-KAT-TAH: glad that' },
      { item: 'g:nante', story: 'Gen’s NAN pours TEA while walking a tightrope over the bridge. “My NAN… TEA… on a rope?! To think!” Plain form + NAHN-TEH: surprise, disbelief.', image: 'a grandma, a NAN, pours TEA while walking a tightrope — “to think!” — plain form + NAHN-TEH: surprise, disbelief' },
      { item: 'g:te-kurete-arigatou', story: 'An ALLIGATOR ferries Gen across when the bridge is crowded. “TEH… CURE-ET… ALLI-GATOR!” Thank you for doing it for me: TEH-form + KOO-REH-TEH AH-REE-GAH-TOH.', image: 'an ALLIGATOR ferries an old man across — “TEH, CURE-ET, ALLI-GATOR!” — TEH-form + KOO-REH-TEH: thank you for doing it for me' },
    ],
  },
  {
    id: 'p12-candy',
    room: 12,
    map: 'kokoro',
    anchor: 'ko-sora',
    name: { jp: 'りんごあめの みせ', en: 'Candy-Apple Stall' },
    emoji: '🍎',
    memories: [
      { item: 'w:ochikomu', story: 'A chick drops its candy apple in the dust by Sora’s stall. “OH… CHICK… COME back…” it peeps, and slumps against the counter: feeling down.', image: 'a chick drops its candy apple in the dust — “OH… CHICK… COME back…” — and slumps against a post: feeling down' },
      { item: 'w:ayamaru', story: 'Sora bows so low that her nose touches A MARBLE on the counter: “AH, YA, MA-ROO…” A deep, deep bow: apologise.', image: 'someone bows so low their nose touches A MARBLE — “AH, YA, MA-ROO…” — a deep, deep bow: apologise' },
      { item: 'w:yurusu', story: 'SUE played a RUSE and stole your candy apple. “YOU… RUSE… SUE… it’s okay.” You hug her anyway: forgive.', image: 'a girl named SUE played a RUSE and stole your sweet — “YOU, RUSE, SUE… it’s okay” — and you hug her anyway: forgive' },
      { item: 'w:nagusameru', story: 'A crying GOOSE won’t stop NAGging at Sora’s stall, so she wraps it in a blanket and hums A MERRY tune: NAG, GOOSE, A MERRY. Comfort.', image: 'a crying GOOSE won’t stop NAGging, so someone wraps it in a blanket and hums A MERRY tune: comfort' },
      { item: 'w:hagemasu', story: 'An old HAG behind the stall waves a ladle at a shy kid: “HAH, GEH! A whole MASS of courage, go on!” Encourage.', image: 'an old HAG waves a ladle at a shy kid — “HAH, GEH! A whole MASS of courage, go on!” — encourage' },
      { item: 'w:gaman-suru', story: 'A GUMMY MAN is stuck to Sora’s nose and it tickles terribly, but she clamps her mouth shut and holds in the sneeze: GUMMY MAN, putting up with it.', image: 'a GUMMY MAN is stuck to someone’s nose and tickles terribly, but they clamp their mouth and hold in the sneeze: putting up with it' },
      { item: 'w:ouen-suru', story: 'Sora climbs on her counter waving a flag: “OH, WEN-dy, go, go, go!” OH-EN: cheering for her friend.', image: 'someone climbs on a counter waving a flag — “OH, WEN-dy, go, go, go!” — cheering for a friend' },
    ],
  },
  {
    id: 'p12-drum',
    room: 12,
    map: 'kokoro',
    anchor: 'ko-drummer',
    name: { jp: 'まつりの たいこ', en: 'Festival Drum' },
    emoji: '🥁',
    memories: [
      { item: 'w:dokidoki', story: 'Pon beats a boat-shaped drum that thumps “DOCK-EE, DOCK-EE!” faster and faster, exactly like a heart about to go on stage: pounding.', image: 'a drum shaped like a boat thumps “DOCK-EE, DOCK-EE!” faster and faster, like a heart before a show: pounding' },
      { item: 'w:wakuwaku', story: 'Pon’s feet can’t stay still before the parade: “WALK-OO, WALK-OO!” they patter around the drum. Tingling with excitement.', image: 'feet that can’t stay still patter around — “WALK-OO, WALK-OO!” — tingling with excitement before a parade' },
      { item: 'w:iraira', story: 'A fly keeps buzzing in Pon’s EAR, EAR, RAH! He swats, misses, swats. Every beat comes out cross: irritated.', image: 'a fly keeps buzzing in someone’s EAR, EAR, RAH! — they swat, miss, swat — irritated' },
      { item: 'w:nikoniko', story: 'Pon taps his KNEE between beats and beams: “KNEE-KOH, KNEE-KOH!” A wide, warm grin: all smiles.', image: 'a drummer taps his KNEE and beams — “KNEE-KOH, KNEE-KOH!” — a wide, warm grin: all smiles' },
      { item: 'w:niyaniya', story: 'A tanuki has hidden Pon’s drumsticks behind its back and wears a sly “KNEE-YAH, KNEE-YAH” grin: smirking.', image: 'a tanuki hides the drumsticks behind its back and wears a sly “KNEE-YAH, KNEE-YAH” grin: smirking' },
      { item: 'w:shikushiku', story: 'Behind the big drum, SHE COOs very softly, “SHE-COO, SHE-COO,” wiping her eyes with her sleeve: sobbing quietly.', image: 'behind something big, SHE COOs very softly — “SHE-COO, SHE-COO” — wiping her eyes with her sleeve: sobbing quietly' },
      { item: 'w:mesomeso', story: 'A toddler drops a shaved ice by the drum and whimpers, “MESS-OH… MESS-OH…” on and on: snivelling.', image: 'a toddler drops a shaved ice and whimpers “MESS-OH… MESS-OH…” on and on: snivelling' },
      { item: 'w:gakkari', story: 'Pon CARRIES his drum all the way up the hill — GACK! — the parade is cancelled. “GACK… CARRY… for nothing.” Disappointed.', image: 'someone CARRIES a heavy drum all the way uphill — GACK! — and the parade is cancelled: disappointed' },
    ],
  },
  {
    id: 'p12-gossip',
    room: 12,
    map: 'kokoro',
    anchor: 'ko-aunt',
    name: { jp: 'うわさの かど', en: 'Gossip Corner' },
    emoji: '🗣️',
    memories: [
      { item: 'w:hotto', story: 'Kiyo pulls her HOT TOE out of a too-hot footbath and lets out a long “HOT… TOE…” sigh: relieved.', image: 'someone pulls a HOT TOE out of a too-hot footbath and lets out a long “HOT… TOE…” sigh: relieved' },
      { item: 'w:bikkuri', story: 'Kiyo bites into what she thinks is CURRY bread and finds a BIC pen inside. “BIC… CURRY?!” She jumps: startled.', image: 'someone bites into CURRY bread and finds a BIC pen inside — “BIC… CURRY?!” — and jumps: startled' },
      { item: 'w:ukiuki', story: 'Kiyo skips down the street swinging a new KEY: “OO-KEY, OO-KEY!” Light on her feet, in high spirits.', image: 'someone skips along swinging a new KEY — “OO-KEY, OO-KEY!” — light on their feet, in high spirits' },
      { item: 'w:moyamoya', story: 'A grey fog of half-heard rumours hangs over Kiyo’s corner, and someone MOWs it with a lawnmower, “MOW-YA, MOW-YA,” but it won’t clear: a murky, unsettled feeling.', image: 'someone MOWs a grey fog with a lawnmower — “MOW-YA, MOW-YA” — but it won’t clear: a murky, unsettled feeling' },
      { item: 'w:zotto', story: 'An icy finger touches the back of Kiyo’s neck. ZOT! A shiver runs from her collar to her heels: chills.', image: 'an icy finger touches the back of someone’s neck — ZOT! — and a shiver runs from collar to heels: chills' },
      { item: 'w:punpun', story: 'Someone tells Kiyo a terrible PUN, then another PUN. PUN, PUN! She puffs out her cheeks and stomps off: in a huff.', image: 'someone tells a terrible PUN, then another PUN, and the listener puffs out their cheeks and stomps off: in a huff' },
      { item: 'w:sowasowa', story: 'Kiyo waits for the newest gossip: “SO? WAH? SO? WAH?” She shifts from foot to foot and can’t sit still: restless.', image: 'someone waiting for news goes “SO? WAH? SO? WAH?”, shifting from foot to foot, unable to sit still: restless' },
    ],
  },
  {
    id: 'p12-stage',
    room: 12,
    map: 'kokoro-stage',
    anchor: 'ks-ren',
    name: { jp: 'がくや', en: 'Backstage Room' },
    emoji: '🪭',
    memories: [
      { item: 'w:namida', story: 'A single drop rolls down the cheek of Ren’s mask. “NAH… ME… DAH…” she whispers, and catches it on her fingertip: tears.', image: 'a single drop rolls down a mask’s cheek — “NAH… ME… DAH…” — and someone catches it on a fingertip: tears' },
      { item: 'w:egao', story: 'Ren paints a smile on an EGG between rehearsals. “EGG-OW!” it says, grinning from ear to ear: a smiling face.', image: 'someone paints a smile on an EGG, and it says “EGG-OW!”, grinning from ear to ear: a smiling face' },
      { item: 'w:kenka', story: 'KEN and his rival tug at the same toy CAR backstage, shouting: KEN, CAR, KEN, CAR! A quarrel.', image: 'a boy called KEN and his rival tug at the same toy CAR, shouting — KEN, CAR, KEN, CAR! — a quarrel' },
      { item: 'w:nakanaori', story: 'Two dancers KNOCK heads in the doorway. “NAH, ORRY… sorry!” KNOCK-A-NAH-ORRY, and they end up hugging: making up.', image: 'two dancers KNOCK heads — “NAH, ORRY… sorry!” — KNOCK-A-NAH-ORRY, and they end up hugging: making up' },
      { item: 'w:ikari', story: 'Ren is told to CARRY the great drum by herself. “EE! CARRY it yourself!” Red steam pours from under her mask: anger.', image: 'someone is told to CARRY a huge drum alone — “EE! CARRY it yourself!” — and red steam pours out: anger' },
      { item: 'w:tanoshimi', story: 'Ren packs sun cream for her beach TAN after the festival: “TAN, OH, SHE-ME!” She ticks off the days on the wall: something to look forward to.', image: 'someone packs sun cream for a beach TAN — “TAN, OH, SHE-ME!” — ticking off the days: something to look forward to' },
      { item: 'w:omoiyari', story: 'A pirate backstage takes off his coat and wraps it round shivering Ren. “OH, MOI? YARR-EE.” Thinking of others: kindness.', image: 'a pirate takes off his coat and wraps it round someone shivering — “OH, MOI? YARR-EE” — thinking of others: kindness' },
      { item: 'w:kibun', story: 'Ren eats a KEY-shaped BUN before going on. Sweet bun, sweet mood: KEY-BUN, how you’re feeling right now.', image: 'someone eats a KEY-shaped BUN — sweet bun, sweet mood — KEY-BUN: how you’re feeling right now' },
    ],
  },
  {
    id: 'p12-terraces',
    room: 12,
    map: 'kokoro',
    anchor: 'ko-mamoru',
    name: { jp: 'たなだ', en: 'Rice Terraces' },
    emoji: '🌾',
    memories: [
      { item: 'w:yokatta', story: 'A CAT stuck in an ox YOKE in Mamoru’s paddy wriggles free. “YOKE… CAT… TA-DA!” Everyone breathes out: thank goodness.', image: 'a CAT stuck in an ox YOKE wriggles free — “YOKE, CAT, TA-DA!” — and everyone breathes out: thank goodness' },
      { item: 'w:saikou', story: 'Mamoru’s PSYCHO-fast rice harvester zooms down the paddies and wins a gold medal: SIGH-KOH! The best!', image: 'a PSYCHO-fast harvester zooms through the paddies and wins a gold medal — SIGH-KOH! — the best' },
      { item: 'w:saiaku', story: 'Mamoru steps in mud, loses a boot, then sneezes into the paddy: “SIGH… AH-KOO!” The worst day ever.', image: 'someone steps in mud, loses a boot, then sneezes — “SIGH… AH-KOO!” — the worst day ever' },
      { item: 'w:taihen', story: 'Mamoru has to TIE up a HEN that keeps escaping into the rice: TIE, HEN, TIE, HEN… It’s tough work!', image: 'someone has to TIE up a HEN that keeps escaping — TIE, HEN, TIE, HEN — tough work' },
      { item: 'w:mendoukusai', story: 'Three MEN knead DOUGH by the paddies all night, cooing and sighing: MEN, DOUGH, COO, SIGH. What a hassle.', image: 'three MEN knead DOUGH all night, cooing and sighing — MEN, DOUGH, COO, SIGH — what a hassle' },
      { item: 'w:heiki', story: 'Mamoru tumbles off a terrace into a HAY stack and holds up his KEY, grinning: “HAY-KEY! I’m fine!”', image: 'someone tumbles into a HAY stack and holds up a KEY, grinning — “HAY-KEY! I’m fine!”' },
      { item: 'w:kawaii', story: 'A duckling drives a tiny toy CAR along the edge of the paddy. “CAR? WHY? EE!” everyone squeals: so cute!', image: 'a duckling drives a tiny toy CAR, and everyone squeals “CAR? WHY? EE!”: so cute' },
    ],
  },
  {
    id: 'p12-farmhouse',
    room: 12,
    map: 'kokoro-farmhouse',
    anchor: 'kf-obaa',
    name: { jp: 'おばあさんの いろり', en: 'Grandma’s Hearth' },
    emoji: '🔥',
    memories: [
      { item: 'w:ki-ni-naru', story: 'Grandma Chiyo has a strange KEY balanced on her KNEE, and she can’t stop glancing at it: KEY, KNEE, NAH-ROO. It’s on her mind.', image: 'someone has a strange KEY balanced on their KNEE and can’t stop glancing at it — KEY, KNEE, NAH-ROO — it’s on their mind' },
      { item: 'w:ki-wo-tsukeru', story: 'Grandma ties her KEY on a string round your neck before you SKATE out the door: “KEY, OH, SKATE-ROO… be careful!”', image: 'a grandma hangs a KEY on a string round your neck before you SKATE off — “KEY, OH, SKATE-ROO… be careful!”' },
      { item: 'w:omedetou', story: 'Grandma serves an OMELETTE shaped like a TOE with a candle on top: “OH-MEH-DEH-TOE!” Congratulations!', image: 'a grandma serves an OMELETTE shaped like a TOE with a candle on top — “OH-MEH-DEH-TOE!” — congratulations' },
      { item: 'w:uso', story: 'A fisherman by the hearth spreads his arms: “WHO SO big a fish? Me!” Grandma snorts. A lie!', image: 'a fisherman spreads his arms wide — “WHO SO big a fish? Me!” — and everyone snorts: a lie' },
      { item: 'w:masaka', story: 'MA opens a rice SACK by the hearth and a tiny dragon pops out. “MA! SACK! AH?!” No way!', image: 'a mum, MA, opens a rice SACK and a tiny dragon pops out — “MA! SACK! AH?!” — no way' },
      { item: 'w:honki', story: 'A goose HONKS and snatches Grandma’s KEY, and it is not joking: HONK-KEY. It means it, for real, serious.', image: 'a goose HONKS and snatches a KEY, and it is not joking — HONK-KEY — it means it, for real' },
      { item: 'w:tereru', story: 'Grandma praises TERRY’s rice, and TERRY turns pink and scratches his head: “TEH-REH-ROO…” Bashful.', image: 'someone praises TERRY’s cooking, and TERRY turns pink and scratches his head — “TEH-REH-ROO…” — bashful' },
      { item: 'w:raku', story: 'Grandma sinks into a RACK of soft cushions by the fire: “RAH-KOO…” No work, no worries: easy and comfortable.', image: 'someone sinks into a RACK of soft cushions by a fire — “RAH-KOO…” — no work, no worries: easy and comfortable' },
    ],
  },
]
