import type { RegionSprites } from '../types'

/**
 * Region 12 pixel art (palette chars: art/raster.ts LEGEND).
 *
 * maskmaker  Kaede, the mask carver: short black hair under a white
 *            headband, a brown work kimono with an orange sash and a paper-
 *            white carving apron
 * dancer     Ren, the kagura dancer: long black hair with two gold hairpins,
 *            a white chihaya jacket over vermilion hakama, a gold sash
 * menrei     a mask spirit: a blank white Noh mask (ko-omote) with painted
 *            hair, slit eyes and red lips, trailing crimson cords and wisps
 * hannya     the Hannya mask: golden horns and eyes, furrowed red brows, a
 *            pale face framed by wild black hair, a wide mouth of fangs
 */
export const SPRITES: RegionSprites = {
  characters: {
    maskmaker: {
      down: [
        '................',
        '.......nn.......',
        '....nnnnnnnn....',
        '...nwwwwwwwwn...',
        '...nnnnnnnnnn...',
        '...nnffffffnn...',
        '...nfkffffkfn...',
        '...ffkffffkfF...',
        '....hffffffh....',
        '...OoLffffLoO...',
        '..fOooLLLLooOf..',
        '...OeeeeeeeeO...',
        '...OoppppppoO...',
        '....OppppppO....',
        '.....ww.........',
        '................',
      ],
      up: [
        '................',
        '.......nn.......',
        '....nnnnnnnn....',
        '...nwwwwwwwwn...',
        '...nnnnnnnnnn...',
        '...nnnnnnnnnn...',
        '...nnnnnnnnnn...',
        '...FnnnnnnnnF...',
        '....FFFFFFFF....',
        '...OooooooooO...',
        '..fOooooooooOf..',
        '...OeeeeeeeeO...',
        '...OooooooooO...',
        '....OooooooO....',
        '.....ww.........',
        '................',
      ],
      side: [
        '................',
        '....nn..........',
        '...nnnnn........',
        '...wwwwwwww.....',
        '...nnnnnnnnn....',
        '...nnnnffffff...',
        '...nnnFfffkff...',
        '...nnnFfffkff...',
        '....nnfffhff....',
        '.....OoLLoO.....',
        '.....OoLfoO.....',
        '....OeeeeeO.....',
        '.....OoppoO.....',
        '.....OppppO.....',
        '.....ww..ww.....',
        '................',
      ],
    },
    dancer: {
      down: [
        '................',
        '......y..y......',
        '....nnnnnnnn....',
        '...nnnnnnnnnn...',
        '...nnnnnnnnnn...',
        '...nnffffffnn...',
        '...nfkffffkfn...',
        '...nfkffffkfn...',
        '...nhffffffhn...',
        '..nnwwvffvwwnn..',
        '..fnwwwwwwwwnf..',
        '...vvyyyyyyvv...',
        '...vvvvvvvvvv...',
        '...vvvvvvvvvv...',
        '.....ww.........',
        '................',
      ],
      up: [
        '................',
        '......y..y......',
        '....nnnnnnnn....',
        '...nnnnnnnnnn...',
        '...nnnnnnnnnn...',
        '...nnnnnnnnnn...',
        '...nnnnnnnnnn...',
        '...nnnnnnnnnn...',
        '...nnnnnnnnnn...',
        '..nnnnnnnnnnnn..',
        '..fwnnnnnnnnwf..',
        '...vvyyyyyyvv...',
        '...vvvvvvvvvv...',
        '...vvvvvvvvvv...',
        '.....ww.........',
        '................',
      ],
      side: [
        '................',
        '.....y..........',
        '...nnnnnn.......',
        '...nnnnnnnn.....',
        '...nnnnnnnnn....',
        '...nnnnffffff...',
        '..nnnnFfffkff...',
        '..nnnnFfffkff...',
        '..nnnnffffhf....',
        '..nnnwwvvwwh....',
        '..nn.wwwwwwf....',
        '....vvyyyyv.....',
        '....vvvvvvv.....',
        '....vvvvvvv.....',
        '.....ww..ww.....',
        '................',
      ],
    },
  },
  enemies: {
    menrei: {
      sym: true,
      anim: 'bob',
      rows: [
        '................',
        '................',
        '................',
        '..........pwwwww',
        '........pwwwwnnn',
        '.......pwwwwwnnn',
        '......pwwwwwwwnn',
        '.....pwwwwwwwwwn',
        '.....pwwwwwwwwww',
        '....pwwkkwwwwwww',
        '.VV.pwwwwwwwwwww',
        '..VVpwwwwwwwwwww',
        '...Vpwkkkkwwwwww',
        '..VVpwwkkwwwwwww',
        '.V..pwwwwwwwwwww',
        '.V..phwwwwwwwwww',
        '....phhwwwwwwwww',
        '....pwwwwwwwwwwP',
        '.....pwwwwwwwwwP',
        '.....pwwwwwwwwww',
        '.....pwwwwwwwwvV',
        '......pwwwwwwwkk',
        '......pwwwwwwwvv',
        '.......pwwwwwwww',
        '........pwwwwwww',
        '..........pPPPPP',
        '.......u.......u',
        '......uU......uU',
        '.....uU......U..',
        '................',
        '................',
        '................',
      ],
    },
    hannya: {
      sym: true,
      anim: 'bob',
      rows: [
        '..yO............',
        '..yyO...........',
        '...yyO..........',
        '...yyOO.........',
        '....yyOnnnnnnnnn',
        '....nyyOnnnnnnnn',
        '...nnnyOnnnnnnnn',
        '..nnnnppppppnnnn',
        '..nnnpppppppppnn',
        '.nnnppppppppppnp',
        '.nnnpVVVppppppPp',
        '.nnppkVVVVppPPpp',
        '.nnppyyyykVppPpp',
        '.nnppykkyyVpPppp',
        '.nnpppyyyyVppppp',
        '.nnppppppppPpppp',
        '.nnpPpppppppPppp',
        '.nnpPPppppppPkpp',
        '.nnppPPpppppPPpp',
        '..nppVVVVVVVVVVV',
        '..nnpVwwkkkkkkkk',
        '..nnpVwwwkkkkkkk',
        '...npVwkkVVVVVVV',
        '...nnpVwkkkkkkkk',
        '....npVwwwwwwwww',
        '....nnpVVVVVVVVV',
        '.....nppppppPPPP',
        '......nnPPPPPPPP',
        '.......nn.......',
        '........n.......',
        '................',
        '................',
      ],
    },
  },
}
