/**
 * Palette maps for prop tiles (16×16). Flat colours are auto-shaded from
 * the top-left (`shade` lists which colours), then outlined in ink and
 * dropped onto their ground tile with a soft cast shadow.
 */
export interface PropDef {
  rows?: string[]
  /** Animated props: one map per frame. */
  frames?: string[][]
  shade?: string
  /** Cast shadow ellipse [cx, cy, rx, ry] on the ground beneath. */
  shadow?: [number, number, number, number]
}

const LANTERN_BODY = (light: string, glow: string) => [
  '................',
  '......ss........',
  '....ssssss......',
  '..ssssssssss....',
  '.SSSSSSSSSSSS...',
  '...ssssssss.....',
  `...s${glow}${light}${light}${glow}s.....`.slice(0, 16).padEnd(16, '.'),
  `...s${light}${light}${light}${light}s.....`.slice(0, 16).padEnd(16, '.'),
  '...ssssssss.....',
  '....SSSSSS......',
  '.....ssss.......',
  '.....ssss.......',
  '.....ssss.......',
  '...ssssssss.....',
  '...SSSSSSSS.....',
  '................',
]

function shiftRight(rows: string[], n: number) {
  return rows.map((r) => ('.'.repeat(n) + r).slice(0, 16))
}

const LANTERN = (light: string, glow: string) => {
  const r = LANTERN_BODY(light, glow)
  // centre it (body is 12 wide starting at col 1)
  return shiftRight(r, 1).map((row, i) => (i === 6 || i === 7 ? row : row))
}

const FIRE = [
  [
    '................',
    '................',
    '.......x........',
    '......xex.......',
    '......xeex......',
    '.....xxeyex.....',
    '....xxeyyexx....',
    '....xeyllyex....',
    '....xeylllex....',
    '...Lx.eyye.xo...',
    '..LLoooOOoooo...',
    '...ooLLooOOoO...',
    '..sOOOoooOOOOs..',
    '..s.oo....oo.s..',
    '...ss......ss...',
    '................',
  ],
  [
    '................',
    '........x.......',
    '.......xx.......',
    '......xeex......',
    '.....xxeyx......',
    '.....xeyyexx....',
    '....xeyylyex....',
    '....xeylllyx....',
    '....xxeylyex....',
    '...Lx.eyye.xo...',
    '..LLoooOOoooo...',
    '...ooLLooOOoO...',
    '..sOOOoooOOOOs..',
    '..s.oo....oo.s..',
    '...ss......ss...',
    '................',
  ],
  [
    '................',
    '......x.........',
    '......xx........',
    '.....xeex.......',
    '.....xeyex......',
    '....xxeyyex.....',
    '....xeyllyexx...',
    '....xeylllyex...',
    '....xxeyllex....',
    '...Lx.eyye.xo...',
    '..LLoooOOoooo...',
    '...ooLLooOOoO...',
    '..sOOOoooOOOOs..',
    '..s.oo....oo.s..',
    '...ss......ss...',
    '................',
  ],
  [
    '................',
    '................',
    '........x.......',
    '.......xex......',
    '......xeex......',
    '.....xeyyxx.....',
    '....xxeyyyex....',
    '....xeyllyex....',
    '....xeyllyexx...',
    '...Lx.eyye.xo...',
    '..LLoooOOoooo...',
    '...ooLLooOOoO...',
    '..sOOOoooOOOOs..',
    '..s.oo....oo.s..',
    '...ss......ss...',
    '................',
  ],
]

const ALTAR = (c: string) => [
  '................',
  '..l.........l...',
  `..${c}.........${c}...`,
  '..p..ggg....p...',
  '..p.ggrgg...p...',
  '..p..ggg.pp.p...',
  'LLLLLLLLLLLLLLL.',
  'ooooooooooooooo.',
  '.OppppppppppppO.',
  '.OpvvpppppvvppO.',
  '.OppppppppppppO.',
  '.OOOOOOOOOOOOOO.',
  '.o.O........O.o.',
  '.o.O........O.o.',
  '.O.O........O.O.',
  '................',
]

const BAMBOO = (a: number) => {
  const leaf = a ? ['....g', '...gg', '..gg.'] : ['.g...', 'gg...', '.gg..']
  const base = [
    '..Rr.....Rr..Rr.',
    '..Rr.....Rr..Rr.',
    '..GG.....Rr..Rr.',
    '..Rr.....GG..Rr.',
    '..Rr.....Rr..Rr.',
    '..Rr.....Rr..GG.',
    '..Rr.....Rr..Rr.',
    '..Rr.....Rr..Rr.',
    '..Rr.....Rr..Rr.',
    '..GG.....Rr..Rr.',
    '..Rr.....GG..Rr.',
    '..Rr.....Rr..Rr.',
    '..Rr.....Rr..GG.',
    '..Rr.....Rr..Rr.',
    '..Rr.....Rr..Rr.',
    '..Rr.....Rr..Rr.',
  ]
  const rows = base.map((r) => r.split(''))
  const put = (x: number, y: number, m: string[]) =>
    m.forEach((r, j) => [...r].forEach((ch, i) => ch !== '.' && rows[y + j]?.[x + i] !== undefined && (rows[y + j][x + i] = ch)))
  put(3, 3, leaf)
  put(4, 10, leaf)
  put(10, 6, leaf.map((r) => [...r].reverse().join('')))
  return rows.map((r) => r.join(''))
}

export const PROPS: Record<string, PropDef> = {
  tree: {
    shade: 'r',
    shadow: [8, 14.5, 6, 1.6],
    rows: [
      '.....rrrrr......',
      '...rrrrrrrrr....',
      '..rrRrrrrrrrr...',
      '.rrRrrrrrgrrrr..',
      '.rrrrrrggrrrrrr.',
      '.rrrrgrrrrrrrrr.',
      '.rrggrrrrrrgrrr.',
      '.rrrrrrrrrggrrr.',
      '.rrrrrrgrrrrrrr.',
      '..rrrrggrrrrgr..',
      '..rrrrrrrrrgrr..',
      '...rrgrrrrrrr...',
      '.....rrooorr....',
      '.......oO.......',
      '......ooOO......',
      '................',
    ],
  },
  pine: {
    shade: 'g',
    shadow: [8, 14.5, 5, 1.4],
    rows: [
      '.......gg.......',
      '......gggg......',
      '.....gggggg.....',
      '....ggrggggg....',
      '......gggg......',
      '....ggggggggg...',
      '...ggrgggggggg..',
      '..gggggggggGggg.',
      '.....gggggg.....',
      '...grgggggggg...',
      '..gggggggggGgg..',
      '.gggggggggggGggg',
      '.....gGgGGgG....',
      '.......oO.......',
      '......ooOO......',
      '................',
    ],
  },
  sakura: {
    shade: 'h',
    shadow: [8, 14.5, 6, 1.6],
    rows: [
      '.....hhhhh......',
      '...hhhhhhhhh....',
      '..hhphhhhhhhh...',
      '.hhphhhhhHhhhh..',
      '.hhhhhhHHhhhhhh.',
      '.hhhhHhhhhhhhhh.',
      '.hhHHhhhhhhHhhh.',
      '.hhhhhhhhhHHhhh.',
      '.hhhhhhHhhhhhhh.',
      '..hhhhHHhhhhHh..',
      '..hhhhhhhhhHhh..',
      '...hhHhhOhhhh...',
      '.....hhOOOhh....',
      '.......OO.......',
      '......OOnn......',
      '................',
    ],
  },
  bamboo: { frames: [BAMBOO(0), BAMBOO(1)] },
  bush: {
    shade: 'r',
    shadow: [8, 14, 6, 1.5],
    rows: [
      '................',
      '................',
      '................',
      '................',
      '.....rrrr.......',
      '...rrrrrrrrr....',
      '..rrRrrrgrrrr...',
      '.rrRrrrgrrrrrr..',
      '.rrrrrrrrrrgrrr.',
      '.rrrgrrrrrrgrrr.',
      '.rrrrggrrrrrrrr.',
      '.rrrrrrrrgrrrr..',
      '..rrrrrrrrrrr...',
      '................',
      '................',
      '................',
    ],
  },
  rock: {
    shade: 's',
    shadow: [8, 13.5, 5, 1.3],
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '......sss.......',
      '....ssssss......',
      '...ssssssss.....',
      '..sssssSssss....',
      '..ssssssSsss....',
      '...ssssssss.....',
      '................',
      '................',
      '................',
    ],
  },
  boulder: {
    shade: 's',
    shadow: [8, 14.5, 7, 1.5],
    rows: [
      '................',
      '................',
      '.....sssss......',
      '...ssssssss.....',
      '..sssssssssss...',
      '..ssssssSsssss..',
      '.sssssssSsssss..',
      '.ssssssSssssSss.',
      '.ssgsssssssSsss.',
      '.sggssssssssss..',
      '.ssssSSsssssss..',
      '..sssssSsssssss.',
      '..ssssssssssss..',
      '....ssssssss....',
      '................',
      '................',
    ],
  },
  stump: {
    shade: 'o',
    shadow: [8, 13.5, 6, 1.4],
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '....aaaaaaa.....',
      '...aLLLLLLLa....',
      '...aLaaaaaLa....',
      '...aLLLLLLLa....',
      '...ooaaaaaoo....',
      '...oOoooooOo....',
      '...ooooOoooo....',
      '..ooooOooOooo...',
      '.oo..........o..',
      '................',
      '................',
    ],
  },
  sign: {
    shade: 'L',
    shadow: [8, 14.5, 3, 1],
    rows: [
      '................',
      '................',
      '................',
      '..LLLLLLLLLLLL..',
      '..LOOOLLOOOOLL..',
      '..LLLLLLLLLLLL..',
      '..LOOLOOOOLOLL..',
      '..LLLLLLLLLLLL..',
      '..oooooooooooo..',
      '.......Lo.......',
      '.......Lo.......',
      '.......Lo.......',
      '.......Lo.......',
      '.......Lo.......',
      '......LLoo......',
      '................',
    ],
  },
  lantern: {
    shade: 's',
    shadow: [8, 14.5, 5, 1.2],
    frames: [LANTERN('l', 'y'), LANTERN('y', 'e'), LANTERN('l', 'l'), LANTERN('y', 'y')],
  },
  well: {
    shade: 'so',
    shadow: [8, 14.5, 7, 1.3],
    rows: [
      '................',
      '..VVVVVVVVVVVV..',
      '.VvvvvvvvvvvvvV.',
      '..o....p.....o..',
      '..o....p.....o..',
      '..o...ooo....o..',
      '..o...oOo....o..',
      '..o..........o..',
      '..ssssssssssss..',
      '.sBBBBBBBBBBBBs.',
      '.sssssssssssss s'.replace(' ', '.').slice(0, 16),
      '.ssSssSssSssSss.',
      '.sssssssssssss..',
      '.SsSSsSSsSSsSSs.',
      '..SSSSSSSSSSSS..',
      '................',
    ],
  },
  'shrine-bell': {
    shade: 'yo',
    rows: [
      'OOOOOOOOOOOOOOOO',
      'oooooooooooooooo',
      '.......vv.......',
      '......yyyy......',
      '.....yyyyyy.....',
      '....yyyyyyyy....',
      '....yykkkkyy....',
      '.....yyyyyy.....',
      '.......pv.......',
      '.......vp.......',
      '.......pv.......',
      '.......vp.......',
      '.......pv.......',
      '......vpvp......',
      '......pvpv......',
      '.......vv.......',
    ],
  },
  statue: {
    shade: 's',
    shadow: [8, 14.5, 5, 1.2],
    rows: [
      '................',
      '................',
      '......ssss......',
      '.....ssssss.....',
      '.....sSssSs.....',
      '.....ssssss.....',
      '......ssss......',
      '....vvvvvvvv....',
      '....vvvvvvvv....',
      '.....vvvvvv.....',
      '....sssvvsss....',
      '....ssssssss....',
      '....ssssssss....',
      '...SSSSSSSSSS...',
      '...SSSSSSSSSS...',
      '................',
    ],
  },
  stall: {
    shade: 'o',
    shadow: [8, 15, 7, 1],
    rows: [
      'VvvpppvvvpppvvvV',
      'vvvpppvvvpppvvvv',
      'vvpppvvvpppvvvpp',
      'VPPVVVPPPVVVPPPV',
      '.P.V..P..V..P.V.',
      '.o............o.',
      '.o............o.',
      '.o..rr.ee.hhw.o.',
      '.o.rRr.eye.hh.o.',
      'LLLLLLLLLLLLLLLL',
      'oooooooooooooooo',
      'oOooOooOooOooOoo',
      'oooooooooooooooo',
      'OOOOOOOOOOOOOOOO',
      '.O............O.',
      '................',
    ],
  },
  barrel: {
    shade: 'o',
    shadow: [8, 14.5, 5, 1.2],
    rows: [
      '................',
      '................',
      '.....OOOOOO.....',
      '....OoooooOO....',
      '....SSSSSSSS....',
      '...oooooooooo...',
      '...oLooooooOo...',
      '...SSSSSSSSSS...',
      '...oLooooooOo...',
      '...oLooooooOo...',
      '...SSSSSSSSSS...',
      '....oooooooo....',
      '....oooooooo....',
      '.....oooooo.....',
      '................',
      '................',
    ],
  },
  crate: {
    shade: 'L',
    shadow: [8, 14.5, 6, 1.1],
    rows: [
      '................',
      '................',
      '................',
      '..LLLLLLLLLLLL..',
      '..LOOOOOOOOOOL..',
      '..LOLOOOOOOLOL..',
      '..LOOLOOOOLOOL..',
      '..LOOOLOOLOOOL..',
      '..LOOOOLLOOOOL..',
      '..LOOOOLLOOOOL..',
      '..LOOOLOOLOOOL..',
      '..LOOLOOOOLOOL..',
      '..LOLOOOOOOLOL..',
      '..LLLLLLLLLLLL..',
      '................',
      '................',
    ],
  },
  pot: {
    shade: 'd',
    shadow: [8, 14.5, 5, 1.2],
    rows: [
      '................',
      '................',
      '................',
      '.....dddddd.....',
      '....dNNNNNNd....',
      '.....dddddd.....',
      '....dddddddd....',
      '...dddddddddd...',
      '...ddpddddddd...',
      '...dppdddddddd..',
      '...dddddddddd...',
      '...dddddddddd...',
      '....dddddddd....',
      '.....dddddd.....',
      '................',
      '................',
    ],
  },
  chest: {
    shade: 'oy',
    shadow: [8, 14.5, 7, 1.2],
    rows: [
      '................',
      '................',
      '................',
      '....oooooooo....',
      '..oooooooooooo..',
      '.yoooooooooooy..',
      '.yooooooooooooy.',
      '.yyyyyyyyyyyyyy.',
      '.yoooookkoooooy.',
      '.yoooooyyoooooy.',
      '.yooooooooooooy.',
      '.yooooooooooooy.',
      '.yyyyyyyyyyyyyy.',
      '................',
      '................',
      '................',
    ],
  },
  'chest-open': {
    shade: 'oy',
    shadow: [8, 14.5, 7, 1.2],
    rows: [
      '................',
      '..oooooooooooo..',
      '.yoooooooooooo..',
      '.yooooooooooooy.',
      '.yyyyyyyyyyyyyy.',
      '.yOOOOOOOOOOOOy.',
      '.yOOOlOOOOOOOOy.',
      '.yyyyyyyyyyyyyy.',
      '.yoooooooooooooy'.slice(0, 16),
      '.yoooooooooooooy'.slice(0, 15) + '.',
      '.yooooooooooooy.',
      '.yooooooooooooy.',
      '.yyyyyyyyyyyyyy.',
      '................',
      '................',
      '................',
    ],
  },
  cave: {
    shade: 'o',
    rows: [
      'rrrRrrrrrrrRrrrr',
      'grrrrgrrrrrrgrrg',
      'oooOoooooOooooOo',
      'ooooOooooooooooo',
      'oOoooonnnnnoooOo',
      'ooooonnnnnnnoooo',
      'oOoonnkkkkknnooo',
      'ooonnkkkkkkknoOo',
      'oooonkkkkkkkknoo',
      'ooOnkkkkkkkkknoo',
      'ooonkkkkkkkkknoO',
      'oOonkkkkkkkkkknoo'.slice(0, 16),
      'ooonkkkkkkkkknoo',
      'oonkkkkkkkkkkkno',
      'onkkkkkkkkkkkkno',
      'OOOOOOOOOOOOOOOO',
    ],
  },
  'stairs-up': {
    shade: '',
    rows: [
      'SSSSSSSSSSSSSSSS',
      'SmmmmmmmmmmmmmmS',
      'SssssssssssssssS',
      'SSSSSSSSSSSSSSSS',
      'SmmmmmmmmmmmmmmS',
      'SssssssssssssssS',
      'SSSSSSSSSSSSSSSS',
      'SmmmmmmmmmmmmmmS',
      'SssssssssssssssS',
      'SSSSSSSSSSSSSSSS',
      'SppppppppppppppS',
      'SmmmmmmmmmmmmmmS',
      'SssssssssssssssS',
      'SSSSSSSSSSSSSSSS',
      'SppppppppppppppS',
      'SmmmmmmmmmmmmmmS',
    ],
  },
  'stairs-down': {
    rows: [
      'SmmmmmmmmmmmmmmS',
      'SssssssssssssssS',
      'SSSSSSSSSSSSSSSS',
      'SsmmmmmmmmmmmmsS',
      'SSssssssssssssSS',
      'SnSSSSSSSSSSSSnS',
      'SnsssssssssssnnS',
      'SnnSSSSSSSSSSnnS',
      'SnnnSSSSSSSSnnnS',
      'SnnnnnnnnnnnnnnS',
      'SnnnSnnnnnnSnnnS',
      'SnnnnnnnnnnnnnnS',
      'SkkkkkkkkkkkkkkS',
      'SkkkkkkkkkkkkkkS',
      'SkkkkkkkkkkkkkkS',
      'SkkkkkkkkkkkkkkS',
    ],
  },
  'gate-closed': {
    rows: [
      'mmmmmmmmmmmmmmmm',
      'OOOOOOOOOOOOOOOO',
      'OoooooOOOoooooOO',
      'OoyooyOOOoyooyoO',
      'OoooooOOOoooooOO',
      'OoooooOOOoooooOO',
      'OLLLLLOOOLLLLLOO',
      'OoooooOOOoooooOO',
      'OoyooyOOOoyooyoO',
      'OoooooOyOoooooOO',
      'OoooooOOOoooooOO',
      'OLLLLLOOOLLLLLOO',
      'OoooooOOOoooooOO',
      'OoyooyOOOoyooyoO',
      'OoooooOOOoooooOO',
      'OOOOOOOOOOOOOOOO',
    ],
  },
  'gate-open': {
    rows: [
      'mmmmmmmmmmmmmmmm',
      'OOOOOOOOOOOOOOOO',
      'OoLnnnnnnnnnnLoO',
      'OoLnnnnnnnnnnLoO',
      'OoLnkkkkkkkknLoO',
      'OoLnkkkkkkkknLoO',
      'OyLnkkkkkkkknLyO',
      'OoLnkkkkkkkknLoO',
      'OoLnkkkkkkkknLoO',
      'OoLnnkkkkkknnLoO',
      'OoLnnnnnnnnnnLoO',
      'OyLnnnnnnnnnnLyO',
      'OoLsssssssssssoO'.slice(0, 16),
      'OoLssssssssssLoO',
      'OoLmmmmmmmmmmLoO',
      'OOOSSSSSSSSSSOOO',
    ],
  },
  portal: {
    shade: 's',
    rows: [
      '....ssssssss....',
      '..sssssssssss...'.slice(0, 16),
      '.sss........sss.',
      '.ss..........ss.',
      'ss............ss',
      'ss............ss',
      'ss............ss',
      'ss............ss',
      'ss............ss',
      'ss............ss',
      'ss............ss',
      'ss............ss',
      'ss............ss',
      'ss............ss',
      'SS............SS',
      'SS............SS',
    ],
  },
  anvil: {
    shade: 'So',
    shadow: [8, 14.5, 6, 1.2],
    rows: [
      '................',
      '................',
      '................',
      '................',
      '.SSSSSSSSSSSS...',
      '..SSSSSSSSSSSSS.',
      '...SSSSSSSSSS...',
      '.....SSSSSS.....',
      '......SSSS......',
      '.....SSSSSS.....',
      '....oooooooo....',
      '...oooooooooo...',
      '...oOooooooOo...',
      '...oooooooooo...',
      '................',
      '................',
    ],
  },
  tablet: {
    shade: 's',
    shadow: [8, 14.5, 6, 1.2],
    rows: [
      '................',
      '.....ssssss.....',
      '....ssssssss....',
      '...ssssssssss...',
      '...ssSSSSSsss...',
      '...sssssssSss...',
      '...ssSSSSSSss...',
      '...sssSsSssss...',
      '...ssSSSSSsss...',
      '...ssSsssSsss...',
      '...ssSSSSSsss...',
      '...ssssssssss...',
      '...gssssssssg...',
      '..ggssssssssgg..',
      '..SSSSSSSSSSSS..',
      '................',
    ],
  },
  bookshelf: {
    shade: '',
    rows: [
      'OOOOOOOOOOOOOOOO',
      'OoooooooooooooOO',
      'OvbbyyrVbuuyvvoO',
      'OvbbyyrVbuuyvvoO',
      'OvbbyyrVbuuyvvoO',
      'OOOOOOOOOOOOOOOO',
      'OouuvvrrybbVyyoO',
      'OouuvvrrybbVyyoO',
      'OouuvvrrybbVyyoO',
      'OOOOOOOOOOOOOOOO',
      'OoyybbuVvvryrroO',
      'OoyybbuVvvryrroO',
      'OoyybbuVvvryrroO',
      'OOOOOOOOOOOOOOOO',
      'OoooooooooooooOO',
      'OOOOOOOOOOOOOOOO',
    ],
  },
  altar: {
    shade: 'Lo',
    shadow: [8, 15, 7, 1],
    frames: [ALTAR('y'), ALTAR('l'), ALTAR('e')],
  },
  throne: {
    shade: 'Vy',
    shadow: [8, 15, 6, 1],
    rows: [
      '.....y..y.......',
      '....yyyyyyy.....',
      '...yVVVVVVVy....',
      '...yVvvvvvVy....',
      '...yVvvyvvVy....',
      '...yVvvvvvVy....',
      '...yVvvvvvVy....',
      '.yyyVvvvvvVyyy..',
      '.yVVVVVVVVVVVy..',
      '.yyVvvvvvvvVyy..',
      '..yyyyyyyyyyy...',
      '..yVVVVVVVVVy...',
      '..yVVVVVVVVVy...',
      '..yyyyyyyyyyy...',
      '..y.........y...',
      '................',
    ],
  },
  campfire: {
    frames: FIRE,
    shade: '',
    shadow: [8, 13.5, 6, 1.3],
  },
}
