/**
 * Region 7 — 湯の里, the Hot-Spring Hollow. A mountain village of steam,
 * wooden inns, bamboo and snow monkeys, strung across a gorge by a rope
 * bridge. The Yamanba has knotted the village's verbs: nobody can say what
 * they did yesterday, ask if they may, or tell anyone what they must not.
 *
 * Teaches the plain past (た・なかった・だった), the て-form and how to make
 * it (verb groups and the sound changes って・んで・いて・いで・して), and
 * what the て-form unlocks: 〜ている, 〜てもいいですか, 〜てはいけません,
 * 〜てから, linking actions with て — plus 〜たことがある for experience.
 * Vocabulary: the inn and the bath, the body, the mountain, everyday verbs,
 * feelings and the recent past.
 */
import type { RegionData } from '../types'

export const DATA: RegionData = {
  region: {
    id: 7,
    name: 'The Hot-Spring Hollow',
    jp: '湯の里',
    reading: 'ゆのさと',
    tagline: 'Steam on the snow, a bath at dusk, and yesterday told true.',
    teaches: ['The て-form and its sound changes', 'Plain past た・なかった・だった', '〜ている, 〜てもいい, 〜てはいけません, 〜てから, 〜たことがある'],
    color: '#e58f65',
    emoji: '♨️',
    pos: { x: 62, y: 66 },
    map: 'onsen',
  },

  words: [
    // ── The Inn and the Bath
    ['onsen', '温泉', 'おんせん', 'hot spring', 'noun', '♨️', { element: 'water', alt: ['hot springs', 'onsen', 'spa'] }],
    ['ryokan', '旅館', 'りょかん', 'Japanese inn', 'noun', '🏯', { alt: ['inn', 'ryokan', 'traditional inn'] }],
    ['okami', '女将', 'おかみ', 'proprietress', 'noun', '👘', { alt: ['landlady', 'okami', 'hostess', 'innkeeper'] }],
    ['oyu', 'お湯', 'おゆ', 'hot water', 'noun', '🫖', { element: 'water', alt: ['warm water', 'bath water'] }],
    ['ofuro', 'お風呂', 'おふろ', 'bath', 'noun', '🛁', { element: 'water', alt: ['bathtub', 'a bath'] }],
    ['ashiyu', '足湯', 'あしゆ', 'footbath', 'noun', '🦶', { element: 'water', alt: ['foot bath'] }],
    ['heya', '部屋', 'へや', 'room', 'noun', '🚪'],
    ['tatami', '畳', 'たたみ', 'tatami mat', 'noun', '🟩', { alt: ['tatami', 'straw mat'] }],
    ['futon', '布団', 'ふとん', 'futon', 'noun', '🛏️', { alt: ['bedding', 'bed'] }],
    ['yukata', '浴衣', 'ゆかた', 'yukata', 'noun', '🎐', { alt: ['cotton kimono', 'summer kimono', 'bathrobe'] }],
    ['taoru', 'タオル', 'タオル', 'towel', 'noun', '🧣'],
    ['sekken', '石けん', 'せっけん', 'soap', 'noun', '🧼'],
    ['kutsu', '靴', 'くつ', 'shoes', 'noun', '👞', { alt: ['shoe'] }],
    ['mado', '窓', 'まど', 'window', 'noun', '🪟'],
    ['shokuji', '食事', 'しょくじ', 'meal', 'noun', '🍱', { alt: ['dinner', 'food'] }],

    // ── Verbs of the Bath (the て-form lives here)
    ['aruku', '歩く', 'あるく', 'walk', 'verb', '👣', { masu: '歩きます', alt: ['to walk'] }],
    ['hairu', '入る', 'はいる', 'enter', 'verb', '🚪', { masu: '入ります', alt: ['go in', 'get in', 'to enter', 'take a bath'] }],
    ['deru', '出る', 'でる', 'go out', 'verb', '🏃', { masu: '出ます', alt: ['leave', 'exit', 'get out', 'to go out'] }],
    ['ireru', '入れる', 'いれる', 'put in', 'verb', '📥', { masu: '入れます', alt: ['insert', 'to put in'] }],
    ['arau', '洗う', 'あらう', 'wash', 'verb', '🧽', { masu: '洗います', alt: ['to wash'] }],
    ['yasumu', '休む', 'やすむ', 'take a rest', 'verb', '😌', { masu: '休みます', alt: ['rest', 'to rest', 'take a break'] }],
    ['oyogu', '泳ぐ', 'およぐ', 'swim', 'verb', '🏊', { masu: '泳ぎます', alt: ['to swim'] }],
    ['suwaru', '座る', 'すわる', 'sit', 'verb', '🪑', { masu: '座ります', alt: ['sit down', 'to sit'] }],
    ['tatsu', '立つ', 'たつ', 'stand', 'verb', '🧍', { masu: '立ちます', alt: ['stand up', 'to stand'] }],
    ['kiru-wear', '着る', 'きる', 'wear', 'verb', '👘', { masu: '着ます', alt: ['put on', 'to wear', 'dress'] }],
    ['nugu', '脱ぐ', 'ぬぐ', 'take off', 'verb', '🥾', { masu: '脱ぎます', alt: ['undress', 'remove', 'to take off'] }],
    ['noboru', '登る', 'のぼる', 'climb', 'verb', '🧗', { masu: '登ります', alt: ['go up', 'to climb'] }],
    ['asobu', '遊ぶ', 'あそぶ', 'play', 'verb', '🤸', { masu: '遊びます', alt: ['have fun', 'to play'] }],
    ['toru', '撮る', 'とる', 'take (a photo)', 'verb', '📷', { masu: '撮ります', alt: ['take a photo', 'take a picture', 'photograph', 'to take a photo'] }],
    ['tsukareru', '疲れる', 'つかれる', 'get tired', 'verb', '😮‍💨', { masu: '疲れます', alt: ['be tired', 'tire', 'to get tired'] }],

    // ── Mountain and Body
    ['karada', '体', 'からだ', 'body', 'noun', '🧍'],
    ['atama', '頭', 'あたま', 'head', 'noun', '🙆'],
    ['ashi', '足', 'あし', 'foot', 'noun', '🦵', { alt: ['leg', 'feet', 'legs'] }],
    ['kao', '顔', 'かお', 'face', 'noun', '😊'],
    ['kata', '肩', 'かた', 'shoulder', 'noun', '💪', { alt: ['shoulders'] }],
    ['senaka', '背中', 'せなか', 'back', 'noun', '🎒', { alt: ['back of the body'] }],
    ['kami-hair', '髪', 'かみ', 'hair', 'noun', '💇', { alt: ['hair (on the head)'] }],
    ['saru', '猿', 'さる', 'monkey', 'noun', '🐒', { alt: ['ape', 'snow monkey'] }],
    ['take', '竹', 'たけ', 'bamboo', 'noun', '🎋', { element: 'wood' }],
    ['taki', '滝', 'たき', 'waterfall', 'noun', '💦', { element: 'water', alt: ['falls'] }],
    ['tani', '谷', 'たに', 'valley', 'noun', '🏞️', { element: 'earth', alt: ['gorge', 'ravine'] }],
    ['yuge', '湯気', 'ゆげ', 'steam', 'noun', '🌫️', { element: 'water', alt: ['vapor', 'vapour'] }],
    ['tsuribashi', 'つり橋', 'つりばし', 'rope bridge', 'noun', '🌉', { element: 'wood', alt: ['suspension bridge'] }],
    ['saka', '坂', 'さか', 'slope', 'noun', '⛰️', { element: 'earth', alt: ['hill', 'incline'] }],
    ['kitsune', '狐', 'きつね', 'fox', 'noun', '🦊'],

    // ── Yesterday's Steam: feelings, adverbs and the recent past
    ['atatakai', '温かい', 'あたたかい', 'warm', 'i-adj', '🌡️', { alt: ['warm (to the touch)'] }],
    ['kimochiii', '気持ちいい', 'きもちいい', 'feels good', 'i-adj', '😊', { alt: ['pleasant', 'comfortable', 'feel good', 'nice'] }],
    ['itai', '痛い', 'いたい', 'painful', 'i-adj', '🤕', { alt: ['it hurts', 'sore', 'hurts'] }],
    ['nemui', '眠い', 'ねむい', 'sleepy', 'i-adj', '😪', { alt: ['drowsy'] }],
    ['yukkuri', 'ゆっくり', 'ゆっくり', 'slowly', 'adverb', '🐌', { alt: ['leisurely', 'at ease', 'take your time'] }],
    ['issho', '一緒に', 'いっしょに', 'together', 'adverb', '🫂', { alt: ['with someone'] }],
    ['saki-ni', '先に', 'さきに', 'first', 'adverb', '⏩', { alt: ['ahead', 'beforehand', 'before'] }],
    ['ato-de', '後で', 'あとで', 'later', 'adverb', '🔜', { alt: ['afterwards', 'after'] }],
    ['mada', 'まだ', 'まだ', 'still', 'adverb', '⏸️', { alt: ['not yet', 'yet'] }],
    ['mou', 'もう', 'もう', 'already', 'adverb', '✅', { alt: ['anymore'] }],
    ['kinou', '昨日', 'きのう', 'yesterday', 'noun', '⏪'],
    ['kesa', '今朝', 'けさ', 'this morning', 'noun', '🌄'],
    ['senshuu', '先週', 'せんしゅう', 'last week', 'noun', '🗓️'],
    ['sengetsu', '先月', 'せんげつ', 'last month', 'noun', '📆'],
    ['hajimete', '初めて', 'はじめて', 'for the first time', 'adverb', '🌱', { alt: ['first time', 'the first time'] }],
  ],

  grammar: [
    { id: 'verb-groups', region: 7, jp: 'る・う・する／くる', say: 'ru-verbs, u-verbs, the two irregulars', en: 'three verb groups: る-verbs (たべる, きる: an e/i sound before る), う-verbs (all the rest, plus look-alikes like はいる, かえる) and the irregulars する and くる', example: { jp: 'たべる（る）・のむ（う）・はいる（う！）', en: 'taberu is a る-verb, nomu a う-verb, and hairu a う-verb in disguise' } },
    { id: 'te-ru', region: 7, jp: 'る → て', say: 'ru-verbs: drop る, add te', en: 'る-verbs make the て-form by swapping る for て', example: { jp: 'たべる → たべて・きる → きて', en: 'eat → eating…, wear → wearing…' } },
    { id: 'te-tte', region: 7, jp: 'う・つ・る → って', say: '-tte', en: 'う-verbs ending in う, つ or る make って', example: { jp: 'かう → かって・たつ → たって・はいる → はいって', en: 'buy, stand, enter' } },
    { id: 'te-nde', region: 7, jp: 'む・ぶ・ぬ → んで', say: '-nde', en: 'う-verbs ending in む, ぶ or ぬ make んで', example: { jp: 'のむ → のんで・あそぶ → あそんで', en: 'drink, play' } },
    { id: 'te-ite', region: 7, jp: 'く → いて・ぐ → いで', say: '-ite / -ide', en: 'く makes いて and ぐ makes いで; the one exception is いく → いって', example: { jp: 'あるく → あるいて・およぐ → およいで', en: 'walk, swim' } },
    { id: 'te-shite', region: 7, jp: 'す → して・する → して・くる → きて', say: '-shite, and the irregulars', en: 'す-verbs make して; the irregulars する → して and くる → きて', example: { jp: 'はなす → はなして・くる → きて', en: 'speak, come' } },
    { id: 'te-chain', region: 7, jp: '〜て、〜て、〜ます', say: 'te … te … masu', en: 'link actions in order with て; only the last verb shows the tense', example: { jp: 'あさ おきて、かおを あらって、ごはんを たべます。', en: 'In the morning I get up, wash my face and eat breakfast.' } },
    { id: 'te-iru', region: 7, jp: '〜ている', say: 'te iru', en: 'is doing (an action going on) or is in a state (the result of an action)', example: { jp: 'さるが ゆに はいっています。', en: 'A monkey is in the hot water.' } },
    { id: 'te-kara', region: 7, jp: '〜てから', say: 'te kara', en: 'after doing ~, (then …)', example: { jp: 'からだを あらってから、ゆに はいります。', en: 'I wash my body, and then I get into the bath.' } },
    { id: 'te-mo-ii', region: 7, jp: '〜てもいいですか', say: 'te mo ii desu ka', en: 'may I ~? (asking permission); yes: はい、どうぞ', example: { jp: 'ここに すわっても いいですか。', en: 'May I sit here?' } },
    { id: 'te-wa-ikemasen', region: 7, jp: '〜てはいけません', say: 'te wa ikemasen', en: 'you must not ~ (a rule, a prohibition)', example: { jp: 'ゆに タオルを いれては いけません。', en: 'You must not put towels in the bath water.' } },
    { id: 'ta-form', region: 7, jp: '〜た', say: 'ta', en: 'did (plain past): make the て-form, then て → た and で → だ', example: { jp: 'きのう、たきまで あるいた。', en: 'Yesterday I walked to the waterfall.' } },
    { id: 'nakatta', region: 7, jp: '〜なかった', say: 'nakatta', en: 'didn’t (plain past negative): the ない-form with い → かった (る-verbs drop る: たべない; う-verbs go to the あ-sound: はいらない, かわない)', example: { jp: 'けさは おふろに はいらなかった。', en: 'I didn’t take a bath this morning.' } },
    { id: 'datta', region: 7, jp: '〜だった・〜じゃなかった', say: 'datta / ja nakatta', en: 'was / wasn’t (plain past of nouns and な-adjectives)', example: { jp: 'きのうの おんせんは しずかだった。', en: 'The hot spring was quiet yesterday.' } },
    { id: 'ta-koto', region: 7, jp: '〜たことがある', say: 'ta koto ga aru', en: 'have done ~ (at some time, as an experience)', example: { jp: 'さるを みた ことが あります。', en: 'I have seen a monkey before.' } },
  ],

  sentences: [
    { id: 'y1', en: 'I wash my body, then get into the bath.', tokens: ['体', 'を', '洗って', 'から', 'お風呂', 'に', '入ります'], distractors: ['洗いて', 'で'], region: 7, hint: 'てから = “after doing”. 洗う ends in う, so its て-form is 洗って.' },
    { id: 'y2', en: 'May I sit here?', tokens: ['ここ', 'に', '座っても', 'いいですか'], distractors: ['座っては', 'を'], region: 7, hint: '〜てもいいですか asks permission: 座る → 座って + も いいですか.' },
    { id: 'y3', en: 'You must not put a towel in the hot water.', tokens: ['タオル', 'を', 'お湯', 'に', '入れては', 'いけません'], distractors: ['入れても', 'で'], region: 7, hint: '〜てはいけません forbids. 入れる (put in) is a る-verb: 入れて.' },
    { id: 'y4', en: 'A monkey is in the hot spring.', tokens: ['猿', 'が', '温泉', 'に', '入っています'], distractors: ['入れています', 'を'], region: 7, hint: '入る → 入って + います: it went in, and now it is in.' },
    { id: 'y5', en: 'I have been to a hot spring before.', tokens: ['温泉', 'に', '行った', 'ことが', 'あります'], alts: [['温泉', 'へ', '行った', 'ことが', 'あります']], distractors: ['行きた', 'を'], region: 7, hint: '〜たことがある = have done it before. 行く is special: 行って, 行った.' },
    { id: 'y6', en: 'Yesterday I walked as far as the waterfall.', tokens: ['昨日', '滝', 'まで', '歩いた'], distractors: ['歩きた', 'を'], region: 7, hint: '歩く: く → いて, so the plain past is 歩いた. まで = as far as.' },
    { id: 'y7', en: 'I didn’t have a meal this morning.', tokens: ['今朝', 'ご飯', 'を', '食べなかった'], distractors: ['食べないた', 'が'], region: 7, hint: 'Plain past negative: 食べない → 食べなかった.' },
    { id: 'y8', en: 'The hot water was warm.', tokens: ['お湯', 'は', '温かかった', 'です'], distractors: ['温かいだった', 'な'], region: 7, hint: 'い-adjectives make their past with かった, never だった.' },
    { id: 'y9', en: 'I take off my shoes, go in and sit down.', tokens: ['靴', 'を', '脱いで', '入って', '座ります'], distractors: ['脱ぎて', '入りて'], region: 7, hint: 'Chain actions with て: 脱ぐ → 脱いで, 入る → 入って. Only the last verb ends in ます.' },
    { id: 'y10', en: 'Please put on the yukata.', tokens: ['浴衣', 'を', '着て', 'ください'], distractors: ['切って', 'に'], region: 7, hint: '着る (wear) is a る-verb: 着て. 切って means “cut”!' },
    { id: 'y11', en: 'I climbed the mountain and got tired.', tokens: ['山', 'に', '登って', '疲れた'], distractors: ['登りて', 'を'], region: 7, hint: 'て links one thing to the next: 登る → 登って.' },
    { id: 'y12', en: 'The monkeys are playing in the snow.', tokens: ['猿', 'が', '雪', 'の', '中', 'で', '遊んでいます'], distractors: ['遊びています', 'に'], region: 7, hint: '遊ぶ: ぶ → んで. で marks where the playing happens.' },
    { id: 'y13', en: 'You must not swim in the bath.', tokens: ['お風呂', 'で', '泳いでは', 'いけません'], distractors: ['泳ぎては', 'に'], region: 7, hint: '泳ぐ: ぐ → いで, so 泳いでは いけません.' },
    { id: 'y14', en: 'Last week I went to an inn with a friend.', tokens: ['先週', '友達', 'と', '旅館', 'に', '行った'], alts: [['先週', '友達', 'と', '旅館', 'へ', '行った'], ['先週', '旅館', 'に', '友達', 'と', '行った']], distractors: ['行きた', 'を'], region: 7, hint: '行く is the one く-verb that takes って: 行って, 行った.' },
    { id: 'y15', en: 'Have you ever seen a waterfall?', tokens: ['滝', 'を', '見た', 'ことが', 'ありますか'], distractors: ['見って', 'に'], region: 7, hint: '見る is a る-verb: 見た. 〜たことがありますか asks about experience.' },
  ],

  runes: [
    { id: 'y-r1', jp: '温泉に入ったことがあります', reading: 'おんせんにはいったことがあります', answer: 'I have been in a hot spring before.', wrong: ['I am in a hot spring now.', 'I want to go into a hot spring.'], region: 7 },
    { id: 'y-r2', jp: 'ここで泳いではいけません', reading: 'ここでおよいではいけません', answer: 'You must not swim here.', wrong: ['You may swim here.', 'Please swim over here.'], region: 7 },
    { id: 'y-r3', jp: '猿がお湯に入っています', reading: 'さるがおゆにはいっています', answer: 'A monkey is in the hot water.', wrong: ['A monkey got into the hot water yesterday.', 'A monkey is washing in the river.'], region: 7 },
    { id: 'y-r4', jp: '体を洗ってから、入ってください', reading: 'からだをあらってから、はいってください', answer: 'Please wash your body before you get in.', wrong: ['Please get in, then wash your body.', 'Please don’t wash your body.'], region: 7 },
    { id: 'y-r5', jp: '昨日は疲れた', reading: 'きのうはつかれた', answer: 'I was tired yesterday.', wrong: ['I am tired today.', 'I wasn’t tired yesterday.'], region: 7 },
    { id: 'y-r6', jp: '靴を脱いでもいいですか', reading: 'くつをぬいでもいいですか', answer: 'May I take off my shoes?', wrong: ['Please take off your shoes.', 'I took off my shoes.'], region: 7 },
    { id: 'y-r7', jp: '先週、滝まで歩いた', reading: 'せんしゅう、たきまであるいた', answer: 'Last week I walked as far as the waterfall.', wrong: ['Next week I will walk to the waterfall.', 'Last week I swam under the waterfall.'], region: 7 },
    { id: 'y-r8', jp: '浴衣を着て、部屋で休んでいます', reading: 'ゆかたをきて、へやでやすんでいます', answer: 'I’ve put on a yukata and I’m resting in my room.', wrong: ['I’m taking off my yukata in the bath.', 'I put on a yukata and rested in my room yesterday.'], region: 7 },
    { id: 'y-r9', jp: '今朝、お風呂に入らなかった', reading: 'けさ、おふろにはいらなかった', answer: 'I didn’t take a bath this morning.', wrong: ['I took a bath this morning.', 'I won’t take a bath tomorrow morning.'], region: 7 },
  ],

  readings: {
    洗って: 'あらって',
    洗いて: 'あらいて',
    座っても: 'すわっても',
    座っては: 'すわっては',
    入れては: 'いれては',
    入れても: 'いれても',
    入っています: 'はいっています',
    入れています: 'いれています',
    行った: 'いった',
    行きた: 'いきた',
    歩いた: 'あるいた',
    歩きた: 'あるきた',
    食べなかった: 'たべなかった',
    食べないた: 'たべないた',
    温かかった: 'あたたかかった',
    温かいだった: 'あたたかいだった',
    脱いで: 'ぬいで',
    脱ぎて: 'ぬぎて',
    入って: 'はいって',
    入りて: 'はいりて',
    着て: 'きて',
    切って: 'きって',
    登って: 'のぼって',
    登りて: 'のぼりて',
    疲れた: 'つかれた',
    遊んでいます: 'あそんでいます',
    遊びています: 'あそびています',
    泳いでは: 'およいでは',
    泳ぎては: 'およぎては',
    見た: 'みた',
    見って: 'みって',
  },

  npcs: [
    {
      id: 'okami',
      name: 'Haruko the Proprietress',
      jp: 'おかみの はるこ',
      emoji: '👘',
      region: 7,
      personality: 'The calm, sharp-eyed proprietress (okami) of the oldest inn in the Hot-Spring Hollow. Gracious and polite to every guest, quietly strict about the bath rules, and secretly very funny. Has run the inn since she was nineteen and knows every snow monkey by name.',
      politeness: 'polite',
      color: '#e58f65',
      interests: ['the hot springs', 'the inn', 'what guests did today', 'the snow monkeys', 'bath manners'],
      greeting: { jp: 'いらっしゃいませ。ようこそ。', en: 'Welcome. Please, come in.' },
    },
    {
      id: 'bathboy',
      name: 'Jiro the Bath-House Boy',
      jp: 'ゆやの じろう',
      emoji: '🧒',
      region: 7,
      personality: 'Haruko’s cheeky twelve-year-old son, who keeps the counter at the public bath-house. Talks fast and casually, quizzes every visitor on the bath rules, and is very proud that the monkeys trust him.',
      politeness: 'casual',
      color: '#f2b37a',
      interests: ['the bath rules', 'monkeys', 'what you did yesterday', 'swimming (secretly)'],
      greeting: { jp: 'へい、いらっしゃい！', en: 'Hey, come on in!' },
    },
  ],

  scenarios: [
    {
      id: 'onsen-checkin',
      npcId: 'okami',
      region: 7,
      translations: 'always',
      start: 'greet',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Check in at the oldest inn of the Hot-Spring Hollow. Haruko, the proprietress, is polite, kind and very particular.',
        'Use the て-form: 〜てから (after doing), 〜てもいいですか (may I?), 〜てはいけません (must not).',
        'Pick your reply. Wrong answers cost a ❤️.',
      ],
      nodes: {
        greet: {
          id: 'greet',
          line: { jp: 'いらっしゃいませ。湯の里へ ようこそ。', en: 'Welcome. Welcome to the Hot-Spring Hollow.' },
          kana: 'いらっしゃいませ。ゆのさとへ ようこそ。',
          wordIds: ['ryokan', 'okami'],
          next: 'shoes',
          options: [
            { jp: 'こんばんは。おせわに なります。', en: 'Good evening. Thank you for having me.', correct: true, reply: { jp: 'まあ、ごていねいに。', en: 'Oh, how polite of you.' }, effects: { trust: 1 } },
            { jp: 'こんばんは。', en: 'Good evening.', correct: true, reply: { jp: 'はい、こんばんは。', en: 'Good evening to you.' } },
            { jp: 'いただきます。', en: 'Thanks for the food!', correct: false, reply: { jp: 'ごはんは まだですよ。', en: 'Dinner isn’t ready yet.' }, note: 'いただきます is said before eating. When you arrive at an inn, おせわに なります (thank you for having me) is perfect.' },
          ],
        },
        shoes: {
          id: 'shoes',
          line: { jp: 'どうぞ、ここで 靴を 脱いで ください。', en: 'Please take off your shoes here.' },
          kana: 'どうぞ、ここで くつを ぬいで ください。',
          wordIds: ['kutsu', 'nugu'],
          hint: '脱ぐ ends in ぐ, so its て-form is 脱いで. 〜てから = after doing.',
          next: 'yukata',
          options: [
            { jp: 'はい。靴を 脱いでから 入ります。', kana: 'はい。くつを ぬいでから はいります。', en: 'Yes. I’ll take off my shoes, then come in.', correct: true, wordIds: ['kutsu', 'nugu', 'hairu'], reply: { jp: 'ありがとう ございます。', en: 'Thank you very much.' }, effects: { trust: 1 } },
            { jp: 'はい。靴を 脱ぎてから 入ります。', kana: 'はい。くつを ぬぎてから はいります。', en: 'Yes. (wrong て-form of 脱ぐ)', correct: false, wordIds: ['nugu'], reply: { jp: '…ぬぎて？', en: '…Nugite?' }, note: '脱ぐ ends in ぐ: ぐ → いで. The て-form is 脱いで.' },
            { jp: '靴で 入っても いいですか。', kana: 'くつで はいっても いいですか。', en: 'May I come in with my shoes on?', correct: false, wordIds: ['kutsu', 'hairu'], reply: { jp: 'いいえ、靴で 入っては いけません！', en: 'No, you must not come in wearing shoes!' }, note: 'Never wear outdoor shoes on wooden floors or tatami at an inn. Take them off at the entrance.' },
          ],
        },
        yukata: {
          id: 'yukata',
          line: { jp: 'お部屋に 浴衣が あります。', en: 'There is a yukata in your room.' },
          kana: 'おへやに ゆかたが あります。',
          wordIds: ['yukata', 'heya'],
          hint: 'Ask permission: 着る is a る-verb, so 着て + も いいですか.',
          next: 'rules',
          options: [
            { jp: '浴衣を 着て、お風呂に 行っても いいですか。', kana: 'ゆかたを きて、おふろに いっても いいですか。', en: 'May I put on the yukata and go to the bath?', correct: true, wordIds: ['yukata', 'kiru-wear', 'ofuro'], reply: { jp: 'はい、どうぞ。', en: 'Yes, of course.' }, effects: { trust: 1 } },
            { jp: '浴衣を 切っても いいですか。', kana: 'ゆかたを きっても いいですか。', en: 'May I cut the yukata?', correct: false, wordIds: ['yukata'], reply: { jp: 'き、切っては いけません！', en: 'Y-you must not cut it!' }, note: '切る (cut) is a う-verb: 切って. 着る (wear) is a る-verb: 着て. Same sound, very different meaning!' },
            { jp: '浴衣を 着りても いいですか。', kana: 'ゆかたを きりても いいですか。', en: 'May I (wrong form) the yukata?', correct: false, wordIds: ['kiru-wear'], reply: { jp: 'きりて…？', en: 'Kirite…?' }, note: '着る is a る-verb: drop る and add て → 着て.' },
          ],
        },
        rules: {
          id: 'rules',
          line: { jp: 'お風呂の きまりは わかりますか。', en: 'Do you know the bath rules?' },
          kana: 'おふろの きまりは わかりますか。',
          wordIds: ['ofuro', 'arau', 'karada'],
          hint: 'At a hot spring you wash first, then get in: 洗ってから.',
          next: 'towel',
          options: [
            { jp: 'はい。体を 洗ってから、お湯に 入ります。', kana: 'はい。からだを あらってから、おゆに はいります。', en: 'Yes. I wash my body, then get into the water.', correct: true, wordIds: ['karada', 'arau', 'oyu', 'hairu'], reply: { jp: 'そのとおりです。', en: 'Exactly right.' }, effects: { trust: 1 } },
            { jp: 'はい。お湯に 入ってから、体を 洗います。', kana: 'はい。おゆに はいってから、からだを あらいます。', en: 'Yes. I get in, then wash my body.', correct: false, wordIds: ['karada', 'arau'], reply: { jp: 'あら、はんたいですよ。', en: 'Oh dear, that’s backwards.' }, note: 'Everyone shares the bath water, so you wash BEFORE getting in: 洗ってから入ります.' },
            { jp: 'はい。お湯の 中で 体を 洗います。', kana: 'はい。おゆの なかで からだを あらいます。', en: 'Yes. I wash my body in the bath water.', correct: false, wordIds: ['arau'], reply: { jp: 'それは だめです！', en: 'That is not allowed!' }, note: 'Never wash with soap in the bath itself. Wash at the taps, rinse, then get in.' },
          ],
        },
        towel: {
          id: 'towel',
          line: { jp: 'では、タオルは？', en: 'And the towel?' },
          wordIds: ['taoru', 'ireru'],
          hint: 'A towel never goes into the water: 入れては いけません.',
          next: 'before',
          options: [
            { jp: 'タオルを お湯に 入れては いけません。', kana: 'タオルを おゆに いれては いけません。', en: 'You must not put a towel in the water.', correct: true, wordIds: ['taoru', 'ireru', 'oyu'], reply: { jp: 'すばらしい。頭の 上に のせても いいですよ。', en: 'Splendid. You may put it on your head, though.' }, effects: { trust: 1 } },
            { jp: 'タオルを お湯に 入れても いいです。', kana: 'タオルを おゆに いれても いいです。', en: 'It’s fine to put a towel in the water.', correct: false, wordIds: ['taoru', 'ireru'], reply: { jp: 'いいえ、いけません。', en: 'No, it is not.' }, note: '〜てもいいです permits. A towel in the water is forbidden: 入れては いけません.' },
            { jp: 'タオルを お湯に 入って ください。', kana: 'タオルを おゆに はいって ください。', en: 'Please enter the towel into the water.', correct: false, wordIds: ['hairu'], reply: { jp: 'タオルが お風呂に 入るんですか？', en: 'The towel takes a bath?' }, note: '入る = go in (yourself). 入れる = put something in. And towels stay out of the water.' },
          ],
        },
        before: {
          id: 'before',
          line: { jp: '温泉に 入った ことが ありますか。', en: 'Have you ever been in a hot spring?' },
          kana: 'おんせんに はいった ことが ありますか。',
          wordIds: ['onsen', 'hairu', 'hajimete'],
          hint: 'An experience question (〜たことがありますか): answer はい、あります or いいえ、はじめてです.',
          next: 'today',
          options: [
            { jp: 'いいえ、初めてです。', kana: 'いいえ、はじめてです。', en: 'No, this is my first time.', correct: true, wordIds: ['hajimete'], reply: { jp: 'まあ、うれしい。ゆっくり どうぞ。', en: 'How lovely. Take your time and enjoy it.' }, effects: { trust: 1 } },
            { jp: 'はい、あります。', en: 'Yes, I have.', correct: true, reply: { jp: 'では、ここの お湯と くらべて みて くださいね。', en: 'Then do compare our water with the others.' } },
            { jp: 'はい、入ります。', kana: 'はい、はいります。', en: 'Yes, I’ll get in.', correct: false, wordIds: ['hairu'], reply: { jp: 'いえ、まえに 入った ことが あるか、ききました。', en: 'No — I asked whether you have ever been in one before.' }, note: '〜たことがありますか asks about experience. Answer with あります / ありません, or 初めてです (it’s my first time).' },
          ],
        },
        today: {
          id: 'today',
          line: { jp: '今日は どこへ 行きましたか。', en: 'Where did you go today?' },
          kana: 'きょうは どこへ いきましたか。',
          wordIds: ['taki', 'aruku', 'saru'],
          hint: 'Link two actions with て: 歩く → 歩いて (く → いて).',
          next: 'rest',
          options: [
            { jp: '滝まで 歩いて、猿を 見ました。', kana: 'たきまで あるいて、さるを みました。', en: 'I walked to the waterfall and saw monkeys.', correct: true, wordIds: ['taki', 'aruku', 'saru'], reply: { jp: 'いいですね。猿は げんきでしたか。', en: 'How nice. Were the monkeys well?' }, effects: { trust: 1 } },
            { jp: '滝まで 歩きて、猿を 見ました。', kana: 'たきまで あるきて、さるを みました。', en: 'I (wrong form) to the waterfall and saw monkeys.', correct: false, wordIds: ['aruku'], reply: { jp: 'あるきて…？', en: 'Arukite…?' }, note: '歩く ends in く: く → いて. The て-form is 歩いて.' },
            { jp: '明日、滝まで 歩きました。', kana: 'あした、たきまで あるきました。', en: 'Tomorrow, I walked to the waterfall.', correct: false, wordIds: ['aruku'], reply: { jp: 'あしたの ことを、もう？', en: 'You already did tomorrow?' }, note: '明日 is tomorrow. For the past, use 今日 (today) or 昨日 (yesterday).' },
          ],
        },
        rest: {
          id: 'rest',
          line: { jp: 'おつかれでしょう。なにか ききたい ことは ありますか。', en: 'You must be tired. Is there anything you’d like to ask?' },
          wordIds: ['heya', 'yasumu'],
          hint: 'Ask if you may rest in your room: 部屋で 休んでも いいですか (休む: む → んで).',
          next: 'bye',
          input: {
            accepted: ['へやでやすんでもいいですか', '部屋で休んでもいいですか', 'へやで休んでもいいですか', 'やすんでもいいですか', '休んでもいいですか', 'へやでやすんでもいい', '部屋で休んでもいい'],
            model: '部屋で休んでもいいですか',
            modelKana: 'へやで やすんでも いいですか',
            wrongReply: { jp: 'はい…？ もう いちど おねがいします。', en: 'Pardon…? Once more, please.' },
            wrongNote: 'May I rest in my room? 休む ends in む: む → んで, so 部屋で 休んでも いいですか.',
            reply: { jp: 'もちろんです。布団も しいて あります。', en: 'Of course. Your futon is already laid out.' },
          },
        },
        bye: { id: 'bye', line: { jp: 'では、ごゆっくり どうぞ。', en: 'Then please, relax and take your time.' }, end: true },
      },
    },
    {
      id: 'onsen-bathkeeper',
      npcId: 'bathboy',
      region: 7,
      translations: 'always',
      start: 'hello',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Jiro keeps the counter at the public bath-house, and nobody gets in until they pass his quiz.',
        'He talks casually, in the plain form: た (did), なかった (didn’t), ている (is doing).',
        'Pick your reply. Wrong answers cost a ❤️.',
      ],
      nodes: {
        hello: {
          id: 'hello',
          line: { jp: 'へい、いらっしゃい！ ぼく、じろう。この ゆやの ばんだいだよ！', en: 'Hey, welcome! I’m Jiro. I run the counter at this bath-house!' },
          next: 'doing',
          options: [
            { jp: 'こんにちは、じろうくん。', en: 'Hello, Jiro.', correct: true, reply: { jp: 'えへへ。くんづけ、いいね！', en: 'Hehe. “Jiro-kun”, I like that!' }, effects: { trust: 1 } },
            { jp: 'さようなら。', en: 'Goodbye.', correct: false, reply: { jp: 'もう かえるの！？', en: 'Leaving already?!' }, note: 'さようなら is goodbye. To greet someone in the daytime: こんにちは.' },
          ],
        },
        doing: {
          id: 'doing',
          line: { jp: 'クイズ！ いま、ぼくは なにを している でしょう？', en: 'Quiz! What am I doing right now? (He is scrubbing the tub with a brush.)' },
          wordIds: ['arau', 'ofuro'],
          hint: 'Something happening right now: 〜ている. 洗う → 洗って → 洗っている.',
          next: 'swim',
          options: [
            { jp: 'お風呂を 洗っている。', kana: 'おふろを あらっている。', en: 'You’re washing the bath.', correct: true, wordIds: ['ofuro', 'arau'], reply: { jp: 'せいかい！ ぴかぴかに しているんだ。', en: 'Correct! I’m making it sparkle.' }, effects: { trust: 1 } },
            { jp: 'お風呂を 洗った。', kana: 'おふろを あらった。', en: 'You washed the bath.', correct: false, wordIds: ['arau'], reply: { jp: 'まだ おわって ないよ！', en: 'I’m not finished yet!' }, note: '洗った is the past (finished). For “right now”, use 〜ている: 洗っている.' },
            { jp: 'お風呂を 洗って ください。', kana: 'おふろを あらって ください。', en: 'Please wash the bath.', correct: false, wordIds: ['arau'], reply: { jp: 'てつだって くれるの？ …ちがう ちがう！', en: 'You’re asking me to? …No, no!' }, note: '〜てください is a request. To say what someone is doing now: 〜ている.' },
          ],
        },
        swim: {
          id: 'swim',
          line: { jp: 'ねえ、お湯の 中で 泳いでも いい？', en: 'Hey, can I swim in the bath?' },
          kana: 'ねえ、おゆの なかで およいでも いい？',
          wordIds: ['oyogu', 'oyu'],
          hint: 'Forbid it: 泳ぐ → 泳いで + は いけません.',
          next: 'before',
          options: [
            { jp: 'ううん、泳いでは いけないよ。', kana: 'ううん、およいでは いけないよ。', en: 'Nope, you must not swim.', correct: true, wordIds: ['oyogu'], reply: { jp: 'ちぇっ。…せいかい。', en: 'Tch. …That’s right.' }, effects: { trust: 1 } },
            { jp: 'うん、泳いでも いいよ。', kana: 'うん、およいでも いいよ。', en: 'Sure, you can swim.', correct: false, wordIds: ['oyogu'], reply: { jp: 'やったー！ …って、かあちゃんに おこられる！', en: 'Yay! …Wait, Mum would kill me!' }, note: 'Swimming in a shared bath is forbidden: 泳いでは いけません.' },
            { jp: 'ううん、泳ぎては いけないよ。', kana: 'ううん、およぎては いけないよ。', en: 'Nope, you must not (wrong form).', correct: false, wordIds: ['oyogu'], reply: { jp: 'およぎて…？ へんな ことば！', en: 'Oyogite…? Weird word!' }, note: '泳ぐ ends in ぐ: ぐ → いで. So 泳いでは いけない.' },
          ],
        },
        before: {
          id: 'before',
          line: { jp: 'じゃあ、お湯に 入る まえに なにを する？', en: 'Then what do you do before getting in the water?' },
          kana: 'じゃあ、おゆに はいる まえに なにを する？',
          wordIds: ['karada', 'arau'],
          hint: 'First wash, then get in: 洗ってから入る.',
          next: 'past',
          options: [
            { jp: '体を 洗ってから 入る。', kana: 'からだを あらってから はいる。', en: 'I wash my body, then get in.', correct: true, wordIds: ['karada', 'arau', 'hairu'], reply: { jp: 'かんぺき！', en: 'Perfect!' }, effects: { trust: 1 } },
            { jp: '入ってから 体を 洗う。', kana: 'はいってから からだを あらう。', en: 'I get in, then wash my body.', correct: false, wordIds: ['arau'], reply: { jp: 'ぎゃく、ぎゃく！', en: 'Backwards, backwards!' }, note: '〜てから puts the first action first: wash, THEN get in.' },
          ],
        },
        past: {
          id: 'past',
          line: { jp: 'きのう、お風呂に 入った？', en: 'Did you take a bath yesterday?' },
          kana: 'きのう、おふろに はいった？',
          wordIds: ['kinou', 'hairu'],
          hint: '入る is a う-verb in disguise: 入って → 入った.',
          next: 'morning',
          options: [
            { jp: 'うん、入った。', kana: 'うん、はいった。', en: 'Yeah, I did.', correct: true, wordIds: ['hairu'], reply: { jp: 'えらい！', en: 'Good for you!' }, effects: { trust: 1 } },
            { jp: 'うん、はいた。', en: 'Yeah, I (wrong form).', correct: false, wordIds: ['hairu'], reply: { jp: 'はいた？ くつを？', en: 'Haita? Your shoes?' }, note: '入る looks like a る-verb but is a う-verb: 入って, 入った. (はいた means “put on shoes”!)' },
            { jp: 'うん、入る。', kana: 'うん、はいる。', en: 'Yeah, I’ll get in.', correct: false, wordIds: ['hairu'], reply: { jp: 'きのうの はなしだよ！', en: 'I’m asking about yesterday!' }, note: 'For yesterday, use the past: 入った.' },
          ],
        },
        morning: {
          id: 'morning',
          line: { jp: 'じゃあ、今朝は？', en: 'And this morning?' },
          kana: 'じゃあ、けさは？',
          wordIds: ['kesa'],
          hint: 'Didn’t: 入らない → 入らなかった.',
          next: 'monkeys',
          options: [
            { jp: '今朝は 入らなかった。', kana: 'けさは はいらなかった。', en: 'I didn’t this morning.', correct: true, wordIds: ['kesa', 'hairu'], reply: { jp: 'じゃあ いま 入って いけば？', en: 'Then why not get in now?' }, effects: { trust: 1 } },
            { jp: 'けさは はいなかった。', en: 'I didn’t (wrong form) this morning.', correct: false, wordIds: ['hairu'], reply: { jp: 'う〜ん、おしい！', en: 'Ooh, so close!' }, note: '入る is a う-verb: る → ら, so 入らない → 入らなかった.' },
            { jp: 'けさは はいりなかった。', en: 'I didn’t (wrong form) this morning.', correct: false, wordIds: ['hairu'], reply: { jp: 'へんなの！', en: 'That sounds weird!' }, note: 'The ない-form of 入る is 入らない; its past is 入らなかった.' },
          ],
        },
        monkeys: {
          id: 'monkeys',
          line: { jp: 'さいごの クイズ！ ろてんぶろで 猿を 見た ことが ある？ こたえて！', en: 'Last question! Have you ever seen monkeys in the outdoor bath? Answer!' },
          kana: 'さいごの クイズ！ ろてんぶろで さるを みた ことが ある？ こたえて！',
          wordIds: ['saru'],
          hint: 'Casual answers: うん、ある (yes, I have) or ううん、ない (no, I haven’t).',
          next: 'bye',
          input: {
            accepted: ['うんある', 'ある', 'はいあります', 'あります', 'ううんない', 'ない', 'いいえありません', 'ありません', 'みたことがある', '見たことがある', 'みたことがあります', '見たことがあります', 'みたことがない', '見たことがない', 'みたことがありません', '見たことがありません'],
            model: 'うん、ある',
            modelKana: 'うん、ある',
            wrongReply: { jp: 'ある？ ない？ どっち？', en: 'Have you or haven’t you? Which?' },
            wrongNote: 'Answer the experience question with ある (I have) or ない (I haven’t): うん、ある / ううん、ない.',
            reply: { jp: 'じゃあ こんど いっしょに 見に いこう！', en: 'Then let’s go and see them together sometime!' },
          },
        },
        bye: { id: 'bye', line: { jp: 'ごうかく！ ゆっくり あったまって いきな！', en: 'You pass! Go on in and warm up nice and slow!' }, end: true },
      },
    },
  ],
}
