import type { MapSpec } from '../../world/types'

/**
 * Region 7 — 湯の里, the Hot-Spring Hollow.
 *
 * onsen        the village: the great inn and its courtyard (NW), the footbath
 *              plaza, the bath-house street of paper lanterns running north to
 *              the outdoor bath, the egg cauldron and steam vents, a rope
 *              bridge over the gorge, the snowy upper village with the shrine
 *              of the spring god, the trail up the mountain (N), the old
 *              bath-house (SW), the riverbank shallows (S) and a bamboo grove
 * onsen-inn    Yunosato-ya: genkan, lobby and counter, tatami rooms, kitchen
 * onsen-bath   the outdoor rock bath, open to the stars, where snow monkeys soak
 * onsen-trail  the bamboo path to Yōrō Falls, a fox shrine and a lookout
 * onsen-cave   the Yamanba's steam cave
 */

const SNOWY = { U: { g: 'onsen' }, h: { g: 'snow', o: 'snow-pine' }, y: { g: 'snow', o: 'snowman' } } as const

// prettier-ignore
const ONSEN_ROWS = [
  'hhhhhhhhhhhhhhhhhhhhh77hhhhhWWWWWhhhhh88hhhhhhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhhhhhhh==hhhhhWWWWWhhhhh==hhhhhhhhhhhhhhhhhhhh',
  'h*h*hh*******hh*****hδ=***hCWWWWWC****ε=h**************h***h',
  'P*^^^^^^^^^^^^^^^**h*==h***CWWWWWCh***==******h************P',
  'P.^^^^^^^^^^^^^^^...l==l...CWWWWWC****==****vvvvvvvvvvv****P',
  'P.^^^^^^^^^^^^^^^....==....CWWWWWCh*h*==****vvvvvvvvvvv****P',
  'P.AAAAAAAAAAAAAAA....==....CWWWWWC***]==****jjjjjjjjjjj****P',
  'P.#H#H#HEdEH#}#H#....==....CWWWWWC*hh*==****#H##H##H##H****P',
  'P...NnnnnmnnnnN.....l==l...CWWWWWC*h**==*****Nnnn6nnnN*****P',
  'P...nn+nnnnnnnn......==.[..CWWWWWC*UU*==***h*nnnnnnnnn****hP',
  'P...nnnnnnnnnnn......==.UU.CWWWWWC***h==**y*hnnθnnnnnn*****P',
  'P...."...=..vvvvvvvv.==.UU.CWWWWWC****==**h**h***=**hh**h**P',
  'P.nnnnnn.=..vvvvvvvvl==l...CWWWWWCh***==********h=******y**P',
  'P.nUUUnn.=..jjjjjjjj.==.nnnCWWWWWC****==*h*******I*********P',
  'P.nUUUn(.=..#H#EEH#H.==.n2nCWWWWWC....==.......h.=.α.......P',
  'P.nnnnβn.===nnnnnnnn.==.n3nCWWWWWC..hh==...UU.h..=..hiiii..P',
  'P.nnnnnn.=..nnnn4nn5l==l...CWWWWWC....==...UU....=...iiii.hP',
  'P........=...."......==....CWWWWWC....==........h=...iiii..P',
  'P.^^^^^^1=..^^^^^^^..==....CWWWWWC.hh.==.........I.........P',
  'P.^^^^^^.=..^^^^^^^".==....CWWWWWC....==...h.....=.........P',
  'P"AAAAAA.=..AAAAAAA.l==l...CWWWWWC....==.........=..h..h...P',
  'P.#HDH#H.=..#H#D#H#".==....CWWWWWC....==.........=.....h..hP',
  'P........=...........==..K.CWWWWWC.γ..==.........=..h....!.P',
  'P..$.....=...........==...)CWWWWWC....==.........=.........P',
  '9==========================-------========================z0',
  '9q=========================-------=========================0',
  'P.....=...........T.......TCWWWWWC............=.........?..P',
  'P.....=.....T..............CWWWWWC.TTBBBBBBBBB=BBBBBBBBBBB.P',
  'P.^^^^^^^^^.......T.....T..CWWWWWCTT.BBBBBBBBB=BBBBBBBBBBB.P',
  'P.^^^^^^^^^...........T....CWWWWWCT.TBB;;;BB;;=;;;;;;;;BBB.P',
  'P.AAAAAAAAA..;;;b;;b;b.....CWWWWWC...BB;B;;;.....B;;B;B;BB.P',
  'P.#H#HDH#H#..;bb;;;;;;....TCWWWWWC.T.BB;;;B;..{..;B;;;;;BB.P',
  'PT_________..;;;b;;;;;....TCWWWWWCT..BB;;;B;.....;;;;;;;BB.P',
  'P._________..;;;;;;bb;T....CWWWWWC...BBB;;;B;;;B;;;;;;;`BB.P',
  'P._________..;;;;;;;;;.:::::~~~~~:...BB;;;;;B;;;;BB;;;;BBB.P',
  'P;;;.;..;..;;;;;;;;;;;.:::::~~~~~:...BB;;;;;;;;;;;;;;;;;BB.P',
  'P.;.;;;..T..;;;b;;;;;;.:::::~~~~~:...BB;;;;;;;B;;;;;;;;;BB.P',
  'P.;;..;;;T;;.;;;;;;;b;.:::::~~~~~:...BB;;;;;;;;;;B;;;;;;BB.P',
  'P;..;;;;;.;.;;;;;;;b;;.:::::~~~~~:...BB;;B;;;;;;B;;;;;;;BB.P',
  'P..;;;.;;;.;;........T.:::::sssss:...BBBB;;;;;;B;;;;;;;;BB.P',
  'P./.;..;..;;...........:::::~~~~~:...BBBBBBBBBBBBBBBBBBBBB.P',
  'P.;..;.;;...;.......T..:::::~~~~~:...BBBBBBBBBBBBBBBBBBBBB.P',
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
  'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
]

export const ONSEN: MapSpec = {
  id: 'onsen',
  name: 'The Hot-Spring Hollow',
  jp: '湯の里',
  region: 7,
  music: 'onsen',
  particles: 'dust',
  tint: 'rgba(240, 150, 110, 0.12)',
  rows: ONSEN_ROWS,
  legend: {
    ...SNOWY,
    l: { g: 'path', o: 'chochin' },
    v: { g: 'grass', o: 'roof-red' },
    j: { g: 'grass', o: 'roof-red-edge' },
    E: { g: 'grass', o: 'noren' },
    i: { g: 'ice' },
  },
  spawn: 'west',
  inn: 'inn',
  points: {
    q: { name: 'west', dir: 'right' },
    z: { name: 'east', dir: 'left' },
    m: { name: 'inn', dir: 'down' },
    δ: { name: 'bath', dir: 'down' },
    ε: { name: 'trail', dir: 'down' },
  },
  exits: [
    { at: '9', to: '@prev', point: 'east' },
    { at: '0', to: '@next', point: 'west' },
    { at: 'd', to: 'onsen-inn', point: 'door', tile: 'door' },
    { at: '7', to: 'onsen-bath', point: 'gate' },
    { at: '8', to: 'onsen-trail', point: 'south' },
  ],
  entities: [
    { at: '1', id: 'o-porter', kind: 'activity', sprite: 'villager-a', dir: 'down', wander: 1, activities: ['r7-words-2'], name: { jp: 'にもつはこびの ごんた', en: 'Gonta the Porter' }, lines: [{ jp: 'あるく、はいる、やすむ… ゆのさとの うごく ことばを おしえよう！', en: 'Walk, go in, rest… let me teach you the moving words of the Hollow!' }] },
    { at: '2', id: 'o-eggs', kind: 'activity', tile: 'pot', activities: ['r7-forge-1'], name: { jp: 'たまごの かま', en: 'Egg Cauldron' }, lines: [{ jp: 'おんせんの おゆで、たまごが ゆっくり にえている。ことばも にえるかも？', en: 'Eggs simmer slowly in the spring water. Maybe words cook here too?' }] },
    { at: '3', id: 'o-egg-seller', kind: 'activity', sprite: 'villager-b', dir: 'left', activities: ['r7-forge-2'], name: { jp: 'たまごやの おきく', en: 'Okiku the Egg Seller' }, lines: [{ jp: 'おんせんたまご、いかが？ ぶんも たまごと おなじ。ならべてから、ゆっくり ゆでるの。', en: 'Hot-spring eggs? Sentences are like eggs: line them up, then simmer them slowly.' }] },
    { at: '4', id: 'o-jiro', kind: 'activity', sprite: 'child', dir: 'down', activities: ['r7-bathkeeper'], name: { jp: 'じろう', en: 'Jiro' }, lines: [{ jp: 'ゆやに はいりたい？ まず ぼくの クイズに こたえて！', en: 'Want to use the bath-house? Answer my quiz first!' }] },
    { at: '5', id: 'o-board', kind: 'activity', tile: 'sign', activities: ['r7-runes'], name: { jp: 'ゆの おきて', en: 'Bath Rules Board' }, lines: [{ jp: 'ゆやの はりがみ。「〜ては いけません」が たくさん かいてある。', en: 'The bath-house notices, full of “you must not…”.' }] },
    { at: '6', id: 'o-bell', kind: 'activity', tile: 'shrine-bell', activities: ['r7-listen'], name: { jp: 'ゆがみさまの すず', en: 'Bell of the Spring God' }, lines: [{ jp: 'すずを ならすと、ゆげの むこうから こえが きこえる。', en: 'Ring the bell and voices answer from beyond the steam.' }] },
    { at: '!', id: 'o-trial', kind: 'activity', tile: 'statue', activities: ['r7-mastery'], name: { jp: 'しれんの いし', en: 'Trial Stone' }, lines: [{ jp: 'ゆのさとの しれん。ゆげが はれる まえに、ぶんを くみたてよ。', en: 'The Hollow’s trial. Build your sentences before the steam clears.' }] },
    { at: '$', id: 'o-sign-west', kind: 'sign', tile: 'sign', name: { jp: 'かんばん', en: 'Sign' }, lines: [{ jp: 'ゆのさとへ ようこそ！ 靴を 脱いで、ゆっくり 休んで ください。', en: 'Welcome to the Hot-Spring Hollow! Take off your shoes and rest at your leisure.' }] },
    { at: '?', id: 'o-sign-east', kind: 'sign', tile: 'sign', name: { jp: 'かんばん', en: 'Sign' }, lines: [{ jp: 'ひがし：じょうかまち。やまんばが いる かぎり、たびびとは とおれない…', en: 'East: the Castle Town. While the Yamanba prowls, no traveller gets through…' }] },
    { at: ')', id: 'o-bridge', kind: 'landmark', tile: 'sign', word: 'tsuribashi', name: { jp: 'つりばし', en: 'Rope Bridge' }, lines: [{ jp: 'たにの 上の つり橋。かぜで ゆらゆら ゆれている。', en: 'A rope bridge over the gorge, swaying in the wind.' }] },
    { at: '(', id: 'o-ashiyu', kind: 'landmark', tile: 'sign', word: 'ashiyu', name: { jp: 'あしゆ', en: 'Footbath' }, lines: [{ jp: 'だれでも 足を 入れて いい あしゆ。ただです！', en: 'A footbath anyone may dip their feet in. Free!' }] },
    { at: '[', id: 'o-vent', kind: 'landmark', tile: 'rock', word: 'yuge', name: { jp: 'ゆげの いわ', en: 'Steaming Rock' }, lines: [{ jp: 'いわの すきまから、しろい ゆげが もくもく あがっている。', en: 'White steam billows from cracks in the rock.' }] },
    { at: ']', id: 'o-slope', kind: 'landmark', tile: 'sign', word: 'noboru', name: { jp: 'やまみちの しるし', en: 'Trail Marker' }, lines: [{ jp: '↑ たきと きつねの やしろ。ゆっくり 登って ください。', en: '↑ To the falls and the fox shrine. Please climb slowly.' }] },
    { at: '{', id: 'o-foxden', kind: 'landmark', tile: 'stump', word: 'kitsune', name: { jp: 'きつねの あな', en: 'Fox Den' }, lines: [{ jp: 'たけやぶの 中の きりかぶ。下に、きつねの あなが ある。', en: 'A stump in the bamboo. Beneath it is a fox den.' }] },
    { at: '}', id: 'o-inn', kind: 'landmark', tile: 'wall-window', word: 'ryokan', name: { jp: 'ゆのさとや', en: 'Yunosato-ya Inn' }, lines: [{ jp: 'ゆのさとで いちばん 古い 旅館。まどから ごはんの においが する。', en: 'The oldest inn in the Hollow. The smell of dinner drifts from the window.' }] },
    { at: '+', id: 'o-cat', kind: 'npc', sprite: 'cat', wander: 2, name: { jp: 'ねこ', en: 'Cat' }, lines: [{ jp: 'にゃ〜。（あしゆの そばで ねていた）', en: 'Mrrow~ (It was napping by the footbath.)' }] },
    { at: 'α', id: 'o-monkey', kind: 'npc', sprite: 'monkey', wander: 2, name: { jp: 'ゆきざる', en: 'Snow Monkey' }, lines: [{ jp: 'キキッ！', en: 'Kik-kik!' }] },
    { at: 'θ', id: 'o-monkey-2', kind: 'npc', sprite: 'monkey', wander: 1, name: { jp: 'こざる', en: 'Little Monkey' }, lines: [{ jp: 'キ？', en: 'Ki?' }] },
    { at: 'β', id: 'o-grandpa', kind: 'npc', sprite: 'elder', dir: 'left', name: { jp: 'げんじい', en: 'Grandpa Gen' }, lines: [{ jp: 'ふう… あしゆは きもちいいのう。', en: 'Phew… the footbath feels wonderful.' }] },
    { at: 'γ', id: 'o-photographer', kind: 'npc', sprite: 'villager-b', wander: 1, name: { jp: 'しゃしんやの ミツ', en: 'Mitsu the Photographer' }, lines: [{ jp: 'ゆきと ゆげ… いい しゃしんが とりたいなあ。', en: 'Snow and steam… I’d love to take a good photo.' }] },
    { at: '/', id: 'o-chest-willow', kind: 'chest', tile: 'chest', chest: { item: 'herb', n: 2, shards: 25, lock: { answer: 'ぬいで', jp: 'ふたに「くつを ＿＿ ください」。', en: '“Kutsu o ___ kudasai” (Please take off your shoes). Chant the て-form of ぬぐ.' } } },
    { at: '`', id: 'o-chest-grove', kind: 'chest', tile: 'chest', chest: { item: 'smoke', n: 2, shards: 20 } },
  ],
}

// prettier-ignore
const INN_ROWS = [
  '###H#H6####H#H############',
  '#ttttttt#ttttttt#xwkwkpew#',
  '#ttttttt#ttttt7t#wwwwwwww#',
  '#tt3tttt#ttt&ttt#wwww4www#',
  '#ttttt$t#ttttttt#wwwwwwww#',
  '#ttttttt#ttttttt#wwwwwwww#',
  '####t#######t#######w#####',
  '#wwwwwwwwwwwwwwwwwwwwwwww#',
  '#wwwwwwwwwwwwwwwwwwwwwwww#',
  '#pwwwwwwwwwwMMwwwwwwwwwww#',
  '#wwwww2wwwwwMMwwwww1wwwkw#',
  '#wwwwwwwwwwwMMwwwaaaaawww#',
  '#wwwwwwwwwwwMMwwwwwwwwwww#',
  '#wwwwwwwwwwwvMwwwwwwwwwww#',
  '#wwwwwwwwwnnnnnnwwwwwwwww#',
  '#pwwwwwww5nnnnnnwwwwwwwwp#',
  '############00############',
]

export const ONSEN_INN: MapSpec = {
  id: 'onsen-inn',
  name: 'Yunosato-ya Inn',
  jp: 'ゆのさとや',
  region: 7,
  music: 'onsen',
  interior: true,
  particles: 'none',
  bg: '#140c08',
  tint: 'rgba(255, 190, 120, 0.12)',
  rows: INN_ROWS,
  legend: {
    '#': { g: 'wood-floor', o: 'wall' },
    H: { g: 'wood-floor', o: 'wall-window' },
    p: { g: 'wood-floor', o: 'pot' },
    e: { g: 'wood-floor', o: 'barrel' },
    x: { g: 'wood-floor', o: 'crate' },
    a: { g: 'wood-floor', o: 'shop-awning' },
  },
  spawn: 'door',
  points: { v: { name: 'door', dir: 'up' } },
  exits: [{ at: '0', to: 'onsen', point: 'inn', tile: 'carpet' }],
  entities: [
    { at: '1', id: 'oi-okami', kind: 'activity', sprite: 'okami', dir: 'down', activities: ['r7-words-1', 'r7-checkin'], name: { jp: 'おかみの はるこ', en: 'Haruko, the Proprietress' }, lines: [{ jp: 'いらっしゃいませ。ゆっくり して いって くださいね。', en: 'Welcome. Please make yourself at home.' }] },
    { at: '2', id: 'oi-guestbook', kind: 'activity', tile: 'bookshelf', activities: ['r7-trace'], name: { jp: 'やどちょう', en: 'Guestbook' }, lines: [{ jp: 'おきゃくさんが「きのう した こと」を ふでで かく ちょうめん。', en: 'A book where guests write, by brush, what they did the day before.' }] },
    { at: '3', id: 'oi-guest', kind: 'activity', sprite: 'villager-b', dir: 'right', activities: ['r7-words-4'], name: { jp: 'ねむそうな おきゃく', en: 'Sleepy Guest' }, lines: [{ jp: 'ふあ… きのうは つかれた… でも おんせんは きもちよかった〜。', en: 'Yawn… yesterday wore me out… but the hot spring felt so good~' }] },
    { at: '4', id: 'oi-cook', kind: 'npc', sprite: 'innkeeper', dir: 'down', wander: 1, name: { jp: 'いたまえの ぶん', en: 'Bun the Cook' }, lines: [{ jp: 'しょくじは ろくじから。きょうは やまの なべだよ！', en: 'Dinner is from six. Tonight it’s mountain hotpot!' }] },
    { at: '5', id: 'oi-shoes', kind: 'landmark', tile: 'crate', word: 'kutsu', name: { jp: 'くつばこ', en: 'Shoe Cupboard' }, lines: [{ jp: 'げんかんで 靴を 脱いで、ここに 入れます。', en: 'At the entrance, you take off your shoes and put them in here.' }] },
    { at: '6', id: 'oi-window', kind: 'landmark', tile: 'wall-window', word: 'mado', name: { jp: 'まど', en: 'Window' }, lines: [{ jp: 'まどの そとで、ゆきが しずかに ふっている。', en: 'Outside the window, snow falls quietly.' }] },
    { at: '7', id: 'oi-futon', kind: 'landmark', tile: 'carpet', word: 'futon', name: { jp: 'ふとん', en: 'Futon' }, lines: [{ jp: 'ふかふかの 布団。ここで ねても いいのかな？', en: 'A fluffy futon. Am I allowed to sleep here?' }] },
    { at: '$', id: 'oi-chest', kind: 'chest', tile: 'chest', chest: { item: 'herb', n: 2, shards: 20 } },
  ],
}

// prettier-ignore
const BATH_ROWS = [
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'hh***h****hh**h*hhh****h**h**h*h',
  'hh$****hh*h*h******h**h*rrrrr**h',
  'hhh******h***hh*****hh**rUUUr**h',
  'h***********************rrrrr**h',
  'h**y***rrrrrrrrrrrrrrrr***5****h',
  'h******rUUUUUUUUUUUUUUr********h',
  'h******rUUUUUUUUUUUUUUr********h',
  'h******rUUUUUUUUUUUUUUr********h',
  'h******rUUUUUUUUUUUUUUr********h',
  'h******rUUUUUUUUUUUUUUr********h',
  'h******rUUUUUUUUUUUUUUr********h',
  'h******rrrrrrrrrrrrrrrr********h',
  'h^^^^^**nnnnn1nnnnn4nn**f.ff.f*h',
  'hAAAAA**nnnnnnnnnnnnnn**nn2n3n*h',
  'h#E#H#*********==********N***N*h',
  'h**************==**************h',
  'h**************==**************h',
  'h**************v=**************h',
  'h**************==**************h',
  'hhhhhhhhhhhhhhh99hhhhhhhhhhhhhhh',
]

export const ONSEN_BATH: MapSpec = {
  id: 'onsen-bath',
  name: 'The Starlit Rock Bath',
  jp: 'ほしの ろてんぶろ',
  region: 7,
  music: 'onsen',
  particles: 'sparkles',
  bg: '#0b0e22',
  tint: 'rgba(40, 50, 120, 0.22)',
  rows: BATH_ROWS,
  legend: {
    ...SNOWY,
    r: { g: 'snow', o: 'rock' },
    E: { g: 'snow', o: 'noren' },
    '^': { g: 'snow', o: 'roof' },
    A: { g: 'snow', o: 'roof-edge' },
    '#': { g: 'snow', o: 'wall' },
    H: { g: 'snow', o: 'wall-window' },
    f: { g: 'snow', o: 'fence' },
  },
  spawn: 'gate',
  points: { v: { name: 'gate', dir: 'up' } },
  exits: [{ at: '9', to: 'onsen', point: 'bath' }],
  entities: [
    { at: '1', id: 'ob-saru', kind: 'activity', sprite: 'monkey', dir: 'down', activities: ['r7-words-3'], name: { jp: 'ゆきざるの サル', en: 'Saru the Snow Monkey' }, lines: [{ jp: 'キキッ。あたま、かた、せなか… ゆに つかる まえに、からだの ことばを おぼえな。', en: 'Kik! Head, shoulders, back… learn the body’s words before you soak.' }] },
    { at: '2', id: 'ob-taps', kind: 'landmark', tile: 'well', word: 'sekken', name: { jp: 'あらいば', en: 'Wash Taps' }, lines: [{ jp: 'せっけんと おけ。ここで からだを 洗ってから、ゆに 入ろう。', en: 'Soap and wooden buckets. Wash here before getting in.' }] },
    { at: '3', id: 'ob-towels', kind: 'landmark', tile: 'crate', word: 'taoru', name: { jp: 'タオルだな', en: 'Towel Shelf' }, lines: [{ jp: 'しろい タオルが たたんで ある。ゆに 入れては いけません。', en: 'Folded white towels. Never put them in the water.' }] },
    { at: '4', id: 'ob-pool', kind: 'landmark', tile: 'rock', word: 'onsen', name: { jp: 'いわぶろ', en: 'Rock Bath' }, lines: [{ jp: 'ほしの 下の 温泉。ゆげの むこうで、さるが めを とじている。', en: 'A hot spring under the stars. Through the steam, monkeys sit with their eyes closed.' }] },
    { at: '5', id: 'ob-source', kind: 'landmark', tile: 'rock', word: 'oyu', name: { jp: 'わきだしぐち', en: 'Spring Source' }, lines: [{ jp: 'あつい お湯が、いわの あいだから わいている。', en: 'Hot water wells up between the rocks.' }] },
    { at: '$', id: 'ob-chest', kind: 'chest', tile: 'chest', chest: { item: 'ether', n: 1, shards: 25, lock: { answer: 'はいって', jp: 'ふたに「おゆに ＿＿ も いいですか」。', en: '“Oyu ni ___ mo ii desu ka” (May I get in the water?). Chant the て-form of はいる.' } } },
  ],
}

// prettier-ignore
const TRAIL_ROWS = [
  'BBBBBBBBBBBBBBBBBBBBBBBCC88CCBBB',
  'BB.CCWWWWCCC.PPPPPPPP.BCC==CCBBB',
  'BB.CCWWWWCCC..........BBB==BBBBB',
  'BB...WWWW.............BB?m=BBBBB',
  'BB...WWWW.............BBB==BBBBB',
  'BB...WWWW.............BBB==BBBCC',
  'BB.~~~~~~~~~..........BBB==....C',
  'BB.~r~~~~~~~4.........BBB==.5..C',
  'BB.~~~~~~~r~..........BBB==....C',
  'BB.R~~~~~~~~..........BBB==....C',
  'BB....................BBB==BBBBC',
  'BBBBBBBBBBBB..BBBBBBBBBBB==BBBBB',
  'BBBBBBBBBB=================BBBBB',
  'BBBBBBBBBB=================BBBBB',
  'BBBBBBBBBBBBBBBBBBBBBBB==BBBBBBB',
  'BBBBBBBBBBBBBBBBBBBBBBB==BSnnnSB',
  'BBBBBBBBBBBBBBBBBBBBBBB==BnInnnB',
  'BBBBBBBBBBBBBBBBBBBBBBB===nInnnB',
  'BBBBBBBBBBBBBBBBBBBBBBB==BnInnnB',
  'BBBBBBBBBBBBBBBBBBBBBBB==BnnnnnB',
  'BBBBBB===================Bnn2nnB',
  'BBBBBB===================BBBBBBB',
  'B;;;;B==B".....".....BBBBBBBBBBB',
  'B;;;;B==B.;;;;.....""BBBBBBBBBBB',
  'B;$;;B==..;;1;"."....BBBBBBBBBBB',
  'B;;;;B==..;;;;......"BBBBBBBBBBB',
  'B;;;;;==B....""."..."BBBBBBBBBBB',
  'B;;;;B==B"........3..BBBBBBBBBBB',
  'B;;;;B==B......."."".BBBBBBBBBBB',
  'B;;;;B==7BBBBBBBBBBBBBBBBBBBBBBB',
  'BBBBBB===========BBBBBBBBBBBBBBB',
  'BBBBBB===========BB;;BB;;B;;BBBB',
  'BBBBBBBBBBBBBBB==B;;;;BB;;;;BBBB',
  'BBBBBBBBBBBBBBB==;;;;;;;;;;;BBBB',
  'BBBBBBBBBBBBBBB==6B;;;;;;;;;BBBB',
  'BBBBBBBBBBBBBBB==B;;;;;;;;;;BBBB',
  'BBBBBBBBBBBBBBB==;;;;B;;;;B;BBBB',
  'BBBBBBBBBBBBBBBv=BBBBBBBBBBBBBBB',
  'BBBBBBBBBBBBBBB==BBBBBBBBBBBBBBB',
  'BBBBBBBBBBBBBBB99BBBBBBBBBBBBBBB',
]

export const ONSEN_TRAIL: MapSpec = {
  id: 'onsen-trail',
  name: 'The Bamboo Trail',
  jp: 'たけの やまみち',
  region: 7,
  music: 'onsen',
  particles: 'fireflies',
  tint: 'rgba(60, 140, 90, 0.14)',
  rows: TRAIL_ROWS,
  legend: { B: { g: 'grass-dark', o: 'bamboo' } },
  spawn: 'south',
  points: { v: { name: 'south', dir: 'up' }, m: { name: 'cave', dir: 'down' } },
  exits: [
    { at: '9', to: 'onsen', point: 'trail' },
    { at: '8', to: 'onsen-cave', point: 'mouth', tile: 'cave' },
  ],
  entities: [
    { at: '1', id: 'ot-monk', kind: 'activity', sprite: 'villager-a', dir: 'right', wander: 1, activities: ['r7-combat'], name: { jp: 'やまぶし', en: 'Mountain Monk' }, lines: [{ jp: 'たけやぶに かまいたちが でる。ことばの まほうで たたかう れんしゅうを しよう！', en: 'Sickle-weasels haunt the bamboo. Let’s practise fighting them with word magic!' }] },
    { at: '2', id: 'ot-fox', kind: 'activity', tile: 'statue', activities: ['r7-defense'], name: { jp: 'きつねの せきぞう', en: 'Fox Statue' }, lines: [{ jp: 'いなりの きつねが、たけやぶの かぜを みはっている。', en: 'The Inari fox keeps watch over the winds in the bamboo.' }] },
    { at: '3', id: 'ot-stone', kind: 'activity', tile: 'tablet', activities: ['r7-cross'], name: { jp: 'たびびとの いしぶみ', en: 'Travellers’ Stone' }, lines: [{ jp: 'たびびとたちが ことばを ほった いし。ますめが ならんでいる。', en: 'A stone where travellers carved words, in rows of squares.' }] },
    { at: '4', id: 'ot-falls', kind: 'landmark', tile: 'rock', word: 'taki', name: { jp: 'ようろうの たき', en: 'Yōrō Falls' }, lines: [{ jp: 'しろい 滝が、ごうごうと おちている。', en: 'A white waterfall roars down.' }] },
    { at: '5', id: 'ot-lookout', kind: 'landmark', tile: 'sign', word: 'tani', name: { jp: 'みはらし', en: 'Lookout' }, lines: [{ jp: 'ふかい 谷の そこに、ゆのさとの ゆげが みえる。', en: 'Far below in the deep gorge, the Hollow’s steam rises.' }] },
    { at: '6', id: 'ot-bamboo', kind: 'landmark', tile: 'bamboo', word: 'take', name: { jp: 'おおきな 竹', en: 'Giant Bamboo' }, lines: [{ jp: 'とても たかい 竹。かぜが ふくと、さらさら うたう。', en: 'Very tall bamboo. It sings when the wind blows.' }] },
    { at: '7', id: 'ot-slope', kind: 'landmark', tile: 'sign', word: 'saka', name: { jp: 'さかの しるし', en: 'Slope Marker' }, lines: [{ jp: 'ここから きゅうな 坂。足に きを つけて。', en: 'Steep slope from here. Mind your feet.' }] },
    { at: '?', id: 'ot-warning', kind: 'sign', tile: 'sign', name: { jp: 'たてふだ', en: 'Warning Sign' }, lines: [{ jp: '「この さき、やまんばの いわや。入っては いけません。」', en: '“Ahead: the Yamanba’s cave. You must not enter.”' }] },
    { at: '$', id: 'ot-chest', kind: 'chest', tile: 'chest', chest: { item: 'smoke', n: 2, shards: 20 } },
  ],
}

// prettier-ignore
const CAVE_ROWS = [
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'Cnnnnnnnnn^^^^^^^^^nnrnrnnnC',
  'CnnUUnnnnr^^^^^^^^^nnnnrnnnC',
  'CnnUUnnnrrAAAAAAAAAnnnUUUnnC',
  'Cnnnnnnnnn#H#H#D#H#nrnUUUnnC',
  'Cnnnnnnnnnrnn__nnnnnnnnnnnnC',
  'Cnnnnnnnnnnnn__nnnnnnrnnnrnC',
  'CnnnnnnnnUUnn6_np&nnnnnnnnnC',
  'Cnnnnnnnnnnrn__n2nnnnnnnnnnC',
  'Cnnnnnnnnnnnn__nnnnnnnnnnnnC',
  'Cnnnnnnnnnnnn__nnnnrnUUUnnnC',
  'CrnnUUnnnnnnn__nnnnnnUUUnrnC',
  'CnnnUUnnnnnnn__nnnnnnUUUnnnC',
  'Cnnnnnnnnnnnn__nrnnnnnnnnnnC',
  'Cnnnnnnnnnnnn__nnnn1nnnnnnnC',
  'Cn$nnnnnnnnnnv_nnnnnnnnnrnnC',
  'Cnnnnnnnnnnnn__nnnnnnnnnnnnC',
  'CCCCCCCCCCCCC99CCCCCCCCCCCCC',
]

export const ONSEN_CAVE: MapSpec = {
  id: 'onsen-cave',
  name: 'The Yamanba’s Steam Cave',
  jp: 'やまんばの いわや',
  region: 7,
  music: 'onsen',
  particles: 'dust',
  bg: '#120808',
  tint: 'rgba(150, 60, 50, 0.18)',
  rows: CAVE_ROWS,
  legend: {
    C: { g: 'dirt', o: 'cliff' },
    U: { g: 'onsen' },
    r: { g: 'stone-floor', o: 'rock' },
    '^': { g: 'stone-floor', o: 'roof' },
    A: { g: 'stone-floor', o: 'roof-edge' },
    '#': { g: 'stone-floor', o: 'wall' },
    H: { g: 'stone-floor', o: 'wall-window' },
    D: { g: 'stone-floor', o: 'door' },
    p: { g: 'stone-floor', o: 'pot' },
  },
  spawn: 'mouth',
  points: { v: { name: 'mouth', dir: 'up' } },
  exits: [{ at: '9', to: 'onsen-trail', point: 'cave' }],
  entities: [
    { at: '6', id: 'oc-yamanba', kind: 'boss', sprite: 'yamanba', activities: ['r7-boss'], name: { jp: 'もつれの やまんば', en: 'The Knotting Yamanba' }, lines: [{ jp: 'ひっひっひ… きのうは もう ないよ。あるのは「いま」だけさ。', en: 'Hee hee hee… There is no yesterday any more. Only “now”.' }] },
    { at: '1', id: 'oc-wall', kind: 'activity', tile: 'tablet', activities: ['r7-mastery-2'], name: { jp: 'いわやの かべ', en: 'Cave Wall' }, lines: [{ jp: 'かべに、むかしの ゆの おきてが ほってある。よみがなは ない。', en: 'Old bath laws are carved into the wall, with no readings to help.' }] },
    { at: '2', id: 'oc-pot', kind: 'landmark', tile: 'pot', name: { jp: 'やまんばの なべ', en: 'Yamanba’s Pot' }, lines: [{ jp: 'なべの 中で、むすばれた ことばが ぐつぐつ にえている。', en: 'Knotted words bubble away in the pot.' }] },
    { at: '$', id: 'oc-chest', kind: 'chest', tile: 'chest', chest: { item: 'charm', n: 1, shards: 40, lock: { answer: 'あそんで', jp: 'ふたに「さるが ゆきで ＿＿ いる」。', en: '“Saru ga yuki de ___ iru” (The monkeys are playing in the snow). Chant the て-form of あそぶ.' } } },
  ],
}

export const MAPS: MapSpec[] = [ONSEN, ONSEN_INN, ONSEN_BATH, ONSEN_TRAIL, ONSEN_CAVE]
