import type { RegionSprites } from '../types'

/**
 * Region 7 pixel art (palette chars: art/raster.ts LEGEND).
 *
 * okami       Haruko, the proprietress: hair in a high bun, an indigo
 *             kimono with a white apron and an orange obi, white tabi
 * monkey      a snow monkey (Japanese macaque): tan fur, red face and hands,
 *             walking on all fours like the cat, dog and fox
 * kamaitachi  the sickle-weasel, leaping on its own whirlwind
 * yamanba     the mountain woman: a mane of wild white hair, a ragged
 *             vermilion kimono, a kitchen knife and a knotted straw rope
 */
export const SPRITES: RegionSprites = {
  characters: {
    okami: {
      down: [
        '................',
        '.......nn.......',
        '......nnnn......',
        '....nnnnnnnn....',
        '...nnnnnnnnnn...',
        '...nnffffffnn...',
        '...nfkffffkfn...',
        '...ffkffffkfF...',
        '....hffffffh....',
        '...NdwffffwdN...',
        '..fNddwwwwddNf..',
        '...eeeyyyyeeV...',
        '...NddwwwwddN...',
        '....NdwwwwdN....',
        '.....ww.........',
        '................',
      ],
      up: [
        '................',
        '.......nn.......',
        '......nnnn......',
        '....nnnnnnnn....',
        '...nnnnnnnnnn...',
        '...nnnnnnnnnn...',
        '...nnnnnnnnnn...',
        '...FnnnnnnnnF...',
        '....FFFFFFFF....',
        '...NddddddddN...',
        '..fNddddddddNf..',
        '...eeeyyyyeeV...',
        '...NddddddddN...',
        '....NddddddN....',
        '.....ww.........',
        '................',
      ],
      side: [
        '................',
        '....nn..........',
        '...nnnn.........',
        '....nnnnnnn.....',
        '...nnnnnnnnn....',
        '...nnnnffffff...',
        '...nnnFfffkff...',
        '...nnnFfffkff...',
        '....nnfffhff....',
        '.....NdwwdN.....',
        '.....NdwfdN.....',
        '....eeeyyeV.....',
        '.....NdwwdN.....',
        '.....NddddN.....',
        '.....ww..ww.....',
        '................',
      ],
    },
    // Slots: 1 fur (auto-shaded), 2 ears, 3 face, 4 nose and mouth, 5 hands and feet.
    monkey: {
      slots: { 1: 'woodLight', 2: 'skinShade', 3: 'sakuraDark', 4: 'crimson', 5: 'wood' },
      shade: '1',
      legRows: [12, 13],
      span: [3, 12],
      down: [
        '................',
        '................',
        '................',
        '.....111111.....',
        '....11111111....',
        '..211333333112..',
        '..213k3333k312..',
        '...13k3333k31...',
        '...1133443311...',
        '...1111111111...',
        '..511111111115..',
        '....11111111....',
        '.....55..55.....',
        '.....55.........',
        '................',
        '................',
      ],
      up: [
        '................',
        '................',
        '................',
        '.....111111.....',
        '....11111111....',
        '..211111111112..',
        '..211111111112..',
        '...1111111111...',
        '...1111111111...',
        '...1111111111...',
        '..511111111115..',
        '....11111111....',
        '.....55..55.....',
        '.....55.........',
        '................',
        '................',
      ],
      side: [
        '................',
        '................',
        '................',
        '..........1111..',
        '.........111111.',
        '........2113333.',
        '.........13k333.',
        '.........13k334.',
        '.........113333.',
        '..1.1111111111..',
        '...11111111111..',
        '...11111111111..',
        '...5..5...5..5..',
        '...5..5...5..5..',
        '................',
        '................',
      ],
      side1: [
        '................',
        '................',
        '................',
        '..........1111..',
        '.........111111.',
        '........2113333.',
        '.........13k333.',
        '.........13k334.',
        '.........113333.',
        '..1.1111111111..',
        '...11111111111..',
        '...11111111111..',
        '....5.5...5.5...',
        '....5.5...5.5...',
        '................',
        '................',
      ],
    },
  },
  enemies: {
    kamaitachi: {
      anim: 'bob',
      shade: 'L',
      rows: [
        '................................',
        '................................',
        '................................',
        '.......................LLppp....',
        '......................LLppppp...',
        '......................LLppppp...',
        '.....................LLLppppp...',
        '.....oL...Lo.........LLLppppp...',
        '.....LLLLLL..........LLLLpppL...',
        '....LLLLLLLL.........LLLLLLLL...',
        '....LLkLLkLL.........LLoLLLLL...',
        '....ppkpLkLLLooooooo.oooooLLL...',
        '...kkppppLLLLoooooooooooooLL....',
        '....ppppLLLLLLLLLLLLLLLLooLL....',
        '....VV..LLLLLLLLLLLLLLLLLLL.....',
        '........LooppppppppppLLL........',
        '...wwwwmmmmpppppppppppL.........',
        '..wmmmmmmS..ppppppppoo..........',
        '...wS...............oo..........',
        '....w................mm.........',
        '.....................wmS........',
        '...........jjjjjjjjj..wm...jj...',
        '.........jj............jj.......',
        '.........ccjjjjjjjjjjjj.........',
        '...cc.cccjjjjjjjjjjjjjjccc......',
        '.....ccjjjj..........jjjjcc.....',
        '.....ccjjjj..........jjjjcc.....',
        '......cccjjjjjjjjjjjjjjccc......',
        '.........cccccccccccccc.........',
        '................................',
        '................................',
        '................................',
      ],
      // the whirlwind spins: its wisps trade places
      frame1: [
        { x: 9, y: 22, rows: ['__', '..'] },
        { x: 27, y: 21, rows: ['__'] },
        { x: 3, y: 24, rows: ['__'] },
        { x: 26, y: 23, rows: ['cc'] },
      ],
    },
    yamanba: {
      anim: 'bob',
      shade: 'v',
      rows: [
        '................................',
        '.............wwwwww.............',
        '..........wwwwwwwwwwww..........',
        '.........wwwwwwwwwwwwww.........',
        '........wwwwwwwwwwwwwwww........',
        '.......wwwwwwwwwwwwwwwwww.......',
        '.......wwwwwwwffffwwwwwww.......',
        '......wmwwwwwffffffwwwwwmw......',
        '......wmwwwwSSffffSSwwwwmw......',
        '......wmwwwwfkkffkkfwwwwmw......',
        '......wmmwwfffkffkfffwwmmw......',
        '.......wmmwwffffffffwwmmw.......',
        '.......wmmmmffFffFffmmmmw.......',
        '........wmmmmfVwwVfmmmmw........',
        '.........wmmmvvvvvvmmmw.........',
        '..........wvvvvvvvvvvw..........',
        '.........vvvvwwvvvvwwvv.........',
        '.........vvvvvwwvvwwvvv.........',
        '.......vvvvvvvvvvvvvvvvv.vv.....',
        '.....vvvvvvvvvvvvvvvvvvvvvvvv...',
        '....Fffvvvvvvvvvvvvvvvvvv..ffF..',
        '...mmffvvddddddddddddddvv..fff..',
        '...wm..vvNNNNNNNNNNNNNNvv.aaa...',
        '...w...vvvvvvvvvvvvvvvvvvaoaoa..',
        '.......vvvvvvvvvvvvvvvvvv.aaa...',
        '........vvvvvvvvvvvvvvvv...a....',
        '.........vvvvvvvvvvvvvv....o....',
        '.........vvvvvvvvvvvvvv.........',
        '...........vvvvvvvvvv...........',
        '.........v.vv.v..v.vv.v.........',
        '..........v..v....v..v..........',
        '............OO....OO............',
      ],
      // her grin widens and the knife glints
      frame1: [
        { x: 14, y: 13, rows: ['VwwwwV'] },
        { x: 3, y: 22, rows: ['w'] },
      ],
    },
  },
}
