/**
 * Region 11 — おしゃべりの駅町, the Chattering Station Town. A busy little
 * town round a railway station, below the Cloud Capital and before the
 * Valley of Hearts. The dragon's hunger is eating its small talk: the
 * greetings, the "yeah"s and "really?"s, the words for breakfast and
 * homework. Nopperabō, the faceless yokai, has wiped the townsfolk's faces,
 * and with them their expressions and little words.
 *
 * So this region is about everyday words and natural casual speech, and
 * above all about LISTENING: understanding real conversation by ear.
 *
 * Words: greetings and replies, question words and conversation glue,
 * places and things of daily life, food and home, everyday adjectives,
 * everyday verbs and people.
 * Grammar: casual だ, casual questions, 〜んです, よ/ね, けど, 〜って, the
 * spoken contractions (てる, ちゃう, とく), あいづち, かな, connectors,
 * dropped particles and じゃん.
 */
import type { RegionData } from '../types'

export const DATA: RegionData = {
  region: {
    id: 11,
    name: 'The Chattering Station Town',
    jp: 'おしゃべりの駅町',
    reading: 'おしゃべりのえきまち',
    tagline: 'Every train leaves on a word. Learn to hear them.',
    teaches: ['Everyday words: greetings, food, home, work', 'Natural casual speech: だ, 〜の？, 〜んだ, よ/ね, って, てる/ちゃう/とく', 'Listening: following real conversation by ear'],
    color: '#4fc3a1',
    emoji: '🚉',
    pos: { x: 50, y: 32 },
    map: 'ekimae',
  },

  words: [
    // ── Greetings & Replies
    ['ohayou', 'おはよう', 'おはよう', 'good morning', 'expression', '🌅', { alt: ['morning', 'good morning (casual)'] }],
    ['konbanwa', 'こんばんは', 'こんばんは', 'good evening', 'expression', '🌆', { alt: ['evening', 'hello (in the evening)'] }],
    ['sayounara', 'さようなら', 'さようなら', 'goodbye', 'expression', '👋', { alt: ['bye', 'farewell'] }],
    ['oyasumi', 'おやすみ', 'おやすみ', 'good night', 'expression', '😴', { alt: ['night night', 'sleep well', 'goodnight'] }],
    ['hai', 'はい', 'はい', 'yes', 'expression', '🙋', { alt: ['yes (polite)', 'okay', 'here'] }],
    ['iie', 'いいえ', 'いいえ', 'no', 'expression', '🙅‍♂️', { alt: ['no (polite)', 'not at all'] }],
    ['un', 'うん', 'うん', 'yeah', 'expression', '👍', { alt: ['yes (casual)', 'uh-huh', 'yep', 'yes'] }],
    ['uun', 'ううん', 'ううん', 'nope', 'expression', '👎', { alt: ['no (casual)', 'uh-uh', 'nah', 'no'] }],
    ['ee', 'ええ', 'ええ', 'yes (gentle)', 'expression', '🙂', { alt: ['yes', 'yeah', 'right', 'certainly'] }],
    ['daijoubu', '大丈夫', 'だいじょうぶ', 'all right', 'na-adj', '👌', { alt: ['okay', 'ok', 'fine', 'no problem', 'alright', 'safe'] }],
    ['gomennasai', 'ごめんなさい', 'ごめんなさい', 'sorry', 'expression', '🙇', { alt: ['I’m sorry', "I'm sorry", 'forgive me'] }],
    ['itadakimasu', 'いただきます', 'いただきます', 'let’s eat', 'expression', '🍽️', { alt: ["let's eat", 'thanks for the food', 'bon appetit', 'I humbly receive'] }],
    ['gochisousama', 'ごちそうさま', 'ごちそうさま', 'thanks for the meal', 'expression', '😋', { alt: ['thank you for the meal', 'that was delicious', 'that was a feast'] }],
    ['tadaima', 'ただいま', 'ただいま', 'I’m home', 'expression', '🏠', { alt: ["I'm home", 'I’m back', "I'm back"] }],
    ['okaeri', 'おかえり', 'おかえり', 'welcome home', 'expression', '🤗', { alt: ['welcome back'] }],

    // ── Questions & Conversation Glue
    ['nani', '何', 'なに', 'what', 'pronoun', '❓', { alt: ['what?'] }],
    ['dare', '誰', 'だれ', 'who', 'pronoun', '👤', { alt: ['who?', 'whom'] }],
    ['itsu', 'いつ', 'いつ', 'when', 'pronoun', '🕰️', { alt: ['when?', 'what time'] }],
    ['dou', 'どう', 'どう', 'how', 'adverb', '🤷', { alt: ['how about', 'in what way', 'how is it'] }],
    ['doushite', 'どうして', 'どうして', 'why', 'adverb', '🤔', { alt: ['why?', 'for what reason'] }],
    ['nande', 'なんで', 'なんで', 'how come', 'adverb', '😤', { alt: ['why (casual)', 'why', 'how come?'] }],
    ['donna', 'どんな', 'どんな', 'what kind of', 'expression', '🧐', { alt: ['what sort of', 'what kind'] }],
    ['sou', 'そう', 'そう', 'like that', 'adverb', '↩️', { alt: ['so', 'that way', 'that’s right', 'really'] }],
    ['naruhodo', 'なるほど', 'なるほど', 'I see', 'expression', '☝️', { alt: ['indeed', 'that makes sense', 'now I understand'] }],
    ['eeto', 'ええと', 'ええと', 'um', 'expression', '💭', { alt: ['let me see', 'uh', 'well', 'er'] }],
    ['anou', 'あのう', 'あのう', 'um, excuse me', 'expression', '🙋‍♂️', { alt: ['excuse me', 'um', 'er', 'say'] }],
    ['jaa', 'じゃあ', 'じゃあ', 'well then', 'expression', '👉', { alt: ['then', 'so', 'see you', 'in that case'] }],
    ['chotto', 'ちょっと', 'ちょっと', 'a little', 'adverb', '🤏', { alt: ['a bit', 'just a moment', 'slightly', 'a moment'] }],
    ['yappari', 'やっぱり', 'やっぱり', 'as expected', 'adverb', '🔄', { alt: ['after all', 'I knew it', 'just as I thought', 'sure enough'] }],
    ['hee', 'へえ', 'へえ', 'wow, really?', 'expression', '😮', { alt: ['really?', 'huh', 'oh really', 'wow'] }],

    // ── Town Life: places and things of every day
    ['jikan', '時間', 'じかん', 'time', 'noun', '⏳', { alt: ['hour', 'hours'] }],
    ['shigoto', '仕事', 'しごと', 'job', 'noun', '💼', { alt: ['work', 'occupation'] }],
    ['kaisha', '会社', 'かいしゃ', 'company', 'noun', '🏢', { alt: ['office', 'firm', 'business'] }],
    ['kuruma', '車', 'くるま', 'car', 'noun', '🚗', { alt: ['automobile', 'vehicle'], element: 'metal' }],
    ['densha', '電車', 'でんしゃ', 'train', 'noun', '🚃', { alt: ['electric train'], element: 'light' }],
    ['basu', 'バス', 'バス', 'bus', 'noun', '🚌', { element: 'metal' }],
    ['jitensha', '自転車', 'じてんしゃ', 'bicycle', 'noun', '🚲', { alt: ['bike', 'cycle'], element: 'metal' }],
    ['denwa', '電話', 'でんわ', 'telephone', 'noun', '☎️', { alt: ['phone', 'phone call', 'call'] }],
    ['sumaho', 'スマホ', 'スマホ', 'smartphone', 'noun', '📱', { alt: ['mobile', 'cell phone', 'smart phone', 'phone'] }],
    ['byouin', '病院', 'びょういん', 'hospital', 'noun', '🏥', { alt: ['clinic'] }],
    ['ginkou', '銀行', 'ぎんこう', 'bank', 'noun', '🏦', { element: 'metal' }],
    ['toire', 'トイレ', 'トイレ', 'toilet', 'noun', '🚻', { alt: ['bathroom', 'restroom', 'loo', 'washroom'], element: 'water' }],
    ['konbini', 'コンビニ', 'コンビニ', 'convenience store', 'noun', '🏪', { alt: ['corner shop', 'konbini', '24-hour store'] }],
    ['eiga', '映画', 'えいが', 'movie', 'noun', '🎬', { alt: ['film', 'cinema'] }],
    ['ongaku', '音楽', 'おんがく', 'music', 'noun', '🎵'],

    // ── Food & Home
    ['niku', '肉', 'にく', 'meat', 'noun', '🍖', { element: 'fire' }],
    ['yasai', '野菜', 'やさい', 'vegetables', 'noun', '🥦', { alt: ['vegetable', 'veggies', 'greens'], element: 'wood' }],
    ['tamago', '卵', 'たまご', 'egg', 'noun', '🥚', { alt: ['eggs'] }],
    ['gyuunyuu', '牛乳', 'ぎゅうにゅう', 'milk', 'noun', '🥛', { alt: ['cow’s milk'], element: 'water' }],
    ['asagohan', '朝ご飯', 'あさごはん', 'breakfast', 'noun', '🍳', { alt: ['morning meal'] }],
    ['hirugohan', '昼ご飯', 'ひるごはん', 'lunch', 'noun', '🥪', { alt: ['midday meal'] }],
    ['bangohan', '晩ご飯', 'ばんごはん', 'dinner', 'noun', '🍲', { alt: ['supper', 'evening meal'] }],
    ['obentou', 'お弁当', 'おべんとう', 'boxed lunch', 'noun', '🍱', { alt: ['bento', 'lunch box', 'packed lunch', 'lunchbox'] }],
    ['koohii', 'コーヒー', 'コーヒー', 'coffee', 'noun', '☕'],
    ['terebi', 'テレビ', 'テレビ', 'television', 'noun', '📺', { alt: ['TV', 'tv', 'telly'] }],
    ['shashin', '写真', 'しゃしん', 'photo', 'noun', '📸', { alt: ['photograph', 'picture'] }],
    ['shuumatsu', '週末', 'しゅうまつ', 'weekend', 'noun', '🗓️', { alt: ['the weekend'] }],
    ['tanjoubi', '誕生日', 'たんじょうび', 'birthday', 'noun', '🎂'],
    ['tsukue', '机', 'つくえ', 'desk', 'noun', '🗄️', { alt: ['writing desk', 'table (desk)'], element: 'wood' }],
    ['shukudai', '宿題', 'しゅくだい', 'homework', 'noun', '📝', { alt: ['assignment'] }],

    // ── How It Is: everyday adjectives
    ['ii', 'いい', 'いい', 'good', 'i-adj', '🌟', { alt: ['nice', 'fine', 'okay', 'great'] }],
    ['warui', '悪い', 'わるい', 'bad', 'i-adj', '😈', { alt: ['wrong', 'evil', 'my bad'] }],
    ['atsui-weather', '暑い', 'あつい', 'hot (weather)', 'i-adj', '🥵', { alt: ['hot', 'hot weather', 'boiling'], element: 'fire' }],
    ['samui', '寒い', 'さむい', 'cold (weather)', 'i-adj', '🥶', { alt: ['cold', 'chilly', 'freezing'], element: 'water' }],
    ['ooi', '多い', 'おおい', 'many', 'i-adj', '🔢', { alt: ['a lot', 'lots', 'numerous', 'plenty'] }],
    ['sukunai', '少ない', 'すくない', 'few', 'i-adj', '🪶', { alt: ['not many', 'little', 'scarce', 'not much'] }],
    ['chikai', '近い', 'ちかい', 'near', 'i-adj', '📍', { alt: ['close', 'nearby', 'close by'] }],
    ['tooi', '遠い', 'とおい', 'far', 'i-adj', '🔭', { alt: ['distant', 'far away'] }],
    ['isogashii', '忙しい', 'いそがしい', 'busy', 'i-adj', '🏃', { alt: ['hectic'] }],
    ['hima', '暇', 'ひま', 'free (not busy)', 'na-adj', '🛋️', { alt: ['free', 'not busy', 'idle', 'free time', 'spare time'] }],
    ['muzukashii', '難しい', 'むずかしい', 'difficult', 'i-adj', '🧩', { alt: ['hard', 'tough', 'tricky'] }],
    ['omoshiroi', '面白い', 'おもしろい', 'interesting', 'i-adj', '😆', { alt: ['funny', 'fun', 'amusing'] }],
    ['tsumaranai', 'つまらない', 'つまらない', 'boring', 'i-adj', '🥱', { alt: ['dull', 'uninteresting', 'dreary'] }],
    ['akarui', '明るい', 'あかるい', 'bright', 'i-adj', '💡', { alt: ['light', 'cheerful', 'sunny'], element: 'light' }],
    ['kurai', '暗い', 'くらい', 'dark', 'i-adj', '🌑', { alt: ['gloomy', 'dim'] }],

    // ── Doing and People: everyday verbs, he, she, everyone
    ['iu', '言う', 'いう', 'say', 'verb', '🗣️', { masu: '言います', alt: ['to say', 'tell', 'to tell', 'call (name)'] }],
    ['sumu', '住む', 'すむ', 'live (reside)', 'verb', '🏘️', { masu: '住みます', alt: ['to live', 'live', 'reside', 'dwell'] }],
    ['hataraku', '働く', 'はたらく', 'work', 'verb', '👷', { masu: '働きます', alt: ['to work', 'labour', 'labor'] }],
    ['motsu', '持つ', 'もつ', 'hold', 'verb', '✋', { masu: '持ちます', alt: ['to hold', 'carry', 'have', 'to have', 'to carry'] }],
    ['owaru', '終わる', 'おわる', 'end', 'verb', '🔚', { masu: '終わります', alt: ['to end', 'finish', 'be over', 'to finish'] }],
    ['hajimaru', '始まる', 'はじまる', 'start', 'verb', '▶️', { masu: '始まります', alt: ['to start', 'begin', 'to begin', 'get started'] }],
    ['akeru', '開ける', 'あける', 'open', 'verb', '🔓', { masu: '開けます', alt: ['to open', 'open (something)'] }],
    ['shimeru', '閉める', 'しめる', 'close', 'verb', '🔒', { masu: '閉めます', alt: ['to close', 'shut', 'to shut', 'close (something)'] }],
    ['tetsudau', '手伝う', 'てつだう', 'help out', 'verb', '🤝', { masu: '手伝います', alt: ['help', 'to help', 'assist', 'lend a hand'] }],
    ['ganbaru', '頑張る', 'がんばる', 'do one’s best', 'verb', '💪', { masu: '頑張ります', alt: ["do one's best", 'try hard', 'hang in there', 'go for it', 'persevere'] }],
    ['yobu', '呼ぶ', 'よぶ', 'call', 'verb', '📣', { masu: '呼びます', alt: ['to call', 'call out', 'summon', 'invite'] }],
    ['kare', '彼', 'かれ', 'he', 'pronoun', '👨', { alt: ['him', 'boyfriend'] }],
    ['kanojo', '彼女', 'かのじょ', 'she', 'pronoun', '👩', { alt: ['her', 'girlfriend'] }],
    ['minna', 'みんな', 'みんな', 'everyone', 'pronoun', '👨‍👩‍👧‍👦', { alt: ['everybody', 'all', 'all of us'] }],
    ['jibun', '自分', 'じぶん', 'oneself', 'pronoun', '🪞', { alt: ['myself', 'self', 'yourself', 'one’s self'] }],
  ],

  grammar: [
    { id: 'casual-da', region: 11, jp: '〜だ／〜じゃない', say: 'da / ja nai', en: 'casual “is / isn’t”: です → だ, じゃないです → じゃない (after a noun the だ is often dropped too)', example: { jp: 'あれは バスじゃない。電車だ。', en: 'That’s not a bus. It’s a train.' } },
    { id: 'casual-question', region: 11, jp: '〜？（↗）／〜の？', say: 'rising tone / no?', en: 'casual questions: drop か and let your voice rise; add の to ask about the situation', example: { jp: 'あした、来る？ …どこ 行くの？', en: 'Coming tomorrow? …Where are you off to?' } },
    { id: 'n-desu', region: 11, jp: '〜んです／〜んだ', say: 'n desu / n da', en: 'explaining, or asking for the story behind something (plain form + んです; casual んだ)', example: { jp: 'どうしたの？ …おなかが いたいんです。', en: 'What’s wrong? …My stomach hurts, you see.' } },
    { id: 'yo-ne', region: 11, jp: '〜よ／〜ね／〜よね', say: 'yo / ne / yo ne', en: 'sentence endings: よ tells the listener something new, ね asks them to agree, よね checks “…right?”', example: { jp: 'この パン、おいしいね。…うん、おいしいよ！', en: 'This bread’s good, isn’t it. …Yeah, it really is!' } },
    { id: 'kedo-soft', region: 11, jp: '〜けど／〜が（…）', say: 'kedo / ga', en: '“but…”: softens a request or opener and lets it trail off politely', example: { jp: 'すみません、トイレに 行きたいんですけど…', en: 'Excuse me, I’d like to use the toilet, but… (where is it?)' } },
    { id: 'tte-quote', region: 11, jp: '〜って', say: 'tte', en: 'casual quoting: “(someone) says…”, “I heard that…”, and “what you call…”', example: { jp: '電車、おくれるって。', en: 'They say the train’s going to be late.' } },
    { id: 'teru-contraction', region: 11, jp: '〜てる・〜てく', say: 'teru / teku', en: 'spoken 〜ている and 〜ていく: 見ている → 見てる, もっていく → もってく', example: { jp: 'いま テレビ 見てる。…かさ、もってく？', en: 'I’m watching TV. …Taking an umbrella?' } },
    { id: 'chau', region: 11, jp: '〜ちゃう・〜じゃう', say: 'chau / jau', en: 'spoken 〜てしまう / 〜でしまう: do completely, all the way (たべちゃう, のんじゃう)', example: { jp: 'しゅくだい、もう やっちゃった。', en: 'I already finished off my homework.' } },
    { id: 'toku', region: 11, jp: '〜とく・〜どく', say: 'toku / doku', en: 'spoken 〜ておく: do something now, ready for later (あけとく, よんどく)', example: { jp: 'まど、あけとくね。', en: 'I’ll leave the window open (for later).' } },
    { id: 'aizuchi', region: 11, jp: 'うん・そう・へえ・なるほど・ほんと？', say: 'aizuchi', en: 'back-channel replies: little sounds that show you are listening (yeah, right, oh, I see, really?)', example: { jp: 'きのう ふじさんに のぼったんだ。…へえ、すごい！', en: 'I climbed Mount Fuji yesterday. …Wow, amazing!' } },
    { id: 'kana-wonder', region: 11, jp: '〜かな', say: 'kana', en: 'wondering aloud: “I wonder…” (plain form + かな)', example: { jp: 'あした、晴れるかな。', en: 'I wonder if it’ll be sunny tomorrow.' } },
    { id: 'connectors', region: 11, jp: 'でも・だから・それで・じゃあ', say: 'demo / dakara / sore de / jaa', en: 'joining turns in conversation: but / so / and then / well then', example: { jp: '雨だよ。…じゃあ、かさ もってく。', en: 'It’s raining. …Well then, I’ll take an umbrella.' } },
    { id: 'particle-drop', region: 11, jp: '（は・を・が・に）の しょうりゃく', say: 'dropped particles', en: 'casual speech often drops は, を, が and に: コーヒー のむ？ (= コーヒーを のむ？)', example: { jp: 'コーヒー のむ？ …うん、のむ。', en: 'Want some coffee? …Yeah.' } },
    { id: 'jan', region: 11, jp: '〜じゃん', say: 'jan', en: 'casual “isn’t it!” / “you know!”: points something out and pushes for agreement', example: { jp: 'この 写真、いいじゃん！', en: 'This photo’s great, isn’t it!' } },
  ],

  sentences: [
    { id: 'ek1', en: 'Where are you going? (casual)', tokens: ['どこ', '行く', 'の'], distractors: ['です', 'を'], region: 11, hint: 'Casual questions drop か. 〜の？ with a rising tone asks what’s going on: どこ 行くの？' },
    { id: 'ek2', en: 'I’m just popping to the convenience store.', tokens: ['ちょっと', 'コンビニ', '行って', 'くる'], distractors: ['を', '行きます'], region: 11, hint: 'In speech the に is often dropped: コンビニ 行ってくる = go (and come back).' },
    { id: 'ek3', en: 'That’s not a bus. (casual)', tokens: ['あれ', 'は', 'バス', 'じゃない'], distractors: ['です', 'を'], region: 11, hint: 'Casual “isn’t” after a noun is じゃない (polite: じゃないです).' },
    { id: 'ek4', en: 'I’m free today. (casual)', tokens: ['今日', 'は', '暇', 'だ'], distractors: ['な', 'を'], region: 11, hint: 'だ is the casual です: 暇だ. (な only goes before a noun: 暇な 日.)' },
    { id: 'ek5', en: 'Why were you late? (asking for the story)', tokens: ['どうして', 'おくれた', 'の'], distractors: ['か', 'です'], region: 11, hint: 'Plain past + の？ asks for the story behind something.' },
    { id: 'ek6', en: 'It’s because the train stopped.', tokens: ['電車', 'が', '止まった', 'んだ'], distractors: ['を', '止まります'], region: 11, hint: '〜んだ explains: plain form + んだ. 止まる takes が (the train stops by itself).' },
    { id: 'ek7', en: 'This coffee is good, isn’t it?', tokens: ['この', 'コーヒー', 'おいしい', 'ね'], distractors: ['か', 'を'], region: 11, hint: 'ね asks the listener to agree. In casual talk the は is often dropped.' },
    { id: 'ek8', en: 'He says he’s busy.', tokens: ['彼', 'は', '忙しい', 'って'], distractors: ['を', 'です'], region: 11, hint: '〜って passes on what someone said: plain form + って.' },
    { id: 'ek9', en: 'I’m watching TV right now.', tokens: ['今', 'テレビ', '見てる'], distractors: ['見た', 'か'], region: 11, hint: '見てる = 見ている in speech, and the を is dropped too.' },
    { id: 'ek10', en: 'I’ll leave the window open (for you).', tokens: ['窓', '開けとく', 'ね'], distractors: ['開けた', 'か'], region: 11, hint: '開けとく = 開けておく: do it now, ready for later.' },
    { id: 'ek11', en: 'I ate up all the meat!', tokens: ['肉', 'ぜんぶ', '食べちゃった'], distractors: ['食べる', 'か'], region: 11, hint: '食べちゃった = 食べてしまった: ate it all, completely.' },
    { id: 'ek12', en: 'I wonder if it’ll be hot tomorrow.', tokens: ['明日', 'は', '暑い', 'かな'], distractors: ['よ', 'を'], region: 11, hint: '〜かな wonders aloud: plain form + かな.' },
    { id: 'ek13', en: 'This photo is great, isn’t it!', tokens: ['この', '写真', 'いい', 'じゃん'], distractors: ['です', 'を'], region: 11, hint: '〜じゃん: a casual “isn’t it!” that pushes for agreement.' },
    { id: 'ek14', en: 'But I’ve got homework, you see.', tokens: ['でも', '宿題', 'が', 'ある', 'んだ'], distractors: ['だから', 'を'], region: 11, hint: 'でも pushes back on what was said; 〜んだ gives your reason as an explanation.' },
    { id: 'ek15', en: 'Um, excuse me, where is the toilet?', tokens: ['あのう', 'トイレ', 'は', 'どこ', 'です', 'か'], distractors: ['を', 'じゃん'], region: 11, hint: 'あのう politely gets a stranger’s attention before a question.' },
    { id: 'ek16', en: 'Well then, see you tomorrow!', tokens: ['じゃあ', 'また', '明日'], distractors: ['でも', 'を'], region: 11, hint: 'じゃあ (well then) wraps a conversation up.' },
  ],

  runes: [
    { id: 'ek-r1', jp: 'ちょっと待って！', reading: 'ちょっとまって！', answer: 'Wait a moment!', wrong: ['I waited for a long time.', 'Don’t wait for me.'], region: 11 },
    { id: 'ek-r2', jp: '今日、暇？', reading: 'きょう、ひま？', answer: 'Are you free today?', wrong: ['I am busy today.', 'Today was boring.'], region: 11 },
    { id: 'ek-r3', jp: '電車、おくれるって', reading: 'でんしゃ、おくれるって', answer: 'They say the train will be late.', wrong: ['The train left early.', 'Let’s take the train.'], region: 11 },
    { id: 'ek-r4', jp: 'どうしたの？ おなかがいたいんだ', reading: 'どうしたの？ おなかがいたいんだ', answer: 'What’s wrong? — My stomach hurts, you see.', wrong: ['Shall we eat? — I’m hungry.', 'Where are you going? — To the hospital.'], region: 11 },
    { id: 'ek-r5', jp: 'この映画、面白いじゃん！', reading: 'このえいが、おもしろいじゃん！', answer: 'This movie is really good, isn’t it!', wrong: ['This movie is boring.', 'Shall we go and see a movie?'], region: 11 },
    { id: 'ek-r6', jp: '窓、開けとくね', reading: 'まど、あけとくね', answer: 'I’ll leave the window open.', wrong: ['Please close the window.', 'The window was already open.'], region: 11 },
    { id: 'ek-r7', jp: '宿題、もう終わっちゃった', reading: 'しゅくだい、もうおわっちゃった', answer: 'My homework’s already all done.', wrong: ['I haven’t started my homework.', 'Homework starts tomorrow.'], region: 11 },
    { id: 'ek-r8', jp: '明日、晴れるかな', reading: 'あした、はれるかな', answer: 'I wonder if it’ll be sunny tomorrow.', wrong: ['It will definitely be sunny tomorrow.', 'It was sunny yesterday.'], region: 11 },
    { id: 'ek-r9', jp: 'ただいま！ —おかえり！', reading: 'ただいま！ —おかえり！', answer: 'I’m home! — Welcome back!', wrong: ['Goodbye! — See you!', 'Good morning! — Good night!'], region: 11 },
    { id: 'ek-r10', jp: '彼女、どこに住んでるの？', reading: 'かのじょ、どこにすんでるの？', answer: 'Where does she live?', wrong: ['Where does she work?', 'When did she move here?'], region: 11 },
  ],

  readings: {
    行って: 'いって',
    止まった: 'とまった',
    止まります: 'とまります',
    見てる: 'みてる',
    見た: 'みた',
    開けとく: 'あけとく',
    開けた: 'あけた',
    食べちゃった: 'たべちゃった',
  },

  npcs: [
    {
      id: 'eki-yui',
      name: 'Yui the Barista',
      jp: 'バリスタの ユイ',
      emoji: '☕',
      region: 11,
      personality: 'Bright, quick barista at Café Komorebi by the station. Starts every customer politely, then slides into friendly casual talk as soon as she likes you. Nopperabō has wiped her face only halfway, so she can still smile, just barely.',
      politeness: 'polite',
      color: '#c98b5b',
      interests: ['coffee', 'regulars and their stories', 'the weather', 'where travellers are headed'],
      greeting: { jp: 'いらっしゃいませ！ こんにちは。', en: 'Welcome! Hello.' },
    },
    {
      id: 'eki-haruto',
      name: 'Haruto the Student',
      jp: 'こうこうせいの ハルト',
      emoji: '🎒',
      region: 11,
      personality: 'High-school student stuck on the platform because no train will leave. Talks fast and very casually, says マジで a lot, works a part-time job he complains about, and loves scary movies.',
      politeness: 'casual',
      color: '#5aa9e6',
      interests: ['scary movies', 'his part-time job', 'the weekend', 'trains'],
      greeting: { jp: 'あ、おはよう！', en: 'Oh, morning!' },
    },
    {
      id: 'eki-mari',
      name: 'Mari the Grocer (on the phone)',
      jp: 'やおやの マリ（でんわ）',
      emoji: '📞',
      region: 11,
      personality: 'The chatty grocer of the shopping street, calling the phone box by the plaza. On the phone she talks even faster than in person, and never quite finishes a sentence: けど…',
      politeness: 'casual',
      color: '#f28a2e',
      interests: ['vegetables', 'gossip from the shopping street', 'her customers', 'closing time'],
      greeting: { jp: 'もしもし？ マリだけど！', en: 'Hello? It’s Mari!' },
    },
  ],

  scenarios: [
    {
      id: 'ekimae-cafe',
      npcId: 'eki-yui',
      region: 11,
      translations: 'always',
      start: 'greet',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Café Komorebi by the station. Yui the barista still has half a face… just. Order a drink and chat with her.',
        'She starts polite, then slips into casual talk. Listen for the endings: ね, よ, 〜の？, 〜んです.',
        'Pick the reply that fits. Wrong answers cost a ❤️.',
      ],
      nodes: {
        greet: {
          id: 'greet',
          line: { jp: 'いらっしゃいませ！ こんにちは。', en: 'Welcome! Hello.' },
          next: 'order',
          options: [
            { jp: 'こんにちは。', en: 'Hello.', correct: true, wordIds: ['konnichiwa'], reply: { jp: 'あ… あいさつ、ひさしぶりに 聞きました！', en: 'Oh… it’s been ages since anyone greeted me!' }, effects: { trust: 1 } },
            { jp: 'おやすみ。', en: 'Good night.', correct: false, wordIds: ['oyasumi'], reply: { jp: 'え、もう ねるんですか？ まだ おひるですよ。', en: 'Huh, you’re off to bed? It’s only lunchtime.' }, note: 'おやすみ is “good night”, said before sleeping. To greet someone in the daytime: こんにちは.' },
            { jp: 'ごちそうさま。', en: 'Thanks for the meal.', correct: false, wordIds: ['gochisousama'], reply: { jp: 'まだ 何も 食べて いませんよ！', en: 'You haven’t eaten anything yet!' }, note: 'ごちそうさま is said after eating. Greet with こんにちは.' },
          ],
        },
        order: {
          id: 'order',
          line: { jp: 'ご注文は？ コーヒーと、こうちゃが ありますよ。', en: 'What would you like? We have coffee and tea.' },
          kana: 'ごちゅうもんは？ コーヒーと、こうちゃが ありますよ。',
          wordIds: ['koohii'],
          hint: 'Ask for it with 〜を ください.',
          next: 'size',
          options: [
            { jp: 'コーヒーを ください。', en: 'A coffee, please.', correct: true, reply: { jp: 'はい、コーヒーですね！', en: 'One coffee, coming up!' }, effects: { trust: 1 } },
            { jp: 'コーヒーは 誰？', kana: 'コーヒーは だれ？', en: 'Who is coffee?', correct: false, wordIds: ['dare'], reply: { jp: 'だれ…？ コーヒーは コーヒーですけど…', en: 'Who…? Coffee is just coffee…' }, note: '誰 (だれ) means “who”. To order: コーヒーを ください.' },
            { jp: 'コーヒーは いつ？', en: 'When is coffee?', correct: false, wordIds: ['itsu'], reply: { jp: 'いつでも ありますよ？ …ご注文ですか？', en: 'It’s always available…? Is that an order?' }, note: 'いつ means “when”. To order: コーヒーを ください.' },
          ],
        },
        size: {
          id: 'size',
          line: { jp: 'ホットと アイス、どっちが いいですか。', en: 'Hot or iced: which would you like?' },
          hint: 'いい = good: ホットが いいです (hot is good, please).',
          next: 'chat',
          options: [
            { jp: 'ホットが いいです。', en: 'Hot, please.', correct: true, wordIds: ['ii'], reply: { jp: 'ホットですね。きょうに ぴったり！', en: 'Hot it is. Perfect for today!' }, effects: { trust: 1 } },
            { jp: 'ホットが 悪いです。', kana: 'ホットが わるいです。', en: 'Hot is bad.', correct: false, wordIds: ['warui'], reply: { jp: 'わ、悪い…？ じゃあ アイス…？', en: 'B-bad…? So, iced…?' }, note: '悪い (わるい) is “bad”. To choose: 〜が いいです.' },
            { jp: 'ホットが 遠いです。', kana: 'ホットが とおいです。', en: 'Hot is far away.', correct: false, wordIds: ['tooi'], reply: { jp: 'とおい？ ここに ありますよ？', en: 'Far away? It’s right here?' }, note: '遠い (とおい) means “far”. To choose: 〜が いいです.' },
          ],
        },
        chat: {
          id: 'chat',
          line: { jp: 'きょうは 寒いですね。', en: 'It’s cold today, isn’t it?' },
          kana: 'きょうは さむいですね。',
          wordIds: ['samui'],
          hint: 'ね asks you to agree. Agree with ね too: そうですね.',
          next: 'travel',
          options: [
            { jp: 'そうですね。', en: 'It sure is.', correct: true, wordIds: ['sou'], reply: { jp: 'ね！ 手が つめたく なっちゃう。', en: 'Right! My hands get so cold.' }, effects: { trust: 1 } },
            { jp: 'そうですか。', en: 'Oh, is that so?', correct: false, wordIds: ['sou'], reply: { jp: '…え？ 外、寒く なかったですか？', en: '…Huh? Wasn’t it cold outside?' }, note: 'そうですか (↘) receives news you didn’t know. She’s asking you to agree about something you both feel: そうですね.' },
            { jp: 'いただきます。', en: 'Let’s eat.', correct: false, wordIds: ['itadakimasu'], reply: { jp: 'まだ コーヒー、できて ないですよ！', en: 'Your coffee isn’t ready yet!' }, note: 'いただきます is said just before you eat or drink. To agree: そうですね.' },
          ],
        },
        travel: {
          id: 'travel',
          line: { jp: 'その かばん、大きいですね。旅行なんですか？', en: 'That’s a big bag. Are you travelling?' },
          kana: 'その かばん、おおきいですね。りょこうなんですか？',
          hint: 'She asks with 〜んですか. Explain with 〜んです: 〜に 行くんです.',
          next: 'casual',
          options: [
            { jp: 'はい、こころの たにに 行くんです。', kana: 'はい、こころの たにに いくんです。', en: 'Yes, I’m going to the Valley of Hearts.', correct: true, wordIds: ['hai'], reply: { jp: 'へえ！ いいですね！ あそこは きれいですよ。', en: 'Ooh! Lovely! It’s beautiful there.' }, effects: { trust: 1 } },
            { jp: 'はい、こころの たにに 行くんですか。', kana: 'はい、こころの たにに いくんですか。', en: 'Yes, are you going to the Valley of Hearts?', correct: false, wordIds: ['hai'], reply: { jp: 'え、わたしですか？ わたしは お店が あるので…', en: 'Huh, me? I’ve got the café to run…' }, note: 'The か turns it into a question back at her. To explain your own plans: 〜に 行くんです.' },
            { jp: 'ううん、旅行じゃないだ。', kana: 'ううん、りょこうじゃないだ。', en: '(Nope, not-a-trip-is.)', correct: false, wordIds: ['uun'], reply: { jp: '…じゃない、だ？', en: '…Isn’t… is?' }, note: 'じゃない already means “isn’t”; there is no だ after it. Casual: 旅行じゃない.' },
          ],
        },
        casual: {
          id: 'casual',
          line: { jp: 'あ、ため口で いい？ …で、どこから 来たの？', en: 'Oh, is it OK if I talk casually? …So, where did you come from?' },
          kana: 'あ、ためぐちで いい？ …で、どこから きたの？',
          hint: 'Her question ends in casual の？ Answer casually with 〜んだ: 〜から 来たんだ.',
          next: 'pay',
          options: [
            { jp: '雲の みやこから 来たんだ。', kana: 'くもの みやこから きたんだ。', en: 'I came from the Cloud Capital.', correct: true, reply: { jp: 'えっ、雲の 上から？ すごい！', en: 'Whoa, from above the clouds? Amazing!' }, effects: { trust: 1 } },
            { jp: '雲の みやこから 来たの？', kana: 'くもの みやこから きたの？', en: 'Did you come from the Cloud Capital?', correct: false, reply: { jp: 'わたし？ ううん、ずっと ここだよ。', en: 'Me? Nope, I’ve always been here.' }, note: 'の？ with a rising tone asks a question. You are answering, so explain: 〜から 来たんだ.' },
            { jp: 'いつ 来たの？', kana: 'いつ きたの？', en: 'When did you come?', correct: false, wordIds: ['itsu'], reply: { jp: 'え？ わたしが 聞いたんだけど…', en: 'Huh? I’m the one who asked…' }, note: 'She asked where you came from (どこから). Answer it: 〜から 来たんだ.' },
          ],
        },
        pay: {
          id: 'pay',
          line: { jp: 'はい、コーヒー、おまたせ！ ゆっくり して ってね。', en: 'Here’s your coffee, sorry for the wait! Take your time.' },
          hint: 'What do you say right before drinking?',
          next: 'after',
          options: [
            { jp: 'いただきます！', en: 'Here goes! (thanks)', correct: true, wordIds: ['itadakimasu'], reply: { jp: 'どうぞ！', en: 'Enjoy!' }, effects: { trust: 1 } },
            { jp: 'ごちそうさま！', en: 'Thanks for the meal!', correct: false, wordIds: ['gochisousama'], reply: { jp: 'え、もう のんだの？ はやっ！', en: 'Huh, you drank it already? That was fast!' }, note: 'ごちそうさま comes after. Before you start: いただきます.' },
            { jp: 'ただいま！', en: 'I’m home!', correct: false, wordIds: ['tadaima'], reply: { jp: 'ここ、きみの 家じゃないよ！', en: 'This isn’t your house!' }, note: 'ただいま is what you say when you get home. Before drinking: いただきます.' },
          ],
        },
        after: {
          id: 'after',
          line: { jp: 'どう？ おいしい？', en: 'How is it? Good?' },
          wordIds: ['dou'],
          hint: 'Agree casually: うん (yeah).',
          next: 'leave',
          options: [
            { jp: 'うん、すごく おいしい！', en: 'Yeah, really good!', correct: true, wordIds: ['un'], reply: { jp: 'よかった〜！', en: 'Yay, I’m so glad!' }, effects: { trust: 1 } },
            { jp: 'ううん、すごく おいしい！', en: 'Nope, really good!', correct: false, wordIds: ['uun'], reply: { jp: 'どっち？！', en: 'Which is it?!' }, note: 'ううん is a casual “no”. A casual “yes” is うん. Listen for the long ううん with a dip in the middle.' },
            { jp: 'どうして？', en: 'Why?', correct: false, wordIds: ['doushite'], reply: { jp: 'どうしてって… 味を 聞いただけ！', en: '“Why”? I only asked how it tastes!' }, note: 'どう? means “how is it?”; どうして means “why?”. Answer her: うん、おいしい！' },
          ],
        },
        leave: {
          id: 'leave',
          line: { jp: 'もう 行くの？ じゃあ、また 来てね！', en: 'Leaving already? Well then, come again!' },
          kana: 'もう いくの？ じゃあ、また きてね！',
          wordIds: ['jaa'],
          hint: 'After finishing a meal or drink: ごちそうさま.',
          next: 'end',
          options: [
            { jp: 'うん、ごちそうさま！ またね。', en: 'Yeah, thanks for the coffee! See you.', correct: true, wordIds: ['gochisousama'], reply: { jp: 'またね！', en: 'See you!' }, effects: { trust: 1 } },
            { jp: 'うん、いただきます！ またね。', en: 'Yeah, let’s eat! See you.', correct: false, wordIds: ['itadakimasu'], reply: { jp: 'これから 食べるの？ もう 行くのに？', en: 'You’re about to eat? But you’re leaving?' }, note: 'いただきます is before eating. When you have finished: ごちそうさま.' },
            { jp: 'おはよう！', en: 'Good morning!', correct: false, wordIds: ['ohayou'], reply: { jp: 'いまから 一日が 始まるの？', en: 'Is your day only starting now?' }, note: 'おはよう is a morning greeting. When leaving after a drink: ごちそうさま、またね.' },
          ],
        },
        end: { id: 'end', line: { jp: 'ありがとう！ …なんか、顔が あったかく なった みたい。', en: 'Thanks! …Somehow my face feels warmer.' }, kana: 'ありがとう！ …なんか、かおが あったかく なった みたい。', end: true },
      },
    },

    {
      id: 'ekimae-weekend',
      npcId: 'eki-haruto',
      region: 11,
      translations: 'hint',
      start: 'greet',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Haruto, a high-school student, has been stuck on the platform all morning. He talks fast and casual.',
        'English is hidden this time: listen to his Japanese (buy a hint if you are lost).',
        'Answer like a friend would: うん, ううん, へえ, 〜んだ…',
      ],
      nodes: {
        greet: {
          id: 'greet',
          line: { jp: 'あ、おはよう！ …って、もう おひるか。', en: 'Oh, morning! …Well, it’s already noon, huh.' },
          hint: 'He greeted you with a casual good morning. Greet him back the same way.',
          next: 'train',
          options: [
            { jp: 'おはよう！', en: 'Morning!', correct: true, wordIds: ['ohayou'], reply: { jp: 'おはよ！', en: 'Mornin’!' }, effects: { trust: 1 } },
            { jp: 'こんばんは！', en: 'Good evening!', correct: false, wordIds: ['konbanwa'], reply: { jp: 'え、まだ よるじゃないよ？', en: 'Huh, it’s not night yet?' }, note: 'こんばんは is for the evening. He said おはよう, so say it back.' },
            { jp: 'さようなら！', en: 'Goodbye!', correct: false, wordIds: ['sayounara'], reply: { jp: 'え、もう 行っちゃうの？', en: 'Huh, you’re leaving already?' }, note: 'さようなら is a (rather final) goodbye. To greet: おはよう.' },
          ],
        },
        train: {
          id: 'train',
          line: { jp: '電車、ぜんぜん 来ないね。', en: 'The train just isn’t coming, is it.' },
          kana: 'でんしゃ、ぜんぜん こないね。',
          wordIds: ['densha'],
          hint: 'ね wants you to agree: うん、来ないね.',
          next: 'weekend',
          options: [
            { jp: 'うん、来ないね。', kana: 'うん、こないね。', en: 'Yeah, it isn’t, huh.', correct: true, wordIds: ['un'], reply: { jp: 'だよね〜。', en: 'Right?' }, effects: { trust: 1 } },
            { jp: 'うん、来るね。', kana: 'うん、くるね。', en: 'Yeah, it’s coming, huh.', correct: false, wordIds: ['un'], reply: { jp: 'え、どこに？ 見えないけど…', en: 'Huh, where? I can’t see it…' }, note: 'He said 来ない (isn’t coming). Agree with the same thing: 来ないね.' },
            { jp: 'ううん、来ないね。', kana: 'ううん、こないね。', en: 'Nope, it isn’t, huh.', correct: false, wordIds: ['uun'], reply: { jp: 'ううん…なのに、来ない？ どっち？', en: 'Nope… but it isn’t coming? Which is it?' }, note: 'To agree, start with うん (yeah). ううん is a casual “no”.' },
          ],
        },
        weekend: {
          id: 'weekend',
          line: { jp: '週末、何 してた？', en: 'What were you up to at the weekend?' },
          kana: 'しゅうまつ、なに してた？',
          wordIds: ['shuumatsu', 'nani'],
          hint: 'してた = していた (was doing). Say what you were doing: 〜を 見てた.',
          next: 'kind',
          options: [
            { jp: '映画を 見てた。', kana: 'えいがを みてた。', en: 'I was watching movies.', correct: true, wordIds: ['eiga'], reply: { jp: 'へえ、いいな！', en: 'Ooh, nice!' }, effects: { trust: 1 } },
            { jp: '映画を 見てる。', kana: 'えいがを みてる。', en: 'I’m watching a movie.', correct: false, wordIds: ['eiga'], reply: { jp: 'いま？ ここで？', en: 'Right now? Here?' }, note: '見てる is happening now. He asked about the weekend (past): 見てた.' },
            { jp: '映画は 誰？', kana: 'えいがは だれ？', en: 'Who is the movie?', correct: false, wordIds: ['dare'], reply: { jp: 'だれ…？ え、なに？', en: 'Who…? Huh, what?' }, note: '誰 means “who”. He asked what you did: 〜を 見てた.' },
          ],
        },
        kind: {
          id: 'kind',
          line: { jp: 'どんな 映画？', en: 'What kind of movie?' },
          kana: 'どんな えいが？',
          wordIds: ['donna'],
          hint: 'どんな asks “what kind”. Describe it: 〜い 映画.',
          next: 'job',
          options: [
            { jp: 'こわくて 面白い 映画！', kana: 'こわくて おもしろい えいが！', en: 'A scary, really fun movie!', correct: true, wordIds: ['omoshiroi'], reply: { jp: 'マジで？ おれ、こわい 映画 大好き！', en: 'For real? I love scary movies!' }, effects: { trust: 1 } },
            { jp: '二時間！', kana: 'にじかん！', en: 'Two hours!', correct: false, wordIds: ['jikan'], reply: { jp: 'ながさ じゃなくて…', en: 'Not how long…' }, note: '二時間 says how long. どんな asks what kind: こわい映画, 面白い映画…' },
            { jp: 'きのう！', en: 'Yesterday!', correct: false, wordIds: ['itsu'], reply: { jp: 'いつ、じゃなくて どんな、だよ。', en: 'Not “when”, “what kind”.' }, note: 'きのう answers いつ (when). どんな asks what kind.' },
          ],
        },
        job: {
          id: 'job',
          line: { jp: 'おれは ずっと バイト。店長が、来週も 来てって。', en: 'Me? Part-time job the whole time. My manager says come in next week too.' },
          kana: 'おれは ずっと バイト。てんちょうが、らいしゅうも きてって。',
          wordIds: ['shigoto'],
          hint: '〜って passes on what someone said. Sympathise: 忙しいね (you’re busy, huh).',
          next: 'why',
          options: [
            { jp: 'えー、忙しいね！', kana: 'えー、いそがしいね！', en: 'Ugh, you’re busy, huh!', correct: true, wordIds: ['isogashii'], reply: { jp: 'でしょ？ でも まあ、お金 ほしいし。', en: 'Right? But hey, I want the money.' }, effects: { trust: 1 } },
            { jp: 'えー、暇だね！', kana: 'えー、ひまだね！', en: 'Ugh, you’re so free!', correct: false, wordIds: ['hima'], reply: { jp: 'ひま？！ 毎日 はたらいてるのに？', en: 'Free?! I work every day!' }, note: '暇 means free, not busy. Working every day: 忙しい.' },
            { jp: 'へえ、店長が 来るの？', kana: 'へえ、てんちょうが くるの？', en: 'Oh, your manager is coming?', correct: false, reply: { jp: 'ちがう ちがう、おれが 行くの！', en: 'No, no, I’m the one going!' }, note: '来てって = “(he said) come”. The manager wants Haruto to come in.' },
          ],
        },
        why: {
          id: 'why',
          line: { jp: 'でも、なんで みんな しゃべらないんだろう。顔も ないし…', en: 'But how come nobody’s talking? And they’ve got no faces…' },
          kana: 'でも、なんで みんな しゃべらないんだろう。かおも ないし…',
          wordIds: ['nande', 'minna'],
          hint: 'なんで = why (casual). Explain with 〜んだ: のっぺらぼうの せいなんだ.',
          next: 'cheer',
          options: [
            { jp: 'のっぺらぼうの せいなんだ。', en: 'It’s because of Nopperabō.', correct: true, reply: { jp: 'のっぺらぼう？ あの、顔が ない おばけ？ マジか…', en: 'Nopperabō? That ghost with no face? Seriously…' }, effects: { trust: 1 } },
            { jp: 'のっぺらぼうは いつ？', en: 'When is Nopperabō?', correct: false, wordIds: ['itsu'], reply: { jp: 'いつ…？ なんの はなし？', en: 'When…? What are you on about?' }, note: 'He asked why (なんで). Give a reason with 〜んだ.' },
            { jp: 'なんでも ない。', en: 'It’s nothing.', correct: false, reply: { jp: 'なんでも なく ないでしょ！', en: 'It’s not “nothing”!' }, note: 'He really wants to know. Explain with 〜んだ: のっぺらぼうの せいなんだ.' },
          ],
        },
        cheer: {
          id: 'cheer',
          line: { jp: 'じゃあ、たおしてよ！ おれ、ここで 待ってるから。', en: 'Well then, go and beat it! I’ll be waiting here.' },
          kana: 'じゃあ、たおしてよ！ おれ、ここで まってるから。',
          wordIds: ['jaa'],
          hint: 'Promise you will: うん、頑張る！ (yeah, I’ll do my best).',
          next: 'bye',
          options: [
            { jp: 'うん、頑張る！', kana: 'うん、がんばる！', en: 'Yeah, I’ll do my best!', correct: true, wordIds: ['ganbaru'], reply: { jp: 'よし！ たのんだ！', en: 'Alright! Counting on you!' }, effects: { trust: 1 } },
            { jp: 'うん、頑張った！', kana: 'うん、がんばった！', en: 'Yeah, I did my best!', correct: false, wordIds: ['ganbaru'], reply: { jp: 'え、もう おわったの？', en: 'Huh, it’s over already?' }, note: '頑張った is past. It hasn’t happened yet: 頑張る.' },
            { jp: 'ううん、頑張る！', kana: 'ううん、がんばる！', en: 'Nope, I’ll do my best!', correct: false, wordIds: ['uun'], reply: { jp: 'ううん…なのに？', en: 'Nope… but you will?' }, note: 'ううん is a casual “no”. Start with うん to agree.' },
          ],
        },
        bye: {
          id: 'bye',
          line: { jp: 'あ、電車が 来たら、ぜったい 呼んでね！ じゃ、またね…って、友だちっぽく 言って みて！', en: 'Oh, when the train comes, be sure to call me! See ya… go on, say bye like a friend!' },
          kana: 'あ、でんしゃが きたら、ぜったい よんでね！ じゃ、またね…って、ともだちっぽく いって みて！',
          wordIds: ['yobu', 'iu'],
          hint: 'A casual goodbye between friends: じゃあね / またね.',
          next: 'end',
          input: {
            accepted: ['じゃあね', 'じゃあまたね', 'またね', 'じゃあまた', 'じゃね', 'じゃまたね', 'ばいばい', 'バイバイ', 'またあした', 'じゃあまたあした', 'またあとで'],
            model: 'じゃあね',
            modelKana: 'じゃあね',
            wrongReply: { jp: 'え〜、かたい かたい！ もっと 友だちっぽく！', en: 'Ugh, so stiff! More like a friend!' },
            wrongNote: 'Between friends: じゃあね or またね.',
            reply: { jp: 'うん、じゃあね！', en: 'Yeah, see ya!' },
          },
        },
        end: { id: 'end', line: { jp: '…あれ？ なんか、ひさしぶりに ちゃんと しゃべった 気が する！', en: '…Huh? I feel like I just had a proper chat for the first time in ages!' }, kana: '…あれ？ なんか、ひさしぶりに ちゃんと しゃべった きが する！', end: true },
      },
    },

    {
      id: 'ekimae-phone',
      npcId: 'eki-mari',
      region: 11,
      translations: 'hint',
      start: 'ring',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Rrring! The phone box by the station plaza is ringing. It’s Mari the grocer, calling from her shop.',
        'On the phone you can’t see a face, and the English is hidden. Listen closely.',
        'She talks fast: listen for what she wants, how many, and by when.',
      ],
      nodes: {
        ring: {
          id: 'ring',
          line: { jp: 'もしもし？ あ、つながった！ マリだけど、いま 大丈夫？', en: 'Hello? Oh, it connected! It’s Mari. Is now OK?' },
          kana: 'もしもし？ あ、つながった！ マリだけど、いま だいじょうぶ？',
          wordIds: ['daijoubu'],
          hint: '大丈夫？ = is it all right? Say yes casually: うん、大丈夫.',
          next: 'favour',
          options: [
            { jp: 'うん、大丈夫！', kana: 'うん、だいじょうぶ！', en: 'Yeah, it’s fine!', correct: true, wordIds: ['un'], reply: { jp: 'よかった〜！', en: 'Phew, great!' }, effects: { trust: 1 } },
            { jp: 'ごめんなさい、誰？', kana: 'ごめんなさい、だれ？', en: 'Sorry, who is this?', correct: false, wordIds: ['dare', 'gomennasai'], reply: { jp: 'マリだって！ やおやの！', en: 'It’s Mari, I said! From the grocer’s!' }, note: 'She said her name: マリだけど (it’s Mari…). Answer her question: 大丈夫?' },
            { jp: 'おかえり！', en: 'Welcome home!', correct: false, wordIds: ['okaeri'], reply: { jp: 'え？ わたし、家に いないよ？', en: 'Huh? I’m not home?' }, note: 'おかえり greets someone coming home. She asked if now is OK: うん、大丈夫.' },
          ],
        },
        favour: {
          id: 'favour',
          line: { jp: 'あのね、ちょっと たのみが あるんだけど…', en: 'Listen, there’s a little favour I want to ask, but…' },
          wordIds: ['chotto'],
          hint: 'けど… trails off: she is waiting for you to say “go on”: うん、何？',
          next: 'what',
          options: [
            { jp: 'うん、何？', kana: 'うん、なに？', en: 'Sure, what is it?', correct: true, wordIds: ['nani'], reply: { jp: 'あのね…', en: 'So…' }, effects: { trust: 1 } },
            { jp: 'じゃあね！', en: 'Bye!', correct: false, wordIds: ['jaa'], reply: { jp: 'ちょっと！ きらないで！', en: 'Hey! Don’t hang up!' }, note: 'じゃあね is goodbye! Her けど… means she wants to go on. Let her: うん、何？' },
            { jp: 'へえ、たのみが あるんだ。じゃあね。', en: 'Oh, you have a favour. Bye.', correct: false, wordIds: ['hee'], reply: { jp: 'まって まって！ まだ 何も 言って ない！', en: 'Wait, wait! I haven’t said anything yet!' }, note: 'A trailing けど… invites you to say “go ahead”: うん、何？' },
          ],
        },
        what: {
          id: 'what',
          line: { jp: 'コンビニで 卵と 牛乳、買って きて くれない？ 店のが なくなっちゃって。', en: 'Could you buy eggs and milk at the konbini for me? The shop’s run clean out.' },
          kana: 'コンビニで たまごと ぎゅうにゅう、かって きて くれない？ みせのが なくなっちゃって。',
          wordIds: ['konbini'],
          hint: 'Listen for the food: 卵 (たまご, eggs) and 牛乳 (ぎゅうにゅう, milk).',
          next: 'many',
          options: [
            { jp: 'うん、卵と 牛乳ね。', kana: 'うん、たまごと ぎゅうにゅうね。', en: 'Sure, eggs and milk.', correct: true, wordIds: ['tamago', 'gyuunyuu'], reply: { jp: 'そう そう！', en: 'That’s it!' }, effects: { trust: 1 } },
            { jp: 'うん、肉と 野菜ね。', kana: 'うん、にくと やさいね。', en: 'Sure, meat and vegetables.', correct: false, wordIds: ['niku', 'yasai'], reply: { jp: '野菜は うちに いっぱい あるって！', en: 'I’ve got heaps of vegetables, silly!' }, note: 'She said たまご (eggs) and ぎゅうにゅう (milk).' },
            { jp: 'うん、コーヒーと お弁当ね。', kana: 'うん、コーヒーと おべんとうね。', en: 'Sure, coffee and a boxed lunch.', correct: false, wordIds: ['koohii', 'obentou'], reply: { jp: 'それは テツさんの ほしい もの！', en: 'That’s what Tetsu would want!' }, note: 'Listen again: たまご and ぎゅうにゅう.' },
          ],
        },
        many: {
          id: 'many',
          line: { jp: '卵は ひとパック、牛乳は 二本ね。', en: 'One pack of eggs, two cartons of milk.' },
          kana: 'たまごは ひとパック、ぎゅうにゅうは にほんね。',
          wordIds: ['tamago', 'gyuunyuu'],
          hint: 'ひとパック = one pack; 二本 (にほん) = two (long things like cartons).',
          next: 'when',
          options: [
            { jp: '卵 ひとパックと、牛乳 二本だね。', kana: 'たまご ひとパックと、ぎゅうにゅう にほんだね。', en: 'One pack of eggs and two cartons of milk.', correct: true, reply: { jp: 'そう！ さすが！', en: 'Yes! You’re good!' }, effects: { trust: 1 } },
            { jp: '卵 ふたパックと、牛乳 一本だね。', kana: 'たまご ふたパックと、ぎゅうにゅう いっぽんだね。', en: 'Two packs of eggs and one carton of milk.', correct: false, reply: { jp: 'ぎゃく、ぎゃく！', en: 'Other way round!' }, note: 'ひとパック (one pack) of eggs, にほん (two) of milk.' },
            { jp: '卵 ひとパックと、牛乳 二パックだね。', kana: 'たまご ひとパックと、ぎゅうにゅう ふたパックだね。', en: 'One pack of eggs and two packs of milk.', correct: false, reply: { jp: '牛乳は 本だよ、本！', en: 'Milk is counted in 本!' }, note: 'She said 二本 (にほん): two cartons.' },
          ],
        },
        when: {
          id: 'when',
          line: { jp: 'お店、六時に 閉めるから、それまでに おねがい！', en: 'I close the shop at six, so before then, please!' },
          kana: 'おみせ、ろくじに しめるから、それまでに おねがい！',
          wordIds: ['shimeru'],
          hint: '閉める (しめる) = close. When? 六時 (ろくじ) = six o’clock.',
          next: 'tetsu',
          options: [
            { jp: 'わかった、六時までに 行くね。', kana: 'わかった、ろくじまでに いくね。', en: 'Got it, I’ll come by six.', correct: true, reply: { jp: 'たすかる〜！', en: 'You’re a lifesaver!' }, effects: { trust: 1 } },
            { jp: 'わかった、六時に 開けるね。', kana: 'わかった、ろくじに あけるね。', en: 'Got it, I’ll open at six.', correct: false, wordIds: ['akeru'], reply: { jp: 'あける の じゃなくて、しめるの！', en: 'Not open: close!' }, note: '開ける (あける) is open; she said 閉める (しめる), close.' },
            { jp: 'わかった、九時までに 行くね。', kana: 'わかった、くじまでに いくね。', en: 'Got it, I’ll come by nine.', correct: false, reply: { jp: 'くじ？ もう しまってるよ！', en: 'Nine? I’ll be closed by then!' }, note: 'She said ろくじ (six o’clock), not くじ (nine).' },
          ],
        },
        tetsu: {
          id: 'tetsu',
          line: { jp: 'あ、それから… テツさんが 呼んでたよ。駅に 来てって。', en: 'Oh, and also… Tetsu was asking for you. He says come to the station.' },
          kana: 'あ、それから… テツさんが よんでたよ。えきに きてって。',
          wordIds: ['yobu'],
          hint: '来てって = “(he said) come”. Tetsu wants YOU to go to the station.',
          next: 'bye',
          options: [
            { jp: 'え、テツさんが？ わかった、駅に 行くね。', kana: 'え、テツさんが？ わかった、えきに いくね。', en: 'Oh, Tetsu? OK, I’ll go to the station.', correct: true, reply: { jp: 'うん、よろしく！', en: 'Yep, thanks!' }, effects: { trust: 1 } },
            { jp: 'え、テツさんが 来るの？ 待ってるね。', kana: 'え、テツさんが くるの？ まってるね。', en: 'Oh, Tetsu is coming? I’ll wait.', correct: false, reply: { jp: 'ちがう ちがう、きみが 行くの！', en: 'No, no, YOU go to HIM!' }, note: '来てって quotes Tetsu’s message: “come (to the station)”. You go.' },
            { jp: 'え、マリさんが 駅に いるの？', kana: 'え、マリさんが えきに いるの？', en: 'Oh, you’re at the station?', correct: false, reply: { jp: 'わたしは お店だって！', en: 'I’m at the shop, I told you!' }, note: 'It’s Tetsu (テツさん) who called for you. 呼んでた = was calling for.' },
          ],
        },
        bye: {
          id: 'bye',
          line: { jp: 'じゃあ、おねがいね。ばいば〜い！', en: 'OK, I’m counting on you. Bye-bye!' },
          wordIds: ['jaa'],
          hint: 'Say bye back, casually.',
          next: 'end',
          options: [
            { jp: 'うん、じゃあね！', en: 'Yeah, bye!', correct: true, wordIds: ['jaa'], reply: { jp: 'じゃあね〜！', en: 'Bye~!' }, effects: { trust: 1 } },
            { jp: 'うん、おはよう！', en: 'Yeah, good morning!', correct: false, wordIds: ['ohayou'], reply: { jp: 'いま きる ところ なのに？', en: 'Just as I’m hanging up?' }, note: 'おはよう starts a day. To hang up: じゃあね.' },
            { jp: 'うん、いただきます！', en: 'Yeah, let’s eat!', correct: false, wordIds: ['itadakimasu'], reply: { jp: 'でんわで 何 食べるの？！', en: 'What are you eating on the phone?!' }, note: 'いただきます is before eating. To hang up: じゃあね.' },
          ],
        },
        end: { id: 'end', line: { jp: '（ツー、ツー…）', en: '(Beep… beep… the call has ended.)' }, end: true },
      },
    },
  ],
}
