import type { Locus } from '../types'

/**
 * Room 11: the Chattering Station Town. Start with Pon on the station
 * plaza, through the ticket gate to Tetsu and up onto the platform (the
 * door of car three), back down to the big clock and the bus stop, across
 * to the clinic steps, west to the konbini and the bank, down into the park
 * (Old Gen's bench, the lawn), along the shopping arcade, into Mari's
 * grocer and Café Komorebi, and finally up to the apartment rooftop.
 */
export const ROOM: Locus[] = [
  {
    id: 'p11-pon',
    room: 11,
    map: 'ekimae',
    anchor: 'e-pon',
    name: { jp: 'ポンの いばしょ', en: 'Pon’s Corner' },
    emoji: '🦝',
    memories: [
      { item: 'w:ohayou', story: 'Pon yawns on the plaza and yells “OHIO!” at the rising sun, waving a tiny flag of Ohio. Every commuter waves back: this is how mornings begin here.', image: 'a sleepy tanuki yells “OHIO!” at the rising sun, waving a tiny Ohio flag, and everyone waves back: good morning' },
      { item: 'w:konbanwa', story: 'As the lamps come on, a CONE-shaped busker plays a BANJO next to Pon: “CONE, BAN, WA!” He serenades everyone heading home for the evening.', image: 'as the lamps come on, a CONE-shaped busker strums a BANJO — “CONE, BAN, WA!” — for everyone heading home: good evening' },
      { item: 'w:sayounara', story: 'Pon lets out an enormous SIGH, “SIGH, YO, NARRATOR!”, as the narrator of his life packs a suitcase and walks off forever. A long, final goodbye.', image: 'someone heaves a huge SIGH — “SIGH, YO, NARRATOR!” — as the narrator of their life walks off with a suitcase: a long, final goodbye' },
      { item: 'w:oyasumi', story: 'Pon pulls a blanket over his head on the plaza bench: “OH, YA, SUE ME, I’m going to bed!” His snores start before he finishes. Good night.', image: 'a yawning tanuki pulls a blanket over his head mumbling “OH YA, SUE ME, I’m off to bed” and starts snoring at once: good night' },
      { item: 'w:hai', story: 'Pon asks the crowd a question and every hand shoots up so HIGH it scrapes the station roof: “HIGH!” Yes, yes, yes, all at once.', image: 'a whole crowd shoots their hands up so HIGH they scrape the ceiling, all shouting yes at once' },
      { item: 'w:iie', story: 'A pushy salesman offers Pon a fake train ticket. “EE-EH!” Pon shakes his head so hard his ears flap. No, no and no.', image: 'a tanuki shakes his head so hard his ears flap — “EE-EH!” — no, no and no, and a pushy salesman backs away' },
      { item: 'w:un', story: 'Pon’s mouth is stuffed with dumplings, so when you ask if they’re good he just grunts “OON” and nods. The lazy, friendly yes you give a friend.', image: 'someone with a mouth full of dumplings grunts “OON” and nods: the lazy, friendly yeah you give a friend' },
      { item: 'w:uun', story: '“OO-OON,” hums Pon, swinging his head slowly side to side like a pendulum, when you offer him a salad. The casual no: nope, not for me.', image: 'someone hums “OO-OON” and swings their head side to side like a slow pendulum: the easy, casual nope' },
    ],
  },
  {
    id: 'p11-gate',
    room: 11,
    map: 'ekimae',
    anchor: 'e-tetsu',
    name: { jp: 'かいさつ', en: 'Ticket Gate' },
    emoji: '🎫',
    memories: [
      { item: 'w:ee', story: 'Tetsu tips his cap to a grand old lady and murmurs a soft “EH.” Not a question at all: the gentle, polite yes of a man in a pressed uniform.', image: 'a gentleman in a pressed uniform tips his cap and murmurs a soft, polite “EH”: yes, certainly' },
      { item: 'w:daijoubu', story: 'A ghost called JOE leaps out of the ticket machine: “BOO!” Tetsu doesn’t even blink. “DIE, JOE, BOO… I’m all right. Everything’s fine.”', image: 'a ghost named JOE leaps out — “BOO!” — and the man just shrugs, “DIE, JOE, BOO… I’m all right, everything’s fine”' },
      { item: 'w:gomennasai', story: 'A commuter bumps into Tetsu and bows so low that a rocket full of NASA men blasts out of his eye: “GO, MEN, NASA, EYE!” So sorry, so very sorry.', image: 'someone bows deeply after a bump, and a rocket full of NASA men blasts out of their eye — “GO, MEN, NASA, EYE!” — so sorry' },
      { item: 'w:itadakimasu', story: 'Tetsu presses his palms together over his lunch, which is an entire wooden dock with keys hanging off it: “EAT A DOCK, KEY, MASS!” Let’s eat.', image: 'someone presses their palms together over a lunch that is a whole wooden dock with keys on it — “EAT A DOCK, KEY, MASS!” — let’s eat' },
      { item: 'w:gochisousama', story: 'Tetsu pats his full belly and a sumo wrestler made entirely of cheese bows back to him: “GO, CHEESE, OH, SUMO!” Thanks for the meal.', image: 'someone pats a full belly and a sumo wrestler made of cheese bows back — “GO, CHEESE, OH, SUMO!” — thanks for the meal' },
      { item: 'w:tadaima', story: 'The night-shift guard bursts back through the gate with jazz hands: “TA-DA! I’M A… home!” Everyone knows that line: I’m home.', image: 'a tired worker bursts through the door with jazz hands — “TA-DA! I’M A… home!” — I’m home' },
      { item: 'w:okaeri', story: 'Tetsu throws his arms round the returning guard and hands him an OKRA: “OKRA, EAR, EE!” Welcome home, here’s a vegetable.', image: 'someone comes home and is wrapped in a hug and handed an OKRA — “OKRA, EAR, EE!” — welcome home' },
      { item: 'g:casual-da', story: 'Tetsu tosses his stiff polite ending into the bin and points like a toddler instead: “Train, DA! Not bus, JA NAI!” Casual is; casual isn’t.', image: 'someone throws a stiff polite ending into a bin and points like a toddler — “train, DA! not bus, JA NAI!” — casual “is” and “isn’t”' },
    ],
  },
  {
    id: 'p11-car',
    room: 11,
    map: 'ekimae-platform',
    anchor: 'p-car',
    name: { jp: '三ごうしゃの ドア', en: 'Car Three' },
    emoji: '🚃',
    memories: [
      { item: 'w:densha', story: 'Out of the doors of car three rolls a family of bears, as if leaving their DEN, with a great “SHAH!” of steam behind them. A train.', image: 'a family of bears rolls out of their DEN on rails with a great “SHAH!” of steam: a train' },
      { item: 'w:owaru', story: 'On the platform a kangaroo finishes its show and bows as the curtain drops over the train door: “OH, WAH, ROO!” It’s over, the end.', image: 'a kangaroo bows as the curtain falls — “OH, WAH, ROO!” — it’s over, the end' },
      { item: 'w:hajimaru', story: 'A man called JIM waves a big round flag, a MARU, at the train door — “HA, JIM, MARU!” — and the race along the platform starts.', image: 'a man called JIM waves a big round flag — “HA, JIM, MARU!” — and the race starts' },
      { item: 'w:ganbaru', story: 'A kangaroo grips the grab-bar in car three and does pull-ups until its chin is GONE over the BAR: “GONE BAR, ROO!” Do your best!', image: 'a kangaroo grits its teeth doing pull-ups until its chin is GONE over the BAR — “GONE BAR, ROO!” — do your best' },
      { item: 'g:chau', story: 'A passenger in car three wolfs a whole bento in one gulp: “CHOW!” Gone, done, all of it. The spoken squeeze of “finish completely”.', image: 'someone gulps a whole lunch box in one bite — “CHOW!” — done completely, every last grain, in the squeezed spoken form' },
    ],
  },
  {
    id: 'p11-clock',
    room: 11,
    map: 'ekimae',
    anchor: 'e-clock',
    name: { jp: '大どけい', en: 'Big Station Clock' },
    emoji: '🕰️',
    memories: [
      { item: 'w:jikan', story: 'Somebody has strapped a JEEP CAN to the big clock — “JEE, KAHN!” — and it drips out minutes and hours like fuel. Time is running out.', image: 'a jeep can strapped to a clock drips out minutes and hours like fuel — “JEE, KAHN!” — time is running out' },
      { item: 'w:itsu', story: 'A hen perches on the minute hand, ticking her head round and clucking “IT’S… IT’S…?” She only ever wants to know when, when, when.', image: 'a hen ticks her head like a clock hand, clucking “IT’S… IT’S…?” — always wanting to know when' },
      { item: 'w:nani', story: 'A NANNY pushing a pram stops under the clock and stares blankly at it: “NANNY? What? What is it?” Her baby only ever says what.', image: 'a nanny pushing a pram stares blankly — “NANNY? what? what is it?” — and the baby only ever says what' },
      { item: 'w:dare', story: 'A masked stranger leans on the clock post and whispers, “I DARE you to guess.” And all you can ask is: who? Who are you?', image: 'a masked stranger leans in close — “I DARE you to guess” — and all you can ask is who, who are you' },
      { item: 'w:dou', story: 'The clock’s hands have turned into floppy bread DOUGH. Tetsu scratches his head: how on earth does it tell the time now? How?', image: 'clock hands made of floppy bread DOUGH droop while someone asks how on earth it works: how?' },
      { item: 'w:doushite', story: 'A lump of DOUGH drops off the clock onto a clean white SHEET. “DOUGH, SHE-TEH?!” wails the baker. Why? Why did it fall?', image: 'a lump of DOUGH flops onto a clean SHEET and a baker wails “DOUGH, SHE-TEH?!”: why, why did it happen?' },
      { item: 'w:nande', story: 'A NUN on a DAY trip stamps her foot under the clock: “NUN, DAY?! How come the train’s not here?!” The casual, slightly cross way to ask why.', image: 'a nun on a day trip stamps her foot — “NUN, DAY?! how come?!” — the casual, slightly cross way to ask why' },
      { item: 'g:casual-question', story: 'Pon swings on the clock hand and snips the end off his question with scissors, letting his voice curl UP like a hook: “Going?↗” or “…NO?↗” to fish for the story.', image: 'someone snips the end off a question with scissors and lets their voice curl UP like a hook — “going?↗”, “…NO?↗” — a casual question' },
    ],
  },
  {
    id: 'p11-bus',
    room: 11,
    map: 'ekimae',
    anchor: 'e-busstop',
    name: { jp: 'バスてい', en: 'Bus Stop' },
    emoji: '🚏',
    memories: [
      { item: 'w:basu', story: 'A giant BASS guitar has bought a ticket and sits in the queue. When it gets on, it thrums “BASS, BASS” at every single stop along the route.', image: 'a giant BASS guitar rides along on a long blue coach, thrumming “BASS, BASS” every time it pulls in' },
      { item: 'w:kuruma', story: 'A cooing kangaroo mama — COO, ROO, MA — pulls up beside the queue in a little red car, her joey waving from the passenger seat.', image: 'a cooing kangaroo mama — COO, ROO, MA — drives up in a little red car with her joey in the passenger seat' },
      { item: 'w:jitensha', story: '“GEE, TEN SHARKS!” shouts the queue, as ten sharks wobble past on one very long bicycle, ringing their little bells.', image: '“GEE, TEN SHARKS!” — ten sharks wobble past on one very long bicycle, ringing their little bells' },
      { item: 'w:donna', story: 'A donut seller called DONNA works the queue with her tray: every flavour, every shape. What kind would you like? What kind?', image: 'a donut seller called DONNA holds out a tray of every flavour: what kind would you like?' },
      { item: 'w:sou', story: 'A granny SEWING on the bench nods along to everything anyone says — “SO, SO” — stitch, stitch. Like that, yes, just so.', image: 'a granny SEWING nods along to everything — “SO, SO” — stitch by stitch: like that, just so' },
      { item: 'w:naruhodo', story: 'A NARWHAL in a HOODIE reads the timetable and taps its horn against its head: “NARU, HOO, DO!” The penny drops. I see!', image: 'a NARWHAL in a HOODIE taps its horn against its head — “NARU, HOO, DO!” — the penny drops: I see' },
      { item: 'g:aizuchi', story: 'One commuter tells a long story, and the whole queue keeps it going with tiny noises — mm, oh, really?, I see — chirping “EYE, ZOO, CHEE!” like birds on a wire.', image: 'a row of listeners chirp tiny noises — mm, oh, really?, I see — “EYE, ZOO, CHEE!” — keeping a story going like birds on a wire' },
    ],
  },
  {
    id: 'p11-clinic',
    room: 11,
    map: 'ekimae',
    anchor: 'e-nurse',
    name: { jp: 'びょういんの いりぐち', en: 'Clinic Steps' },
    emoji: '🏥',
    memories: [
      { item: 'w:byouin', story: 'A poorly bee groans “BYO, OH, IN!” and is wheeled up the clinic steps on a stretcher the size of a matchbox. Saki takes its tiny temperature.', image: 'a poorly bee groans “BYO, OH, IN!” and is wheeled in on a tiny stretcher to see the doctor' },
      { item: 'w:isogashii', story: 'Saki juggles three clipboards, a thermometer and two ringing phones. “EASY? GOSH, SHE’s busy!” gasp the patients.', image: 'a nurse juggles clipboards, a thermometer and two ringing phones — “EASY? GOSH, SHE’s busy!”' },
      { item: 'w:hima', story: 'On the steps a man lies counting the clouds. “HE, MA, is free all day!” says his mother. Nothing to do, all the time in the world.', image: 'a bored man lies counting clouds — “HE, MA, is free all day!” — nothing to do, all the time in the world' },
      { item: 'w:warui', story: 'A naughty kangaroo kicks over the medicine trolley: “WAH! ROO, EE!” Bad roo, very bad!', image: 'a naughty kangaroo kicks over a trolley — “WAH! ROO, EE!” — bad, very bad' },
      { item: 'w:ii', story: 'A little girl squeals “EEEE!” when Saki gives her a shiny gold star for being brave. Good, so good!', image: 'a child squeals “EEEE!” with delight at a shiny gold star sticker: good, very good' },
      { item: 'w:kare', story: 'A man pulls up at the steps in a CAR with a RAY of light behind him, and the nurses whisper: “CAR, RAY… that’s him.” He.', image: 'a man pulls up in a CAR with a RAY of light behind him and everyone whispers “CAR, RAY… that’s him”: he' },
      { item: 'w:kanojo', story: 'A woman snatches a fizzy can out of Joe’s hand on the steps: “CAN, NO, JOE! Not in a hospital!” She is in charge here. She.', image: 'a woman snatches a can out of Joe’s hand — “CAN, NO, JOE!” — she is the one in charge: she' },
      { item: 'g:yo-ne', story: 'Saki flicks a YO-YO of news at a patient — “you can go home, YO!” — then casts a little NET to catch a nod: “good news, NE?”', image: 'someone flicks a YO-YO of news at you, “you can go, YO!”, then casts a little NET to catch your nod, “good, NE?”' },
    ],
  },
  {
    id: 'p11-konbini',
    room: 11,
    map: 'ekimae',
    anchor: 'e-clerk',
    name: { jp: 'コンビニの いりぐち', en: 'Konbini Door' },
    emoji: '🏪',
    memories: [
      { item: 'w:konbini', story: 'Ken turns out to be a CON man in a BEANIE who never, ever shuts the shop: “CON, BEANIE, open all night!” A convenience store.', image: 'a con man in a BEANIE runs a little shop that never shuts — “CON, BEANIE, open all night!” — a convenience store' },
      { item: 'w:toire', story: 'A child points a TOY RAY-gun across the shop at the back room, zaps, and somewhere a toilet flushes with a happy gurgle.', image: 'a child zaps a TOY RAY-gun across the room and a toilet flushes with a happy gurgle' },
      { item: 'w:sumaho', story: 'A SUMO wrestler waits by the shop door and HOlds a tiny smartphone between two huge fingers, texting very, very slowly.', image: 'a SUMO wrestler HOlds a tiny smartphone between two huge fingers, texting very, very slowly' },
      { item: 'w:denwa', story: 'In a DEN behind the counter a bear picks up an old black telephone and growls, “WA? Who’s calling my den?”', image: 'a bear in its DEN picks up an old black telephone and growls “WA? who’s calling?”' },
      { item: 'w:eeto', story: 'Ken freezes with the price gun in his hand and starts counting on his toes: “EH… TOE… um…” Buying time while he thinks.', image: 'someone freezes mid-sentence and counts on their toes — “EH… TOE… um…” — buying time to think' },
      { item: 'w:anou', story: 'A shy schoolboy taps Ken on the shoulder and gets as far as “AH, NO…” before going pink. Um, excuse me…', image: 'a shy boy taps a stranger’s shoulder — “AH, NO…” — and goes pink: um, excuse me…' },
      { item: 'w:jaa', story: 'Ken opens a JAR of sweets, pops one in your hand and slams the lid: “JAAA, then! See you!” Well then, off you go.', image: 'someone opens a JAR, drops a sweet in your hand and slams the lid — “JAAA!” — well then, see you' },
      { item: 'g:particle-drop', story: 'Ken’s sentences have holes in them — “coffee… drink?” — because tiny ants carrying the little joining words have climbed out and are having a PARTY on the floor.', image: 'tiny ants carrying the little joining words climb out of a sentence and PARTY on the floor — “coffee… drink?” — dropped in casual talk' },
    ],
  },
  {
    id: 'p11-bank',
    room: 11,
    map: 'ekimae',
    anchor: 'e-bank',
    name: { jp: 'ぎんこうの まえ', en: 'Bank Front' },
    emoji: '🏦',
    memories: [
      { item: 'w:ginkou', story: 'A GIN-sipping KOala in a waistcoat guards the vault behind the sign, counting everyone’s coins: GIN, KO. The bank.', image: 'a GIN-sipping KOala in a waistcoat guards a vault full of everyone’s coins: GIN, KO' },
      { item: 'w:kaisha', story: 'Above the bank, a whole office building is flying on a string like a KITE — “KAI! SHA!” — with workers waving from its windows. A company.', image: 'a whole office building flies on a string like a KITE — “KAI! SHA!” — workers waving from every window: a company' },
      { item: 'w:shigoto', story: 'A clerk sits outside, buried in paperwork up to her nose. “SHE GOT, OH, so much!” Her job, never finished.', image: 'a clerk buried in paperwork up to her nose — “SHE GOT, OH, so much!” — her job, never finished' },
      { item: 'w:hataraku', story: 'At nine sharp a teller hangs her HAT on a RACK by the door and works, works, works until it falls off at night: “HAT, A, RACK!”', image: 'a worker hangs her HAT on a RACK at nine sharp and works, works, works until it falls off at night' },
      { item: 'w:chotto', story: 'The guard holds finger and thumb an inch apart: “CHOT, TOE.” Just a little. Just a moment, please.', image: 'someone holds finger and thumb an inch apart — “CHOT, TOE” — just a little, just a moment' },
      { item: 'w:yappari', story: 'The bank’s parrot yaps out exactly what everyone expected it to say: “YAP, PARROT!” Just as I thought, after all.', image: 'a parrot yaps out exactly what everyone expected — “YAP, PARROT!” — just as I thought, after all' },
      { item: 'w:hee', story: 'You tell the teller you came down from the clouds, and her eyebrows shoot up into her hair: “HEH-EH?!” Wow, really?', image: 'someone’s eyebrows shoot up into their hair — “HEH-EH?!” — wow, really?' },
      { item: 'g:n-desu', story: 'Every answer at the bank comes on a little NN-DESK whose drawer slides open to show the story behind it: “I’m late… the train stopped, NN-DESK.”', image: 'every answer arrives on a little NN-DESK whose drawer slides open to show the story behind it: explaining, or asking why' },
    ],
  },
  {
    id: 'p11-bench',
    room: 11,
    map: 'ekimae',
    anchor: 'e-oldman',
    name: { jp: 'ゲンさんの ベンチ', en: 'Old Gen’s Bench' },
    emoji: '🪑',
    memories: [
      { item: 'w:ongaku', story: 'Old Gen strikes a little gong on his lap — “ON! GA! KOO!” — and all the park pigeons coo in time. Music fills the air.', image: 'an old man strikes a little gong — “ON! GA! KOO!” — and all the pigeons coo in time: music' },
      { item: 'w:eiga', story: 'Gen has hung a sheet between two trees and a cowboy on it fires his pistol. “AY, GAH!” gasps the whole audience. A movie.', image: 'a cowboy on a huge screen fires his pistol and the whole audience gasps “AY, GAH!”: a movie' },
      { item: 'w:omoshiroi', story: 'Gen’s friend ROY tells jokes into a toy phone — “OH, MOSHI, ROY!” — and the bench shakes with laughter. Funny, interesting!', image: '“OH, MOSHI, ROY!” — a man called Roy tells jokes into a toy phone and everyone laughs: funny, interesting' },
      { item: 'w:tsumaranai', story: 'Gen reads aloud from a very long book about a man called SUE MARA… and nods off: “nai…” Boring, so boring.', image: 'someone nods off in the middle of a lecture about a man called SUE MARA — “nai…” — boring, so boring' },
      { item: 'w:minna', story: 'A whole school of MINNOWS swims up out of the pond, and every single one of them waves at Gen. Everyone!', image: 'a whole school of MINNOWS swims past and every single one of them waves: everyone' },
      { item: 'w:jibun', story: 'Gen points at his own nose with a bun on a stick, like a ship’s JIB: “JIB, BUN! Me, myself!”', image: 'someone points at their own nose with a bun on a stick — “JIB, BUN!” — me, myself, oneself' },
      { item: 'g:connectors', story: 'Gen lays his conversation out like a toy railway with switch points: a DEMOlition sign (but), a DUCK CAR (so), a SORE DEAD end (and then), a JAR (well then).', image: 'a man steers his sentences through railway switch points — a DEMO sign (but), a DUCK CAR (so), a JAR (well then) — joining each turn to the next' },
      { item: 'g:kana-wonder', story: 'Gen squints at the clouds with an old tin CAN balanced on his head: “Rain tomorrow, CAN-NA?” Wondering aloud to nobody in particular.', image: 'someone squints at the clouds with a CAN on their head, murmuring “rain tomorrow, CAN-NA?”: wondering aloud' },
    ],
  },
  {
    id: 'p11-lawn',
    room: 11,
    map: 'ekimae',
    anchor: 'e-kids',
    name: { jp: 'こうえんの しばふ', en: 'Park Lawn' },
    emoji: '🌳',
    memories: [
      { item: 'w:akarui', story: 'A kangaroo drives across the lawn with its headlights blazing — “AH, CAR, ROO, EE!” — and Mio shades her eyes. So bright, so cheerful!', image: 'a kangaroo drives up with its headlights blazing — “AH, CAR, ROO, EE!” — so bright and cheerful' },
      { item: 'w:kurai', story: 'Inside the tunnel slide, a pigeon coos “COO, RYE…” It is so dark in there it can’t see its own wings.', image: 'a pigeon coos “COO, RYE…” inside a tunnel so dark it cannot see its own wings: dark' },
      { item: 'w:atsui-weather', story: 'The children fan a girl called SUE who is melting on the swings in the summer sun: “AT, SUE, EE!” Hot, the weather is so hot!', image: 'children fan a girl called SUE melting in the summer sun — “AT, SUE, EE!” — the weather is so hot' },
      { item: 'w:samui', story: 'A boy called SAM came out in shorts on a snowy day and stands shivering on the lawn: “SAM, OOH, EE!” Cold, so cold!', image: 'a boy called SAM shivers in shorts in the snow — “SAM, OOH, EE!” — cold, so cold' },
      { item: 'w:ooi', story: 'So many children pile onto one slide that it groans under them: “OH, OY!” Many, a lot, far too many.', image: 'so many children pile onto one slide that it groans “OH, OY!”: many, a lot' },
      { item: 'w:sukunai', story: 'At nightfall only a few children are left on the lawn, SCOOTING home as NIGHT comes: “SCOOT, NIGH.” Few, not many.', image: 'only a few children are left, SCOOTING home as NIGHT falls — “SCOOT, NIGH” — few, not many' },
      { item: 'g:jan', story: 'Mio slaps a JAM jar down on the grass: “Look, it’s great, JAN!” — pushing you to agree. Isn’t it obvious? Come on!', image: 'a girl slaps a JAM jar down — “it’s great, JAN!” — pushing you to agree: isn’t it, come on!' },
    ],
  },
  {
    id: 'p11-arcade',
    room: 11,
    map: 'ekimae',
    anchor: 'e-reporter',
    name: { jp: 'しょうてんがい', en: 'Shopping Arcade' },
    emoji: '🏮',
    memories: [
      { item: 'w:chikai', story: 'Aya the reporter stands so near you that her CHEEK presses against your EYE: “CHEEK, EYE!” Near, very close.', image: 'someone stands so near that their CHEEK presses against your EYE — “CHEEK, EYE!” — near, very close' },
      { item: 'w:tooi', story: 'Aya’s cameraman stubs his TOE on a lantern — “TOE, EE!” — and it flies far, far away down the arcade and out of sight.', image: 'a cameraman stubs his TOE — “TOE, EE!” — and it flies far, far away until it is a speck' },
      { item: 'w:muzukashii', story: 'Outside the shops, a MOOSE tries to count CASH with its hooves for Aya’s camera: “MOOSE, CASH, EE!” Difficult, so difficult.', image: 'a MOOSE tries to count CASH with its hooves — “MOOSE, CASH, EE!” — difficult, so difficult' },
      { item: 'w:iu', story: 'Aya thrusts her microphone right under your nose: “EE, YOU!” Say it! Say something!', image: 'someone thrusts a microphone at you — “EE, YOU!” — say it, say something' },
      { item: 'w:yobu', story: 'Aya spots a friend at the far end of the arcade and yells over the crowd: “YO! BOO!” Calling her by name.', image: 'someone calls across a crowded street — “YO! BOO!” — calling a friend by name' },
      { item: 'g:tte-quote', story: 'A TATTLE-tale teddy bear sits on Aya’s shoulder, passing on every rumour: “The train’s late, TTE!” That’s what I heard.', image: 'a TATTLE-tale teddy whispers “the train’s late, TTE!”, passing on what someone else said' },
    ],
  },
  {
    id: 'p11-grocer',
    room: 11,
    map: 'ekimae-yaoya',
    anchor: 'y-mari',
    name: { jp: 'マリの カウンター', en: 'Mari’s Counter' },
    emoji: '🥬',
    memories: [
      { item: 'w:niku', story: 'A pigeon perches on Mari’s KNEE, cooing “COO” and guarding a huge steak on the counter: KNEE, COO. Meat!', image: 'a pigeon perches on someone’s KNEE cooing “COO” over a huge steak: KNEE, COO — meat' },
      { item: 'w:yasai', story: 'Sota sighs “YA, SIGH…” at the pile of broccoli, carrots and cabbage his mum has stacked on his plate. Vegetables.', image: 'a boy sighs “YA, SIGH…” at a plate piled high with broccoli, carrots and cabbage: vegetables' },
      { item: 'w:tamago', story: 'A cat called TAMA rolls an egg across the counter with one paw: “TAMA, GO!” and Mari catches it just in time. An egg.', image: 'a cat called TAMA rolls an egg across a table with one paw — “TAMA, GO!” — an egg' },
      { item: 'w:gyuunyuu', story: 'A cow pokes its head through the shop door and hands Mari a brand NEW bottle with a happy squeeze — “GYU, NEW!” Milk.', image: 'a cow hands over a brand NEW bottle with a happy squeeze — “GYU, NEW!” — fresh milk' },
      { item: 'w:asagohan', story: 'At sunrise a rooster hops onto the counter shouting “AH, SAH, GO!” and hands Mari a bowl of rice, an egg and miso soup. Breakfast.', image: 'at sunrise a rooster shouts “AH, SAH, GO!” and serves rice, an egg and miso soup: breakfast' },
      { item: 'w:hirugohan', story: 'At noon a superHERO swoops into the shop and wolfs down a rice bowl, sun straight overhead: “HERO, GO, HAN!” Lunch.', image: 'a superHERO wolfs down a rice bowl at noon, sun straight overhead — “HERO, GO, HAN!” — lunch' },
      { item: 'w:bangohan', story: 'In the evening Mari hits the dinner gong — BANG! — “BANG, GO, HAN!” and the whole family runs to the table. Dinner.', image: 'a gong goes BANG in the evening — “BANG, GO, HAN!” — and the whole family runs to the table: dinner' },
      { item: 'w:obentou', story: 'A boy called BEN opens the boxed lunch Mari packed him and finds a sausage shaped exactly like a toe: “OH, BEN, TOE!”', image: 'a boy called BEN opens a boxed lunch — “OH, BEN, TOE!” — and finds a sausage shaped like a toe' },
    ],
  },
  {
    id: 'p11-cafe',
    room: 11,
    map: 'ekimae-cafe',
    anchor: 'k-yui',
    name: { jp: 'カフェの カウンター', en: 'Café Counter' },
    emoji: '☕',
    memories: [
      { item: 'w:koohii', story: 'Yui pours a steaming cup that hisses its own name as it rises: “CO-HEE…” The smell of COFFEE fills the café.', image: 'a steaming cup hisses its own name as it rises — “CO-HEE…” — and the smell of COFFEE fills the air' },
      { item: 'w:terebi', story: 'On the little TELLY above the counter, a BEE in a tie reads the evening news: “TELLY, BEE!” The television.', image: 'a BEE in a tie reads the news on a little TELLY — “TELLY, BEE!” — the television' },
      { item: 'w:shashin', story: 'A customer snaps her latte art — “SHA!” — and the picture comes out SHINY on her screen: “SHA, SHIN!” A photo.', image: 'someone snaps a picture of a latte — “SHA, SHIN!” — and it comes out shiny on the screen: a photo' },
      { item: 'w:motsu', story: 'A girl called SUE carries a tray with a tiny castle and its MOAT across the café: “MOAT, SUE!” Hold it steady, carry it!', image: 'a girl called SUE carries a tray with a tiny castle and its MOAT — “MOAT, SUE!” — hold it steady' },
      { item: 'w:akeru', story: 'A kangaroo kicks the café door wide open: “AH, KAY, ROO!” Open, it’s open!', image: 'a kangaroo kicks a door wide open — “AH, KAY, ROO!” — open' },
      { item: 'w:shimeru', story: '“SHE MAY, ROO… but not today,” says Yui, and shuts the door on the kangaroo. Close it, shut!', image: 'a woman shuts the door on a kangaroo — “SHE MAY, ROO… not today” — close, shut' },
      { item: 'g:toku', story: 'Before the morning rush, Yui lines up little TOKENS along the counter, one for each cup: “ready, TOKU.” Doing it now, ready for later.', image: 'someone lines up little TOKENS along a counter before the rush — “ready, TOKU” — doing it in advance, for later' },
      { item: 'g:kedo-soft', story: '“I’d like the window seat, KEDO…” A customer’s request trails off as a KEG of doughnuts rolls slowly away across the café. Soft, polite, unfinished.', image: 'a KEG rolls slowly away as a voice trails off — “I’d like a seat, KEDO…” — soft, polite and unfinished' },
    ],
  },
  {
    id: 'p11-roof',
    room: 11,
    map: 'ekimae-rooftop',
    anchor: 'r-board',
    name: { jp: 'おくじょうの けいじばん', en: 'Rooftop Board' },
    emoji: '📌',
    memories: [
      { item: 'w:shuumatsu', story: 'A note on the board shows a girl called SUE lying on a doormat with her SHOES off: “SHOE, MAT, SUE.” A lazy Saturday: the weekend.', image: 'a girl called SUE lies on her doormat with her SHOES off — “SHOE, MAT, SUE” — a lazy Saturday: the weekend' },
      { item: 'w:tanjoubi', story: 'Pinned to the board: a photo of JOE with a fresh TAN, a paper crown and a cake full of candles. “TAN, JOE, BEE!” A birthday.', image: 'a man called JOE with a fresh TAN wears a paper crown over a cake full of candles — “TAN, JOE, BEE!” — a birthday' },
      { item: 'w:tsukue', story: 'Beside the board stands a crooked desk, so SKEWed that every pencil rolls off it: “SKEW, EH?” A desk.', image: 'a crooked desk leans so far that every pencil rolls off — “SKEW, EH?” — a desk' },
      { item: 'w:shukudai', story: 'A pigeon sits on a SHOE on top of the board, staring at a pile of worksheets: “SHOE, COO, DIE!” Homework.', image: 'a pigeon sits on a SHOE glaring at a pile of worksheets — “SHOE, COO, DIE!” — homework' },
      { item: 'w:sumu', story: 'A note on the board: “SUE, MOO! Flat 3B.” A girl called Sue lives up here with a cow. That’s where they reside.', image: 'a girl called SUE lives in a tiny flat with a cow — “SUE, MOO!” — that’s where they live' },
      { item: 'w:tetsudau', story: 'A boy called TET helps SUE knead an enormous ball of DOUGH on the rooftop table: “TET, SUE, DOUGH!” Helping out.', image: 'a boy called TET helps SUE knead an enormous ball of DOUGH — “TET, SUE, DOUGH!” — helping out' },
      { item: 'g:teru-contraction', story: 'Someone wrings a TERRY towel on the washing line until its middle drips away: “watching, TERU!” The “is doing” form, squeezed short in speech.', image: 'someone wrings a TERRY towel until its middle drips away — “watching, TERU!” — the “is doing” form squeezed short in speech' },
    ],
  },
]
