import type { RegionSprites } from '../types'

/**
 * Pixel art for the Chattering Station Town: Tetsu the stationmaster (a
 * peaked cap with a gold badge, a blue uniform with gold buttons, white
 * gloves), Mari the grocer (an orange headscarf knotted at the side, a
 * green apron), the yamabiko echo spirit (big ears, mouth wide open,
 * sound rings round it) and Nopperabō, whose face is perfectly blank.
 *
 * Slots follow the human convention: 1 cloth, 2 cloth shade, 3 trim, 4 cloth
 * light, 5 hair, 6 hair shade, 7 legs, 8 shoes.
 */
export const SPRITES: RegionSprites = {
  characters: {
    stationmaster: {
      slots: { 1: 'dusk', 2: 'navy', 3: 'gold', 4: 'mist', 5: 'night', 6: 'navy', 7: 'navy', 8: 'woodDark' },
      down: [
        '................',
        '.....111111.....',
        '....11133111....',
        '...NNNNNNNNNN...',
        '...5ffffffff5...',
        '...5fkffffkf5...',
        '...ffkffffkfF...',
        '....hffffffh....',
        '...1ww1111ww1...',
        '...w11y11y11w...',
        '...w11111111w...',
        '...wOOOyyOOOw...',
        '....12111121....',
        '.....77..77.....',
        '.....88.........',
        '................',
      ],
      up: [
        '................',
        '.....111111.....',
        '....11111111....',
        '...NNNNNNNNNN...',
        '...5555555555...',
        '...5555555555...',
        '...F55555555F...',
        '....FFFFFFFF....',
        '...1111111111...',
        '...w11111111w...',
        '...w11111111w...',
        '...wOOOOOOOOw...',
        '....12111121....',
        '.....77..77.....',
        '.....88.........',
        '................',
      ],
      side: [
        '................',
        '.....11111......',
        '....1111331.....',
        '....NNNNNNNNN...',
        '...5556fffff....',
        '...556Fffkff....',
        '...556Fffkff....',
        '....56ffhff.....',
        '.....1ww11......',
        '.....11y11......',
        '.....1w1y1......',
        '.....OOOyO......',
        '.....121121.....',
        '....77...77.....',
        '....88...88.....',
        '................',
      ],
    },
    grocer: {
      slots: { 1: 'leaf', 2: 'leafDark', 3: 'leafDark', 4: 'grassLight', 5: 'woodDark', 6: 'wood', 7: 'navy', 8: 'woodDark' },
      down: [
        '................',
        '.....eeeeee.....',
        '....eeyeeeeex...',
        '...5eeeeeeee5x..',
        '...5ffffffff5...',
        '...5fkffffkf5...',
        '...5fkffffkf6...',
        '...5hffffffh6...',
        '...ppwwffwwpp...',
        '...p11111111p...',
        '...f11111111f...',
        '....111yy111....',
        '....12222221....',
        '.....77..77.....',
        '.....88.........',
        '................',
      ],
      up: [
        '................',
        '.....eeeeee.....',
        '....eeeeeeee....',
        '...5eeeeexee5...',
        '...5555555555...',
        '...5555555555...',
        '...5555555556...',
        '....55555556....',
        '...pp3pppp3pp...',
        '...p3pppppp3p...',
        '...fpp3333ppf...',
        '....pp3333pp....',
        '....12222221....',
        '.....77..77.....',
        '.....88.........',
        '................',
      ],
      side: [
        '................',
        '.....eeeeee.....',
        '....eeeeeyee....',
        '...xeeeeeeee....',
        '...x556fffff....',
        '...556Fffkff....',
        '...556Fffkff....',
        '....56ffhff.....',
        '.....pp11p......',
        '.....p111f......',
        '.....p1111......',
        '.....11y11......',
        '.....122221.....',
        '....77...77.....',
        '....88...88.....',
        '................',
      ],
    },
  },
  enemies: {
    yamabiko: {
      sym: true,
      anim: 'bob',
      rows: [
        '................',
        '................',
        '................',
        '................',
        '..........OO....',
        '.........OLLO...',
        '.........OLhO...',
        '..U......OLhOOOO',
        '.U......OoooOooo',
        '.U..U...Oooooooo',
        'U..U...Ooooooooo',
        'U..U..Ooofffffff',
        'U..U..Oofffkkfff',
        'U..U..Oofffkwfff',
        '.U..U.Oofffkkfff',
        '.U....Ooofffffff',
        '..U....Oooffffff',
        '.......OoofVVVVV',
        '......OoooofVwVV',
        '.....OLoooooVVVV',
        '....OLLoooooofff',
        '...OLooooooooooo',
        '...OooOoooooLooo',
        '...Oo.OooooLLLoo',
        '....O.OoooooLLoo',
        '......Oooooooooo',
        '......OooooOoooo',
        '.....OooooO.Oooo',
        '.....OOOOO..OOOO',
        '................',
        '................',
        '................',
      ],
    },
    nopperabo: {
      sym: true,
      anim: 'bob',
      rows: [
        '................',
        '...............n',
        '..............nn',
        '............nnnn',
        '..........nnnnnn',
        '........nnnnnnnn',
        '.......nnnnnnnnn',
        '.......nnFFfffff',
        '......nnFfffffff',
        '......nnFffffffp',
        '......nFffffffff',
        '......nFffffffff',
        '......nFffffffff',
        '......nnFfffffff',
        '.......nFFffffff',
        '........FFffffff',
        '.........FFfffff',
        '.......uuuuwwfff',
        '.....uuuuuuuwwff',
        '....uuuuuuuuuwwf',
        '...uuuUuuuuuuuww',
        '..uuuUUuuuuuuuuw',
        '..uuUUuuuuuuuuuu',
        '.uuUUuuuuuuuuuuu',
        '.uUUuuuuuuuuuuuu',
        '.uuuuuuuyyyyyyyy',
        '..uuuuuuyyVyyyyy',
        '...uuuuuuuuuuuuu',
        '....muuuuuuuuuuu',
        '.....mmmuuuuuuuu',
        '.......mmmmuuuuu',
        '..........mmmmmm',
      ],
    },
  },
}
