/**
 * Region 6 maps: the harbour town (market street, piers, the lighthouse
 * headland, the Ebisu shrine on the hill), the fish-market hall, the
 * lighthouse, Captain Kai's ship at the pier, and the sea cove where the
 * Umibōzu rises.
 */
import type { MapSpec } from '../../world/types'

/** Tiles of the harbour: red roofs, noren, boats, nets and paper lanterns. */
const LEGEND: MapSpec['legend'] = {
  v: { g: 'grass', o: 'roof-red' },
  j: { g: 'grass', o: 'roof-red-edge' },
  E: { g: 'grass', o: 'noren' },
  z: { g: 'water', o: 'boat' },
  h: { g: 'sand', o: 'net' },
  m: { g: 'path', o: 'chochin' },
}

const room = { interior: true, particles: 'dust' as const, bg: '#0b0a14', tint: 'rgba(255, 170, 90, 0.10)' }

export const HARBOUR: MapSpec = {
  id: 'harbour',
  name: 'The Harbour of Numbers',
  jp: '数の港',
  region: 6,
  music: 'harbour',
  particles: 'none',
  tint: 'rgba(255, 196, 140, 0.08)',
  legend: { ...LEGEND, r: { g: 'stone-floor', o: 'rock' } },
  rows: [
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPP99PPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PPZZZZZZZZZZZZZZZZZPPPPPPPPPP==PPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'P.ZnnnnnnnnnnnnnnnZT.P..PP.."q=...T..PPP.."PT..........P....',
    '.PZnKnL.....LnnnKnZP....PP.PP==PP"PTT.".."..T.""PP..TP..P..P',
    '..Znnnnn/nnnnnnnnnZ..P.TPP.PP==PPTT..P.T".PP.P..PP"......P.T',
    '..ZnnnnnnnnnnnnnnnZP.P.P.....==TPP......P....P..P.....$.PPP.',
    'T.ZnnnnnnnnnnnnnnnZPP..TPP.T.==========================.T..T',
    'P.ZnnnnnnnnnnnnnnnZP...P..PPT==PP..."...P..."P.."T...PP."T..',
    'PPZnnnnnnnInnnnnnnZ.P.P"."...==.T....PP....PPPPT..P.P".PP.PT',
    'T.ZZZZZZZZ=ZZZZZZZZ...P...P..==!.....P."P..P.PP...T.PPP.....',
    'CCCCCCCCCC=CCCCCCCCCCCCCCCCC===CCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    '..........=====================...vvvvvvvvvvvvvvvv..........',
    '..vvvvvvv...vvvvvv...vvvvvv..==...vvvvvvvvvvvvvvvv..vvvvvv..',
    '..vvvvvvv...vvvvvv...vvvvvv..==...vvvvvvvvvvvvvvvv..vvvvvv..',
    '..jjjjjjj...jjjjjj...jjjjjj..==...jjjjjjjjjjjjjjjj..jjjjjj..',
    '..#H#D#H#...#HDH#H...#H#HDH..==...#H##HEE77EE##H##..#H#D#H..',
    '....m.....m.....m.....m.....m==...m.....mi....m.....m.......',
    '.==========================================================0',
    '.========================================================d=0',
    '........................[....==......=......................',
    '.^^^^^^^^^..........(........==.....%.%.......%.%...........',
    '.AAAAAAAAA...................==nnnnnn.......................',
    '.#########...................==nn]nnn.......................',
    '.xx.e.x..e...................==nnnnnn.......................',
    '...........+.................==nnnnnn.......................',
    '.............................==.............................',
    '::::::::::::ww::h:::::::h:ww::::2::h::::ww::::~~~~~~~~~~~~~~',
    '8l::::::::::wwh:::{:h:}:::ww:::::::h::::ww::nnnnnnnnnnnnnnrn',
    '8:::::4::::hww1::::h:::h::ww:::::::)::::ww::nnnnrnnrnnnnnrnr',
    ':::::::::h::ww::::::::h:::ww::::::::::::ww::::~~nnrnZZZZnnnn',
    '~~~~~~~~~~~~ww~~~~~~~~~~~~ww~~~~~~~~~~~~ww~~~~~~nnnnZZZZnnnn',
    '~~~~~~~~~~~~ww~~~~~~~~~~~~ww~~~~~~~~~~z~ww~~~~~~nnrnZZZZrnnn',
    '~~~~~~~~~~z~ww~~~~~~~~~~~~ww~~~~~~~~~~~~ww~~~~~~rnnnZ6ZZnnnn',
    '~~~~~~~~~~~~ww~~~~~~~~~~z~ww~~~~~~~~~~~~ww~z~~~~nnrnrynnnnnn',
    '~~~~~~~~~~~~ww~z~~~~~~~~~~ww~~~~~~~~~~~~ww~~~~~~nnnnrnnnnnnr',
    '~~~~~~~~~~~~ww~~~~~~~~~~~~ww~z~~~~~~~~~~ww~~~~~~rnnnnnnnnnnn',
    'WWWWWWWzWWWWwwWWWWWWWWWWWWwwWWWWWWWWWWwwwwwwWW~~nnnnnnnnnnnr',
    'WWWWWWWWWWWWw3WWWWWWWWWWWWwwWWWWWzWWWWWWWWWWWW~~rnnnnnnnnnrn',
    'WWWWWWWWWWwwwwwwWWWWzWWWWWwwWWWWWWWWWWWWWWWWWW~~nnnnnnrnnnnn',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWwwWWWWWWWWWWWWWWWWWW~~nrnnnnnnn?nn',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWUwWWWWWWWWWWWWWWWWWW~~nnrnnnnnrnnn',
    'WWWWWWWWWWWWWWWWWWWWWWWWwwwwwwWWWWWWWWWWWWWWWW~~~WWWWWWWWWW~',
    'WWWWWWWWWWWWWWWWWWWWWWWWww55wwWWWWWWWWWWWWWWWW~~~WWWWWWWWWW~',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW~~~WWWWWWWWWW~',
  ],
  spawn: 'west',
  inn: 'west',
  points: {
    q: { name: 'west', dir: 'down' },
    d: { name: 'east', dir: 'left' },
    l: { name: 'cove', dir: 'right' },
    i: { name: 'market', dir: 'down' },
    y: { name: 'lighthouse', dir: 'down' },
    U: { name: 'pier', dir: 'up' },
  },
  exits: [
    { at: '9', to: '@prev', point: 'east' },
    { at: '0', to: '@next', point: 'west' },
    { at: '8', to: 'harbour-cove', point: 'east' },
    { at: '7', to: 'harbour-market', point: 'door', tile: 'noren' },
    { at: '6', to: 'harbour-lighthouse', point: 'door', tile: 'door' },
    { at: '5', to: 'harbour-ship', point: 'gangplank' },
  ],
  entities: [
    { at: '1', id: 'ha-gen', kind: 'activity', sprite: 'sailor', dir: 'down', activities: ['r6-words-1'], name: { jp: 'げんじいさん', en: 'Old Gen' }, lines: [{ jp: 'いち、に、さん… あれ？ つぎは なんだっけ。かずが あたまから こぼれて いく…', en: 'One, two, three… huh? What comes next? The numbers keep spilling out of my head…' }] },
    { at: '/', id: 'ha-ebisu-stone', kind: 'activity', tile: 'tablet', activities: ['r6-trace'], name: { jp: 'えびすの いしぶみ', en: 'Ebisu Stone' }, lines: [{ jp: 'りょうの かみ、えびすさまの いしぶみ。かずの 字が きざまれている。', en: 'A tablet to Ebisu, god of fishermen. The number kanji are carved into it.' }] },
    { at: '2', id: 'ha-board', kind: 'activity', tile: 'sign', activities: ['r6-runes'], name: { jp: 'みなとの けいじばん', en: 'Harbour Notice Board' }, lines: [{ jp: 'はりがみが たくさん。ふねの じかん、さかなの ねだん…', en: 'Notices everywhere: ship times, fish prices…' }] },
    { at: '3', id: 'ha-gullkid', kind: 'activity', sprite: 'child', dir: 'down', activities: ['r6-defense'], name: { jp: 'かもめばん', en: 'Gull Watch' }, lines: [{ jp: 'かもめが さかなを ねらってる！ ことばで おいはらって！', en: 'The gulls are after the fish! Drive them off with words!' }] },
    { at: '4', id: 'ha-netmender', kind: 'activity', sprite: 'villager-b', dir: 'right', activities: ['r6-cross'], name: { jp: 'あみなおしの フク', en: 'Fuku the Net-Mender' }, lines: [{ jp: 'あみの めは ますめ みたいでしょう。ことばを あみこんでごらん。', en: 'The holes in a net are like a grid, aren’t they? Knot your words into it.' }] },
    { at: '!', id: 'ha-sign', kind: 'sign', tile: 'sign', name: { jp: 'かんばん', en: 'Sign' }, lines: [{ jp: 'みなみ：みなと。ひがしの みちは やまへ。うみぼうずに ちゅうい！', en: 'South: the harbour. The east road climbs into the hills. Beware the Umibōzu!' }] },
    { at: '(', id: 'ha-cat', kind: 'npc', sprite: 'cat', wander: 2, name: { jp: 'みなとねこ', en: 'Harbour Cat' }, lines: [{ jp: 'にゃあ。（さかなを いっぴき ねだっている。）', en: 'Meow. (It is begging for one fish.)' }] },
    { at: ')', id: 'ha-sailor', kind: 'npc', sprite: 'sailor', wander: 2, name: { jp: 'りょうし', en: 'Fisherman' }, lines: [{ jp: 'あさ ごじに ふねを だすんだ。…でも いまは なんじか わからない！', en: 'We put out at five in the morning. …But now nobody knows what time it is!' }, { jp: 'なみが たかい ひは、うみぼうずが でるって いうよ。', en: 'They say the Umibōzu comes out on days when the waves are high.' }] },
    { at: '+', id: 'ha-porter', kind: 'npc', sprite: 'villager-a', wander: 1, name: { jp: 'にもつはこびの タロ', en: 'Taro the Porter' }, lines: [{ jp: 'はこが いくつ あるか、かぞえられないんだ。こまったなあ。', en: 'I can’t count how many boxes there are. What a mess.' }] },
    { at: '[', id: 'ha-fishwife', kind: 'npc', sprite: 'fisher', wander: 2, name: { jp: 'さかなうり', en: 'Fishwife' }, lines: [{ jp: 'あじ いっぴき、ひゃくえん！ …あれ、ひゃくって いくつだっけ？', en: 'Mackerel, one hundred yen each! …Wait, how many is a hundred again?' }] },
    { at: '$', id: 'ha-chest-hill', kind: 'chest', tile: 'chest', chest: { item: 'herb', n: 2, shards: 20 } },
    { at: '?', id: 'ha-chest-rocks', kind: 'chest', tile: 'chest', chest: { item: 'charm', n: 1, shards: 40, lock: { answer: 'はちじゅうはち', jp: 'ふたに「八十八」。かずを となえよ。', en: 'The lid says 八十八. Chant the number.' } } },
    { at: ']', id: 'ha-anchor', kind: 'landmark', tile: 'statue', word: 'minato', name: { jp: 'いかりの ひ', en: 'Anchor Monument' }, lines: [{ jp: '「この 港を まもる」と ほってある。', en: '“Guardian of this harbour,” it says.' }] },
    { at: '{', id: 'ha-boat', kind: 'landmark', tile: 'boat', word: 'fune', name: { jp: 'すなはまの ふね', en: 'Beached Boat' }, lines: [{ jp: 'ちいさな 船。あしたの あさ、また うみへ でる。', en: 'A little boat. Tomorrow morning it puts out to sea again.' }] },
    { at: '}', id: 'ha-shells', kind: 'landmark', tile: 'pot', word: 'kai', name: { jp: 'かいの かご', en: 'Shell Basket' }, lines: [{ jp: 'かごいっぱいの 貝。しおの においが する。', en: 'A basket full of shellfish, smelling of the sea.' }] },
  ],
}

export const HARBOUR_MARKET: MapSpec = {
  ...room,
  id: 'harbour-market',
  name: 'Fish Market Hall',
  jp: 'うおいちば',
  region: 6,
  music: 'harbour',
  legend: { ...LEGEND, h: { g: 'wood-floor', o: 'net' }, x: { g: 'wood-floor', o: 'crate' }, e: { g: 'wood-floor', o: 'barrel' } },
  rows: [
    '##########################',
    '#kkkkkkkkkkkkkkkkkkkkkkkk#',
    '#www1wwwwwwwwwwwwwwwww6ww#',
    '#w%%%%%ww%%%%%ww%%%%%wwww#',
    '#wwwww[wwwwww2wwwwwwwwwww#',
    '#wwwwwwwwwwwwwwwwwwwwwwww#',
    '#wexwewxwwwxewxwwwexwewww#',
    '#wwwwwwwwwwwwwwwwwwwwwwww#',
    '#ww(wwwwwwwwwwwww3wwwwwww#',
    '#w%%%%wwwwwwwwww%%%%wwwww#',
    '#wwwwwwww4wwwwwwwwwwwwwww#',
    '#hwwwwwwwwwwwww)wwww5wwww#',
    '#wwwwwwwwwwwqwwwwwwwwwww$#',
    '############00############',
  ],
  spawn: 'door',
  points: { q: { name: 'door', dir: 'up' } },
  exits: [{ at: '0', to: 'harbour', point: 'market', tile: 'noren' }],
  entities: [
    { at: '1', id: 'hm-banto', kind: 'activity', sprite: 'merchant', dir: 'down', activities: ['r6-words-4'], name: { jp: 'ばんとうの ゼニ', en: 'Zeni the Head Clerk' }, lines: [{ jp: 'うる、かう、はらう… あきないの ことばは わたしに まかせなさい。', en: 'Sell, buy, pay… leave the words of trade to me.' }] },
    { at: '2', id: 'hm-auctioneer', kind: 'activity', sprite: 'sailor', dir: 'down', activities: ['r6-listen'], name: { jp: 'せりの おじさん', en: 'The Auctioneer' }, lines: [{ jp: 'さあ、せりの はじまりだ！ こえを よく きけよ！', en: 'The auction begins! Listen sharp!' }] },
    { at: '6', id: 'hm-ume', kind: 'activity', sprite: 'fisher', dir: 'down', activities: ['r6-shop'], name: { jp: 'さかなやの ウメ', en: 'Ume the Fishmonger' }, lines: [{ jp: 'いらっしゃい！ ちゃんと かぞえられる おきゃくさんにだけ うるよ！', en: 'Welcome! I only sell to customers who can count properly!' }] },
    { at: '3', id: 'hm-buyer', kind: 'npc', sprite: 'villager-a', wander: 1, name: { jp: 'すしやの おやかた', en: 'Sushi Master' }, lines: [{ jp: 'まぐろを いっぽん！ …いや、まぐろは「ぽん」じゃない。…なんだっけ？', en: 'One tuna! …No, tuna isn’t counted with ぽん. …Or is it?' }] },
    { at: '4', id: 'hm-grandma', kind: 'npc', sprite: 'villager-b', name: { jp: 'ウメの おばあちゃん', en: 'Ume’s Grandmother' }, lines: [{ jp: 'わたしの ほうちょうは もう ろくじゅうねん つかってるのよ。', en: 'I’ve used this knife for sixty years, you know.' }, { jp: 'かずは、くちに だすと おぼえるよ。いち、に、さん！', en: 'Numbers stick when you say them out loud. One, two, three!' }] },
    { at: '5', id: 'hm-tuna', kind: 'landmark', tile: 'barrel', word: 'takusan', name: { jp: 'こおりの たる', en: 'Barrel of Ice' }, lines: [{ jp: 'さかなが たくさん、こおりに うまっている。', en: 'Lots of fish, packed in ice.' }] },
    { at: '(', id: 'hm-cat', kind: 'npc', sprite: 'cat', wander: 1, name: { jp: 'いちばねこ', en: 'Market Cat' }, lines: [{ jp: 'にゃ。（さかなの あたまを みつめている。）', en: 'Nya. (It is staring at a fish head.)' }] },
    { at: ')', id: 'hm-sailor', kind: 'npc', sprite: 'sailor', wander: 1, name: { jp: 'ふなのり', en: 'Sailor' }, lines: [{ jp: 'しちじに しゅっこう… の はずだった。とけいが とまってるんだ。', en: 'We were supposed to sail at seven. The clocks have all stopped.' }] },
    { at: '[', id: 'hm-customer', kind: 'npc', sprite: 'fisher', wander: 1, name: { jp: 'おきゃくさん', en: 'Customer' }, lines: [{ jp: 'これ、いくら？ …え、「ふにゃふにゃえん」？ ねだんが へんだよ！', en: 'How much is this? …“Squiggle yen”? The prices have gone strange!' }] },
    { at: '$', id: 'hm-chest', kind: 'chest', tile: 'chest', chest: { item: 'ether', n: 1, shards: 15 } },
  ],
}

export const HARBOUR_LIGHTHOUSE: MapSpec = {
  ...room,
  id: 'harbour-lighthouse',
  name: 'The Lighthouse',
  jp: 'とうだい',
  region: 6,
  music: 'harbour',
  bg: '#0a1020',
  tint: 'rgba(255, 220, 140, 0.12)',
  rows: [
    'XXXXXXXXXXXXXXX',
    'XXXXXnnnnnXXXXX',
    'XXXnnnnnnnnnXXX',
    'XXnnnkkknkkknnX',
    'XnnnnnnnnnnnnnX',
    'Xnnnnnn2nnnnnnX',
    'XnnnnnnnnnnnnnX',
    'Xnnn1nnnnn3nnnX',
    'XnnnnnnnnnnnnnX',
    'XnnnnnnnnnnnnnX',
    'Xnn(nnnnnnnnnnX',
    'XXnnnnnnnnn$nnX',
    'XXXnnnnnnnnnXXX',
    'XXXXXnnqnnXXXXX',
    'XXXXXXX0XXXXXXX',
  ],
  spawn: 'door',
  points: { q: { name: 'door', dir: 'up' } },
  exits: [{ at: '0', to: 'harbour', point: 'lighthouse', tile: 'door' }],
  entities: [
    { at: '1', id: 'hl-keeper', kind: 'activity', sprite: 'elder', dir: 'right', activities: ['r6-words-3'], name: { jp: 'とうだいもりの トキ', en: 'Toki the Keeper' }, lines: [{ jp: 'あさ、ひる、よる… ときを かぞえるのが わしの しごとじゃ。', en: 'Morning, noon, night… counting the hours is my job.' }] },
    { at: '2', id: 'hl-lamp', kind: 'landmark', tile: 'altar', word: 'toudai', name: { jp: 'おおきな ランプ', en: 'The Great Lamp' }, lines: [{ jp: 'とうだいの ひ。ふねを ぶじに みなとへ みちびく。', en: 'The lighthouse flame. It guides ships safely home.' }] },
    { at: '3', id: 'hl-clock', kind: 'landmark', tile: 'tablet', word: 'ji', name: { jp: 'しおの とけい', en: 'Tide Clock' }, lines: [{ jp: 'はりが とまっている。くじはんの まま…', en: 'The hands have stopped, stuck at half past nine…' }] },
    { at: '(', id: 'hl-cat', kind: 'npc', sprite: 'cat', name: { jp: 'とうだいねこ', en: 'Lighthouse Cat' }, lines: [{ jp: 'にゃー。（まどの そとの なみを かぞえている みたい。）', en: 'Nyaa. (It seems to be counting the waves outside.)' }] },
    { at: '$', id: 'hl-chest', kind: 'chest', tile: 'chest', chest: { item: 'smoke', n: 2, shards: 15 } },
  ],
}

export const HARBOUR_SHIP: MapSpec = {
  id: 'harbour-ship',
  name: 'The Tide-Runner',
  jp: 'しおかぜまる',
  region: 6,
  music: 'harbour',
  particles: 'none',
  bg: '#1d4e7a',
  tint: 'rgba(255, 210, 150, 0.06)',
  legend: { ...LEGEND, f: { g: 'wood-floor', o: 'fence' }, x: { g: 'wood-floor', o: 'crate' }, e: { g: 'wood-floor', o: 'barrel' }, h: { g: 'wood-floor', o: 'net' }, m: { g: 'wood-floor', o: 'chochin' } },
  rows: [
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWffffffffffffffffffffffffffWWWWW',
    'WWWfvvvvvvwwwwwwwwwwwwwwwwwwfWWWWW',
    'WWWfvvvvvvwwxxwewwwwwweewwwwfWWWWW',
    'WWWfjjjjjjwwxwwwwwwwwwwwwwwwffWWWW',
    'WWWf#H#H#Hwwwwwwwwwww)wwwwwwfwfWWW',
    'WWWfwwwwwwwwwwwwwwwwwwwww1wwfwwfWW',
    'WWWfwwww[wwwmwwwwwwmwwwwwwmw3wwwfW',
    'WWWfwwwwwwwwwwwwwwwwwwwwwwwwfwwwfW',
    'WWWfwwwwwwwwwwwww2wwwwwwwwwwfwwfWW',
    'WWWfwwwwww(wwwwwwwwwhhwwwwwwfwfWWW',
    'WWWfwwwwwwwwwwwwwwwwwwwwwwwwffWWWW',
    'WWWfw$wwwwwwwwwwwwwwwwwwwwwwfWWWWW',
    'WWWfwwwwwwwwwwqwwwwwwwwwwwwwfWWWWW',
    'WWWfffffffffff55fffffffffffffWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
  spawn: 'gangplank',
  points: { q: { name: 'gangplank', dir: 'up' } },
  exits: [{ at: '5', to: 'harbour', point: 'pier' }],
  entities: [
    { at: '1', id: 'hs-kai', kind: 'activity', sprite: 'sailor', dir: 'left', activities: ['r6-forge'], name: { jp: 'せんちょうの カイ', en: 'Captain Kai' }, lines: [{ jp: 'ことばは つなと おなじだ。ただしい じゅんばんで むすべば、あらしにも まけない！', en: 'Words are like ropes: tie them in the right order and no storm can break them!' }] },
    { at: '2', id: 'hs-mate', kind: 'activity', sprite: 'child', dir: 'down', wander: 1, activities: ['r6-words-2'], name: { jp: 'みならいの タク', en: 'Taku the Cabin Boy' }, lines: [{ jp: 'ふね、なみ、しま… うみの ことば、おしえてあげる！', en: 'Ship, wave, island… I’ll teach you the words of the sea!' }] },
    { at: '3', id: 'hs-figurehead', kind: 'landmark', tile: 'statue', word: 'nami', name: { jp: 'へさきの かざり', en: 'Figurehead' }, lines: [{ jp: '波を わける へさきの かみさま。', en: 'The spirit at the bow who parts the waves.' }] },
    { at: '[', id: 'hs-bell', kind: 'landmark', tile: 'shrine-bell', word: 'asa', name: { jp: 'ふねの かね', en: 'Ship’s Bell' }, lines: [{ jp: 'あさ いちばんに ならす かね。', en: 'The bell rung first thing in the morning.' }] },
    { at: '(', id: 'hs-cat', kind: 'npc', sprite: 'cat', wander: 1, name: { jp: 'ふなねこ', en: 'Ship’s Cat' }, lines: [{ jp: 'にゃっ。（ねずみを さんびき つかまえた かおを している。）', en: 'Nyat. (It looks like it caught three mice.)' }] },
    { at: ')', id: 'hs-sailor', kind: 'npc', sprite: 'sailor', wander: 2, name: { jp: 'すいふ', en: 'Deckhand' }, lines: [{ jp: 'げつようびに しゅっぱつ だ！ …きょうは なんようび？', en: 'We sail on Monday! …What day is it today?' }] },
    { at: '$', id: 'hs-chest', kind: 'chest', tile: 'chest', chest: { item: 'herb', n: 3, shards: 15 } },
  ],
}

export const HARBOUR_COVE: MapSpec = {
  id: 'harbour-cove',
  name: 'Umibōzu Cove',
  jp: 'うみぼうずの いりえ',
  region: 6,
  music: 'harbour',
  particles: 'sparkles',
  tint: 'rgba(40, 70, 140, 0.16)',
  legend: { ...LEGEND, r: { g: 'sand', o: 'rock' }, p: { g: 'stone-floor', o: 'pot' } },
  rows: [
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    'CCCCCCCCCCCCCCVCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCVCCCCCCCCCCCCCCC',
    'cccccccccccccccccccccccccccccccccccccccccccccc',
    '::::::::::r::r:::r::::r::::::::::::::r::::::::',
    '::$:::::::::::rr:::::::::::::::::rr:::::::::::',
    '::::::r::::r::::r:::::::::r:::::::2::::r::r:::',
    '::::::rrr::::::::::::::r::::r:r::::::r:::::::r',
    '::::::::::::::::~~~~::::::::::::::::::::::::::',
    '::::::::~~~:::::~~~~::::::::::::::::::::::::::',
    '::::::::~~~:::::~~~~::::::::::::::::::::===q=0',
    '::::::::::::::::::::::::::::::::::::::::=====0',
    '~~~~::::::::::::::::::::::::~~~:::::::::::::::',
    '~~~~::::::::::::::::::::::::~~~:::::::::::::::',
    '~~~~::::::::::::::::::::::::::::::::::::::::::',
    '~~~~::::::::::::::::::zz::::::::::::::::::::::',
    '~~~~::::::::::::::::::::::::::::::::::::::::::',
    '~~~~:::::::1::::::::::::::::::::::::::::::::::',
    'WWWWWWWWWW::::::::::::::::::::::::::::::::::::',
    'WWWWWWWWWW~~~~~~~~~~~~~~~~~~~~~~~~~~~~s~~~~~~~',
    'WWWWWWWWWW~~~~~~~~~~~~~~~~~~~~~~~~~~~~s~~~~~~~',
    'WWWWWWWWWW~~~~~~~~~~~~~~~~~~~~~~~~~~~~s~~~~~~~',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWsWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWnnnnpWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWnnnnnWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn?nnnWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
  spawn: 'east',
  points: { q: { name: 'east', dir: 'left' } },
  exits: [{ at: '0', to: 'harbour', point: 'cove' }],
  entities: [
    { at: '1', id: 'hc-umibozu', kind: 'boss', sprite: 'umibozu', activities: ['r6-boss'], name: { jp: 'うみぼうず', en: 'The Umibōzu' }, lines: [{ jp: 'ひとつ… ふたつ… かずは ぜんぶ わしの ものだ…', en: 'One… two… every number belongs to me…' }] },
    { at: '2', id: 'hc-tidestone', kind: 'activity', tile: 'statue', activities: ['r6-mastery'], name: { jp: 'しおの いし', en: 'Tide Stone' }, lines: [{ jp: 'みちしおと ひきしお。しおの とけいは まってくれない。', en: 'High tide, low tide. The tide clock waits for no one.' }] },
    { at: '$', id: 'hc-chest', kind: 'chest', tile: 'chest', chest: { item: 'ether', n: 2, shards: 25 } },
    { at: '?', id: 'hc-chest-islet', kind: 'chest', tile: 'chest', chest: { item: 'charm', n: 1, shards: 50, lock: { answer: 'さんびゃく', jp: 'ふたに「三百」。かずを となえよ。', en: 'The lid says 三百. Chant the number.' } } },
  ],
}

export const MAPS: MapSpec[] = [HARBOUR, HARBOUR_MARKET, HARBOUR_LIGHTHOUSE, HARBOUR_SHIP, HARBOUR_COVE]
