import type { Locus } from '../types'

/**
 * Room 6: the Harbour of Numbers. Down the hill road past the sign, west
 * to the Ebisu stone, along the market street to the fishwife, into the
 * fish-market hall (Ume's counter, the auction block, the head clerk, the
 * ice barrel), out to the anchor square and Taro's warehouse, along the
 * beach (nets, the beached boat, the shell basket) to the notice board,
 * onto Captain Kai's ship (the wheel, the bell) and finally up into the
 * lighthouse (the keeper's chair, the tide clock, the great lamp).
 */
export const ROOM: Locus[] = [
  {
    id: 'p6-sign',
    room: 6,
    map: 'harbour',
    anchor: 'ha-sign',
    name: { jp: 'さかの かんばん', en: 'Hill Road Sign' },
    emoji: '🪧',
    memories: [
      { item: 'w:hyaku', story: 'The hill sign is studded with exactly a hundred nails, and a woodpecker hammers every one of them, shrieking “HYAH! COO!” a hundred times before breakfast.', image: 'a woodpecker hammers a hundred nails in a row, shrieking “HYAH! COO!” a hundred times before breakfast' },
      { item: 'w:sen-1000', story: 'A thousand paper lanterns hang off the signpost, and each one whispers “SEN… SEN…” like a SENtry counting the whole way to a thousand.', image: 'a thousand paper lanterns sway in a row, each whispering “SEN… SEN…” like a SENtry counting all the way to a thousand' },
      { item: 'w:man', story: 'A MAN in a straw coat leans on the sign holding up ten fingers, bellowing “ten THOUSAND!” as ten thousand ants march over his sandals.', image: 'a MAN in a straw coat holds up ten fingers and bellows “ten THOUSAND!” while ten thousand ants march over his sandals' },
      { item: 'w:zero', story: 'Someone has painted a huge ZERO on the sign: an empty ring you can poke your head through. Nothing inside it. Nothing at all.', image: 'a huge painted ring, a ZERO big enough to poke your head through, with nothing inside it at all' },
      { item: 'g:big-numbers', story: 'Porters stagger down past the sign with sacks: three hundred go SAN-BYAH-ku with a B, six hundred ROP-PYAH-ku with a pop, eight hundred HAP-PYAH-ku with a hiccup, three thousand SAN-ZEN with a buzz.', image: 'sacks thump down in piles: three hundred go SAN-BYAH-ku with a B, six hundred ROP-PYAH-ku with a pop, eight hundred HAP-PYAH-ku with a hiccup' },
    ],
  },
  {
    id: 'p6-ebisu',
    room: 6,
    map: 'harbour',
    anchor: 'ha-ebisu-stone',
    name: { jp: 'えびすの いしぶみ', en: 'Ebisu Stone' },
    emoji: '🎣',
    memories: [
      { item: 'w:yon', story: 'The Ebisu stone sprouts four stony arms and does an enormous four-armed YAWN, “YO-N!”, stretching until all four fists pop.', image: 'a stone god grows four arms and lets out a huge four-armed YAWN, “YO-N!”, stretching until all four fists pop' },
      { item: 'w:go', story: 'Five fishermen crouch at the foot of the stone, and at the shout “GO!” all five throw up five fingers like starting flags.', image: 'five racers crouch at a line and at the shout “GO!” each throws up five fingers like a starting flag' },
      { item: 'w:roku', story: 'Six ROCKs roll down the shrine steps, ROCK-oo, ROCK-oo, and settle in a neat row of six in front of the stone.', image: 'six ROCKs tumble down a staircase, ROCK-oo, ROCK-oo, and settle into a neat row of six' },
      { item: 'w:nana', story: 'Seven grannies, seven NANAs, sit in a row on the stone’s plinth, each knitting a big red number seven out of wool.', image: 'seven grannies, seven NANAs in a row, each knitting a big red number seven out of wool' },
      { item: 'w:hachi', story: 'An octopus clings to the stone and sneezes “HATCHI!” eight times; the splatter loops round the god into a figure eight.', image: 'an eight-legged octopus sneezes “HATCHI!” eight times, and the splatter loops into a figure eight' },
      { item: 'w:kyuu', story: 'Nine pilgrims stand in a QUEUE for Ebisu’s blessing, a neat line of exactly nine, tapping their feet on the stone path.', image: 'nine people wait in a QUEUE, a neat line of exactly nine, tapping their feet impatiently' },
      { item: 'w:juu', story: 'A pilgrim squeezes an orange over the stone and ten drops of JUICE fall, JOO, JOO, ten bright orange dots on the carving.', image: 'an orange gets squeezed and ten drops of JUICE fall, JOO, JOO, making ten bright orange dots' },
    ],
  },
  {
    id: 'p6-fishwife',
    room: 6,
    map: 'harbour',
    anchor: 'ha-fishwife',
    name: { jp: 'さかなうりの みせさき', en: 'Fishwife’s Stall' },
    emoji: '🐟',
    memories: [
      { item: 'w:en', story: 'The fishwife spins every coin on her board and shouts “EN-ough!” at each one: round coins, round as a ring, the harbour’s money.', image: 'round coins spin on a counter while a seller shouts “EN-ough!” at each one, every coin a perfect ring' },
      { item: 'w:okane', story: 'She leans on a walking CANE made entirely of stacked coins. “OH, a CANE of money!” you gasp, and it jingles with every step she takes.', image: 'a walking CANE made entirely of stacked coins jingles with every step — “OH, a CANE of money!”' },
      { item: 'w:yasui', story: 'She slaps a tiny price tag on a mackerel and sings “YA, SWEET deal!” because it costs almost nothing.', image: 'a seller slaps a tiny price tag on a fish and sings “YA, SWEET deal!” because it costs almost nothing' },
      { item: 'w:harau', story: 'A customer pays by plucking a HARP at her stall, HAH-ROW, and coins drop out of its strings onto the fish one by one.', image: 'a customer pays by plucking a HARP, HAH-ROW, and coins drop out of its strings one by one' },
      { item: 'w:otsuri', story: 'Your change comes back from the fishwife as a handful of OATS, and a gull swoops down crying “REE!” to steal it.', image: 'your change comes back as a handful of OATS and a bird swoops down crying “REE!” to steal it' },
      { item: 'w:ikura', story: 'A shopper points at her bowl of glistening orange salmon eggs and gasps “ICK, COO-RAH!” at the price: how much?!', image: 'a shopper points at glistening orange salmon eggs and gasps “ICK, COO-RAH!” at the price tag: how much?!' },
      { item: 'g:ikura-desu-ka', story: 'A crow perches on the fishwife’s scales and caws “IKURA DESS KAH?” at every single fish, asking the price of everything.', image: 'a crow perches on a scale and caws “IKURA DESS KAH?” at every fish, asking the price of everything' },
    ],
  },
  {
    id: 'p6-ume',
    room: 6,
    map: 'harbour-market',
    anchor: 'hm-ume',
    name: { jp: 'ウメの みせ', en: 'Ume’s Fish Counter' },
    emoji: '🔪',
    memories: [
      { item: 'g:counter-hiki', story: 'Ume counts the fish on her counter with a HICCUP on each one: ip-PIKI, ni-HIKI, san-BIKI. The hiccup changes shape every time she’s surprised.', image: 'a fishmonger counts fish with a HICCUP on each one, ip-PIKI, ni-HIKI, san-BIKI, the hiccup changing every time' },
      { item: 'g:count-order', story: 'Ume taps her grandmother’s knife four times: THING, O, NUMBER, PLEASE. Order in the wrong order and she won’t serve you.', image: 'a cook taps a knife four times — THING, O, NUMBER, PLEASE — and refuses anyone who orders in the wrong order' },
      { item: 'w:kani', story: 'A CANNY crab in a tiny hat snips Ume’s apron string and scuttles sideways along the counter, far too clever to catch.', image: 'a CANNY crab in a tiny hat snips an apron string and scuttles sideways, too clever to catch' },
      { item: 'w:tako', story: 'An octopus on Ume’s counter hugs a giant TACO with all eight arms, lettuce sticking out everywhere, and refuses to be sold.', image: 'an octopus hugs a giant TACO with all eight arms, lettuce sticking out everywhere, and refuses to let go' },
      { item: 'w:ika', story: 'A squid on the ice squirts black ink and shrieks “EEK, AH!” every time Ume reaches for it.', image: 'a squid squirts black ink and shrieks “EEK, AH!” every time a hand reaches toward it' },
      { item: 'w:ichiba', story: 'Ume’s neighbour scratches an ITCH with a fresh fish, “ITCHY, BAH!”, and the whole market hall roars with laughter.', image: 'in a crowded market a man scratches an ITCH with a fresh fish, “ITCHY, BAH!”, and every stallholder roars' },
    ],
  },
  {
    id: 'p6-auction',
    room: 6,
    map: 'harbour-market',
    anchor: 'hm-auctioneer',
    name: { jp: 'せりの だい', en: 'Auction Block' },
    emoji: '📣',
    memories: [
      { item: 'w:ikutsu', story: 'The auctioneer jabs at a pile of eels and bellows “EE, COOT, SOO? how many?!”, and a coot bird pops out of the pile to count them.', image: 'a coot bird pops out of a pile of eels as someone bellows “EE, COOT, SOO? how many?!”' },
      { item: 'g:counter-tsu', story: 'The auctioneer sneezes a tiny “TSU!” on every box he counts: hito-TSU, futa-TSU, mit-TSU, one sneeze per box.', image: 'someone sneezes a tiny “TSU!” on every box he counts, one sneeze per box, hito-TSU, futa-TSU, mit-TSU' },
      { item: 'w:hitotsu', story: 'He holds up a single onion and TOOTS a little horn, “HE TOOTS, one!”, before tossing it to the crowd.', image: 'a man holds up a single onion and TOOTS a little horn — “HE TOOTS, one!” — before tossing it to the crowd' },
      { item: 'w:futatsu', story: 'Two toddlers, two FOOT-TOTS, wobble up onto the block, each holding one shoe, and together they make a pair.', image: 'two toddlers, two FOOT-TOTS, wobble up a step, each holding one shoe, making a pair' },
      { item: 'w:mittsu', story: 'Three woolly MITTS flop onto the auction block and wave in the air, as if bidding on the tuna.', image: 'three woolly MITTS flop onto a table and wave in the air, as if bidding on something' },
      { item: 'w:kazoeru', story: 'A KAZOO ERUPTS from the auctioneer’s mouth on every number he counts: one, buzz, two, buzz, three, buzz.', image: 'a KAZOO ERUPTS with a buzz on every number someone counts, one, two, three, buzz, buzz, buzz' },
    ],
  },
  {
    id: 'p6-banto',
    room: 6,
    map: 'harbour-market',
    anchor: 'hm-banto',
    name: { jp: 'ばんとうの ちょうば', en: 'Head Clerk’s Desk' },
    emoji: '🧮',
    memories: [
      { item: 'w:uru', story: 'Zeni the clerk sells every item with a long wolf HOWL, “OOO-ROO!”, and the price tags swing on their strings.', image: 'a shopkeeper sells every item with a long wolf HOWL, “OOO-ROO!”, swinging the price tags on their strings' },
      { item: 'w:kore', story: 'Zeni taps the abacus right under his own nose: “the CORE of it — this one, right here!”', image: 'a clerk taps the thing right under his own nose and insists “the CORE, this one, right here!”' },
      { item: 'w:sore', story: 'He points at the coin in your hand and shouts “SORE!” — that one, near you — and your hand suddenly aches.', image: 'someone points at the object in your hand and shouts “SORE!” — that one, near you — and your hand suddenly aches' },
      { item: 'w:are', story: 'He waves at a crate far across the hall, “AH, RAY!”, and a sunbeam through the roof lights up that one over there.', image: 'a man waves at a crate far across a hall, “AH, RAY!”, and a sunbeam lights up that one over there' },
      { item: 'w:dore', story: 'A DOOR with five handles appears behind the desk and rattles “DOOR-AY? which one?”, waiting for you to choose.', image: 'a DOOR with five handles rattles and asks “DOOR-AY? which one?”, waiting for you to choose' },
      { item: 'w:saifu', story: 'Zeni’s fat leather wallet SIGHS, “SIGH… FOO…”, every time he pulls out yet another coin.', image: 'a fat leather wallet SIGHS, “SIGH… FOO…”, every time someone pulls another coin out of it' },
      { item: 'w:hako', story: 'On the desk sits a little wooden box wearing a tiny winter coat, shivering: it HAs a COat. HA-KO.', image: 'a little wooden box wearing a tiny winter coat shivers; it HAs a COat, HA-KO' },
    ],
  },
  {
    id: 'p6-icebarrel',
    room: 6,
    map: 'harbour-market',
    anchor: 'hm-tuna',
    name: { jp: 'こおりの たる', en: 'Ice Barrel' },
    emoji: '🧊',
    memories: [
      { item: 'w:takusan', story: 'A TAXI pulls up beside the barrel packed with SUNfish, “TAK-SAN!”, and an avalanche of a LOT of fish pours into the ice.', image: 'a TAXI pulls up packed with SUNfish — “TAK-SAN!” — and an avalanche of a LOT of fish pours out' },
      { item: 'w:sukoshi', story: 'Only a sliver of ice is left in the barrel. Someone SCOOTS it over with one finger: “SKO-SHEE,” just a little.', image: 'someone SCOOTS a tiny sliver over with one finger, “SKO-SHEE”, just a little, barely anything' },
      { item: 'w:zenbu', story: 'A calm ZEN monk shouts “BOO!” at the barrel and ALL of it, every fish and every cube, leaps out at once: “ZEN-BOO!”', image: 'a calm ZEN monk shouts “BOO!” and ALL of it, every last piece, leaps out at once — “ZEN-BOO!”' },
    ],
  },
  {
    id: 'p6-anchor',
    room: 6,
    map: 'harbour',
    anchor: 'ha-anchor',
    name: { jp: 'いかりの ひろば', en: 'Anchor Square' },
    emoji: '⚓',
    memories: [
      { item: 'w:minato', story: 'Sailors stamp their toes on the great anchor monument chanting “ME, NAH, TOE!”, the song every harbour sings.', image: 'sailors stamp their toes on a huge anchor chanting “ME, NAH, TOE!”, the song every harbour sings' },
      { item: 'g:counter-nin', story: 'One HE-TORI and two FOO-TARI sit on the anchor; then a NINja leaps up beside them, “san-NIN!”, people counted one by one.', image: 'one HE-TORI and two FOO-TARI sit together, then a NINja leaps up — “san-NIN!” — people counted one by one' },
      { item: 'g:counter-ko', story: 'Small round pebbles roll off the anchor and KONK the paving one after another: ik-KO, ni-KO, san-KO.', image: 'small round pebbles roll and KONK the ground one after another — ik-KO, ni-KO, san-KO — little round things counted' },
    ],
  },
  {
    id: 'p6-porter',
    room: 6,
    map: 'harbour',
    anchor: 'ha-porter',
    name: { jp: 'タロの そうこ', en: 'Taro’s Warehouse' },
    emoji: '📦',
    memories: [
      { item: 'g:counter-hon', story: 'Taro drops long poles off his shoulder one by one: IP-PONG, ni-HONK, san-BONG. Long thin things, counted with a clatter.', image: 'long poles drop one by one, going IP-PONG, ni-HONK, san-BONG, long thin things counted with a clatter' },
      { item: 'g:counter-mai', story: 'Flat things flutter out of Taro’s pocket, a ticket, a plate, a sheet of paper, and each lands with a soft “MY!”: ichi-MY, ni-MY.', image: 'flat things flutter down — a ticket, a plate, a sheet — and each lands with a soft “MY!”, ichi-MY, ni-MY' },
      { item: 'w:kippu', story: 'The ferryman presses a ticket into Taro’s hand and barks “KEEP! POO!”: keep this ticket safe.', image: 'a ferryman presses a ticket into your hand and barks “KEEP! POO!” — keep this ticket safe' },
    ],
  },
  {
    id: 'p6-nets',
    room: 6,
    map: 'harbour',
    anchor: 'ha-netmender',
    name: { jp: 'あみほしば', en: 'Net-Drying Racks' },
    emoji: '🕸️',
    memories: [
      { item: 'w:ami', story: 'Fuku unrolls a net she has woven in the exact shape of you — “AH, ME!” — and drapes it over your head to check the fit.', image: 'someone unrolls a net woven in the exact shape of you — “AH, ME!” — and drapes it over your head' },
      { item: 'w:shima', story: 'Beyond the drying nets, a tiny island drifts past with a single SHEEP on it bleating “SHEE-MAAA!” across the water.', image: 'a tiny island drifts past with a single SHEEP on it bleating “SHEE-MAAA!” across the water' },
    ],
  },
  {
    id: 'p6-boat',
    room: 6,
    map: 'harbour',
    anchor: 'ha-boat',
    name: { jp: 'すなはまの ふね', en: 'The Beached Boat' },
    emoji: '⛵',
    memories: [
      { item: 'w:fune', story: 'The little beached boat is piled high with FOOD, and it NEIGHS like a horse — “FOO-NEIGH!” — and tries to gallop down to the sea.', image: 'a little boat piled high with FOOD NEIGHS like a horse — “FOO-NEIGH!” — and paddles off on its own' },
      { item: 'w:nami', story: 'A wave rears up behind the boat and shouts “NAH, ME FIRST!”, slapping the sand before anyone else can launch.', image: 'a wave rears up tall and shouts “NAH, ME FIRST!”, slapping the shore before anyone else can' },
    ],
  },
  {
    id: 'p6-shells',
    room: 6,
    map: 'harbour',
    anchor: 'ha-shells',
    name: { jp: 'かいの かご', en: 'The Shell Basket' },
    emoji: '🐚',
    memories: [
      { item: 'w:kai', story: 'A clam in the basket opens its shell and flies a tiny KITE out of it, flapping in the sea breeze.', image: 'a clam opens its shell and flies a tiny KITE out of it, flapping in the breeze' },
      { item: 'w:suna', story: 'Warm sand pours out of the basket SOONER than you can blink — “SOO-NAH!” — and buries your toes.', image: 'warm sand pours out SOONER than you can blink — “SOO-NAH!” — and buries your toes' },
    ],
  },
  {
    id: 'p6-board',
    room: 6,
    map: 'harbour',
    anchor: 'ha-board',
    name: { jp: 'けいじばん', en: 'Notice Board' },
    emoji: '📅',
    memories: [
      { item: 'w:getsuyoubi', story: 'Monday’s notice shows a big MOON, and a bee zooms off it shouting “GET SUE, YO!”, chasing poor Sue into the start of the week.', image: 'the MOON drops down and a bee zooms off it shouting “GET SUE, YO!”, chasing her into the start of the week' },
      { item: 'w:kayoubi', story: 'Tuesday’s notice is on FIRE, and a flaming bee zips out of it: “KAH-YO, BEE careful!”', image: 'a flaming bee zooms past shouting “KAH-YO, BEE careful!”, its wings on FIRE' },
      { item: 'w:suiyoubi', story: 'Wednesday’s notice is soaking WET; it drips on Sue’s head and she squeals “SUE-EE, YO!”', image: 'cold WATER pours over Sue’s head and she squeals “SUE-EE, YO!” in the middle of the week' },
      { item: 'w:mokuyoubi', story: 'Thursday’s notice sprouts a TREE through the board, and a dove on its branch coos “MO-COO, YO!”', image: 'a TREE sprouts through a wall and a dove on its branch coos “MO-COO, YO!”' },
      { item: 'w:kinyoubi', story: 'Friday’s notice is pure GOLD, and everyone crowding the board shouts “KEEN, YO!”: payday at last.', image: 'shiny GOLD coins shower down and everyone shouts “KEEN, YO!” because payday has finally come' },
      { item: 'w:doyoubi', story: 'Saturday’s notice is caked in EARTH; a baker kneads the mud off it like bread DOUGH: “DOUGH, YO!”', image: 'a baker kneads a lump of EARTH like bread DOUGH, “DOUGH, YO!”, muddy to the elbows' },
      { item: 'w:nichiyoubi', story: 'Sunday’s notice blazes with the SUN, and someone kneels in front of the board to sunbathe: “KNEE-CHEE, YO!”', image: 'someone kneels in blazing SUNshine shouting “KNEE-CHEE, YO!”, the laziest day of the week' },
    ],
  },
  {
    id: 'p6-kai',
    room: 6,
    map: 'harbour-ship',
    anchor: 'hs-kai',
    name: { jp: 'せんちょうの かじ', en: 'Captain’s Wheel' },
    emoji: '🧭',
    memories: [
      { item: 'w:mainichi', story: 'Captain Kai rubs his creaky knee at the wheel and groans “MY KNEE, CHEE!”, the same complaint every single day.', image: 'an old sailor rubs his creaky knee and groans “MY KNEE, CHEE!”, the same complaint every single day' },
      { item: 'g:kara-made', story: 'Kai stretches a rope from a toy CAR on the deck all the way to his MADE bunk — “from CARA, until MADE!” — start to finish.', image: 'a rope stretches from a toy CAR all the way to a MADE bed — “from CARA, until MADE!” — start to finish' },
    ],
  },
  {
    id: 'p6-bell',
    room: 6,
    map: 'harbour-ship',
    anchor: 'hs-bell',
    name: { jp: 'ふねの かね', en: 'Ship’s Bell' },
    emoji: '🔔',
    memories: [
      { item: 'w:asa', story: 'The ship’s bell clangs at dawn and a sleepy deckhand sits bolt upright in his hammock gasping “AH, SAH!”: morning has come.', image: 'a bell clangs at dawn and a sleepy sailor sits bolt upright gasping “AH, SAH!”, the morning has come' },
      { item: 'w:hiru', story: 'At high noon the bell is too hot to touch, and a kangaroo hops across the deck squealing “HE, ROO!”', image: 'at high noon a kangaroo hops across the deck squealing “HE, ROO!”, the sun straight overhead' },
    ],
  },
  {
    id: 'p6-keeper',
    room: 6,
    map: 'harbour-lighthouse',
    anchor: 'hl-keeper',
    name: { jp: 'トキの いす', en: 'Keeper’s Chair' },
    emoji: '⏰',
    memories: [
      { item: 'w:nanji', story: 'Old Toki nudges his NAN in the next chair: “NAN, GEE, what time is it?” and she squints out of the window at the sun.', image: 'an old man nudges his NAN, “NAN, GEE, what time is it?”, and she squints up at the sun' },
      { item: 'g:nanji-desu-ka', story: 'Toki’s parrot paces on the back of his chair screeching “NAN-JEE DESS KAH?” over and over, asking the time.', image: 'a parrot paces on a perch screeching “NAN-JEE DESS KAH?” over and over, asking the time' },
      { item: 'w:ji', story: 'Beside Toki’s chair, a tiny clock rings “GEE!” exactly on every hour: one o’clock GEE, two o’clock GEE.', image: 'a tiny clock rings “GEE!” exactly on every hour, one o’clock GEE, two o’clock GEE' },
      { item: 'w:fun', story: 'A little bird pops out of Toki’s pocket watch going “FOON!” every single minute: sixty FOONs an hour, which is no FUN.', image: 'a little bird pops out of a clock going “FOON!” every single minute, sixty FOONs an hour, which is no FUN' },
    ],
  },
  {
    id: 'p6-clock',
    room: 6,
    map: 'harbour-lighthouse',
    anchor: 'hl-clock',
    name: { jp: 'しおの とけい', en: 'Tide Clock' },
    emoji: '🕤',
    memories: [
      { item: 'w:han', story: 'A HAND chops the stopped clock face neatly in HALF — “HAN!” — so the long hand points straight down at the half hour.', image: 'a HAND chops a clock face neatly in HALF — “HAN!” — so the long hand points straight down at half past' },
      { item: 'g:ji-han', story: 'A dove COOs on the nine while a HAND points at the six — “KOO-JEE-HAN!” — half past nine. Four, seven and nine always sneak a different sound in: YO-ji, SHICHI-ji, KU-ji.', image: 'a dove COOs on the nine while a HAND points at the six — “KOO-JEE-HAN!” — half past the hour' },
    ],
  },
  {
    id: 'p6-lamp',
    room: 6,
    map: 'harbour-lighthouse',
    anchor: 'hl-lamp',
    name: { jp: 'おおきな ランプ', en: 'The Great Lamp' },
    emoji: '💡',
    memories: [
      { item: 'w:toudai', story: 'The great lamp sits on top of a giant’s iron TOE, DIE-cast and standing in the sea: the TOE-DIE, shining for ships.', image: 'a giant’s iron TOE stands in the sea with a lamp on top — the TOE-DIE — shining for ships' },
      { item: 'w:yoru', story: 'At night the lamp YAWNS and ROLLS its beam across the dark water, “YO-ROO”, until the sun comes back.', image: 'a sleepy lamp YAWNS and ROLLS its beam across the dark — “YO-ROO” — all through the night' },
    ],
  },
]
