/**
 * Pixel art for the harbour: fisherfolk (an indigo headscarf over a sea-blue
 * kimono and white apron), a sailor in a white hachimaki and striped shirt,
 * the giant crab, and the Umibōzu: a vast bald sea-monk rising from the
 * waves with two pale lantern eyes. Palette chars: src/art/raster.ts.
 */
import type { CharDef } from '../../art/sprites/characters'
import type { EnemyDef } from '../../art/sprites/enemies'
import type { RegionSprites } from '../types'

const HUMAN = { 5: 'night', 6: 'navy', 7: 'navy', 8: 'woodDark' }
const E16 = '................'
/** Pad a half-map (left 16 columns, mirrored) to 32 rows, content from `top`. */
const rows32 = (top: number, body: string[]) => [...Array(top).fill(E16), ...body, ...Array(Math.max(0, 32 - top - body.length)).fill(E16)].slice(0, 32)

const fisher: CharDef = {
  slots: { ...HUMAN, 1: 'water', 2: 'waterDeep', 3: 'navy', 4: 'waterLight' },
  down: [
    '................',
    '.....555555.....',
    '....55555555....',
    '...5555555556...',
    '...3333333333v..',
    '...5ffffffff6...',
    '...5fkffffkf6...',
    '...ffkffffkfF...',
    '....hffFFffh....',
    '...41pppppp12...',
    '..f41pppppp12f..',
    '..F41PPPPPP12F..',
    '...41pppppp12...',
    '.....77..77.....',
    '.....88.........',
    '................',
  ],
  up: [
    '................',
    '.....555555.....',
    '....55555555....',
    '...5555555556...',
    '...3333333333...',
    '...5555vv5556...',
    '...5555vv5566...',
    '...F55555566F...',
    '....FFFFFFFF....',
    '...41p1111p12...',
    '..f411pppp112f..',
    '..F4111111112F..',
    '...4111111112...',
    '.....77..77.....',
    '.....88.........',
    '................',
  ],
  side: [
    '................',
    '.....55555......',
    '....5555555.....',
    '...555555555....',
    '..v333333333....',
    '..v5556ffffff...',
    '...556Ffffkff...',
    '...556Ffffkff...',
    '....56fffhff....',
    '....41111pp.....',
    '....4111fpp.....',
    '....41111pP.....',
    '....41111pp.....',
    '....77...77.....',
    '....88...88.....',
    '................',
  ],
}

const sailor: CharDef = {
  slots: { ...HUMAN, 1: 'navy', 2: 'night', 4: 'water', 7: 'stoneDark' },
  down: [
    '................',
    '.....555555.....',
    '....55555555....',
    '...5555555556...',
    '...ppppppppppv..',
    '...5ffffffff6...',
    '...5fkffffkf6...',
    '...ffkffffkfF...',
    '....hffFFffh....',
    '...4w1w1w1w12...',
    '..f4w1w1w1w12f..',
    '..F41w1w1w1w2F..',
    '...7777777777...',
    '.....77..77.....',
    '.....88.........',
    '................',
  ],
  up: [
    '................',
    '.....555555.....',
    '....55555555....',
    '...5555555556...',
    '...pppppppppp...',
    '...5555vv5556...',
    '...5555vv5566...',
    '...F55555566F...',
    '....FFFFFFFF....',
    '...4w1w1w1w12...',
    '..f4w1w1w1w12f..',
    '..F41w1w1w1w2F..',
    '...7777777777...',
    '.....77..77.....',
    '.....88.........',
    '................',
  ],
  side: [
    '................',
    '.....55555......',
    '....5555555.....',
    '...555555555....',
    '..vppppppppp....',
    '..v5556ffffff...',
    '...556Ffffkff...',
    '...556Ffffkff...',
    '....56fffhff....',
    '....4w1w1w1.....',
    '....4w1w1ff.....',
    '....4w1w1w1.....',
    '....7777777.....',
    '....77...77.....',
    '....88...88.....',
    '................',
  ],
}

const crab: EnemyDef = {
  sym: true,
  shade: 'v',
  anim: 'bob',
  rows: rows32(6, [
    '..VV............',
    '.VvvV...........',
    'VvvvvV..........',
    'VvVvvV..........',
    'Vv.VvV..........',
    'VvVvvV..........',
    '.VvvV...........',
    '..Vv......Vwww..',
    '...Vv.....Vwkk..',
    '....Vv.....VV...',
    '.....VvvvvvVvvvv',
    '....Vvvvvvvvvvvv',
    '...Vvvevvvvvvvvv',
    '..Vvvvvvvvvvvvvv',
    '..Vvvvvvvvvvvvvv',
    '..VVvvvvvvvvvvvv',
    '...VVvvvvvvvvvvv',
    '....VVVVVVVVVVVV',
    '...V.V.V........',
    '..V..V..V.......',
    '.V...V...V......',
  ]),
}

const umibozu: EnemyDef = {
  sym: true,
  shade: 'n',
  anim: 'bob',
  rows: rows32(2, [
    '..........NNNNNN',
    '........NNNnnnnn',
    '.......NNnnnnnnn',
    '......NNnnnnnnnn',
    '.....NNnnnnnnnnn',
    '.....Nnnnnnnnnnn',
    '....NNnnnnnnnnnn',
    '....Nnnnnnnnnnnn',
    '....Nnnnnnnnnnnn',
    '...NNnnnnnnnnnnn',
    '...Nnnnnnyynnnnn',
    '...NnnnnyCCynnnn',
    '...Nnnnnnyynnnnn',
    '...Nnnnnnnnnnnnn',
    '..NNnnnnnnnnnnnn',
    '..Nnnnnnnnnnnnnn',
    '..Nnnnnnnnnnnnnn',
    '.NNnnnnnnnnnnnnn',
    '.Nnnnnnnnnnnnnnn',
    'NNnnnnnnnnnnnnnn',
    'Nnnnnnnnnnnnnnnn',
    'BbBnnnnnnnnnnnnn',
    'bcbBbnnnnnnnnnnn',
    'CbcbBbBnnnnnnnnn',
    'bCbcbcbBbBbnnnnn',
    'cbCbCbcbcbCbBbBb',
    'bcbcbCbcbcbcbCbc',
    'CbCbcbCbCbcbCbcb',
    'bbbbbbbbbbbbbbbb',
  ]),
}

export const SPRITES: RegionSprites = {
  characters: { fisher, sailor },
  enemies: { crab, umibozu },
}
