/**
 * High-resolution illustrated art (generated in Higgsfield). Every entry
 * lists where the image is used, its target size and the prompt to
 * generate it. Until an image exists in public/art/hd/, the game falls
 * back to the original pixel art, so assets can arrive one at a time.
 *
 * Workflow: drop raw downloads into art-src/<category>/<id>.(png|jpg|webp),
 * run `npm run art:process`, commit public/art/hd/. The processor removes
 * the flat key-colour background from cut-out art and converts to WebP.
 */

export type HdCategory = 'portraits' | 'enemies' | 'bosses' | 'backdrops' | 'scenes' | 'title'

export interface HdAsset {
  id: string
  category: HdCategory
  /** Short human name. */
  name: string
  /** Where it appears in the game. */
  usage: string
  /** Generation size (px). */
  w: number
  h: number
  /** Cut-out art is generated on a flat key colour that the processor removes. */
  cutout?: { key: '#00ff00' | '#ff00ff' }
  /** 1 = biggest visual impact, do first. */
  priority: 1 | 2 | 3
  /** Subject prompt (the shared STYLE prompt is appended). */
  prompt: string
}

/** Shared style: append to every prompt so all art matches. */
export const STYLE =
  'Style: hand-painted anime fantasy illustration, soft watercolor washes over clean confident ink linework, warm cinematic lighting with gentle rim light, rich but soft colors (vermilion, indigo, sakura pink, jade green, antique gold), subtle washi paper texture, Japanese folklore setting in an Edo-era countryside, whimsical and cozy, highly detailed, consistent character design. No text, no letters, no watermark, no logo, no border.'

const CUTOUT = (key: '#00ff00' | '#ff00ff') =>
  `Full body, centered, generous empty margin on all sides, isolated on a perfectly flat solid pure ${key === '#00ff00' ? 'green (#00FF00)' : 'magenta (#FF00FF)'} background, no ground, no cast shadow, no scenery.`

/** The recurring cast, described once so every image keeps them on-model. */
export const CAST = {
  mage: 'a young apprentice mage (age about 16, friendly, gender-neutral) with short brown hair and bright eyes, wearing a tall pointed indigo wizard hat with a gold band and a tiny gold star, an indigo robe with gold trim and a sash, holding a wooden staff topped with a glowing golden orb',
  scribe: 'Kotone, the girl with the brush from long ago (age about 15, gentle, warm and determined): long straight black hair to her waist tied with a vermilion ribbon, a soft wisteria-lilac kimono with a white collar and a deep indigo hakama, ink smudges on her fingers and cheek, carrying a large calligraphy brush with a red-lacquered handle and a gold band, its bristles wet with glowing ink',
  shadow: 'the Nameless Quiet: a small, soft, smoke-like shadow creature the colour of dusk, a wisp of indigo-grey mist with two faint lonely silver eyes and wispy ragged edges, half translucent, more sad than scary',
  fude: 'Fude, a tiny floating calligraphy-brush spirit mascot: a plump round white body shaped like a soft brush tip, big shiny black eyes, rosy cheeks, a red-lacquered brush handle with a gold band on top like a little hat, and a swirling black ink-drop tail; cute, expressive, glowing faintly',
}

export const HD_ASSETS: HdAsset[] = [
  // ── Title ──────────────────────────────────────────────────────────
  { id: 'title-wide', category: 'title', name: 'Title key art (wide)', usage: 'Title screen background on desktop', w: 1920, h: 1080, priority: 1, prompt: `Key art for a Japanese fantasy RPG about the magic of words. Night on a grassy hill above a sleeping village with glowing paper lanterns, a huge full moon, a sky of stars where glowing hiragana-like brush strokes drift like fireflies. In the foreground, seen from behind and slightly to the side, ${CAST.mage}, looking up at the sky, with ${CAST.fude} floating beside them. Sakura petals drift on the wind. Leave the upper-middle third of the image calm and uncluttered for a logo.` },
  { id: 'title-tall', category: 'title', name: 'Title key art (tall)', usage: 'Title screen background on phones', w: 1080, h: 1920, priority: 1, prompt: `Vertical key art, same scene as the wide version: night hill above a lantern-lit village, full moon, glowing brush strokes drifting in the starry sky, ${CAST.mage} seen from behind looking up, ${CAST.fude} floating beside them, sakura petals. Keep the top third calm for a logo and the bottom quarter simple for menu buttons.` },

  // ── Portraits (dialogue & cutscenes) ───────────────────────────────
  { id: 'fude', category: 'portraits', name: 'Fude (companion)', usage: 'Dialogue portrait, cutscenes, hints', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 1, prompt: `Character portrait of ${CAST.fude}, cheerful expression, small sparkles of ink around it. ${CUTOUT('#ff00ff')}` },
  { id: 'mage', category: 'portraits', name: 'The player mage', usage: 'Player portrait in dialogue, status, battle', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 1, prompt: `Character portrait, waist-up, three-quarter view, of ${CAST.mage}, determined hopeful smile. ${CUTOUT('#ff00ff')}` },
  { id: 'scribe', category: 'portraits', name: 'Kotone, the girl with the brush', usage: 'Fude’s memories (cutscenes) and the true ending', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 1, prompt: `Character portrait, waist-up, three-quarter view, of ${CAST.scribe}. She holds the brush up as if about to write a word in the air, a faint trail of glowing ink characters drifting from its tip, a kind, slightly wistful smile. ${CUTOUT('#00ff00')}` },
  { id: 'elder', category: 'portraits', name: 'Village Elder', usage: 'Word lessons in the village', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Character portrait, waist-up, of a kind wise village elder: an old man with a long white beard and bushy eyebrows, round spectacles, brown haori over a grey kimono, leaning on a gnarled wooden cane, warm smile. ${CUTOUT('#00ff00')}` },
  { id: 'merchant', category: 'portraits', name: 'Mina the Spell Merchant', usage: 'Spell shop (ください dialogue)', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Character portrait, waist-up, of Mina, a cheerful young woman shopkeeper who sells magic spells: pink hachimaki headband, sleeves tied back with a tasuki cord, an apron over a sakura-patterned kimono, holding a rolled spell scroll and a wooden abacus, winking. ${CUTOUT('#00ff00')}` },
  { id: 'guard', category: 'portraits', name: 'Goro the Bridge Guard', usage: 'Bridge guard dialogue puzzle', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 2, prompt: `Character portrait, waist-up, of Goro, a burly bridge guard with a big moustache, lacquered blue lamellar armor, a flat jingasa hat, holding a long spear upright, stern face but kind eyes. ${CUTOUT('#ff00ff')}` },
  { id: 'priest', category: 'portraits', name: 'Shrine Priest', usage: 'Shrine priest dialogue, cutscenes', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Character portrait, waist-up, of a calm Shinto shrine priest (kannushi): white and pale-lavender robes, tall black eboshi hat, holding a gohei wand with white paper streamers, serene expression. ${CUTOUT('#00ff00')}` },
  { id: 'king', category: 'portraits', name: 'The King', usage: 'Throne room politeness challenge', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Character portrait, waist-up, of a proud fantasy Japanese king: golden crown with jade ornaments, crimson cape with white fur trim, layered royal robes in gold and deep red, raised eyebrow, haughty but fair. ${CUTOUT('#00ff00')}` },
  { id: 'child', category: 'portraits', name: 'Village kid', usage: 'Village cutscenes and NPC chatter', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 3, prompt: `Character portrait, waist-up, of an energetic village kid (about 8) in a short green-and-white checked kimono with a bandage on the nose, grinning and pointing excitedly. ${CUTOUT('#ff00ff')}` },
  { id: 'farmer', category: 'portraits', name: 'Farmer', usage: 'Fields cutscenes and NPCs', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 3, prompt: `Character portrait, waist-up, of a friendly rice farmer with a wide straw hat, rolled-up sleeves, a towel around the neck, holding a bundle of golden rice, sunburnt cheerful face. ${CUTOUT('#ff00ff')}` },
  { id: 'innkeeper', category: 'portraits', name: 'Innkeeper', usage: 'Inns (rest after a lost battle)', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `Character portrait, waist-up, of a warm middle-aged innkeeper woman in an indigo kimono and white apron, hair in a neat bun with a comb, holding a tray with a teapot, welcoming smile. ${CUTOUT('#00ff00')}` },
  { id: 'jailer', category: 'portraits', name: 'Jailer', usage: 'Tower dungeon apology scene', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `Character portrait, waist-up, of a grumpy but comical tower jailer: bald, big iron key ring on a belt, dark grey uniform with red cord, arms crossed, one eyebrow raised. ${CUTOUT('#00ff00')}` },


  // ── Folklore spirits (Spirit Scroll + their tales' dialogue) ───────────
  { id: 'yokai-zashiki-warashi', category: 'portraits', name: 'Zashiki-warashi', usage: 'Village folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of a zashiki-warashi, a mischievous house-spirit child of about six with a bobbed okappa haircut and rosy cheeks, wearing a faded red kimono, peeking out from behind a sliding paper door with a sly giggle, holding a beanbag otedama. ${CUTOUT('#00ff00')}` },
  { id: 'yokai-kasa-obake', category: 'portraits', name: 'Kasa-obake', usage: 'Village folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of a kasa-obake tsukumogami: an old oiled-paper umbrella come to life, hopping on a single wooden leg, one big round eye and a long lolling tongue, its paper patched and torn, looking playful and a little lonely. ${CUTOUT('#00ff00')}` },
  { id: 'yokai-shitakiri-suzume', category: 'portraits', name: 'The tongue-cut sparrow', usage: 'Village folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of Ochun, a plump little brown sparrow spirit wearing a tiny kimono and apron of the sparrows inn, perched beside a small wicker tsuzura basket, bowing politely. ${CUTOUT('#00ff00')}` },
  { id: 'yokai-kappa', category: 'portraits', name: 'Kappa', usage: 'Fields folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 2, prompt: `Portrait of a friendly kappa river imp: green turtle-shell back, webbed hands, a beak-like mouth and a shallow dish of water on top of its head, bowing politely so the water nearly spills, clutching a cucumber. ${CUTOUT('#ff00ff')}` },
  { id: 'yokai-kasa-jizo', category: 'portraits', name: 'Kasa Jizō', usage: 'Fields folklore tale; Spirit Scroll', w: 1024, h: 1024, priority: 2, prompt: `Six small stone Jizō statues standing in a row in light snow, each wearing a straw kasa hat and a red bib, gentle smiling faces, one holding out a rice-cake gift. Square composition.` },
  { id: 'yokai-tsuru', category: 'portraits', name: 'The crane’s return', usage: 'Fields folklore tale (the crane and Tsuu); Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of Tsuu, the crane maiden: a graceful young woman in a white kimono with a pattern of crane feathers, long black hair, a red crown-like hair ornament, a pair of white crane wings softly unfolding behind her, holding a bolt of shimmering woven cloth. ${CUTOUT('#00ff00')}` },
  { id: 'yokai-tengu', category: 'portraits', name: 'Tengu', usage: 'Forest folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of a proud mountain tengu: red face with a long nose, bushy white eyebrows, a small black tokin cap, yamabushi robes with pom-pom sash, black feathered wings, holding a feather fan, a stern but fond expression. ${CUTOUT('#00ff00')}` },
  { id: 'yokai-bunbuku', category: 'portraits', name: 'Bunbuku Chagama', usage: 'Forest folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of Bunbuku Chagama: a round iron tea kettle with a tanuki head, paws and bushy tail poking out of it, balancing on a tightrope with a little parasol, beaming proudly. ${CUTOUT('#00ff00')}` },
  { id: 'yokai-yamabiko', category: 'portraits', name: 'Yamabiko', usage: 'Forest folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 2, prompt: `Portrait of a shy yamabiko echo spirit: a small furry mountain creature like a pale grey-white monkey with big ears and huge round eyes, cupping its hands around its mouth to call, standing on a mossy rock. ${CUTOUT('#ff00ff')}` },
  { id: 'yokai-tsuki-usagi', category: 'portraits', name: 'The moon rabbit', usage: 'Shrine folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of the moon rabbit: a white rabbit standing on its hind legs, wearing a tiny happi coat and headband, holding a wooden kine mallet over a mortar of white mochi. ${CUTOUT('#00ff00')}` },
  { id: 'yokai-noppera-bo', category: 'portraits', name: 'Noppera-bō', usage: 'Shrine folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of a gentle noppera-bō: a slender figure in a plain grey kimono with long black hair whose face is smooth and blank like an egg, holding a paper lantern, posture shy and sad rather than scary. ${CUTOUT('#00ff00')}` },
  { id: 'yokai-tanabata', category: 'portraits', name: 'Orihime and Hikoboshi', usage: 'Shrine folklore tale (the two star lovers); Spirit Scroll', w: 1024, h: 1024, priority: 2, prompt: `Orihime the weaver princess in a flowing pink-and-white star-patterned robe and Hikoboshi the cowherd in simple blue clothes reaching toward each other across a bridge of magpies over the glittering Milky Way, bamboo with colourful tanzaku wishes in the corner. Square composition.` },
  { id: 'yokai-kaguya-hime', category: 'portraits', name: 'Kaguya-hime', usage: 'Tower folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 2, prompt: `Portrait of Kaguya-hime, the moon princess: very long straight black hair, a layered jūnihitoe court robe in moonlight silver and pale violet, holding a glowing stalk of bamboo, a serene and wistful expression, soft moonlight on her face. ${CUTOUT('#ff00ff')}` },
  { id: 'yokai-baku', category: 'portraits', name: 'Baku', usage: 'Tower folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of a gentle baku dream-eater: an elephant trunk, tiger paws, an ox tail and a patterned hide like a temple carving, sleepy kind eyes, slurping a small swirl of dark nightmare mist through its trunk. ${CUTOUT('#00ff00')}` },
  { id: 'yokai-urashima', category: 'portraits', name: 'Urashima Tarō', usage: 'Tower folklore tale; Spirit Scroll', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of Urashima Tarō, an old fisherman with a long white beard and a straw raincoat, holding a lacquered black-and-red tamatebako box tied with a purple cord, a small sea turtle at his feet, looking out to sea. ${CUTOUT('#00ff00')}` },

  // ── Extra cast (folklore tales, memories) ────────────────────────────
  { id: 'villager', category: 'portraits', name: 'Village woman', usage: 'Villager-b NPCs: the housekeeper, Granny Tsuru, Tsuu, the weeping figure', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Character portrait, waist-up, three-quarter view, of a kind village woman in her forties with black hair in a simple low bun and a hand towel tied over it, a faded indigo kasuri-patterned kimono with rolled-up sleeves and a pale apron, a gentle tired smile. ${CUTOUT('#00ff00')}` },
  { id: 'cat', category: 'portraits', name: 'Village cat', usage: 'Cat NPCs (Tama, the moon rabbit stand-in)', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of a small fluffy calico cat with a red collar and a tiny silver bell, sitting upright, big curious amber eyes, one paw raised like a maneki-neko. ${CUTOUT('#00ff00')}` },
  { id: 'dog', category: 'portraits', name: 'Village dog', usage: 'Dog NPCs', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of a friendly Shiba Inu dog with a curled tail and a blue scarf, tongue out, sitting happily. ${CUTOUT('#00ff00')}` },
  { id: 'fox', category: 'portraits', name: 'Fox', usage: 'Fox NPCs (not spirits)', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of a slender red fox with bright golden eyes and a white-tipped bushy tail, sitting alert with its ears pricked, a few autumn leaves stuck in its fur. ${CUTOUT('#00ff00')}` },
  { id: 'shadow', category: 'portraits', name: 'The Nameless Quiet', usage: 'Fude’s memories: the lonely quiet that became the dragon', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 2, prompt: `Portrait of ${CAST.shadow}, curling in on itself, looking up hopefully as if waiting to be called by a name. ${CUTOUT('#00ff00')}` },

  // ── Fude’s memories (sepia memory cutscenes) and the true ending ─────
  { id: 'memory-1', category: 'scenes', name: 'Memory I: A Name in the Rain', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `Night rain on a lonely hillside path, sepia-tinted like an old memory: ${CAST.scribe} kneels under a red paper umbrella, cupping a small cracked white calligraphy brush in her palms. The little brush is ${CAST.fude}, but cracked, dim and sleepy, its eyes just opening. A single warm glow where she touches it.` },
  { id: 'memory-2', category: 'scenes', name: 'Memory II: The Hundred Friends', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `A sunny village lane long ago, sepia-tinted: ${CAST.scribe} writes glowing names in the air with her brush while ${CAST.fude} bobs at her shoulder; around them a crowd of friendly yokai — a kappa, a fox, a tanuki, a one-eyed umbrella spirit, a little house-spirit child — gather to watch, the written names settling on a river, a mountain and a flower and making them glow.` },
  { id: 'memory-3', category: 'scenes', name: 'Memory III: The Thing Between Words', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `Dusk over wide rice fields, the wind gone still, sepia-tinted: ${CAST.scribe} sits on a ridge path looking apologetically at an empty space in the air where ${CAST.shadow} hovers, barely visible, listening. ${CAST.fude} peeks from behind her sleeve. Quiet, melancholy mood.` },
  { id: 'memory-4', category: 'scenes', name: 'Memory IV: Footsteps in the Mist', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `A misty forest path, sepia-tinted: ${CAST.scribe} turns in alarm as a growing shadow — ${CAST.shadow}, now bigger — swallows a bird’s song, the glowing notes being drawn into it like smoke; ${CAST.fude} hides in her hair.` },
  { id: 'memory-5', category: 'scenes', name: 'Memory V: The Hungry Quiet', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `A forest village under a darkening sky, sepia-tinted: the shadow has grown into a huge swirling cloud of dusk with lonely silver eyes, pulling glowing name-glyphs off houses and lanterns; ${CAST.scribe} stands in front of it with her brush raised, not to fight but pleading, ${CAST.fude} glowing at her side.` },
  { id: 'memory-6', category: 'scenes', name: 'Memory VI: Kotone’s Promise', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `A shrine at night lit by lanterns, sepia-tinted: ${CAST.scribe} stands on the shrine steps making a promise, one hand on her heart, surrounded by a circle of gentle yokai holding lanterns; ${CAST.fude} floats before her, glowing warmly.` },
  { id: 'memory-7', category: 'scenes', name: 'Memory VII: The Night of the Dragon', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `A tall tower against a black storm sky, sepia-tinted: a colossal serpentine dragon of darkness and ink coils around the tower, yokai scattering below; ${CAST.scribe} stands on a balcony holding her brush, its bristles dry and empty of ink, ${CAST.fude} crying out beside her.` },
  { id: 'memory-8', category: 'scenes', name: 'Memory VIII: Ink of the Heart', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `A dark void lit by golden light, sepia-tinted: ${CAST.scribe} writes with her brush and the ink is her own glowing name flowing from her heart, ribbons of golden characters wrapping the great shadow dragon and lulling it to sleep; her outline is beginning to fade into light, ${CAST.fude} reaching for her.` },
  { id: 'memory-9', category: 'scenes', name: 'Memory IX: The Last Line', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `Dawn breaking over a quiet hill, sepia-tinted: a faded, almost transparent ${CAST.scribe} smiles and gently hands ${CAST.fude} to the morning wind, an open book of glowing pages beside her with the last line left blank.` },
  { id: 'memory-10', category: 'scenes', name: 'Memory X: The Gentlest Name', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `A starry night on a hill, sepia-tinted: ${CAST.scribe} sits alone looking up at the stars with her brush resting on her knees, a soft smile, a single glowing character drifting up toward the moon like a wish.` },
  { id: 'true-ending', category: 'scenes', name: 'True ending: the Hundred Spirits’ Parade', usage: 'Memory cutscene illustration', w: 1920, h: 1080, priority: 1, prompt: `Night on a hill under a sky full of stars: ${CAST.mage} and ${CAST.fude} watch a joyful hyakki yagyō parade of friendly yokai with lanterns winding down the hill — a kappa, tengu, tanuki tea kettle, moon rabbit, umbrella spirit, a crane maiden — while a calm, gentle dragon made of soft night sky curls protectively around the moon, and the translucent smiling figure of ${CAST.scribe} waves from among the spirits. Warm, joyful, bittersweet.` },
  // ── Bosses ─────────────────────────────────────────────────────────
  { id: 'kana-oni', category: 'bosses', name: 'The Kana Oni', usage: 'Region 1 boss battle and cutscenes', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 1, prompt: `A menacing but slightly comical red oni demon, muscular, with two horns, wild white hair, a tiger-skin loincloth, and an iron kanabō club; its skin is covered in glowing golden hiragana-like brush-stroke tattoos that seem jumbled and scrambled; fierce grin with fangs, dynamic threatening pose. ${CUTOUT('#00ff00')}` },
  { id: 'radical-golem', category: 'bosses', name: 'The Radical Golem', usage: 'Region 2 boss battle', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 1, prompt: `A towering stone golem assembled from carved stone blocks, each block engraved with a glowing kanji radical symbol (fire, water, tree, mouth, person strokes as abstract glyphs, not readable text), moss and small flowers growing in the cracks, glowing amber eyes, heavy fists. ${CUTOUT('#ff00ff')}` },
  { id: 'particle-guardian', category: 'bosses', name: 'The Particle Guardian', usage: 'Region 3 boss battle', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 1, prompt: `An ancient forest guardian spirit: a giant tree-like being with a face in its bark, antler-like branches, glowing jade eyes, surrounded by three floating circular shields of light, each shield marked with a single glowing abstract brush glyph; roots coiling like legs, fireflies around it. ${CUTOUT('#ff00ff')}` },
  { id: 'silent-librarian', category: 'bosses', name: 'The Silent Librarian', usage: 'Region 4 boss battle', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 1, prompt: `An eerie, elegant ghost librarian: a pale translucent woman in flowing white and indigo robes that fade into blue spirit flame at the hem, long black hair, eyes closed, a finger to her lips asking for silence, surrounded by floating open books and paper talismans orbiting her. ${CUTOUT('#00ff00')}` },
  { id: 'shifting-chimera', category: 'bosses', name: 'The Shifting Chimera', usage: 'Region 5 boss battle (adjective forms)', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 1, prompt: `A majestic nine-tailed kitsune chimera, fox body with a mane, each tail made of a different element (flame, ice crystals, swirling wind, lightning, water, glowing light, earth stones, leaves, shadow), shimmering fur shifting colors, fierce clever eyes, poised to pounce. ${CUTOUT('#00ff00')}` },
  { id: 'void-dragon', category: 'bosses', name: 'The Void Dragon', usage: 'Final boss battle and ending', w: 1920, h: 1080, cutout: { key: '#00ff00' }, priority: 1, prompt: `An enormous serpentine eastern dragon made of darkness and swirling ink, coiling through space, with deep violet and crimson scales, glowing golden eyes, long whiskers, pale mane, jagged fins; torn fragments of glowing brush-stroke glyphs are being sucked into its open mouth; epic, awe-inspiring. Whole dragon visible. ${CUTOUT('#00ff00')}` },

  // ── Regular enemies ────────────────────────────────────────────────
  { id: 'slime', category: 'enemies', name: 'Slime', usage: 'Village random battles', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 3, prompt: `A cute blue water-drop slime monster with a glossy jelly body, big eyes and a cheeky grin. ${CUTOUT('#ff00ff')}` },
  { id: 'ice-slime', category: 'enemies', name: 'Ice slime', usage: 'Fields random battles', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 3, prompt: `A cute pale-cyan ice slime monster with frost crystals on top, shivering, breath misting. ${CUTOUT('#ff00ff')}` },
  { id: 'imp', category: 'enemies', name: 'Fire imp', usage: 'Village random battles', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `A small mischievous purple fire imp with bat wings, little horns, a flaming tail tip and a toothy grin, hovering. ${CUTOUT('#00ff00')}` },
  { id: 'bat', category: 'enemies', name: 'Bat', usage: 'Village random battles', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `A round fluffy dark-blue cave bat monster with huge ears, wings spread, sleepy but grumpy eyes. ${CUTOUT('#00ff00')}` },
  { id: 'mushroom', category: 'enemies', name: 'Mushroom', usage: 'Village random battles', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `A walking red-capped mushroom monster with white spots, tiny legs and an annoyed face, releasing a puff of spores. ${CUTOUT('#00ff00')}` },
  { id: 'kappa', category: 'enemies', name: 'Kappa', usage: 'Fields random battles', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 3, prompt: `A kappa river yokai: green turtle-like creature with a shell, a beak, and a water-filled dish on its head, holding a cucumber, playful fighting stance. ${CUTOUT('#ff00ff')}` },
  { id: 'tanuki', category: 'enemies', name: 'Tanuki', usage: 'Fields random battles', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `A shapeshifting tanuki yokai standing upright with a leaf on its head, straw hat on its back and a sake bottle, round belly, sly grin, puff of transformation smoke. ${CUTOUT('#00ff00')}` },
  { id: 'golem', category: 'enemies', name: 'Stone golem', usage: 'Fields random battles', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 3, prompt: `A small mossy stone golem made of rounded river stones, glowing blue eyes, stubby arms, sturdy stance. ${CUTOUT('#ff00ff')}` },
  { id: 'wisp', category: 'enemies', name: 'Will-o-wisp', usage: 'Forest and shrine random battles', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `A hitodama spirit wisp: a floating ball of blue-white ghost fire with a curling tail and small hollow eyes, eerie glow. ${CUTOUT('#00ff00')}` },
  { id: 'kitsune', category: 'enemies', name: 'Kitsune', usage: 'Forest random battles', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `A white fox spirit (kitsune) with three tails tipped in blue foxfire, red markings on its face, elegant and sly. ${CUTOUT('#00ff00')}` },
  { id: 'harpy', category: 'enemies', name: 'Storm harpy', usage: 'Forest and tower random battles', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `A storm harpy: a bird-woman with grey-blue storm-cloud feathered wings, talons, crackling small lightning around her, fierce. ${CUTOUT('#00ff00')}` },
  { id: 'treant', category: 'enemies', name: 'Treant', usage: 'Forest random battles', w: 1024, h: 1024, cutout: { key: '#ff00ff' }, priority: 3, prompt: `A grumpy young tree spirit (treant) with a bark face, leafy crown, root feet and branch arms, holding a pinecone. ${CUTOUT('#ff00ff')}` },
  { id: 'tengu', category: 'enemies', name: 'Tengu', usage: 'Shrine and tower random battles', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `A tengu mountain spirit: red face with a very long nose, black crow wings, yamabushi monk clothes with pom-pom sash, a feather fan raised, proud. ${CUTOUT('#00ff00')}` },
  { id: 'oni', category: 'enemies', name: 'Oni', usage: 'Shrine and tower random battles', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `A blue oni brute with one horn, tiger-striped loincloth, spiked iron club over its shoulder, big grin. ${CUTOUT('#00ff00')}` },
  { id: 'skeleton', category: 'enemies', name: 'Skeleton samurai', usage: 'Shrine and tower random battles', w: 1024, h: 1024, cutout: { key: '#00ff00' }, priority: 3, prompt: `A skeleton samurai in battered red lacquer armor and a horned kabuto helmet, katana drawn, faint blue ghost-fire in its eye sockets. ${CUTOUT('#00ff00')}` },

  // ── Battle backdrops ───────────────────────────────────────────────
  { id: 'battle-village', category: 'backdrops', name: 'Village meadow', usage: 'Battle background, region 1', w: 1920, h: 1080, priority: 1, prompt: 'Wide landscape battle background: a sunny meadow just outside a Japanese village, thatched and tiled roofs in the distance, cherry trees in bloom, a stone lantern, soft clouds. The center and lower-middle of the image are open flat grass (monsters will stand there). Eye-level camera, horizon slightly above the middle.' },
  { id: 'battle-fields', category: 'backdrops', name: 'Golden fields', usage: 'Battle background, region 2', w: 1920, h: 1080, priority: 1, prompt: 'Wide landscape battle background: golden rice terraces and fields at late afternoon, scarecrows, a distant mountain with a small shrine, dragonflies. The center and lower-middle are an open dirt path area. Eye-level camera, horizon slightly above the middle.' },
  { id: 'battle-forest', category: 'backdrops', name: 'Deep forest', usage: 'Battle background, region 3', w: 1920, h: 1080, priority: 1, prompt: 'Wide landscape battle background: a deep ancient cedar forest with shafts of light through mist, moss-covered roots, a small red bridge over a stream in the distance, fireflies. The center and lower-middle are an open mossy clearing. Eye-level camera.' },
  { id: 'battle-shrine', category: 'backdrops', name: 'Shrine courtyard at night', usage: 'Battle background, region 4', w: 1920, h: 1080, priority: 1, prompt: 'Wide landscape battle background: a mountain shrine courtyard at night, rows of glowing stone lanterns, a large vermilion torii gate, stone path, paper talismans on ropes, moonlight and blue mist. The center and lower-middle are open stone paving. Eye-level camera.' },
  { id: 'battle-tower', category: 'backdrops', name: 'Tower interior', usage: 'Battle background, region 5', w: 1920, h: 1080, priority: 1, prompt: 'Wide landscape battle background: inside a mystical tower of creation, a grand hall with floating stone stairs, tall arched windows showing a starry purple sky, glowing magic circles on the floor, floating glyph lights. The center and lower-middle are open floor. Eye-level camera.' },
  { id: 'battle-summit', category: 'backdrops', name: 'Tower summit', usage: 'Final battle against the Void Dragon', w: 1920, h: 1080, priority: 1, prompt: 'Wide landscape battle background: the open summit of a tower above the clouds at twilight, a cracked stone platform with a huge glowing magic circle, a swirling black void vortex tearing open the sky, glowing glyph fragments being pulled into it, dramatic. The center and lower-middle are the open platform.' },

  // ── Cutscene stills ────────────────────────────────────────────────
  { id: 'intro-1', category: 'scenes', name: 'Intro: when words were alive', usage: 'Opening cutscene, frame 1', w: 1920, h: 1080, priority: 2, prompt: 'A peaceful Japanese countryside at dawn where words are alive: glowing golden brush-stroke glyphs float over rice fields, rivers and a village like fireflies and birds, people waving at them happily. Dreamy and warm.' },
  { id: 'intro-2', category: 'scenes', name: 'Intro: the Void Dragon', usage: 'Opening cutscene, frame 2', w: 1920, h: 1080, priority: 2, prompt: 'The same countryside at night under a stormy violet sky: a colossal serpentine eastern dragon made of darkness and ink swallows the glowing brush-stroke glyphs, which scatter across the land like falling stars; villagers look up in fear.' },
  { id: 'intro-3', category: 'scenes', name: 'Intro: Fude wakes you', usage: 'Opening cutscene, frame 3', w: 1920, h: 1080, priority: 2, prompt: `Morning on a grassy hill: ${CAST.mage} is waking up under a cherry tree, rubbing their eyes, while ${CAST.fude} floats excitedly in front of their face. Petals falling, a village visible below.` },
  { id: 'arrive-village', category: 'scenes', name: 'Arriving: the village', usage: 'Region 1 arrival cutscene', w: 1920, h: 1080, priority: 2, prompt: `A cozy Japanese village street with tiled roofs, noren curtains, lanterns, a well and cherry trees; villagers and a cat; seen from the entrance as ${CAST.mage} and ${CAST.fude} arrive.` },
  { id: 'arrive-fields', category: 'scenes', name: 'Arriving: the Elemental Fields', usage: 'Region 2 arrival cutscene', w: 1920, h: 1080, priority: 2, prompt: `Vast golden elemental fields: rice paddies reflecting the sky, a stream, a windmill-like water wheel, standing stones glowing with element symbols (fire, water, tree, earth, stone as abstract glyphs); ${CAST.mage} and ${CAST.fude} on the path, small in frame.` },
  { id: 'arrive-forest', category: 'scenes', name: 'Arriving: the Forest of Sentences', usage: 'Region 3 arrival cutscene', w: 1920, h: 1080, priority: 2, prompt: `An ancient forest whose trees have glowing brush-stroke glyphs growing like leaves and vines connecting them into long lines like sentences; light shafts; a red bridge guarded by a figure with a spear in the distance; ${CAST.mage} and ${CAST.fude} entering.` },
  { id: 'arrive-shrine', category: 'scenes', name: 'Arriving: the Shrine of Reading', usage: 'Region 4 arrival cutscene', w: 1920, h: 1080, priority: 2, prompt: `A mountaintop shrine at dusk: long stairs lined with vermilion torii gates, stone tablets covered in carved glyphs, lanterns lighting up, a library pavilion; ${CAST.mage} and ${CAST.fude} climbing the stairs.` },
  { id: 'arrive-tower', category: 'scenes', name: 'Arriving: the Tower of Creation', usage: 'Region 5 arrival cutscene', w: 1920, h: 1080, priority: 2, prompt: `A colossal spiraling tower of creation rising into a twilight sky full of floating glyphs, a dark vortex at its peak; a royal castle at its base; ${CAST.mage} and ${CAST.fude} look up at it from the approach road, awed.` },
  { id: 'ending', category: 'scenes', name: 'Ending: words return', usage: 'Final cutscene', w: 1920, h: 1080, priority: 2, prompt: `Triumphant sunrise over the whole land seen from the tower summit: countless glowing brush-stroke glyphs stream back across the sky into villages, forests and fields, bringing color back; ${CAST.mage} raises their staff while ${CAST.fude} cheers; villagers celebrate far below.` },
]

export const HD_BY_ID = new Map(HD_ASSETS.map((a) => [a.id, a]))

/** Public URL of the processed asset (WebP). */
export function hdUrl(id: string): string {
  const a = HD_BY_ID.get(id)
  return `${import.meta.env?.BASE_URL ?? './'}art/hd/${a?.category ?? 'misc'}/${id}.webp`
}
