/**
 * Region 8 — 城下町, the Castle Town. A bustling Edo town below a white
 * castle: merchant streets hung with red lanterns, a canal under arched
 * bridges, a tea house, a kabuki stage, a dojo, and the castle gate and
 * garden. Nurarihyon, the old yokai who walks into houses uninvited and
 * acts as master, has moved into the keep and eaten the town's courtesy.
 *
 * Teaches polite everyday talk: asking and giving directions (右・左・
 * まっすぐ・曲がる, ここ/そこ/あそこ/どこ, こちら/そちら/あちら/どちら,
 * この/その/あの/どの), shopping phrases (いらっしゃいませ, 〜を
 * おねがいします, 〜はありますか, 〜にします), likes, dislikes, skill and
 * wants (嫌い, 上手, 下手, 欲しい), invitations (〜ませんか, 〜ましょうか),
 * giving and receiving (あげる, くれる, もらう) and a first taste of keigo
 * (いらっしゃる, めしあがる, おっしゃる; まいります, おります, いたします).
 */
import type { RegionData } from '../types'

export const DATA: RegionData | null = {
  region: {
    id: 8,
    name: 'The Castle Town',
    jp: '城下町',
    reading: 'じょうかまち',
    tagline: 'Ask the way, mind your manners, and bow to the lord.',
    teaches: ['Directions: right, left, here, there', 'Shopping and polite requests', 'Likes, wants, giving and receiving', 'First keigo'],
    color: '#d9534f',
    emoji: '🏯',
    pos: { x: 80, y: 54 },
    map: 'castletown',
  },

  words: [
    // ── Which Way? Directions and the town
    ['migi', '右', 'みぎ', 'right', 'noun', '👉', { alt: ['right side'] }],
    ['hidari', '左', 'ひだり', 'left', 'noun', '👈', { alt: ['left side'] }],
    ['massugu', 'まっすぐ', 'まっすぐ', 'straight ahead', 'adverb', '⬆️', { alt: ['straight', 'straight on'] }],
    ['magaru', '曲がる', 'まがる', 'turn', 'verb', '↪️', { masu: '曲がります', alt: ['to turn', 'turn a corner'] }],
    ['kado', '角', 'かど', 'corner', 'noun', '📐', { alt: ['street corner'] }],
    ['tonari', 'となり', 'となり', 'next to', 'noun', '↔️', { alt: ['beside', 'next door', 'neighbour'] }],
    ['mae', '前', 'まえ', 'front', 'noun', '⏫', { alt: ['in front', 'in front of', 'before'] }],
    ['ushiro', '後ろ', 'うしろ', 'behind', 'noun', '🔙', { alt: ['back', 'rear'] }],
    ['koko', 'ここ', 'ここ', 'here', 'pronoun', '📍', { alt: ['this place'] }],
    ['soko', 'そこ', 'そこ', 'there', 'pronoun', '🫳', { alt: ['that place', 'there (near you)'] }],
    ['asoko', 'あそこ', 'あそこ', 'over there', 'pronoun', '🔭', { alt: ['that place over there'] }],
    ['doko', 'どこ', 'どこ', 'where', 'pronoun', '🗺️', { alt: ['what place'] }],
    ['toori', '通り', 'とおり', 'street', 'noun', '🛣️', { alt: ['avenue', 'road'] }],
    ['mon', '門', 'もん', 'gate', 'noun', '🚪', { alt: ['gateway'] }],
    ['machi', '町', 'まち', 'town', 'noun', '🏘️', { alt: ['city'] }],

    // ── Shop Talk: this one, that one, and polite shopping
    ['kono', 'この', 'この', 'this (+ noun)', 'pronoun', '👇', { alt: ['this'] }],
    ['sono', 'その', 'その', 'that (+ noun)', 'pronoun', '👉', { alt: ['that'] }],
    ['ano', 'あの', 'あの', 'that (+ noun) over there', 'pronoun', '🫵', { alt: ['that over there'] }],
    ['dono', 'どの', 'どの', 'which (+ noun)', 'pronoun', '🤔', { alt: ['which'] }],
    ['kochira', 'こちら', 'こちら', 'this way', 'pronoun', '🙇', { alt: ['this side', 'here (polite)', 'this person'] }],
    ['sochira', 'そちら', 'そちら', 'that way', 'pronoun', '➡️', { alt: ['your side', 'there (polite)'] }],
    ['achira', 'あちら', 'あちら', 'that way over there', 'pronoun', '↗️', { alt: ['over there (polite)'] }],
    ['dochira', 'どちら', 'どちら', 'which way', 'pronoun', '🧭', { alt: ['where (polite)', 'which one', 'which of the two'] }],
    ['irasshaimase', 'いらっしゃいませ', 'いらっしゃいませ', 'welcome (to a shop)', 'expression', '🏮', { alt: ['welcome'] }],
    ['onegaishimasu', 'お願いします', 'おねがいします', 'please (a request)', 'expression', '🙏', { alt: ['please', 'I would like'] }],
    ['chaya', '茶屋', 'ちゃや', 'tea house', 'noun', '🫖', { alt: ['teahouse'] }],
    ['dango', '団子', 'だんご', 'dumpling', 'noun', '🍡', { alt: ['dango', 'rice dumpling'] }],
    ['sensu', '扇子', 'せんす', 'folding fan', 'noun', '🪭', { alt: ['fan'] }],
    ['kimono', '着物', 'きもの', 'kimono', 'noun', '👘', { alt: ['traditional clothes'] }],
    ['okyakusan', 'お客さん', 'おきゃくさん', 'customer', 'noun', '🧑‍💼', { alt: ['guest', 'visitor'] }],

    // ── Likes, Wants and Skills, and the people of the castle town
    ['kirai', '嫌い', 'きらい', 'disliked', 'na-adj', '👎', { alt: ['dislike', 'hate', 'hated'] }],
    ['jouzu', '上手', 'じょうず', 'skilful', 'na-adj', '🎯', { alt: ['good at', 'skilled', 'skillful'] }],
    ['heta', '下手', 'へた', 'unskilful', 'na-adj', '🙈', { alt: ['bad at', 'poor at', 'unskillful', 'clumsy'] }],
    ['hoshii', '欲しい', 'ほしい', 'wanted', 'i-adj', '🎁', { alt: ['want', 'desired'] }],
    ['daisuki', '大好き', 'だいすき', 'loved', 'na-adj', '💖', { alt: ['love', 'really like', 'favourite', 'favorite'] }],
    ['isshoni', 'いっしょに', 'いっしょに', 'together', 'adverb', '👫', { alt: ['together with', 'with (someone)'] }],
    ['zehi', 'ぜひ', 'ぜひ', 'by all means', 'adverb', '✨', { alt: ['definitely', 'certainly', 'please do'] }],
    ['mochiron', 'もちろん', 'もちろん', 'of course', 'adverb', '👍', { alt: ['certainly', 'naturally', 'sure'] }],
    ['samurai', '侍', 'さむらい', 'samurai', 'noun', '🎎', { alt: ['warrior', 'retainer'] }],
    ['tono', '殿', 'との', 'lord', 'noun', '👑', { alt: ['my lord', 'feudal lord'] }],
    ['katana', '刀', 'かたな', 'katana', 'noun', '🗡️', { alt: ['sword', 'samurai sword'] }],
    ['shibai', '芝居', 'しばい', 'play', 'noun', '🎭', { alt: ['theatre', 'theater', 'drama', 'show'] }],
    ['odori', '踊り', 'おどり', 'dance', 'noun', '💃', { alt: ['dancing'] }],
    ['doujou', '道場', 'どうじょう', 'dojo', 'noun', '🥋', { alt: ['training hall'] }],
    ['niwa', '庭', 'にわ', 'garden', 'noun', '🪴', { alt: ['yard'] }],

    // ── Gifts and Courtesy: giving, receiving, lending, and keigo
    ['ageru', 'あげる', 'あげる', 'give', 'verb', '🎁', { masu: 'あげます', alt: ['to give', 'give away'] }],
    ['kureru', 'くれる', 'くれる', 'give me', 'verb', '🤲', { masu: 'くれます', alt: ['give to me', 'give (to me)', 'give (to us)'] }],
    ['morau', 'もらう', 'もらう', 'receive', 'verb', '📥', { masu: 'もらいます', alt: ['get', 'to receive', 'be given'] }],
    ['oshieru', '教える', 'おしえる', 'teach', 'verb', '🧑‍🏫', { masu: '教えます', alt: ['to teach', 'tell', 'show'] }],
    ['kasu', '貸す', 'かす', 'lend', 'verb', '🤝', { masu: '貸します', alt: ['to lend', 'loan'] }],
    ['kariru', '借りる', 'かりる', 'borrow', 'verb', '🫴', { masu: '借ります', alt: ['to borrow', 'rent'] }],
    ['au', '会う', 'あう', 'meet', 'verb', '👋', { masu: '会います', alt: ['to meet', 'see (a person)'] }],
    ['annaisuru', '案内する', 'あんないする', 'guide', 'verb', '🧭', { masu: '案内します', alt: ['to guide', 'show around', 'show the way'] }],
    ['shitsureishimasu', '失礼します', 'しつれいします', 'excuse me (for intruding)', 'expression', '🚪', { alt: ['excuse me', 'pardon me', 'sorry to disturb you'] }],
    ['douzo', 'どうぞ', 'どうぞ', 'please, go ahead', 'expression', '🫱', { alt: ['here you are', 'go ahead', 'please'] }],
    ['youkoso', 'ようこそ', 'ようこそ', 'welcome', 'expression', '🎉', { alt: ['welcome!'] }],
    ['omiyage', 'お土産', 'おみやげ', 'souvenir', 'noun', '🧧', { alt: ['gift', 'present'] }],
    ['irassharu', 'いらっしゃる', 'いらっしゃる', 'be, come, go (respectful)', 'verb', '🙇', { masu: 'いらっしゃいます', alt: ['to be (respectful)', 'come (respectful)', 'go (respectful)'] }],
    ['meshiagaru', 'めしあがる', 'めしあがる', 'eat, drink (respectful)', 'verb', '🍱', { masu: 'めしあがります', alt: ['eat (respectful)', 'drink (respectful)'] }],
    ['ossharu', 'おっしゃる', 'おっしゃる', 'say (respectful)', 'verb', '🗣️', { masu: 'おっしゃいます', alt: ['to say (respectful)', 'speak (respectful)'] }],
  ],

  grammar: [
    { id: 'kosoado-place', region: 8, jp: 'ここ・そこ・あそこ・どこ', say: 'koko, soko, asoko, doko', en: 'here (near me), there (near you), over there (far from us both), where?', example: { jp: 'ちゃやは あそこです。', en: 'The tea house is over there.' } },
    { id: 'kono-sono-ano', region: 8, jp: 'この〜・その〜・あの〜・どの〜', say: 'kono, sono, ano, dono', en: 'this / that / that over there / which — always followed by a noun', example: { jp: 'この せんすを ください。', en: 'This fan, please.' } },
    { id: 'kochira-polite', region: 8, jp: 'こちら・そちら・あちら・どちら', say: 'kochira, sochira, achira, dochira', en: 'the polite way to say this way / that way / over there / which way (also: this person, which of two)', example: { jp: 'こちらへ どうぞ。', en: 'This way, please.' } },
    { id: 'wo-ni-magaru', region: 8, jp: '〜を〜に まがる', say: 'o … ni magaru', en: 'the corner you go round takes を, the way you turn takes に', example: { jp: 'かどを ひだりに まがります。', en: 'I turn left at the corner.' } },
    { id: 'no-ichi', region: 8, jp: '〜の となり／まえ／うしろ', say: 'no tonari / mae / ushiro', en: 'next to / in front of / behind ~: the place word comes after の', example: { jp: 'みせは もんの まえに あります。', en: 'The shop is in front of the gate.' } },
    { id: 'wa-arimasu-ka', region: 8, jp: '〜は ありますか', say: 'wa arimasu ka', en: 'do you have ~? (asking in a shop)', example: { jp: 'だんごは ありますか。', en: 'Do you have dango?' } },
    { id: 'ni-shimasu', region: 8, jp: '〜に します', say: 'ni shimasu', en: 'I’ll take ~ / I’ve decided on ~', example: { jp: 'じゃあ、この きものに します。', en: 'Then I’ll take this kimono.' } },
    { id: 'wo-onegaishimasu', region: 8, jp: '〜を おねがいします', say: 'o onegai shimasu', en: '~, please: a polite request or order', example: { jp: 'おちゃを おねがいします。', en: 'Tea, please.' } },
    { id: 'ga-suki', region: 8, jp: '〜が 好き／きらい／上手／下手', say: 'ga suki / kirai / jōzu / heta', en: 'what you like, dislike, or are good or bad at takes が, not を (praise others with 上手, not yourself)', example: { jp: 'わたしは おどりが へたです。', en: 'I’m bad at dancing.' } },
    { id: 'ga-hoshii', region: 8, jp: '〜が ほしい', say: 'ga hoshii', en: 'want (a thing): the thing takes が; for wanting to do something, use 〜たい', example: { jp: 'あたらしい せんすが ほしいです。', en: 'I want a new fan.' } },
    { id: 'masen-ka', region: 8, jp: '〜ませんか', say: 'masen ka', en: 'won’t you ~? A gentle invitation', example: { jp: 'いっしょに しばいを みませんか。', en: 'Won’t you watch the play with me?' } },
    { id: 'mashou-ka', region: 8, jp: '〜ましょうか', say: 'mashō ka', en: 'shall we ~? / shall I ~? Suggesting, or offering to help', example: { jp: 'にもつを もちましょうか。', en: 'Shall I carry your bags?' } },
    { id: 'ageru-kureru', region: 8, jp: 'あげる・くれる', say: 'ageru, kureru', en: 'both mean give: あげる when it goes away from me, くれる when someone gives to me (or my side)', example: { jp: 'ともだちが わたしに だんごを くれました。', en: 'My friend gave me dango.' } },
    { id: 'ni-morau', region: 8, jp: '〜に／から もらう', say: 'ni / kara morau', en: 'receive from ~: the giver takes に or から', example: { jp: 'せんせいに ほんを もらいました。', en: 'I got a book from the teacher.' } },
    { id: 'sonkeigo', region: 8, jp: 'いらっしゃる・めしあがる・おっしゃる', say: 'irassharu, meshiagaru, ossharu', en: 'respectful verbs raise the other person: for いる/くる/いく, たべる/のむ, and いう. Never use them for yourself', example: { jp: 'との、なにを めしあがりますか。', en: 'My lord, what will you have?' } },
    { id: 'kenjougo', region: 8, jp: 'まいります・おります・いたします', say: 'mairimasu, orimasu, itashimasu', en: 'humble verbs lower yourself: for いきます/きます, います, and します', example: { jp: 'すぐに まいります。', en: 'I’ll come right away.' } },
    { id: 'o-kudasai', region: 8, jp: 'お〜ください', say: 'o … kudasai', en: 'a very polite request: お + verb stem + ください', example: { jp: 'こちらで おまちください。', en: 'Please wait here.' } },
  ],

  sentences: [
    { id: 'c1', en: 'Turn right at the corner.', tokens: ['角', 'を', '右', 'に', '曲がります'], distractors: ['で', '左'], region: 8, hint: 'The corner you go round takes を; the direction you turn takes に.' },
    { id: 'c2', en: 'The tea house is next to the gate.', tokens: ['茶屋', 'は', '門', 'の', 'となり', 'です'], distractors: ['に', 'うしろ'], region: 8, hint: 'Gate の next-to: の links the place to となり.' },
    { id: 'c3', en: 'Where is the castle?', tokens: ['城', 'は', 'どこ', 'ですか'], distractors: ['どの', 'を'], region: 8, hint: 'どこ asks for a place. どの needs a noun after it.' },
    { id: 'c4', en: 'I go straight along this street.', tokens: ['この', '通り', 'を', 'まっすぐ', '行きます'], distractors: ['ここ', 'に'], region: 8, hint: 'この goes straight before a noun; ここ stands alone. The street you go along takes を.' },
    { id: 'c5', en: 'I’ll take this fan.', tokens: ['この', '扇子', 'に', 'します'], distractors: ['を', 'あの'], region: 8, hint: 'Deciding on something: 〜に します.' },
    { id: 'c6', en: 'Do you have dango?', tokens: ['団子', 'は', 'ありますか'], distractors: ['を', 'いますか'], region: 8, hint: 'Things use あります; ask with 〜は ありますか.' },
    { id: 'c7', en: 'Tea, please.', tokens: ['お茶', 'を', 'お願いします'], distractors: ['に', 'が'], region: 8, hint: 'What you ask for takes を, then お願いします.' },
    { id: 'c8', en: 'I like dango.', tokens: ['私', 'は', '団子', 'が', '好き', 'です'], distractors: ['を', '嫌い'], region: 8, hint: '好き takes が for the thing you like.' },
    { id: 'c9', en: 'My friend is good at dancing.', tokens: ['友達', 'は', '踊り', 'が', '上手', 'です'], distractors: ['を', '下手'], region: 8, hint: '上手 (good at) also takes が.' },
    { id: 'c10', en: 'I want a kimono.', tokens: ['私', 'は', '着物', 'が', '欲しい', 'です'], distractors: ['を', '好き'], region: 8, hint: 'ほしい: the thing you want takes が.' },
    { id: 'c11', en: 'Won’t you go to the tea house with me?', tokens: ['いっしょに', '茶屋', 'に', '行きませんか'], alts: [['いっしょに', '茶屋', 'へ', '行きませんか'], ['茶屋', 'に', 'いっしょに', '行きませんか']], distractors: ['を', '行きました'], region: 8, hint: 'An invitation: 〜ませんか.' },
    { id: 'c12', en: 'I gave my friend a fan.', tokens: ['私', 'は', '友達', 'に', '扇子', 'を', 'あげました'], distractors: ['くれました', 'が'], region: 8, hint: 'Giving away from me: あげる. The person who receives takes に.' },
    { id: 'c13', en: 'My friend gave me dango.', tokens: ['友達', 'が', '私', 'に', '団子', 'を', 'くれました'], distractors: ['あげました', 'で'], region: 8, hint: 'Someone giving to me: くれる.' },
    { id: 'c14', en: 'I received a book from the teacher.', tokens: ['先生', 'に', '本', 'を', 'もらいました'], alts: [['先生', 'から', '本', 'を', 'もらいました']], distractors: ['くれました', 'で'], region: 8, hint: 'もらう: the giver takes に or から.' },
    { id: 'c15', en: 'I borrow an umbrella from a friend.', tokens: ['友達', 'に', '傘', 'を', '借ります'], alts: [['友達', 'から', '傘', 'を', '借ります']], distractors: ['貸します', 'で'], region: 8, hint: 'Borrowing is 借ります; lending is 貸します.' },
    { id: 'c16', en: 'The lord is in the castle.', tokens: ['殿', 'は', '城', 'に', 'いらっしゃいます'], distractors: ['を', 'まいります'], region: 8, hint: 'Raise the lord with いらっしゃる; まいる is for lowering yourself.' },
    { id: 'c17', en: 'Please wait here.', tokens: ['ここ', 'で', 'お待ちください'], distractors: ['に', '待ちます'], region: 8, hint: 'A very polite request: お + stem + ください.' },
  ],

  runes: [
    { id: 'c-r1', jp: '角を左に曲がります', reading: 'かどをひだりにまがります', answer: 'Turn left at the corner.', wrong: ['Turn right at the corner.', 'Go straight past the corner.'], region: 8 },
    { id: 'c-r2', jp: '茶屋は橋のとなりです', reading: 'ちゃやははしのとなりです', answer: 'The tea house is next to the bridge.', wrong: ['The tea house is behind the bridge.', 'The bridge is in front of the tea house.'], region: 8 },
    { id: 'c-r3', jp: '団子はありますか', reading: 'だんごはありますか', answer: 'Do you have dango?', wrong: ['Where are the dango?', 'I’ll take the dango.'], region: 8 },
    { id: 'c-r4', jp: '私は踊りが下手です', reading: 'わたしはおどりがへたです', answer: 'I am bad at dancing.', wrong: ['I like dancing.', 'I am good at dancing.'], region: 8 },
    { id: 'c-r5', jp: 'いっしょにお茶を飲みませんか', reading: 'いっしょにおちゃをのみませんか', answer: 'Won’t you have tea with me?', wrong: ['I don’t drink tea with anyone.', 'Shall I make the tea?'], region: 8 },
    { id: 'c-r6', jp: '先生に本をもらいました', reading: 'せんせいにほんをもらいました', answer: 'I received a book from the teacher.', wrong: ['I gave the teacher a book.', 'The teacher borrowed my book.'], region: 8 },
    { id: 'c-r7', jp: '殿は庭にいらっしゃいます', reading: 'とのはにわにいらっしゃいます', answer: 'The lord is in the garden.', wrong: ['The lord is in the castle.', 'The lord dislikes the garden.'], region: 8 },
    { id: 'c-r8', jp: 'こちらへどうぞ', reading: 'こちらへどうぞ', answer: 'This way, please.', wrong: ['Over there, please.', 'Which way is it?'], region: 8 },
    { id: 'c-r9', jp: 'この扇子が欲しいです', reading: 'このせんすがほしいです', answer: 'I want this fan.', wrong: ['I like that fan over there.', 'Please lend me this fan.'], region: 8 },
  ],

  readings: {
    行きませんか: 'いきませんか',
    行きました: 'いきました',
    お待ちください: 'おまちください',
  },

  npcs: [
    {
      id: 'kiku',
      name: 'Kiku of the Tea House',
      jp: 'ちゃやの キク',
      emoji: '🍡',
      region: 8,
      personality: 'Elegant, quick-witted mistress of the Kikuya tea house by the canal. Proud of her dango and of her manners; the yokai’s curse keeps making her snap at customers, and she is mortified every time.',
      politeness: 'polite',
      color: '#d9534f',
      interests: ['tea and dango', 'gossip from the castle', 'kabuki actors', 'the seasons in the castle garden'],
      greeting: { jp: 'いらっしゃいませ！', en: 'Welcome!' },
    },
    {
      id: 'ochiyo',
      name: 'Ochiyo the Traveller',
      jp: 'たびびとの おちよ',
      emoji: '🧳',
      region: 8,
      personality: 'A cheerful young traveller from the hot-spring road, visiting the castle town for the first time. Easily lost, always grateful, carries far too many souvenirs.',
      politeness: 'polite',
      color: '#f2a7c3',
      interests: ['sightseeing', 'souvenirs', 'kabuki', 'where to eat'],
      greeting: { jp: 'あのう、すみません…', en: 'Um, excuse me…' },
    },
    {
      id: 'tadashi',
      name: 'Tadashi the Retainer',
      jp: 'けらいの ただし',
      emoji: '🗡️',
      region: 8,
      personality: 'A stiff, earnest young samurai who guards the castle gate for his lord. Honour is everything to him; he expects respectful speech about the lord and humble speech about yourself, and he blushes when praised.',
      politeness: 'formal',
      color: '#7a8bd9',
      interests: ['his lord', 'swordsmanship', 'proper manners', 'the castle garden'],
      greeting: { jp: 'とまれ！ なにものだ！', en: 'Halt! Who goes there?' },
    },
  ],

  scenarios: [
    {
      id: 'castletown-teahouse',
      npcId: 'kiku',
      region: 8,
      translations: 'always',
      start: 'greet',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Kiku runs the Kikuya tea house. Today she is fighting the curse with all her might: help her by being the politest customer in town.',
        'Choose seats with こちら / あちら, order with 〜を おねがいします, ask with 〜は ありますか, and decide with 〜に します.',
        'Wrong answers cost a ❤️.',
      ],
      nodes: {
        greet: {
          id: 'greet',
          line: { jp: 'いらっしゃいませ！ きくやへ ようこそ。', en: 'Welcome! Welcome to Kikuya.' },
          wordIds: ['irasshaimase', 'youkoso'],
          hint: 'Greet her as a guest. いらっしゃいませ is what the shop says, not the customer.',
          next: 'seat',
          options: [
            { jp: 'しつれいします。', en: 'Excuse me (as I come in).', correct: true, wordIds: ['shitsureishimasu'], reply: { jp: 'まあ、ごていねいに。', en: 'Oh, how polite.' }, effects: { trust: 1 } },
            { jp: 'こんにちは。', en: 'Hello.', correct: true, wordIds: ['konnichiwa'], reply: { jp: 'こんにちは！', en: 'Hello!' } },
            { jp: 'いらっしゃいませ。', en: 'Welcome (to my shop).', correct: false, wordIds: ['irasshaimase'], reply: { jp: 'あら、あなたも おみせの ひと？', en: 'Oh? Do you work here too?' }, note: 'いらっしゃいませ is said by shop staff to customers. As a guest, say しつれいします or こんにちは.' },
          ],
        },
        seat: {
          id: 'seat',
          line: { jp: 'こちらの せきと あちらの せき、どちらが いいですか。', en: 'This seat here, or that one over there: which would you like?' },
          wordIds: ['kochira', 'achira', 'dochira'],
          hint: 'Answer with the seat you want and 〜に します.',
          next: 'menu',
          options: [
            { jp: 'こちらに します。', en: 'I’ll take this one.', correct: true, wordIds: ['kochira'], reply: { jp: 'はい、どうぞ。', en: 'Here you are, please sit.' }, effects: { trust: 1 } },
            { jp: 'あちらに します。', en: 'I’ll take that one over there.', correct: true, wordIds: ['achira'], reply: { jp: 'はい、あちらへ どうぞ。', en: 'Of course, over there, please.' } },
            { jp: 'どちらに します。', en: 'I’ll take which one.', correct: false, wordIds: ['dochira'], reply: { jp: '…え？ どちら？', en: '…Huh? Which one?' }, note: 'どちら asks “which?”. To answer, pick こちら (this one) or あちら (that one over there).' },
          ],
        },
        menu: {
          id: 'menu',
          line: { jp: 'きょうは おちゃと だんごが あります。なにに しますか。', en: 'Today we have tea and dango. What will you have?' },
          wordIds: ['dango', 'ocha'],
          hint: 'Order with 〜を おねがいします.',
          next: 'ask',
          options: [
            { jp: 'だんごを おねがいします。', en: 'Dango, please.', correct: true, wordIds: ['dango', 'onegaishimasu'], reply: { jp: 'はい、よろこんで！', en: 'With pleasure!' }, effects: { trust: 1 } },
            { jp: 'おちゃを おねがいします。', en: 'Tea, please.', correct: true, wordIds: ['ocha', 'onegaishimasu'], reply: { jp: 'はい、すぐに！', en: 'Right away!' } },
            { jp: 'だんごが おねがいします。', en: 'Dango (subject) please.', correct: false, wordIds: ['dango', 'onegaishimasu'], reply: { jp: 'だんごが… おねがい？', en: 'The dango… is asking?' }, note: 'What you ask for takes を: だんごを おねがいします.' },
            { jp: 'だんごを あげます。', en: 'I’ll give you dango.', correct: false, wordIds: ['ageru'], reply: { jp: 'くださるの？ …いいえ、うちの だんごですよ。', en: 'You’re giving me some? …They’re my dango, though.' }, note: 'あげます means you give something away. To order: だんごを おねがいします.' },
          ],
        },
        ask: {
          id: 'ask',
          line: { jp: 'ほかに なにか ありますか。', en: 'Anything else?' },
          wordIds: ['tsumetai', 'ocha'],
          hint: 'Ask whether they have cold tea: 〜は ありますか.',
          next: 'taste',
          options: [
            { jp: 'つめたい おちゃは ありますか。', en: 'Do you have cold tea?', correct: true, wordIds: ['tsumetai', 'ocha', 'aru'], reply: { jp: 'はい、ありますよ。いどの みずで ひやしました。', en: 'Yes, we do. Chilled in well water.' }, effects: { trust: 1 } },
            { jp: 'つめたい おちゃは いますか。', en: 'Is there cold tea (living)?', correct: false, wordIds: ['iru'], reply: { jp: 'おちゃは いきて いませんよ。', en: 'Tea isn’t alive, you know.' }, note: 'います is for living things. For tea, use あります: つめたい おちゃは ありますか.' },
            { jp: 'つめたい おちゃを ありますか。', en: 'Cold tea (object) is there?', correct: false, wordIds: ['aru'], reply: { jp: '…はい？', en: '…Pardon?' }, note: 'あります takes は or が, not を: つめたい おちゃは ありますか.' },
          ],
        },
        taste: {
          id: 'taste',
          line: { jp: 'はい、どうぞ。…おだんご、すきですか。', en: 'Here you are. …Do you like dango?' },
          wordIds: ['douzo', 'suki'],
          hint: '好き and 大好き take が. 上手 means “skilful”.',
          next: 'invite',
          options: [
            { jp: 'はい、だいすきです！', en: 'Yes, I love them!', correct: true, wordIds: ['daisuki'], reply: { jp: 'うれしい！', en: 'That makes me so happy!' }, effects: { trust: 1 } },
            { jp: 'はい、すきです。', en: 'Yes, I like them.', correct: true, wordIds: ['suki'], reply: { jp: 'よかった。', en: 'I’m glad.' } },
            { jp: 'はい、じょうずです。', en: 'Yes, I’m skilful.', correct: false, wordIds: ['jouzu'], reply: { jp: 'じょうず…？ たべるのが？', en: 'Skilful…? At eating them?' }, note: '上手 means skilful. To say you like something: すきです or だいすきです.' },
            { jp: 'いいえ、きらいです。', en: 'No, I hate them.', correct: false, wordIds: ['kirai'], reply: { jp: '…そう ですか。', en: '…I see.' }, effects: { trust: -1 }, note: 'Grammatical, but blunt: きらい is a strong word to say to the cook! A softer no: あまり すきじゃ ないです.' },
          ],
        },
        invite: {
          id: 'invite',
          line: { jp: 'こんや、ぶたいで しばいが あるの。でも、いっしょに いく ひとが いなくて…', en: 'There’s a play on the stage tonight. But I have no one to go with…' },
          wordIds: ['shibai', 'isshoni'],
          hint: 'Invite her: いっしょに 〜ませんか.',
          next: 'bye',
          options: [
            { jp: 'いっしょに 見ませんか。', kana: 'いっしょに みませんか。', en: 'Won’t you watch it with me?', correct: true, wordIds: ['isshoni', 'miru'], reply: { jp: 'まあ！ ぜひ！', en: 'Oh! I’d love to!' }, effects: { trust: 1 } },
            { jp: 'いっしょに 行きましょうか。', kana: 'いっしょに いきましょうか。', en: 'Shall we go together?', correct: true, wordIds: ['isshoni', 'iku'], reply: { jp: 'ええ、もちろん！', en: 'Yes, of course!' } },
            { jp: 'ひとりで 見ませんか。', kana: 'ひとりで みませんか。', en: 'Won’t you watch it alone?', correct: false, wordIds: ['miru'], reply: { jp: '…それが いやなんです。', en: '…That’s exactly what I don’t want.' }, note: 'ひとりで means alone. To invite her: いっしょに 見ませんか.' },
            { jp: 'いっしょに 見たいですか。', kana: 'いっしょに みたいですか。', en: 'Do you want to watch it with me?', correct: false, wordIds: ['miru'], reply: { jp: 'え、ええと…', en: 'Er, um…' }, note: 'Asking someone directly what they want (〜たいですか) sounds pushy in Japanese. Invite with 〜ませんか.' },
          ],
        },
        bye: {
          id: 'bye',
          line: { jp: 'では、こんや ぶたいの まえで。また きて くださいね。', en: 'Then tonight, in front of the stage. Do come again.' },
          hint: 'Thank her and take your leave: ありがとうございました, or しつれいします.',
          next: 'end',
          input: {
            accepted: ['ありがとうございました', 'ありがとうございます', 'しつれいします', '失礼します', 'ごちそうさまでした', 'ありがとうございましたしつれいします'],
            model: 'ありがとうございました',
            modelKana: 'ありがとうございました',
            wrongReply: { jp: 'え？ なんて？', en: 'Hm? What was that?' },
            wrongNote: 'Thank her politely (ありがとうございました) or take your leave (しつれいします).',
            reply: { jp: 'こちらこそ！', en: 'The pleasure was mine!' },
          },
        },
        end: { id: 'end', line: { jp: 'まいど ありがとう ございました！', en: 'Thank you, as always!' }, end: true },
      },
    },
    {
      id: 'castletown-directions',
      npcId: 'ochiyo',
      region: 8,
      translations: 'always',
      start: 'hello',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Ochiyo has just arrived on the hot-spring road and is completely lost. Show her the way.',
        'From this crossroads: the castle is straight ahead. The tea house is on the left, next to the bridge. The dojo is on the right, behind the market. The fan shop is far across the street.',
        'Wrong answers cost a ❤️.',
      ],
      nodes: {
        hello: {
          id: 'hello',
          line: { jp: 'あのう、すみません。', en: 'Um, excuse me.' },
          wordIds: ['sumimasen'],
          hint: 'Answer kindly: はい、なんですか.',
          next: 'castle',
          options: [
            { jp: 'はい、なんですか。', en: 'Yes, what is it?', correct: true, reply: { jp: 'よかった！ みちに まよって しまって…', en: 'Thank goodness! I’m lost…' }, effects: { trust: 1 } },
            { jp: 'はい、どうしましたか。', en: 'Yes, is something wrong?', correct: true, reply: { jp: 'みちが わからなくて…', en: 'I don’t know the way…' } },
            { jp: 'いらっしゃいませ。', en: 'Welcome (to my shop).', correct: false, wordIds: ['irasshaimase'], reply: { jp: 'え？ ここ、おみせですか？', en: 'Huh? Is this a shop?' }, note: 'いらっしゃいませ is for shop staff greeting customers. Here: はい、なんですか.' },
          ],
        },
        castle: {
          id: 'castle',
          line: { jp: 'おしろは どこですか。', en: 'Where is the castle?' },
          wordIds: ['doko', 'shiro'],
          hint: 'The castle is straight ahead along this street.',
          next: 'teahouse',
          options: [
            { jp: 'この とおりを まっすぐです。', en: 'Straight along this street.', correct: true, wordIds: ['kono', 'toori', 'massugu'], reply: { jp: 'まっすぐ… わかりました！', en: 'Straight ahead… got it!' }, effects: { trust: 1 } },
            { jp: 'かどを みぎに まがって ください。', en: 'Please turn right at the corner.', correct: false, wordIds: ['kado', 'migi', 'magaru'], reply: { jp: 'みぎ…？ あっちは いちばですよ？', en: 'Right…? Isn’t that the market?' }, note: 'Good grammar, wrong way! The castle is straight ahead: まっすぐです.' },
            { jp: 'ここです。', en: 'It’s here.', correct: false, wordIds: ['koko'], reply: { jp: 'ここ…？ おしろは みえませんけど…', en: 'Here…? I don’t see a castle…' }, note: 'ここ means right here, where you are. The castle is straight ahead: この とおりを まっすぐです.' },
          ],
        },
        teahouse: {
          id: 'teahouse',
          line: { jp: 'それから、ちゃやは どちらですか。', en: 'And which way is the tea house?' },
          wordIds: ['chaya', 'dochira'],
          hint: 'The tea house is on the left, next to the bridge.',
          next: 'dojo',
          options: [
            { jp: 'ひだりです。はしの となりです。', en: 'On the left. Next to the bridge.', correct: true, wordIds: ['hidari', 'tonari', 'hashi'], reply: { jp: 'はしの となり、ですね。', en: 'Next to the bridge, right.' }, effects: { trust: 1 } },
            { jp: 'みぎです。もんの まえです。', en: 'On the right. In front of the gate.', correct: false, wordIds: ['migi', 'mae', 'mon'], reply: { jp: 'もんの まえ？ ほんとうに？', en: 'In front of the gate? Really?' }, note: 'Check the town plan: the tea house is on the left (ひだり), next to (となり) the bridge.' },
            { jp: 'ひだりです。はしの うしろです。', en: 'On the left. Behind the bridge.', correct: false, wordIds: ['hidari', 'ushiro'], reply: { jp: 'はしの うしろ… かわの なか？', en: 'Behind the bridge… in the river?' }, note: 'うしろ is behind. The tea house is next to (となり) the bridge.' },
          ],
        },
        dojo: {
          id: 'dojo',
          line: { jp: 'どうじょうも 見たいです。どうじょうは？', en: 'I’d like to see the dojo too. And the dojo?' }, kana: 'どうじょうも みたいです。どうじょうは？',
          wordIds: ['doujou'],
          hint: 'The dojo is on the right, behind the market.',
          next: 'shop',
          options: [
            { jp: 'みぎです。いちばの うしろです。', en: 'On the right. Behind the market.', correct: true, wordIds: ['migi', 'ushiro'], reply: { jp: 'いちばの うしろ。ありがとう！', en: 'Behind the market. Thank you!' }, effects: { trust: 1 } },
            { jp: 'みぎです。いちばの まえです。', en: 'On the right. In front of the market.', correct: false, wordIds: ['mae'], reply: { jp: 'まえ？ うしろ？', en: 'In front? Behind?' }, note: 'まえ is in front. The dojo is behind (うしろ) the market.' },
            { jp: 'ひだりです。いちばの となりです。', en: 'On the left. Next to the market.', correct: false, wordIds: ['hidari', 'tonari'], reply: { jp: 'ひだりは ちゃやでしたよね？', en: 'Wasn’t the tea house on the left?' }, note: 'The dojo is on the right (みぎ), behind (うしろ) the market.' },
          ],
        },
        shop: {
          id: 'shop',
          line: { jp: '（とおくの みせを ゆびさして）あの みせは なんの みせですか。', en: '(Pointing at a shop far across the street) What kind of shop is that one over there?' },
          wordIds: ['ano', 'sensu'],
          hint: 'The shop is far from both of you: あの. It sells fans.',
          next: 'thanks',
          options: [
            { jp: 'あの みせは せんすの みせです。', en: 'That shop over there is a fan shop.', correct: true, wordIds: ['ano', 'sensu', 'mise'], reply: { jp: 'せんす！ ひとつ ほしいです！', en: 'Fans! I want one!' }, effects: { trust: 1 } },
            { jp: 'この みせは せんすの みせです。', en: 'This shop (right here) is a fan shop.', correct: false, wordIds: ['kono'], reply: { jp: 'この みせ？ ここは だんごやですよ。', en: 'This shop? We’re standing at a dango shop.' }, note: 'この is for things near you. The shop is far from you both: あの みせ.' },
            { jp: 'どの みせは せんすの みせです。', en: 'Which shop is a fan shop.', correct: false, wordIds: ['dono'], reply: { jp: '…しつもん ですか？', en: '…Is that a question?' }, note: 'どの asks “which”. To point far away: あの みせ.' },
          ],
        },
        thanks: {
          id: 'thanks',
          line: { jp: 'ほんとうに ありがとう ございました。これ、ゆの さとの おみやげです。どうぞ！', en: 'Thank you so much. This is a souvenir from the hot-spring village. Please, take it!' },
          wordIds: ['omiyage', 'douzo'],
          hint: 'Receive the gift with thanks.',
          next: 'end',
          options: [
            { jp: 'いいんですか。ありがとうございます！', en: 'Are you sure? Thank you very much!', correct: true, wordIds: ['arigatou'], reply: { jp: 'もちろん！', en: 'Of course!' }, effects: { trust: 1 } },
            { jp: 'ありがとうございます。', en: 'Thank you very much.', correct: true, wordIds: ['arigatou'], reply: { jp: 'どういたしまして。', en: 'You’re welcome.' } },
            { jp: 'はい、あげます。', en: 'Yes, I’ll give it (to you).', correct: false, wordIds: ['ageru'], reply: { jp: 'え？ わたしが あげたんですよ？', en: 'Huh? I’m the one giving it to you.' }, note: 'She is giving the gift to you. Just thank her: ありがとうございます.' },
          ],
        },
        end: { id: 'end', line: { jp: 'では、おしろへ いって きます！', en: 'Well then, off to the castle!' }, end: true },
      },
    },
    {
      id: 'castletown-retainer',
      npcId: 'tadashi',
      region: 8,
      translations: 'hint',
      start: 'halt',
      hearts: 4,
      startTrust: 3,
      trustMax: 8,
      jail: { threshold: 0, node: 'jail' },
      intro: [
        'Tadashi guards the castle gate for his lord. Under the yokai’s curse he can barely stay polite, so you must be polite for two.',
        'Raise the lord with respectful verbs (いらっしゃる, めしあがる, おっしゃる). Lower yourself with humble ones (まいります, おります, いたします).',
        'Rude answers lower his trust 🗡️. If it hits zero, you’ll be sent to sit in the guardhouse!',
      ],
      nodes: {
        halt: {
          id: 'halt',
          line: { jp: 'とまれ！ なにものだ！', en: 'Halt! Who goes there?' },
          hint: 'Introduce yourself politely: はじめまして…',
          next: 'business',
          options: [
            { jp: 'はじめまして。{name}です。よろしく おねがいします。', en: 'How do you do. I’m {name}. Pleased to meet you.', correct: true, tone: 'polite', wordIds: ['onegaishimasu'], effects: { trust: 1 }, reply: { jp: 'む… れいぎ ただしいな。', en: 'Hm… well-mannered.' } },
            { jp: '{name}と もうします。', en: 'My name is {name} (humble).', correct: true, tone: 'polite', reply: { jp: 'うむ。', en: 'Mm.' } },
            { jp: 'おれは {name}だ。', en: 'I’m {name}, see.', correct: false, tone: 'casual', effects: { trust: -1 }, reply: { jp: '…ことばに きを つけよ。', en: '…Mind your words.' }, note: 'おれ and plain だ are rough. Introduce yourself with はじめまして… です.' },
            { jp: 'だれでも いいでしょう。', en: 'Who cares who I am?', correct: false, tone: 'rude', effects: { trust: -2 }, reply: { jp: 'ぶれいな！', en: 'How rude!' }, note: 'Never brush off a guard. はじめまして。〜です.' },
          ],
        },
        business: {
          id: 'business',
          line: { jp: 'なんの ようだ。', en: 'What is your business?' },
          wordIds: ['tono', 'au'],
          hint: 'You have come to see the lord. Lower yourself with まいりました.',
          next: 'from',
          options: [
            { jp: '殿に 会いに まいりました。', kana: 'とのに あいに まいりました。', en: 'I have come to see the lord (humble).', correct: true, tone: 'polite', wordIds: ['tono', 'au'], effects: { trust: 1 }, reply: { jp: 'ほう、けんじょうごが つかえるのか。', en: 'Oh, you can speak humbly.' } },
            { jp: '殿に 会いに 来ました。', kana: 'とのに あいに きました。', en: 'I came to see the lord.', correct: true, tone: 'polite', wordIds: ['tono', 'au'], reply: { jp: 'うむ。', en: 'Mm.' } },
            { jp: '殿に 会いに いらっしゃいました。', kana: 'とのに あいに いらっしゃいました。', en: 'I (honourably) came to see the lord.', correct: false, tone: 'casual', wordIds: ['irassharu'], effects: { trust: -1 }, reply: { jp: 'じぶんに けいごを つかう やつが あるか！', en: 'Who uses honorifics about themselves?!' }, note: 'いらっしゃる raises the other person. Never use it for yourself: say まいりました.' },
            { jp: '殿は どこ？', kana: 'とのは どこ？', en: 'Where’s the lord?', correct: false, tone: 'casual', effects: { trust: -1 }, reply: { jp: '…なんだ、その ききかたは。', en: '…What kind of way to ask is that?' }, note: 'Far too casual. Say 殿に 会いに まいりました.' },
          ],
        },
        from: {
          id: 'from',
          line: { jp: 'どこから 来た。', en: 'Where have you come from?' }, kana: 'どこから きた。',
          hint: 'You came from the hot-spring village (ゆの さと). Humble: まいりました.',
          next: 'lord-eat',
          options: [
            { jp: 'ゆの さとから まいりました。', en: 'I have come from the hot-spring village (humble).', correct: true, tone: 'polite', effects: { trust: 1 }, reply: { jp: 'とおくから、ごくろう。', en: 'A long way. Well done.' } },
            { jp: 'ゆの さとから 来ました。', kana: 'ゆの さとから きました。', en: 'I came from the hot-spring village.', correct: true, tone: 'polite', wordIds: ['kuru'], reply: { jp: 'うむ。', en: 'Mm.' } },
            { jp: 'ゆの さとから いらっしゃいました。', en: 'I (honourably) came from the hot-spring village.', correct: false, tone: 'casual', wordIds: ['irassharu'], effects: { trust: -1 }, reply: { jp: 'また じぶんを あげて おる！', en: 'Raising yourself up again!' }, note: 'いらっしゃる is for others. For yourself: まいりました (humble) or 来ました.' },
            { jp: 'ゆの さとから 来たよ。', kana: 'ゆの さとから きたよ。', en: 'Came from the hot springs, y’know.', correct: false, tone: 'casual', effects: { trust: -1 }, reply: { jp: '…よ？', en: '…“Y’know”?' }, note: 'Plain 来たよ is casual. Say まいりました or 来ました.' },
          ],
        },
        'lord-eat': {
          id: 'lord-eat',
          line: { jp: '殿は おなかを すかせて いらっしゃる。この だんごを さしあげたい。殿に なんと いう？', en: 'The lord is hungry. I wish to offer him these dango. What would you say to the lord?' }, kana: 'とのは おなかを すかせて いらっしゃる。この だんごを さしあげたい。とのに なんと いう？',
          wordIds: ['meshiagaru', 'dango'],
          hint: 'Use the respectful verb for eating: めしあがりますか.',
          next: 'lord-said',
          options: [
            { jp: '殿、おだんごを めしあがりますか。', kana: 'との、おだんごを めしあがりますか。', en: 'My lord, will you have some dango?', correct: true, tone: 'polite', wordIds: ['tono', 'meshiagaru'], effects: { trust: 1 }, reply: { jp: 'みごとだ。', en: 'Splendid.' } },
            { jp: '殿、おだんごを どうぞ。', kana: 'との、おだんごを どうぞ。', en: 'My lord, please have some dango.', correct: true, tone: 'polite', wordIds: ['tono', 'douzo'], reply: { jp: 'うむ、よい。', en: 'Mm, good.' } },
            { jp: '殿、だんご たべる？', kana: 'との、だんご たべる？', en: 'Lord, wanna eat dango?', correct: false, tone: 'rude', wordIds: ['taberu'], effects: { trust: -2 }, reply: { jp: 'なっ…！', en: 'Wha…!' }, note: 'Plain たべる to a lord is shocking. Use the respectful verb: めしあがりますか.' },
            { jp: '殿、おだんごを いただきますか。', kana: 'との、おだんごを いただきますか。', en: 'My lord, will you (humbly) receive dango?', correct: false, tone: 'casual', effects: { trust: -1 }, reply: { jp: 'いただく は じぶんが たべる ときの ことばだ。', en: 'いただく is for when YOU eat.' }, note: 'いただく is humble: it lowers the eater. For the lord, use めしあがる.' },
          ],
        },
        'lord-said': {
          id: 'lord-said',
          line: { jp: '…いま、おくから 殿の こえが した。殿は なんと？', en: '…Just now, the lord’s voice came from within. What did the lord say?' }, kana: '…いま、おくから とのの こえが した。とのは なんと？',
          wordIds: ['ossharu'],
          hint: 'Report the lord’s words with the respectful verb: おっしゃいました.',
          next: 'offer',
          options: [
            { jp: '殿は「ありがとう」と おっしゃいました。', kana: 'とのは「ありがとう」と おっしゃいました。', en: 'The lord said “thank you” (respectful).', correct: true, tone: 'polite', wordIds: ['tono', 'ossharu', 'arigatou'], effects: { trust: 1 }, reply: { jp: '殿が… そう おっしゃったか。', en: 'The lord… said that?' } },
            { jp: '殿は「ありがとう」と 言ったよ。', kana: 'とのは「ありがとう」と いったよ。', en: 'The lord said “thanks”, y’know.', correct: false, tone: 'casual', effects: { trust: -1 }, reply: { jp: '言った、だと？', en: '“Said”, you say?' }, note: 'For the lord’s words, use the respectful おっしゃいました.' },
            { jp: '殿は「ありがとう」と もうしました。', kana: 'とのは「ありがとう」と もうしました。', en: 'The lord said “thank you” (humble).', correct: false, tone: 'casual', effects: { trust: -1 }, reply: { jp: '殿を さげて どうする！', en: 'Why are you lowering the lord?!' }, note: 'もうす is humble: it is for your own words. The lord’s words: おっしゃいました.' },
          ],
        },
        offer: {
          id: 'offer',
          line: { jp: 'もんを あける。…この ちょうちんは おもいな。', en: 'I shall open the gate. …This lantern is heavy.' },
          wordIds: ['mon'],
          hint: 'Offer to carry it yourself: 〜ましょうか.',
          next: 'leave',
          options: [
            { jp: 'わたしが もちましょうか。', en: 'Shall I carry it?', correct: true, tone: 'polite', effects: { trust: 1 }, reply: { jp: 'かたじけない。', en: 'Much obliged.' } },
            { jp: 'てつだいましょうか。', en: 'Shall I help?', correct: true, tone: 'polite', reply: { jp: 'たのむ。', en: 'Please.' } },
            { jp: 'ちょうちんを もちませんか。', en: 'Won’t you carry the lantern?', correct: false, tone: 'casual', reply: { jp: '…いま もって おるが？', en: '…I AM carrying it.' }, note: '〜ませんか invites the other person to do it. To offer to do it yourself: もちましょうか.' },
          ],
        },
        leave: {
          id: 'leave',
          line: { jp: 'よし、とおれ。…殿を たのむ。', en: 'Very well, pass. …I leave the lord to you.' }, kana: 'よし、とおれ。…とのを たのむ。',
          hint: 'Take your leave very humbly: しつれいいたします.',
          next: 'pass',
          options: [
            { jp: 'しつれい いたします。', en: 'Please excuse me (very humble).', correct: true, tone: 'polite', wordIds: ['shitsureishimasu'], effects: { trust: 1 }, reply: { jp: 'うむ！', en: 'Mm!' } },
            { jp: 'しつれいします。', en: 'Excuse me.', correct: true, tone: 'polite', wordIds: ['shitsureishimasu'] },
            { jp: 'じゃあね！', en: 'See ya!', correct: false, tone: 'casual', effects: { trust: -1 }, reply: { jp: 'じゃあね…？', en: '“See ya”…?' }, note: 'Too casual for a samurai. しつれいいたします.' },
            { jp: 'バイバイ！', en: 'Bye-bye!', correct: false, tone: 'casual', effects: { trust: -1 }, reply: { jp: 'こどもか！', en: 'Are you a child?!' }, note: 'Bye-bye is for friends. しつれいいたします.' },
          ],
        },
        pass: { id: 'pass', line: { jp: 'ぶじを いのって おる。', en: 'I pray for your safety.' }, end: true },

        // ── Guardhouse branch ──
        jail: {
          id: 'jail',
          jail: true,
          line: { jp: 'ぶれいもの！ ばんごやで はんせい せよ！', en: 'Insolent! Go and reflect in the guardhouse!' },
          next: 'jail-1',
        },
        'jail-1': {
          id: 'jail-1',
          jail: true,
          line: { jp: '…なにか いう ことは あるか。', en: '…Have you anything to say?' },
          wordIds: ['sumimasen'],
          hint: 'Apologise formally: もうしわけ ありませんでした.',
          next: 'jail-2',
          options: [
            { jp: 'もうしわけ ありませんでした。', en: 'I am deeply sorry.', correct: true, tone: 'polite', effects: { trust: 1 }, reply: { jp: 'ふむ。', en: 'Hmm.' } },
            { jp: 'たいへん しつれい いたしました。', en: 'I was terribly rude (humble).', correct: true, tone: 'polite', effects: { trust: 1 }, reply: { jp: 'ふむ。', en: 'Hmm.' } },
            { jp: 'ごめんね。', en: 'Sorry~', correct: false, tone: 'casual', reply: { jp: 'ごめんね、だと？', en: '“Sorry~”?' }, note: 'ごめんね is for friends. Say もうしわけ ありませんでした.' },
            { jp: 'しらない。', en: 'Don’t know, don’t care.', correct: false, tone: 'rude', reply: { jp: 'では、ずっと ここに おれ。', en: 'Then stay here forever.' }, note: 'Apologise: もうしわけ ありませんでした.' },
          ],
        },
        'jail-2': {
          id: 'jail-2',
          jail: true,
          onEnter: { setTrust: 2 },
          line: { jp: 'よかろう。もう いちど、ていねいに はなせ。', en: 'Very well. Once more, and speak politely.' },
          next: '$resume',
        },
      },
    },
  ],
}
