/**
 * Region 8 — 城下町, the Castle Town. The main map is a whole Edo town below
 * the castle wall: the moat and the gate bridge, the castle square with the
 * notice board, a long main street hung with red lanterns from the hot-spring
 * road (west) to the snow road (east), a canal under three arched bridges,
 * the kabuki stage, the market, and the dojo yard. Off it: the Kikuya tea
 * house, the merchant guild, the castle garden and, at the top, the keep
 * where Nurarihyon sits in the lord's seat.
 */
import type { MapSpec } from '../../world/types'

const ROOM = { interior: true, particles: 'dust' as const, bg: '#0b0a14', tint: 'rgba(255, 170, 90, 0.10)' }

export const CASTLETOWN: MapSpec = {
  id: 'castletown',
  name: 'The Castle Town',
  jp: '城下町',
  region: 8,
  music: 'castletown',
  particles: 'sakura',
  tint: 'rgba(255, 140, 110, 0.10)',
  rows: [
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PPBPPPPBBPBBPPPPPBPPPPPBPP^^^^^^^^^^^^PBBBPPPBPPPPPPPPPPPBPPPPPP',
    'PPPBPPBBPPBPPBBPPBPBPBPPPP^^^^^^^^^^^^PPPPPPPPPPPPBBPPPBPPBPPBPP',
    'PPPPPPPPXXXXXXXXXXXXXXXXXXAAAAAAAAAAAAXXXXXXXXXXXXXXXXXXBBPBPPPP',
    'PPPPPPPPXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXPPPPPPPP',
    'PPPPPPPPXXXXXXXXXXXXXXXXXXXXXXN00NXXXXXXXXXXXXXXXXXXXXXXPPPPPPPP',
    'PPWWWWWWWWWWWWWWWWWWWWWWWWWWWWW||WWWWWWWWWWWWWWWWWWWWWWWWWWWWWPP',
    'PPWWWWWWWWWWWWWWWWWWWWWWWWWWWWW||WWWWWWWWWWWWWWWWWWWWWWWWWWWWWPP',
    'PPWWWWWWWWWWWWWWWWWWWWWWWWWWWWW||WWWWWWWWWWWWWWWWWWWWWWWWWWWWWPP',
    'PPWWWWWWWWWWWWWWWWWWWWWWWWWWWWW||WWWWWWWWWWWWWWWWWWWWWWWWWWWWWPP',
    'PPnnnnnnnnnnnnnnnnnnnnnnnnnnnNnznnNnnnnnnnnn~~~nnnnnnnnnnnnnnnPP',
    'PPnnnnnn\'nnnnnnnnnnnUnnn2nnnγnnnnnn]nnnnndnn---nnnnnnnnnnnnn$nPP',
    'PPnnKnnnnnnnnnnKnnnnnnnnnnnnnnnnnnnnnnKnnnnn~~~nnnnnKnnnnnKnnnPP',
    'PP.^^^^^^^^^...^^^^^^^^^^^^..^^^^^^^^..xe...~~~.^^^^^^^.^^^^^^PP',
    'PP.^^^^^^^^^...^^^^^^^^^^^^..^^^^^^^^......,~o~.^^^^^^^.^^^^^^PP',
    'PPεAAAAAAAAA...AAAAAAAAAAAA..AAAAAAAA.e.....~~~.AAAAAAA.AAAAAAPP',
    'PPl#H#h7h#H#.δ.#H#Hh6hH#H#Hll#Hhhhh#Hl......~~~.#HhhhH#l#Hhh#HPP',
    '9======j============i=======================---================8',
    '9=q=========================================---==============v=8',
    '9===1====================+=======E==========---======)=========8',
    'PP=l=====l====β=l=====l=============l====l==~~~===l=======l={=PP',
    'PP.^^^^^^^^bb.^^^^^^^^.x.^^^^^^^b..^^^^^^^..~~~.^^^^^^^..^^^^^PP',
    'PP.^^^^^^^^...^^^^^^^^...^^^^^^^...^^^^^^^..o~~.^^^^^^^..^^^^^PP',
    'PP.AAAAAAAA./.AAAAAAAA...AAAAAAA..eAAAAAAA..~~~.AAAAAAA..AAAAAPP',
    'PP.#H#hhH#H...#H#H#H#H...#H#h#H#...#HhHhH#α.~~~.#H#h#H#..#HhH#PP',
    'PP=====}====================================---===============PP',
    'PP===%%%%%========5=========3=========(=====---=====m=========PP',
    'PP.^^^^^^^^^^^^^^,,lnnnnnnnnnnnnnnnnnnnnnl..~~~..^^^^^^^^^^^^.PP',
    'PP.^^^^^^^^^^^^^^.,nnnnnnnnnnnnnnnnnnnnnnn.K~~~..^^^^^^^^^^^^.PP',
    'PP.AAAAAAAAAAAAAA..nnnηnnnnnnnιnnnnnnθnnnn..~~o..AAAAAAAAAAAA.PP',
    'PP.lwwwwwwwwwwwwl,.nn%%%%nnnn%%%%nnn%%%%nn..~~~.f#H#H#DDH#H#HfPP',
    'PP.wwwwwwwwwwwwww,.nnnnnnnnnnnnnnnnnnnnnnn.K~~~KfnnnnnnnnnnnnfPP',
    'PP.wwwwww4wwwwwww,,nnnnnnnnnnnnnnnnnnnnnnn..~~~.fnnnnnnnnnnunfPP',
    'PP,wwwwwwwwwwwwww..nnnnnnnnnnnζnnnnnnnnnnn..---.fnnnnnn[nnnnnfPP',
    'PP.______________,,nnnnnnnnnnnnnnnnnnnnnnn.\\~~~.fnnnnnnnnnnnnfPP',
    'PP.nnnnnnnnnnnnnn..nn%%%%nnnnnnnnnnn%%%%nn..~~~.fnunnnnnnnnunfPP',
    'PP.nnnnnnnnnnnnnn..nnnnnnnnx.ennnnnnnnnnnn.K~~~.fnnnnnnnnnnnnfPP',
    'PP.nnxnnxnnxnnxnn.,nnnnnnnn...nnnnnnnnnnnn..~y~.fffff....fffffPP',
    'PP,nnnnnnnnnnnnnn.,nnnnnnnne.xnnnnnnnnnnnn..~~~..K..b;;;;K.b..PP',
    'PP.?nnnnnnnn`nnnn,,lnnnnnnnnnnnnnnnnnnnnnl.K~~~K....;;;;;;;,..PP',
    'PP,..............,..........................~~~.K.b;;;;;;...!.PP',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
  ],
  legend: {
    '^': { g: 'grass', o: 'roof-red' },
    A: { g: 'grass', o: 'roof-red-edge' },
    l: { g: 'path', o: 'chochin' },
    h: { g: 'path', o: 'noren' },
    y: { g: 'water', o: 'boat' },
  },
  spawn: 'west',
  inn: 'west',
  points: {
    q: { name: 'west', dir: 'right' },
    v: { name: 'east', dir: 'left' },
    j: { name: 'teahouse', dir: 'down' },
    i: { name: 'guild', dir: 'down' },
    z: { name: 'gate', dir: 'down' },
  },
  exits: [
    { at: '9', to: '@prev', point: 'east' },
    { at: '8', to: '@next', point: 'west' },
    { at: '7', to: 'castletown-teahouse', point: 'door', tile: 'noren' },
    { at: '6', to: 'castletown-guild', point: 'door', tile: 'noren' },
    { at: '0', to: 'castletown-garden', point: 'gate', tile: 'gate-open' },
  ],
  entities: [
    { at: '1', id: 'ct-sen', kind: 'activity', sprite: 'child', dir: 'down', wander: 1, activities: ['r8-words-1'], name: { jp: 'あんないやの セン', en: 'Sen the Town Guide' }, lines: [{ jp: 'みぎ、ひだり、まっすぐ！ この まちの みちなら、ぜんぶ しってるよ。', en: 'Right, left, straight on! I know every street in this town.' }] },
    { at: '2', id: 'ct-board', kind: 'activity', tile: 'sign', activities: ['r8-runes'], name: { jp: 'こうさつ', en: 'Notice Board' }, lines: [{ jp: 'ふだが たくさん はってある。でも、だれも よまない…', en: 'The board is covered in notices. Nobody reads them any more…' }] },
    { at: '3', id: 'ct-painter', kind: 'activity', sprite: 'villager-a', dir: 'down', activities: ['r8-trace'], name: { jp: 'かんばんやの ゲン', en: 'Gen the Sign Painter' }, lines: [{ jp: 'みせの かんばんを かくのが しごとだ。右と 左、いっしょに かいて みるか？', en: 'I paint shop signs for a living. Want to try writing 右 and 左 with me?' }] },
    { at: '4', id: 'ct-barker', kind: 'activity', sprite: 'villager-a', dir: 'down', wander: 1, activities: ['r8-listen'], name: { jp: 'こやの よびこみ', en: 'Stage Barker' }, lines: [{ jp: 'さあさあ、よって らっしゃい 見て らっしゃい！ みみを すませて！', en: 'Roll up, roll up, come and see! Open your ears!' }] },
    { at: '5', id: 'ct-anvil', kind: 'activity', tile: 'anvil', activities: ['r8-forge'], name: { jp: 'かたなかじの かなとこ', en: 'Swordsmith’s Anvil' }, lines: [{ jp: 'かたなかじは ことばも きたえる という。', en: 'They say the swordsmith forges sentences, too.' }] },
    { at: '+', id: 'ct-ochiyo', kind: 'activity', sprite: 'lady', dir: 'left', activities: ['r8-directions'], name: { jp: 'たびびとの おちよ', en: 'Ochiyo the Traveller' }, lines: [{ jp: 'あのう、すみません… みちに まよって しまって。', en: 'Um, excuse me… I seem to be lost.' }] },
    { at: '(', id: 'ct-dollmaker', kind: 'activity', sprite: 'villager-b', dir: 'down', activities: ['r8-defense'], name: { jp: 'からくりしの おとめ', en: 'Otome the Doll Maker' }, lines: [{ jp: 'わたしの ちゃはこび にんぎょうが、ぜんぶ くるって しまったの！ とめて！', en: 'All my tea-serving dolls have gone haywire! Stop them!' }] },
    { at: ')', id: 'ct-runner', kind: 'activity', sprite: 'villager-a', dir: 'left', wander: 1, activities: ['r8-speed'], name: { jp: 'ひきゃくの はやた', en: 'Hayata the Courier' }, lines: [{ jp: 'てがみを とどけるのが しごと。ことばも はやく とどけて みな！', en: 'Delivering letters is my job. Try delivering words that fast!' }] },
    { at: '[', id: 'ct-dojo', kind: 'activity', sprite: 'samurai', dir: 'down', activities: ['r8-words-3'], name: { jp: 'どうじょうの ごんぞう', en: 'Master Gonzō of the Dojo' }, lines: [{ jp: 'すきな ものと きらいな もの。上手な ことと 下手な こと。まずは そこからだ！', en: 'What you like and dislike. What you are good and bad at. We begin there!' }] },
    { at: ']', id: 'ct-tadashi', kind: 'activity', sprite: 'samurai', dir: 'down', activities: ['r8-keigo'], name: { jp: 'けらいの ただし', en: 'Tadashi the Retainer' }, lines: [{ jp: 'とまれ！ …いや、しつれい。どうも この ごろ、ことばが あらく なって…', en: 'Halt! …Ah, forgive me. Lately my words keep coming out rough…' }] },
    { at: '{', id: 'ct-sign', kind: 'sign', tile: 'sign', name: { jp: 'みちしるべ', en: 'Signpost' }, lines: [{ jp: 'ひがし：雪の寺。…しろに ようかいが いる かぎり、みちは とざされている。', en: 'East: the Snowbound Temple. …While the yokai holds the castle, the road stays shut.' }] },
    { at: '}', id: 'ct-dango', kind: 'npc', sprite: 'villager-b', dir: 'down', name: { jp: 'だんごやの おふく', en: 'Ofuku the Dango Seller' }, lines: [{ jp: 'かうの？ かわないの？ はっきり しな！ …あっ、ちがうの、ほんとうは こんな こと いいたく ないのに！', en: 'Buying or not? Make up your mind! …Oh no, I didn’t mean that! I don’t want to talk like this!' }] },
    { at: '/', id: 'ct-porter', kind: 'npc', sprite: 'villager-a', dir: 'right', name: { jp: 'にもつもちの ごろはち', en: 'Gorohachi the Porter' }, lines: [{ jp: 'どけ、どけ！ …おれ、むかしは「おさきに どうぞ」って いえたんだけどなあ。', en: 'Out of the way! …I used to be able to say “after you”, you know.' }] },
    { at: 'E', id: 'ct-fangirl', kind: 'npc', sprite: 'lady', dir: 'down', wander: 1, name: { jp: 'せんすやの むすめ', en: 'Fan Seller’s Daughter' }, lines: [{ jp: 'おきゃくさんが ひとりも こないの。ちょうば から「いらっしゃいませ」が きえちゃって…', en: 'Not a single customer comes in. The words “irasshaimase” have vanished from our counter…' }, { jp: 'この せんす、きれいでしょう？ …あ、うりものじゃ ない ふりを して しまった。', en: 'Isn’t this fan pretty? …Oh, I pretended it wasn’t for sale again.' }] },
    { at: 'U', id: 'ct-patrol', kind: 'npc', sprite: 'samurai', wander: 2, name: { jp: 'みまわりの さむらい', en: 'Patrolling Samurai' }, lines: [{ jp: 'しろに へんな じいさんが はいって いった。だれも とめなかった。なぜだ…', en: 'A strange old man walked into the castle. Nobody stopped him. Why…?' }, { jp: '刀は こころで ぬく ものだ。ことばも おなじ。', en: 'A katana is drawn with the heart. Words are the same.' }] },
    { at: 'd', id: 'ct-cat', kind: 'npc', sprite: 'cat', wander: 2, name: { jp: 'ねこ', en: 'Cat' }, lines: [{ jp: 'にゃあ。', en: 'Meow.' }] },
    { at: 'm', id: 'ct-dog', kind: 'npc', sprite: 'dog', wander: 2, name: { jp: 'いぬ', en: 'Dog' }, lines: [{ jp: 'わん！', en: 'Woof!' }] },
    { at: '\\', id: 'ct-boatman', kind: 'npc', sprite: 'villager-a', dir: 'right', name: { jp: 'せんどうの じんべえ', en: 'Jinbē the Boatman' }, lines: [{ jp: 'この ほりは、おしろの おほりに つながって いる。ふねで まちを ひとまわり できるよ。', en: 'This canal runs into the castle moat. You can row all the way round the town.' }, { jp: 'はしは みっつ。いちばん きれいなのは、いちばの そばの そりはしだ。', en: 'Three bridges. The prettiest is the arched one by the market.' }] },
    { at: '`', id: 'ct-child', kind: 'npc', sprite: 'child', wander: 2, name: { jp: 'こども', en: 'Kid' }, lines: [{ jp: 'しばいの まねっこ！「みえを きる」って こう やるんだよ！', en: 'I’m playing kabuki! This is how you strike a pose!' }, { jp: 'ぶたいの うしろに、たからばこが あるって うわさ！', en: 'They say there’s a treasure chest behind the stage!' }] },
    { at: "'", id: 'ct-angler', kind: 'npc', sprite: 'elder', dir: 'up', name: { jp: 'つりの ごいんきょ', en: 'Retired Angler' }, lines: [{ jp: 'むかしは だれでも「こんにちは」と いったものだ。いまは、だれも ことばを かわさん。', en: 'Once everyone said “konnichiwa”. Now nobody exchanges a word.' }, { jp: 'ほりの こいは、ことばが すきでな。はなしかけると よって くる。', en: 'The carp in the moat love words. Talk to them and they swim over.' }] },
    { at: '$', id: 'ct-chest-square', kind: 'chest', tile: 'chest', chest: { item: 'herb', n: 2, shards: 10 } },
    { at: '?', id: 'ct-chest-stage', kind: 'chest', tile: 'chest', chest: { item: 'charm', n: 1, shards: 30, lock: { answer: 'どうぞ', jp: 'ふたに「おさきに ＿＿」。あいている ことばを となえよ。', en: 'The lid reads “After you, ___.” Speak the missing word (please, go ahead).' } } },
    { at: '!', id: 'ct-chest-lane', kind: 'chest', tile: 'chest', chest: { item: 'ether', n: 1, shards: 15 } },
    { at: 'α', id: 'ct-corner', kind: 'landmark', tile: 'statue', word: 'kado', name: { jp: 'かどの じぞう', en: 'Corner Jizō' }, lines: [{ jp: '角に たつ じぞう。みちに まよった ひとを みまもって いる。', en: 'A little Jizō on the corner, watching over people who lose their way.' }] },
    { at: 'β', id: 'ct-street', kind: 'landmark', tile: 'sign', word: 'toori', name: { jp: 'ほんどおりの ふだ', en: 'Main Street Sign' }, lines: [{ jp: '「ほんどおり」。にしは ゆの さと、ひがしは 雪の みち。', en: '“Main Street.” West to the hot springs, east to the snow road.' }] },
    { at: 'γ', id: 'ct-gate-lantern', kind: 'landmark', tile: 'lantern', word: 'mon', name: { jp: 'おおてもんの とうろう', en: 'Gate Lantern' }, lines: [{ jp: 'おしろの おおてもん。いまは かたく とじられている…ように 見える。', en: 'The castle’s great gate. It looks firmly shut… or does it?' }] },
    { at: 'δ', id: 'ct-chaya-lantern', kind: 'landmark', tile: 'chochin', word: 'chaya', name: { jp: 'きくやの ちょうちん', en: 'Kikuya’s Lantern' }, lines: [{ jp: 'あかい ちょうちんに「きくや」。あまい においが する。', en: 'A red lantern reading “Kikuya”. Something sweet is in the air.' }] },
    { at: 'ε', id: 'ct-milestone', kind: 'landmark', tile: 'statue', word: 'machi', name: { jp: 'まちの みちしるべ いし', en: 'Town Milestone' }, lines: [{ jp: 'ここから 城下町。ようこそ。', en: 'The castle town starts here. Welcome.' }] },
    { at: 'ζ', id: 'ct-well', kind: 'landmark', tile: 'well', word: 'koko', name: { jp: 'いちばの いど', en: 'Market Well' }, lines: [{ jp: 'まちの まんなか。「ここで あおう」が あいことば。', en: 'The heart of town. “Let’s meet here” is what everyone says.' }] },
    { at: 'η', id: 'ct-stall-dango', kind: 'npc', sprite: 'villager-b', dir: 'down', name: { jp: 'やたいの おばあさん', en: 'Stall Granny' }, lines: [{ jp: 'みたらし だんご、ひとつ どう？ …ほら、「おねがいします」って いって ごらん。', en: 'One sweet-soy dango? …Go on, say “onegaishimasu”.' }] },
    { at: 'θ', id: 'ct-stall-fan', kind: 'npc', sprite: 'merchant', dir: 'down', name: { jp: 'やたいの せんすうり', en: 'Fan Stall Keeper' }, lines: [{ jp: 'この せんす？ その せんす？ あの せんす？ どの せんすに しますか？', en: 'This fan? That fan? That one over there? Which fan will it be?' }] },
    { at: 'ι', id: 'ct-stall-cloth', kind: 'npc', sprite: 'villager-a', dir: 'down', name: { jp: 'ぬのうりの へいすけ', en: 'Heisuke the Cloth Seller' }, lines: [{ jp: 'きものの ぬの、ありますよ！ …いや、「ある」って いうか、うって いるって いうか。', en: 'Kimono cloth, we have it! …Well, “have”, or rather, sell.' }] },
  ],
}

export const CASTLETOWN_TEAHOUSE: MapSpec = {
  ...ROOM,
  id: 'castletown-teahouse',
  name: 'Kikuya Tea House',
  jp: 'ちゃや きくや',
  region: 8,
  music: 'shop',
  rows: [
    '#################',
    '#kHHH2HHHk#pwewp#',
    '#ttttttttt#w1www#',
    '#tx(ttxttt#%%%ww#',
    '#tttttttttwwwwww#',
    '#tttttttttwwwwww#',
    '#txtttx)ttwwwwwe#',
    '#tttttttttwwwwww#',
    '#tx[ttttttwwwwp$#',
    '#tttttttvtwwwwww#',
    '########0########',
  ],
  legend: {
    k: { g: 'tatami', o: 'bookshelf' },
    x: { g: 'tatami', o: 'crate' },
    p: { g: 'wood-floor', o: 'pot' },
    e: { g: 'wood-floor', o: 'barrel' },
    '%': { g: 'wood-floor', o: 'stall' },
  },
  spawn: 'door',
  points: { v: { name: 'door', dir: 'up' } },
  exits: [{ at: '0', to: 'castletown', point: 'teahouse', tile: 'carpet' }],
  entities: [
    { at: '1', id: 'cth-kiku', kind: 'activity', sprite: 'lady', dir: 'down', activities: ['r8-teahouse'], name: { jp: 'おかみの キク', en: 'Kiku, the Mistress' }, lines: [{ jp: 'いらっしゃいませ！ …よかった、きょうは ちゃんと いえた。', en: 'Welcome! …Phew, I managed to say it properly today.' }] },
    { at: '2', id: 'cth-scroll', kind: 'landmark', tile: 'bookshelf', word: 'youkoso', name: { jp: 'かけじく', en: 'Hanging Scroll' }, lines: [{ jp: 'かけじくに「ようこそ」と かいてある。すみが うすく なっている…', en: 'The hanging scroll reads “Welcome”. The ink is fading…' }] },
    { at: '(', id: 'cth-ronin', kind: 'npc', sprite: 'samurai', dir: 'right', name: { jp: 'えらそうな きゃく', en: 'Pompous Customer' }, lines: [{ jp: 'おい、ちゃ！ はやく もって こい！ …む？ わしは いま、なんと いった？', en: 'Oi, tea! Bring it now! …Hm? What did I just say?' }, { jp: 'ほんとうは「おちゃを おねがいします」と いいたいのだ…', en: 'What I MEAN to say is “Tea, please”…' }] },
    { at: ')', id: 'cth-couple', kind: 'npc', sprite: 'elder', dir: 'left', name: { jp: 'ろうふうふの だんな', en: 'Old Husband' }, lines: [{ jp: 'ばあさんや、だんごを あげよう。…いや、くれ。…あれ、どっちだったかな。', en: 'Here, dear, I’ll give you a dango. …No, give me one. …Er, which was it?' }] },
    { at: '[', id: 'cth-poet', kind: 'npc', sprite: 'villager-b', dir: 'up', name: { jp: 'はいじん', en: 'Haiku Poet' }, lines: [{ jp: 'ひとくちの ちゃの まに きこゆ まどの あめ', en: 'One sip of tea; in its pause I hear the rain at the window.' }, { jp: '「ま」が だいじなの。ことばと ことばの あいだの、ちいさな しずけさ。', en: 'The pause, the “ma”, is what matters. The small quiet between one word and the next.' }] },
    { at: '$', id: 'cth-chest', kind: 'chest', tile: 'chest', chest: { item: 'herb', n: 2, shards: 8 } },
  ],
}

export const CASTLETOWN_GUILD: MapSpec = {
  ...ROOM,
  id: 'castletown-guild',
  name: 'Merchant Guild',
  jp: 'あきんどの かいしょ',
  region: 8,
  music: 'shop',
  rows: [
    '###################',
    '#kkkHkkkHkkkHk2kHk#',
    '#ttttttttwwwwwwww$#',
    '#ttttttttwwxwewwww#',
    '#ttttttttwwwwww(ww#',
    '#ttt1ttttwwewxwwww#',
    '#w%%%%%%wwwwwwwwww#',
    '#wwwwwwwwwwwwwwxxw#',
    '#wwwwwwwww)wwwwexw#',
    '#wwwww[wwwwwwwwwww#',
    '#exwwwwwwwwwwwwwwp#',
    '#wwwwwwwwvwwwwwwww#',
    '#########0#########',
  ],
  legend: {
    x: { g: 'wood-floor', o: 'crate' },
    e: { g: 'wood-floor', o: 'barrel' },
    p: { g: 'wood-floor', o: 'pot' },
    '%': { g: 'wood-floor', o: 'stall' },
  },
  spawn: 'door',
  points: { v: { name: 'door', dir: 'up' } },
  exits: [{ at: '0', to: 'castletown', point: 'guild', tile: 'carpet' }],
  entities: [
    { at: '1', id: 'ctg-clerk', kind: 'activity', sprite: 'merchant', dir: 'down', activities: ['r8-words-2'], name: { jp: 'ばんとうの おきぬ', en: 'Okinu the Head Clerk' }, lines: [{ jp: 'いらっしゃいませ。この、その、あの、どの。かいものの ことばを おしえましょう。', en: 'Welcome. This, that, that over there, which. Let me teach you the words of shopping.' }] },
    { at: '2', id: 'ctg-ledger', kind: 'activity', tile: 'bookshelf', activities: ['r8-cross'], name: { jp: 'だいふくちょう', en: 'The Great Ledger' }, lines: [{ jp: 'あきんどの ちょうめん。ますめに ことばが ならんで いる。', en: 'The merchants’ ledger. Its columns are full of words.' }] },
    { at: '(', id: 'ctg-master', kind: 'npc', sprite: 'elder', dir: 'down', name: { jp: 'かいしょの だんな', en: 'Guild Master' }, lines: [{ jp: 'あきないは ことばが いのち。「いらっしゃいませ」が きえた みせに、きゃくは こん。', en: 'Trade lives on words. No customer comes to a shop that has lost its “irasshaimase”.' }, { jp: 'しろの ようかいが、まちの「どうぞ」と「ありがとう」を たべて しまったのだ。', en: 'The yokai in the castle has eaten the town’s “please” and “thank you”.' }] },
    { at: ')', id: 'ctg-apprentice', kind: 'npc', sprite: 'child', wander: 2, name: { jp: 'でっちの かめきち', en: 'Kamekichi the Apprentice' }, lines: [{ jp: 'そろばん、パチパチ！ …ばんとうさんに「こちらへ どうぞ」の れんしゅうを させられてるんだ。', en: 'Abacus, click-clack! …The head clerk makes me practise “kochira e dōzo” all day.' }] },
    { at: '[', id: 'ctg-customer', kind: 'npc', sprite: 'lady', dir: 'up', name: { jp: 'おとくいさま', en: 'Regular Customer' }, lines: [{ jp: 'あの きものが ほしいの。でも、だれも「どうぞ」って いって くれないのよ。', en: 'I want that kimono over there. But nobody will say “please, go ahead” to me.' }] },
    { at: '$', id: 'ctg-safe', kind: 'chest', tile: 'chest', chest: { item: 'ether', n: 2, shards: 25, lock: { answer: 'いらっしゃいませ', jp: 'きんこに「みせの はじめの ことば」。', en: 'The strongbox reads: “the first word of any shop.”' } } },
  ],
}

export const CASTLETOWN_GARDEN: MapSpec = {
  id: 'castletown-garden',
  name: 'The Castle Garden',
  jp: 'おしろの おにわ',
  region: 8,
  music: 'castletown',
  particles: 'sakura',
  tint: 'rgba(120, 90, 160, 0.12)',
  rows: [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XPPPPPPPPPPPPPP^^^^^^^^^^PPPPPPPPPPPPPPX',
    'XPBPBPPBPBPP...^^^^^^^^^^...PPBPPBPBPPPX',
    'XPPBPPBPPBP....AAAAAAAAAA....PPBPPBPBPPX',
    'XPBPPBP.....^^^^^^^^^^^^^^^^...PPBPPBPPX',
    'XPPB........^^^^^^^^^^^^^^^^.....PPBPPPX',
    'XPP.........AAAAAAAAAAAAAAAA........PPBX',
    'X...........HYYHYYH11HYYHYYH...........X',
    'X................L.j=.L................X',
    'X.P..K..========================.......X',
    'X..................==...............$..X',
    'X..o~~~~~~~~~o.P...==...K::::::::::::..X',
    'X..~WWWWWWWWW~..[..==2...::r::::::r::..X',
    'X..~WWWWrWWWW~.....==....::::::::::::..X',
    'X..~WWoWWWWWW~...L.==.L..::::::r:::::..X',
    'X..ssssss?WWWs)....==....::::r:::::R:..X',
    'X..~WWWWWWoWW~.....==....::::::::::::..X',
    'X..~WWWWWWWWW~.K...==..................X',
    'X..~~~~~~~~~~~.....==...P............P.X',
    'X..:::::::::::.....==.......^^^^^^^^...X',
    'X...........(......==.......^^^^^^^^...X',
    'X................L.==.L.....AAAAAAAA...X',
    'X..P;;;;;;;;..P....==.......LwwwwwwL...X',
    'X..;;;;;;;;;.......==..;;;;.www3wwww...X',
    'X..;;;;;;;;;.......==..;;;;............X',
    'X.P;;;;;;;;;.......==..;;;;...K......P.X',
    'X..................q=..................X',
    'XXXXXXXXXXXXXXXXXXX00XXXXXXXXXXXXXXXXXXX',
  ],
  spawn: 'gate',
  points: {
    q: { name: 'gate', dir: 'up' },
    j: { name: 'keep', dir: 'down' },
  },
  exits: [
    { at: '0', to: 'castletown', point: 'gate', tile: 'gate-open' },
    { at: '1', to: 'castletown-keep', point: 'door', tile: 'door' },
  ],
  entities: [
    { at: '2', id: 'cg-trial', kind: 'activity', tile: 'lantern', activities: ['r8-mastery'], name: { jp: 'しれんの とうろう', en: 'Trial Lantern' }, lines: [{ jp: 'ひの きえた とうろう。ただしい ことばを ならべれば、ひが ともる という。', en: 'An unlit stone lantern. They say the right sentences will light it.' }] },
    { at: '3', id: 'cg-ayame', kind: 'activity', sprite: 'lady', dir: 'down', activities: ['r8-words-4'], name: { jp: 'こしもとの あやめ', en: 'Ayame, Lady-in-Waiting' }, lines: [{ jp: 'あげる、くれる、もらう。そして 殿に つかう ことば。わたくしが おしえましょう。', en: 'Giving and receiving, and the words we use for the lord. Let me teach you.' }] },
    { at: '(', id: 'cg-gardener', kind: 'npc', sprite: 'villager-a', dir: 'up', name: { jp: 'にわしの ろくすけ', en: 'Rokusuke the Gardener' }, lines: [{ jp: 'ようかいが きてから、にわが あれほうだいだ。くさむらに からくりが ひそんで おる。', en: 'Since the yokai came the garden has run wild. Clockwork dolls lurk in the long grass.' }, { jp: 'まつは 千ねん、いけの こいは ひゃくねん。ことばは、どう だろうな。', en: 'Pines live a thousand years, the carp a hundred. And words, I wonder?' }] },
    { at: ')', id: 'cg-pond-lantern', kind: 'landmark', tile: 'lantern', word: 'niwa', name: { jp: 'いけの ゆきみどうろう', en: 'Pond Lantern' }, lines: [{ jp: 'いけの ほとりの とうろう。庭ぜんたいが 見わたせる。', en: 'A lantern on the pond’s edge. The whole garden lies in view.' }] },
    { at: '[', id: 'cg-maid', kind: 'npc', sprite: 'villager-b', wander: 1, name: { jp: 'おしろの じょちゅう', en: 'Castle Maid' }, lines: [{ jp: 'あの おじいさん、「おじゃまします」も いわずに はいって きて、殿の ざに すわったんです！', en: 'That old man walked in without so much as an “excuse me” and sat in the lord’s seat!' }] },
    { at: '$', id: 'cg-chest', kind: 'chest', tile: 'chest', chest: { item: 'charm', n: 1, shards: 20 } },
    { at: '?', id: 'cg-chest-stones', kind: 'chest', tile: 'chest', chest: { item: 'ether', n: 1, shards: 20, lock: { answer: 'にわ', jp: 'ふたに「庭」。よみを となえよ。', en: 'The lid bears 庭. Speak its reading.' } } },
  ],
}

export const CASTLETOWN_KEEP: MapSpec = {
  ...ROOM,
  id: 'castletown-keep',
  name: 'The Keep',
  jp: 'てんしゅかく',
  region: 8,
  music: 'castletown',
  particles: 'dust',
  tint: 'rgba(110, 60, 140, 0.16)',
  rows: [
    'XXXXXXXXXXXXXXXXXXX',
    'XkHH#HHHkJkHHH#HHkX',
    'Xt$t#NnnnnnnnN#t2tX',
    'Xttt#tnnnnnnnt#tttX',
    'XtttDtnnn1nnntDtttX',
    'XttttttttMttttttttX',
    'XttNtttttMtttttNttX',
    'XttttttttMttttttttX',
    'Xtttt(tttMttt)ttttX',
    'XttttttttMttttttttX',
    'XttNtttttMtttttNttX',
    'XttttttttMttttttttX',
    'XttttttttvttttttttX',
    'XXXXXXXXX0XXXXXXXXX',
  ],
  legend: {
    k: { g: 'tatami', o: 'bookshelf' },
    N: { g: 'tatami', o: 'lantern' },
    '#': { g: 'tatami', o: 'wall' },
    D: { g: 'tatami', o: 'door' },
  },
  spawn: 'door',
  points: { v: { name: 'door', dir: 'up' } },
  exits: [{ at: '0', to: 'castletown-garden', point: 'keep', tile: 'carpet' }],
  entities: [
    { at: '1', id: 'ck-nurarihyon', kind: 'boss', sprite: 'nurarihyon', activities: ['r8-boss'], name: { jp: 'ぬらりひょん', en: 'Nurarihyon' }, lines: [{ jp: 'ほっほ。ここは わしの いえじゃ。おまえこそ、なにを しに きた？', en: 'Ho ho. This is MY house. And what are YOU doing here?' }] },
    { at: '2', id: 'ck-lord', kind: 'npc', sprite: 'king', dir: 'left', name: { jp: '殿', en: 'The Lord' }, lines: [{ jp: '……。', en: '(The lord sits frozen, unable to say a word.)' }] },
    { at: '(', id: 'ck-retainer-a', kind: 'npc', sprite: 'samurai', dir: 'right', name: { jp: 'こおった けらい', en: 'Frozen Retainer' }, lines: [{ jp: '……どうぞ、ごゆっくり…… ちがう…… でて いけ……', en: '…Please, make yourself at home… no… get out…' }] },
    { at: ')', id: 'ck-retainer-b', kind: 'npc', sprite: 'samurai', dir: 'left', name: { jp: 'こおった けらい', en: 'Frozen Retainer' }, lines: [{ jp: '……おちゃを おもち いたしましょうか…… なぜ わしが……', en: '…Shall I bring you tea… why am I saying this…' }] },
    { at: '$', id: 'ck-chest', kind: 'chest', tile: 'chest', chest: { item: 'charm', n: 2, shards: 30 } },
  ],
}

export const MAPS: MapSpec[] = [CASTLETOWN, CASTLETOWN_TEAHOUSE, CASTLETOWN_GUILD, CASTLETOWN_GARDEN, CASTLETOWN_KEEP]
