import type { Locus } from '../types'

/**
 * Room 8 — the Castle Town. The route follows a visitor's day: in at the
 * town milestone on the west road, Sen the guide, along Main Street to the
 * corner Jizō, into Kikuya for tea and the merchant guild to shop, down to
 * the market well, the kabuki stage and the dojo yard, then up to the great
 * gate, through the garden pavilion, and into the keep to the lord's seat.
 * Directions live on the street, shopping in the shops, likes at the stage,
 * invitations at the dojo, and keigo with the samurai and the lord.
 */
export const ROOM: Locus[] = [
  {
    id: 'p8-milestone',
    room: 8,
    map: 'castletown',
    anchor: 'ct-milestone',
    name: { jp: 'まちの みちしるべ いし', en: 'Town Milestone' },
    emoji: '🪨',
    memories: [
      { item: 'w:machi', story: 'Beside the milestone a whole little town is built of MATCHsticks. A giant strikes one — "MATCH-EE!" — and every tiny roof flares up like a lantern festival.', image: 'a whole little town of houses built from MATCHsticks, and a giant strikes one — "MATCH-EE!" — so every tiny rooftop flares like a lantern festival' },
      { item: 'w:youkoso', story: 'A doorman leaps out from behind the milestone, flings his arms wide and bellows "YO! KO-SO glad you came!" — the warmest welcome anyone ever got into this town.', image: 'a doorman leaps out, flings his arms wide and bellows "YO! KO-SO glad you came!" — the warmest welcome you have ever had' },
      { item: 'w:koko', story: 'A vendor plonks a steaming mug of COCOA right at your feet by the milestone and taps the spot twice: "COCO! Here! Right here, by you!"', image: 'a vendor plonks a steaming mug of COCOA right at your feet and taps the spot twice: "COCO! Here! Right here, by me!"' },
      { item: 'w:soko', story: 'Fude stands a few steps away from the milestone when a bucket of water flies over and SOAKS her, not you — "SO-KO!" — there, by her.', image: 'a bucket of water flies past you and SOAKS your friend instead — "SO-KO!" — it lands there, by them, never here by you' },
      { item: 'w:asoko', story: 'Far off down the road, beyond you and Fude both, a boxer lands a punch on a scarecrow — "AH, SOCKO!" — way over there.', image: 'far away, beyond you and your friend both, a boxer lands a punch on a scarecrow — "AH, SOCKO!" — way over there' },
      { item: 'w:doko', story: 'A lost sailor runs in circles round the milestone, map upside down, shouting "DOCK-O? Where is the DOCK? Where am I?"', image: 'a lost sailor runs round in circles with his map upside down, shouting "DOCK-O? Where is the DOCK? Where am I?"' },
      { item: 'g:kosoado-place', story: 'Four little flags are planted round the milestone, singing KO, SO, A, DO: one at your feet, one by Fude, one far down the road, and one with a big question mark.', image: 'four little flags sing KO, SO, A, DO: one at your feet, one by your friend, one far away from you both, and one wearing a big question mark' },
    ],
  },
  {
    id: 'p8-sen',
    room: 8,
    map: 'castletown',
    anchor: 'ct-sen',
    name: { jp: 'あんないやの セン', en: 'Sen the Guide' },
    emoji: '🧒',
    memories: [
      { item: 'w:migi', story: 'Sen rides a cart horse down the road and yells the old carters’ word, "ME, GEE!" — and the horse swings RIGHT, every time.', image: 'a kid on a cart horse yells the old carters’ command, "ME, GEE!", and the horse swings to the right, every single time' },
      { item: 'w:hidari', story: 'Sen climbs onto stilts, yells "HE DARE-EE!" and swerves hard to the left, his left arm flung out like a signal.', image: 'a daredevil on stilts yells "HE DARE-EE!" and swerves hard to the left, his left arm flung out like a signal' },
      { item: 'w:massugu', story: 'A goose marches past Sen in a dead straight line, never turning, while its owner calls "MA’S GOOSE! MASS-GOO!" — straight ahead it goes.', image: 'a goose marches in a dead straight line, never turning once, while a woman calls "MA’S GOOSE! MASS-GOO!" as it goes straight ahead' },
      { item: 'w:magaru', story: 'A rickshaw rattles past Sen and swings into a turn so sharp the passenger yells "MA! GA-RU!" and clutches her hat round the bend.', image: 'a rickshaw swings into a turn so sharp that its passenger yells "MA! GA-RU!" and clutches her hat all the way round the bend' },
      { item: 'w:annaisuru', story: 'Sen hands his little flag to a guide called ANNA, so NICE, SURE of every street — "ANNA-NICE-SURE!" — and she leads the tourists off.', image: 'a cheerful guide called ANNA, very NICE and SURE of every street, waves a little flag — "ANNA-NICE-SURE!" — and leads a line of travellers' },
      { item: 'g:wo-ni-magaru', story: 'Sen chalks two tags on the road: an "O" on the corner you go round, and a "NEE" on the arrow you turn — round the O, turn to the NEE.', image: 'two chalk tags on the road: a big O on the corner you go round, and a NEE on the arrow showing which way you turn' },
    ],
  },
  {
    id: 'p8-street',
    room: 8,
    map: 'castletown',
    anchor: 'ct-street',
    name: { jp: 'ほんどおり', en: 'Main Street' },
    emoji: '🛣️',
    memories: [
      { item: 'w:toori', story: 'Under the street sign, a parade of giant TOEs marches by in step, chanting "TOE-REE! TOE-REE!" all along the lantern-lined avenue.', image: 'a parade of giant TOEs marches past in step down a long lantern-lined avenue, chanting "TOE-REE! TOE-REE!"' },
      { item: 'w:mae', story: 'A mule plants itself right in front of the street sign, braying "MY-EH! MY-EH!" so nobody can get past its nose.', image: 'a stubborn mule plants itself right in front of you, braying "MY-EH! MY-EH!", so nobody can get past its nose' },
      { item: 'w:ushiro', story: 'Behind you, all along the street, a girl rows a little boat on wheels — "OOH, SHE ROWS!" — and she is always right behind.', image: 'right behind you a girl rows a little boat on wheels — "OOH, SHE ROWS!" — and however you turn, she is always behind' },
      { item: 'w:tonari', story: 'On the bench beside the street sign two strangers squeeze side by side, the seat so NARROW their TOEs touch: TOE-NARROW, right next to each other.', image: 'two strangers squeeze onto a bench so NARROW that their TOEs touch — TOE-NARROW — sitting right next to each other' },
      { item: 'g:no-ichi', story: 'Labels hang from the street sign: "gate NO front", "shop NO behind", "bridge NO next-to" — the landmark first, then NO, then the place word.', image: 'labels flutter on a string: "gate NO front", "shop NO behind", "bridge NO next-to" — the landmark first, then NO, then the place word' },
    ],
  },
  {
    id: 'p8-corner',
    room: 8,
    map: 'castletown',
    anchor: 'ct-corner',
    name: { jp: 'かどの じぞう', en: 'Corner Jizō' },
    emoji: '🗿',
    memories: [
      { item: 'w:kado', story: 'A CAR takes the corner too fast and thumps into the wall right beside the little Jizō — "CAR... DOH!" The Jizō does not even blink.', image: 'a CAR takes a sharp corner far too fast and thumps into the wall — "CAR... DOH!" — while a stone statue does not even blink' },
      { item: 'w:kono', story: 'The Jizō holds up an ice-cream CONE in its own stone hand: "CONE-O! This cone, THIS one, right here in my hand."', image: 'you hold up an ice-cream CONE in your own hand and declare "CONE-O! This cone, THIS one, right here!"' },
      { item: 'w:sono', story: 'Fude holds a rice ball by the Jizō, and you point at it: "SO... NO, not mine — THAT rice ball, the one by you."', image: 'your friend holds a rice ball and you point at it: "SO... NO, not mine — THAT rice ball, the one by you"' },
      { item: 'w:ano', story: 'Far across the street from the Jizō, a kite tangles in a tree: "AH, NO! That kite, over there!"', image: 'far across the street, away from you both, a kite tangles in a tree: "AH, NO! That kite, over there!"' },
      { item: 'w:dono', story: 'A baker sets three DOUGHnuts on the Jizō’s lap and asks, "DOUGH... NO? Which doughnut do you want?"', image: 'a baker holds up three DOUGHnuts and asks, "DOUGH... NO? Which doughnut will it be?"' },
      { item: 'g:kono-sono-ano', story: 'Four shy words cling to the Jizō’s sleeves, each holding a noun by the hand: CONE-O fan, SO-NO fan, AH-NO fan, DOUGH-NO fan. They never walk alone.', image: 'four shy words each hold a noun by the hand — CONE-O fan, SO-NO fan, AH-NO fan, DOUGH-NO fan — and never walk alone' },
    ],
  },
  {
    id: 'p8-teahouse',
    room: 8,
    map: 'castletown-teahouse',
    anchor: 'cth-kiku',
    name: { jp: 'ちゃや きくや', en: 'Kikuya Tea House' },
    emoji: '🍵',
    memories: [
      { item: 'w:irasshaimase', story: 'Every time the noren sways, Kiku scratches her EAR, which has a RASH, and sings "EAR-RASH! I’M-A-SAY welcome!" to the customer.', image: 'a shopkeeper with an itchy EAR RASH sings "EAR-RASH! I’M-A-SAY welcome!" every time the shop curtain sways open' },
      { item: 'w:chaya', story: 'Kiku spins a tray of steaming CHA, green tea, over her head and yells "CHA-YA!" — the whole tea house cheers.', image: 'a waitress spins a tray of steaming CHA, green tea, over her head and yells "CHA-YA!" while the customers cheer' },
      { item: 'w:dango', story: 'Three dumplings roll off their stick and bounce across the tatami. Kiku yells "DANG! GO catch them!"', image: 'three dumplings roll off their stick and bounce across the floor, and a cook yells "DANG! GO catch them!"' },
      { item: 'w:okyakusan', story: 'A shaggy YAK shuffles into Kikuya and sits down for tea. Kiku bows low: "OH, KYAK-SAN, our honoured customer!"', image: 'a shaggy YAK shuffles in to buy something, and the clerk bows low: "OH, KYAK-SAN, our honoured customer!"' },
      { item: 'w:onegaishimasu', story: 'A girl clasps her hands at Kiku’s counter and begs, "OH NAY, GUY, SHE MUST have the last dango — please, please!"', image: 'a girl clasps her hands and begs, "OH NAY, GUY, SHE MUST have the last one — please, please!"' },
      { item: 'w:douzo', story: 'Kiku holds the sliding door open for a guest so long that she DOZEs off upright — "DOH-ZO... go ahead..." — and snores.', image: 'a host holds a door open for so long that she DOZEs off standing — "DOH-ZO... go ahead..." — and starts to snore' },
      { item: 'g:wo-onegaishimasu', story: 'On Kiku’s counter, orders line up like a train: the thing you want, an O carriage, then the big OH-NAY-GUY engine pulling it to the kitchen.', image: 'orders line up like a little train: the thing you want, an O carriage, then the big OH-NAY-GUY engine pulling it away' },
      { item: 'g:o-kudasai', story: 'Kiku wraps a plain verb in a gift box: an O ribbon on the front, the verb’s stem inside, a KUDASAI bow on top — the politest please in the house.', image: 'a plain verb is wrapped like a gift: an O ribbon on the front, its stem inside, and a KUDASAI bow on top — the politest please' },
    ],
  },
  {
    id: 'p8-guild',
    room: 8,
    map: 'castletown-guild',
    anchor: 'ctg-clerk',
    name: { jp: 'かいしょの ちょうば', en: 'Guild Counter' },
    emoji: '🧮',
    memories: [
      { item: 'w:kochira', story: 'A COACH driver bursts into the guild, bows, and sweeps his arm toward himself: "COACH-HERE-A! This way, please!"', image: 'a COACH driver bows and sweeps his arm in toward himself: "COACH-HERE-A! This way, please, this way!"' },
      { item: 'w:sochira', story: 'A cheerleader at the counter points politely at your side of the room: "SO! CHEER-A that way, over by you!"', image: 'a cheerleader points politely toward your side with her pom-pom: "SO! CHEER-A that way, over by you!"' },
      { item: 'w:achira', story: 'Through the guild window, far across the road, a crowd waves flags: "AH! CHEER-A! Over there, kindly!"', image: 'far across the road, away from everyone, a crowd waves little flags: "AH! CHEER-A! Over there, kindly!"' },
      { item: 'w:dochira', story: 'A deer in a merchant’s apron stands at the ledger, politely asking "DOE-CHEER-A? Which way, if you please?"', image: 'a deer in a neat apron stands at a crossroads, asking politely "DOE-CHEER-A? Which way, if you please?"' },
      { item: 'g:kochira-polite', story: 'In the guild the plain little place words change into silk kimonos and come out bowing: KOCHIRA, SOCHIRA, ACHIRA, DOCHIRA — the same places, made polite.', image: 'four plain little place words change into silk kimonos and come out bowing as KOCHIRA, SOCHIRA, ACHIRA, DOCHIRA — the same places, made polite' },
      { item: 'g:wa-arimasu-ka', story: 'A shopper rings the guild bell and leans over the counter: "Fans WA... ARI-MASU-KA? Do you HAVE any?"', image: 'a shopper rings a counter bell and leans over: "Fans WA... ARI-MASU-KA? Do you HAVE any at all?"' },
      { item: 'g:ni-shimasu', story: 'After an hour of dithering, a customer slaps one bolt of cloth and declares "This NEE, SHE MASS — I’ll take it!"', image: 'after an hour of dithering, a customer slaps one bolt of cloth and declares "This one NEE, SHE MASS — I’ll take it!"' },
    ],
  },
  {
    id: 'p8-market',
    room: 8,
    map: 'castletown',
    anchor: 'ct-well',
    name: { jp: 'いちばの いど', en: 'Market Well' },
    emoji: '🪣',
    memories: [
      { item: 'w:sensu', story: 'A folding fan snaps open by the well and fans some SENSE into a foolish boy’s head — "SEN-SU!" — he suddenly does his homework.', image: 'a folding fan snaps open and fans some SENSE into a foolish boy’s head — "SEN-SU!" — and he suddenly does his homework' },
      { item: 'w:kimono', story: 'Hanging over the well on a line, a MONOchrome robe with one silver KEY sewn on the sleeve: KEY-MONO, the finest in the market.', image: 'a long silk robe in MONOchrome black and white, with one silver KEY sewn to its sleeve: KEY-MONO, swaying on a line' },
      { item: 'w:omiyage', story: 'A traveller tips a sack of gifts out by the well: "OH ME, YA GET one, and YA GET one!" — souvenirs for everybody.', image: 'a returning traveller tips out a sack of little gifts: "OH ME, YA GET one, and YA GET one!" — souvenirs for everybody' },
      { item: 'w:hoshii', story: 'A child presses her nose to a stall of sweets near the well: "HO! SHE wants it! SHE wants it!" her mother sighs.', image: 'a child presses her nose to a window full of sweets, and her mother sighs: "HO! SHE wants it! SHE wants it again!"' },
      { item: 'g:ga-hoshii', story: 'Every wanted thing at the market wears a GA badge on a string, never an O: fan GA HO-SHE, kimono GA HO-SHE.', image: 'every wanted thing wears a GA badge on a string, never an O: fan GA HO-SHE, kimono GA HO-SHE' },
      { item: 'w:kasu', story: 'A moneylender at the well counts out CASH to a farmer — "KAS-SOO, it’s only a loan!" — and ties a string to it so it comes back.', image: 'a moneylender hands over a stack of CASH — "KAS-SOO, it’s only a loan!" — and ties a string to it so it comes back' },
      { item: 'w:kariru', story: 'A kangaroo hops up to the well, borrows a bucket and CARRIES it off in its pouch: "CARRY-ROO! I’ll bring it back tomorrow!"', image: 'a kangaroo borrows your umbrella and CARRIES it off in its pouch, calling "CARRY-ROO! I’ll bring it back tomorrow!"' },
    ],
  },
  {
    id: 'p8-stage',
    room: 8,
    map: 'castletown',
    anchor: 'ct-barker',
    name: { jp: 'しばいの ぶたい', en: 'Kabuki Stage' },
    emoji: '🎭',
    memories: [
      { item: 'w:shibai', story: 'The lead actress keeps stopping the play to sell tickets to it, crying "SHE BUY! SHE BUY!" until the drums drown her out.', image: 'an actress keeps stopping her own play to sell tickets for it, crying "SHE BUY! SHE BUY!" until the drums drown her out' },
      { item: 'w:odori', story: 'A dancer twirls across the boards singing "OH, DOE-REE-ME!", fans flashing, sleeves spinning like wheels.', image: 'a dancer twirls with two fans flashing, sleeves spinning like wheels, singing "OH, DOE-REE-ME!" at every turn' },
      { item: 'w:jouzu', story: 'JOE juggles a whole ZOO on the stage — monkeys, plates, a sleepy tortoise — and never drops one. "JOE-ZOO!" the crowd roars. So skilful!', image: 'a man called JOE juggles a whole ZOO — monkeys, plates, a sleepy tortoise — and never drops one, while the crowd roars "JOE-ZOO!" so skilful' },
      { item: 'w:heta', story: 'A clumsy stagehand turns up the HEAT on the smoke machine — "HE-TA!" — and the whole stage disappears in a cough-filled cloud.', image: 'a clumsy cook turns the HEAT up far too high — "HE-TA!" — and burns everything in sight; hopeless at it' },
      { item: 'w:daisuki', story: 'A fan in the front row rolls giant pink DICE down a SKI slope painted on the scenery — every face shows a heart: DICE-SKI, love!', image: 'someone rolls giant pink DICE down a SKI slope, and every face that lands shows a heart: DICE-SKI, true love' },
      { item: 'w:kirai', story: 'A child in the audience spits out a KEY made of RYE bread: "KEE-RYE! I hate it!"', image: 'a child spits out a KEY baked from RYE bread and pulls a face: "KEE-RYE! I hate it! Hate it!"' },
      { item: 'g:ga-suki', story: 'The actors’ likes and dislikes hang on the stage wall, each wearing a GA collar: dango GA loved, dancing GA bad-at. Never an O.', image: 'loved things, hated things, good-at and bad-at things all wear a GA collar, never an O: dango GA loved, dancing GA bad-at' },
    ],
  },
  {
    id: 'p8-dojo',
    room: 8,
    map: 'castletown',
    anchor: 'ct-dojo',
    name: { jp: 'どうじょう', en: 'Dojo Yard' },
    emoji: '🥋',
    memories: [
      { item: 'w:doujou', story: 'Instead of sparring, the students in the yard pound bread DOUGH JOyfully with wooden swords: DOUGH-JO, training hall of bakers.', image: 'students in white uniforms pound bread DOUGH JOyfully with wooden swords — DOUGH-JO — a training hall full of bakers' },
      { item: 'w:katana', story: 'Master Gonzō draws a sword so fast it CUTs ANNA’s apple in half on her head: "CUT-ANNA!" Anna doesn’t even flinch.', image: 'a swordsman draws a curved blade so fast it CUTs ANNA’s apple in half on her head — "CUT-ANNA!" — and she doesn’t flinch' },
      { item: 'w:samurai', story: 'A warrior named SAM eats a loaf of RYE in his armour between bouts: "SAM, YOU, RYE!" his master scolds.', image: 'a warrior named SAM munches a loaf of RYE in full armour, and his master scolds "SAM, YOU, RYE!"' },
      { item: 'w:oshieru', story: 'A teacher raps a RULEr on the dojo post: "OH, SHE-A-RULE!" and teaches the stance again, and again.', image: 'a teacher raps a long RULEr on a post — "OH, SHE-A-RULE!" — and teaches the lesson again, and again' },
      { item: 'w:isshoni', story: 'Two students glued at the knees hop across the yard to the SHOW together: "ISH-SHOW-KNEE!"', image: 'two friends glued together at the KNEES hop off to the SHOW side by side, chanting "ISH-SHOW-KNEE!"' },
      { item: 'w:zehi', story: 'The master’s wife beams from the dojo steps: "ZEH-HEE! By all means, stay for dinner!" — and will not take no.', image: 'a smiling host beams from the steps, "ZEH-HEE! By all means, stay for dinner!" — and will not take no for an answer' },
      { item: 'w:mochiron', story: 'RON stuffs a whole MOCHI rice cake into his mouth in one go: "Of course I can! MOCHI-RON!"', image: 'a boy called RON stuffs a whole MOCHI rice cake in his mouth in one go: "Of course I can! MOCHI-RON!"' },
      { item: 'g:masen-ka', story: 'A shy student holds out a second festival ticket and mumbles "...MASEN KA?" — won’t you come with me?', image: 'a shy student holds out a second festival ticket with a hopeful smile: "...MASEN KA?" — won’t you come with me?' },
      { item: 'g:mashou-ka', story: 'A giant MASHED-potato helper rolls up its sleeves at the dojo door: "MASH-SHOW-KA? Shall I carry that? Shall we go?"', image: 'a giant MASHED-potato helper rolls up its sleeves: "MASH-SHOW-KA? Shall I carry that? Shall we go together?"' },
    ],
  },
  {
    id: 'p8-gate',
    room: 8,
    map: 'castletown',
    anchor: 'ct-tadashi',
    name: { jp: 'おおてもん', en: 'Great Gate' },
    emoji: '🏯',
    memories: [
      { item: 'w:mon', story: 'Tadashi heaves on the castle gate and it MOANs like a tired giant as it swings open: "MOOOAN..."', image: 'a huge wooden gate MOANs like a tired giant as it swings slowly open: "MOOOAN..."' },
      { item: 'w:tono', story: 'A lord in grand robes steps from the gate, and nobody may tread on his TOE: "TOE, NO!" he booms at Tadashi.', image: 'a lord in grand robes stamps his foot and booms "TOE, NO!" — nobody may ever tread on his toe' },
      { item: 'w:shitsureishimasu', story: 'A girl slides open the gatehouse door and bows: "SHE’S SORRY, SHE MUST..." — excuse me for intruding — before she steps in.', image: 'a girl slides open a door, bows low and whispers "SHE’S SORRY, SHE MUST..." — excuse me for intruding — before stepping in' },
      { item: 'w:au', story: 'Two old friends meet at the gate and rush to hug — and bump foreheads: "OW!" Meeting hurts, a little.', image: 'two old friends meet after years and rush to hug — and bump foreheads: "OW!" Meeting hurts, a little' },
      { item: 'g:kenjougo', story: 'Tadashi bows so low his nose touches the gravel and murmurs the humble trio: MY-REE-MASS, OH-REE-MASS, EETA-SHE-MASS — lowering himself, never the lord.', image: 'someone bows so low their nose touches the floor, murmuring the humble trio MY-REE-MASS, OH-REE-MASS, EETA-SHE-MASS — lowering themselves' },
    ],
  },
  {
    id: 'p8-garden',
    room: 8,
    map: 'castletown-garden',
    anchor: 'cg-ayame',
    name: { jp: 'おにわの あずまや', en: 'Garden Pavilion' },
    emoji: '🪴',
    memories: [
      { item: 'w:niwa', story: 'The gardener kneels on the wet moss beside the pavilion: "KNEE... WAH!" — soaked knees, perfect garden.', image: 'a gardener kneels on wet moss — "KNEE... WAH!" — soaked knees among the pines, raked gravel and stone lanterns' },
      { item: 'w:ageru', story: 'An old man in the pavilion gives his hat away to a child: "At my AGE, RUe it? No — take it!" It sails away from him.', image: 'an old man gives his hat away to a passing child — "At my AGE, RUe it? No, take it!" — and it sails away from him' },
      { item: 'w:kureru', story: 'Ayame turns and hands YOU a box of CRAYons — "KOO-RAY-ROO!" — and gifts come flowing toward you, toward you, toward you.', image: 'someone turns and hands YOU a box of CRAYons — "KOO-RAY-ROO!" — and gifts keep flowing toward you' },
      { item: 'w:morau', story: 'You receive gift after gift in the pavilion until the pile topples on your head: "MORE? OW!"', image: 'you receive gift after gift until the pile topples onto your head: "MORE? OW!"' },
      { item: 'g:ageru-kureru', story: 'Two arrows are painted on the pavilion floor: AGE-RU points away from you to others; KOO-RAY-ROO points from others back to you.', image: 'two painted arrows: AGE-RU points away from you toward everyone else; KOO-RAY-ROO points from them back to you' },
      { item: 'g:ni-morau', story: 'The giver at the pavilion wears a NEE badge (or a KARA badge), and you call out "from teacher NEE, MORE-OW!" as the present lands.', image: 'the giver wears a NEE badge, or a KARA badge, and you shout "from teacher NEE, MORE-OW!" as the present lands in your arms' },
    ],
  },
  {
    id: 'p8-keep',
    room: 8,
    map: 'castletown-keep',
    anchor: 'ck-lord',
    name: { jp: 'とのの ざ', en: 'Lord’s Seat' },
    emoji: '👑',
    memories: [
      { item: 'w:irassharu', story: 'A herald announces the lord with a sweep of his fan: "EAR-RASH-ARU! His lordship is here, is coming, is going!"', image: 'a herald sweeps his fan and announces a great person: "EAR-RASH-ARU! Their lordship is here, is coming, is going!"' },
      { item: 'w:meshiagaru', story: 'The lord delicately partakes of a wobbly, MESSY AGAR jelly with golden chopsticks: "MESSY-AGARU", the courtiers whisper respectfully.', image: 'a great lord delicately partakes of a wobbly, MESSY AGAR jelly with golden chopsticks while courtiers whisper "MESSY-AGARU"' },
      { item: 'w:ossharu', story: 'The lord speaks one word, and every courtier gasps "OH-SHA-ROO!" — the lord has spoken — and writes it down.', image: 'a great lord says one word and every courtier gasps "OH-SHA-ROO!" — the great one has spoken — and writes it down' },
      { item: 'g:sonkeigo', story: 'Three golden steps lift the lord’s seat higher: EAR-RASH-ARU, MESSY-AGARU, OH-SHA-ROO — words that raise the other person, never yourself.', image: 'three golden steps lift someone higher: EAR-RASH-ARU, MESSY-AGARU, OH-SHA-ROO — words that raise the other person, never yourself' },
    ],
  },
]
