import type { RegionSprites } from '../types'

const E16 = '................'
/** Pad a half-map to 32 rows (content placed from `top`). */
function rows32(top: number, body: string[]): string[] {
  const out: string[] = []
  for (let i = 0; i < top; i++) out.push(E16)
  out.push(...body)
  while (out.length < 32) out.push(E16)
  return out.slice(0, 32)
}

export const SPRITES: RegionSprites = {
  characters: {
    /** A retainer: shaved pate and topknot, navy kimono, grey hakama, two swords at the hip. */
    samurai: {
      slots: { 7: 'navy', 8: 'woodDark' },
      sideSpan: [2, 12],
      down: [
        '.......kk.......',
        '.......kk.......',
        '.....kffffk.....',
        '....kffffffk....',
        '...kkffffffkk...',
        '...kffffffffk...',
        '...kfkffffkfk...',
        '...ffkffffkfF...',
        '....hffffffh....',
        '...NNNwwwwNNN...',
        '..fNNNNwwNNNNfO.',
        '...yyyyyyyyyyOO.',
        '...SSSSSSSSSS.O.',
        '.....77..77.....',
        '.....88.........',
        '................',
      ],
      up: [
        '.......kk.......',
        '.......kk.......',
        '.....kkkkkk.....',
        '....kkkkkkkk....',
        '...kkkkkkkkkk...',
        '...kkkkkkkkkk...',
        '...kkkkkkkkkk...',
        '...FkkkkkkkkF...',
        '....FFFFFFFF....',
        '...NNNNNNNNNN...',
        '..fNNNNNNNNNNf..',
        '.OOyyyyyyyyyy...',
        '.O.SSSSSSSSSS...',
        '.....77..77.....',
        '.....88.........',
        '................',
      ],
      side: [
        '................',
        '.......kkkkk....',
        '.....kkffffff...',
        '....kkkffffff...',
        '....kkkfffkff...',
        '....kkkfffkff...',
        '....kkFffffff...',
        '.....kffffhf....',
        '......FFFFF.....',
        '....NNNwwNNN....',
        '....NNNNwNNNff..',
        '...OOyyyyyyyO...',
        '..O.SSSSSSSS....',
        '....77...77.....',
        '....88...88.....',
        '................',
      ],
    },

    /** A townswoman in a fine kimono: shimada hair with a gold hairpin, vermilion kimono, gold obi. */
    lady: {
      legRows: [14, 14],
      down: [
        '.....kkkkkk.....',
        '....kkkkkkkky...',
        '...kkkkkkkkkkv..',
        '...kkkkkkkkkk...',
        '..kkkffffffkkk..',
        '..kkffffffffkk..',
        '...kfkffffkfk...',
        '...ffkffffkfF...',
        '....hffffffh....',
        '...vvvwwwwvvV...',
        '..fvvvvwwvvvVf..',
        '...yyyyyyyyyy...',
        '...vvhvvvvhvV...',
        '....vvvvvvvV....',
        '.....ww.........',
        '................',
      ],
      up: [
        '.....kkkkkk.....',
        '...ykkkkkkkk....',
        '..vkkkkkkkkkk...',
        '...kkkkkkkkkk...',
        '..kkkkkkkkkkkk..',
        '..kkkkkkkkkkkk..',
        '...kkkkkkkkkk...',
        '...FkkkkkkkkF...',
        '....FFFFFFFF....',
        '...vvvvvvvvvV...',
        '..fvvvvvvvvvVf..',
        '...yyyyyyyyyy...',
        '...vvvyyyyvvV...',
        '....vvvvvvvV....',
        '.....ww.........',
        '................',
      ],
      side: [
        '....kkkkk.......',
        '...kkkkkkky.....',
        '...kkkkkkkkk....',
        '..kkkkkkkkkk....',
        '..kkkkkffffff...',
        '..kkkkFfffkff...',
        '...kkkFfffkff...',
        '....kkfffhff....',
        '......FFFF......',
        '.....vvwwvV.....',
        '.....vvvvVff....',
        '....yyyyyyy.....',
        '...yyvvhvvV.....',
        '.....vvvvvV.....',
        '.....ww..ww.....',
        '................',
      ],
    },
  },

  enemies: {
    /** A clockwork tea-serving doll gone wrong: bobbed hair, white face, tray and cup, wind-up key. */
    karakuri: {
      sym: true,
      shade: 'vO',
      anim: 'bob',
      rows: rows32(1, [
        '..........kkkkkk',
        '........kkkkkkkk',
        '.......kkkkkkkkk',
        '......kkkkkkkkkk',
        '......kkkkkkkkkk',
        '......kkkwwwwwww',
        '......kkwwwwwwww',
        '......kkwwkkwwww',
        '......kkwwkkwwww',
        '......kkwwwwwwww',
        '......kkwhwwwwwv',
        '.......kkwwwwwww',
        '........kkwwwwww',
        '..........wwwwww',
        '.........vvvwwww',
        '.......vvvvvvwww',
        '......vvvvvvvvww',
        '.....vvvvvvvvvvw',
        '....fvvvvvvvvvvv',
        '....ffVvvvvvvvvv',
        '......yyyyyyyyyy',
        '......yyyyyeyyyy',
        '......vvvvvvvvvv',
        '......vvvhvvvvvv',
        '......vvvvvvvvvv',
        '.....vvvvvvvvvvv',
        '....OOOOOOOOOOOO',
        '....OoooooooooOO',
        '.....kk.....kk..',
      ]),
      patch: [
        // the tea tray and cup, held up in front
        { x: 10, y: 16, rows: ['.....pp.....', '....pccp....', '....pppP....', 'LLLLLLLLLLLL', '.OOOOOOOOOO.'] },
        // the wind-up key in its side
        { x: 0, y: 18, rows: ['s..s', 'ssss', '.ss.', '..ss'] },
      ],
      // its eyes flash red: the doll has gone wrong
      frame1: [
        { x: 10, y: 8, rows: ['xx', 'xx'] },
        { x: 20, y: 8, rows: ['xx', 'xx'] },
      ],
    },

    /** Nurarihyon: a sly old man with a huge gourd-shaped head, fine haori, and a long kiseru pipe. */
    nurarihyon: {
      sym: true,
      shade: 'fN',
      anim: 'bob',
      pivot: 28,
      rows: rows32(1, [
        '...........fffff',
        '.........fffffff',
        '........ffffffff',
        '.......fffffffff',
        '.......fffffffff',
        '......Ffffffffff',
        '......Ffffffffff',
        '......Ffffffffff',
        '......FFffffffff',
        '.......Fffffffff',
        '.......mmFffffff',
        '......mmmFkkffff',
        '......mmmFfkffff',
        '.......mmFffffFf',
        '.......mmFffffff',
        '........mmFffkkk',
        '.........mmmmmmm',
        '..........mmmmmm',
        '.......NNNNmmmmm',
        '.....NNNNNNNNmmm',
        '....NNNNNNNNNNyy',
        '...NNNNNuNNNNNyy',
        '...NNNNNNNNNNNdd',
        '...NNNNNNNNNNNdd',
        '...fNNNNNNNNNNdd',
        '....NNNNNNNNNNdd',
        '....NNNNNNNNNNNN',
        '.....NNNNNNNNNNN',
        '.......kk.......',
        '......OOOO......',
      ]),
      patch: [
        // the long kiseru pipe, smoking
        { x: 24, y: 13, rows: ['....mm..', '...m....', '....m...', '.....yy.', '.....yO.', '....O...', '...O....', '..O.....', '.O......', 'O.......'] },
      ],
      frame1: [{ x: 27, y: 11, rows: ['.mm', 'm..'] }],
    },
  },
}
