/**
 * Region 9 — 雪の寺, the Snowbound Temple. A mountain temple deep in snow
 * where monks copy sutras and keep the old writing alive. The kanji region:
 * sixty kanji taught as items of their own (seasons, the four directions,
 * family, years and weeks, the kanji inside everyday verbs, studying,
 * colours), with how kanji work: on'yomi and kun'yomi, okurigana, compounds,
 * radicals, sound changes (rendaku, small っ), special readings, strokes.
 */
import type { RegionData } from '../types'

export const PACK: RegionData = {
  region: {
    id: 9,
    name: 'The Snowbound Temple',
    jp: '雪の寺',
    reading: 'ゆきのてら',
    tagline: 'Where the monks keep the old writing alive, stroke by stroke.',
    teaches: ['60 kanji with on/kun readings', 'Seasons, directions, family, years', 'How kanji work: compounds, radicals, sound changes'],
    color: '#8fb8de',
    emoji: '❄️',
    pos: { x: 88, y: 32 },
    map: 'snowtemple',
  },

  words: [
    // ── Four Seasons, Four Winds: seasons, directions, snow
    ['haru', '春', 'はる', 'spring', 'noun', '🌸', { alt: ['springtime'] }],
    ['natsu', '夏', 'なつ', 'summer', 'noun', '🌻', { alt: ['summertime'] }],
    ['aki', '秋', 'あき', 'autumn', 'noun', '🍁', { alt: ['fall'] }],
    ['fuyu', '冬', 'ふゆ', 'winter', 'noun', '⛄', { alt: ['wintertime'] }],
    ['kisetsu', '季節', 'きせつ', 'season', 'noun', '🗓️', { alt: ['seasons', 'time of year'] }],
    ['higashi', '東', 'ひがし', 'east', 'noun', '🌅'],
    ['nishi', '西', 'にし', 'west', 'noun', '🌇'],
    ['minami', '南', 'みなみ', 'south', 'noun', '🌴'],
    ['kita', '北', 'きた', 'north', 'noun', '🏔️'],
    ['yuugata', '夕方', 'ゆうがた', 'evening', 'noun', '🌆', { alt: ['dusk', 'early evening'] }],
    ['ooyuki', '大雪', 'おおゆき', 'heavy snow', 'noun', '🌨️', { alt: ['heavy snowfall', 'deep snow'] }],
    ['yukidaruma', '雪だるま', 'ゆきだるま', 'snowman', 'noun', '☃️'],
    ['koori', '氷', 'こおり', 'ice', 'noun', '🧊', { element: 'water' }],
    ['fuyuyasumi', '冬休み', 'ふゆやすみ', 'winter holidays', 'noun', '🛷', { alt: ['winter break', 'winter vacation'] }],
    ['shinshin', 'しんしん', 'しんしん', 'silently (snow falling)', 'adverb', '🤫', { alt: ['silently', 'hushed', 'quietly'] }],

    // ── Family and Temple Folk
    ['chichi', '父', 'ちち', '(my) father', 'noun', '👨', { alt: ['father', 'my father', 'dad'] }],
    ['haha', '母', 'はは', '(my) mother', 'noun', '👩', { alt: ['mother', 'my mother', 'mum', 'mom'] }],
    ['otousan', 'お父さん', 'おとうさん', 'father (polite)', 'noun', '👨‍🦳', { alt: ['father', 'dad', 'someone’s father'] }],
    ['okaasan', 'お母さん', 'おかあさん', 'mother (polite)', 'noun', '👩‍🦳', { alt: ['mother', 'mum', 'mom', 'someone’s mother'] }],
    ['ani', '兄', 'あに', '(my) older brother', 'noun', '👦', { alt: ['older brother', 'big brother', 'my older brother'] }],
    ['oniisan', 'お兄さん', 'おにいさん', 'older brother (polite)', 'noun', '🧑', { alt: ['older brother', 'big brother'] }],
    ['ane', '姉', 'あね', '(my) older sister', 'noun', '👧', { alt: ['older sister', 'big sister', 'my older sister'] }],
    ['oneesan', 'お姉さん', 'おねえさん', 'older sister (polite)', 'noun', '👩‍🦰', { alt: ['older sister', 'big sister'] }],
    ['otouto', '弟', 'おとうと', 'younger brother', 'noun', '👶', { alt: ['little brother', 'my younger brother'] }],
    ['imouto', '妹', 'いもうと', 'younger sister', 'noun', '🎀', { alt: ['little sister', 'my younger sister'] }],
    ['kazoku', '家族', 'かぞく', 'family', 'noun', '👪'],
    ['kyoudai', '兄弟', 'きょうだい', 'siblings', 'noun', '👫', { alt: ['brothers', 'brothers and sisters'] }],
    ['ryoushin', '両親', 'りょうしん', 'parents', 'noun', '👨‍👩‍👧', { alt: ['both parents', 'mother and father'] }],
    ['deshi', '弟子', 'でし', 'apprentice', 'noun', '🧑‍🎓', { alt: ['disciple', 'pupil'] }],
    ['obousan', 'お坊さん', 'おぼうさん', 'Buddhist monk', 'noun', '🧘', { alt: ['monk', 'buddhist priest'] }],

    // ── Years and Weeks
    ['toshi', '年', 'とし', 'year', 'noun', '🎋', { alt: ['age', 'a year'] }],
    ['kotoshi', '今年', 'ことし', 'this year', 'noun', '📅'],
    ['kyonen', '去年', 'きょねん', 'last year', 'noun', '⏪'],
    ['rainen', '来年', 'らいねん', 'next year', 'noun', '⏩'],
    ['maitoshi', '毎年', 'まいとし', 'every year', 'adverb', '🔁', { alt: ['yearly', 'annually'] }],
    ['shinnen', '新年', 'しんねん', 'New Year', 'noun', '🎍', { alt: ['the new year'] }],
    ['konshuu', '今週', 'こんしゅう', 'this week', 'noun', '🗓️'],
    ['raishuu', '来週', 'らいしゅう', 'next week', 'noun', '📆'],
    ['maishuu', '毎週', 'まいしゅう', 'every week', 'adverb', '🔂', { alt: ['weekly'] }],
    ['kongetsu', '今月', 'こんげつ', 'this month', 'noun', '🌙'],
    ['raigetsu', '来月', 'らいげつ', 'next month', 'noun', '🌛'],
    ['gozen', '午前', 'ごぜん', 'a.m.', 'noun', '🌄', { alt: ['am', 'morning', 'before noon'] }],
    ['gogo', '午後', 'ごご', 'p.m.', 'noun', '🕒', { alt: ['pm', 'afternoon'] }],
    ['maiasa', '毎朝', 'まいあさ', 'every morning', 'adverb', '🌞'],
    ['mae-before', '前', 'まえ', 'before', 'noun', '⏮️', { alt: ['in front', 'front', 'ago'] }],

    // ── The Scriptorium: studying, writing, the temple
    ['kanji', '漢字', 'かんじ', 'kanji', 'noun', '🈳', { alt: ['chinese characters', 'chinese character'] }],
    ['ji-letter', '字', 'じ', 'character', 'noun', '✍️', { alt: ['letter', 'handwriting', 'written character'] }],
    ['benkyou', '勉強', 'べんきょう', 'study', 'noun', '📚', { alt: ['studying'] }],
    ['renshuu', '練習', 'れんしゅう', 'practice', 'noun', '🏋️', { alt: ['practise', 'training'] }],
    ['narau', '習う', 'ならう', 'learn (from a teacher)', 'verb', '🧑‍🏫', { masu: '習います', alt: ['learn', 'to learn', 'take lessons'] }],
    ['manabu', '学ぶ', 'まなぶ', 'study (deeply)', 'verb', '🎓', { masu: '学びます', alt: ['learn', 'study', 'to study', 'to learn'] }],
    ['bun-sentence', '文', 'ぶん', 'sentence', 'noun', '📝', { alt: ['text'] }],
    ['sakubun', '作文', 'さくぶん', 'composition', 'noun', '📄', { alt: ['essay', 'written composition'] }],
    ['shodou', '書道', 'しょどう', 'calligraphy', 'noun', '🖌️', { alt: ['the way of writing'] }],
    ['onyomi', '音読み', 'おんよみ', 'on-reading', 'noun', '🀄', { alt: ['onyomi', 'on reading', 'chinese reading'] }],
    ['kunyomi', '訓読み', 'くんよみ', 'kun-reading', 'noun', '🗾', { alt: ['kunyomi', 'kun reading', 'japanese reading'] }],
    ['kane', '鐘', 'かね', 'temple bell', 'noun', '🔔', { element: 'metal', alt: ['bell', 'big bell'] }],
    ['okyou', 'お経', 'おきょう', 'sutra', 'noun', '📿', { alt: ['sutras', 'buddhist scripture'] }],
    ['myouji', '名字', 'みょうじ', 'surname', 'noun', '🪪', { alt: ['family name', 'last name'] }],
    ['ichigyou', '一行', 'いちぎょう', 'one line (of text)', 'noun', '➖', { alt: ['one line', 'a line', 'a line of text'] }],
  ],

  kanji: [
    // seasons
    { char: '春', meaning: 'spring', on: ['シュン'], kun: ['はる'], emoji: '🌸', words: [['春', 'はる', 'spring'], ['春休み', 'はるやすみ', 'spring break'], ['青春', 'せいしゅん', 'youth']] },
    { char: '夏', meaning: 'summer', on: ['カ', 'ゲ'], kun: ['なつ'], emoji: '🌻', words: [['夏', 'なつ', 'summer'], ['夏休み', 'なつやすみ', 'summer holidays'], ['初夏', 'しょか', 'early summer']] },
    { char: '秋', meaning: 'autumn', on: ['シュウ'], kun: ['あき'], emoji: '🍁', words: [['秋', 'あき', 'autumn'], ['春夏秋冬', 'しゅんかしゅうとう', 'the four seasons'], ['秋分', 'しゅうぶん', 'autumn equinox']] },
    { char: '冬', meaning: 'winter', on: ['トウ'], kun: ['ふゆ'], emoji: '⛄', words: [['冬', 'ふゆ', 'winter'], ['冬休み', 'ふゆやすみ', 'winter holidays'], ['冬眠', 'とうみん', 'hibernation']] },
    // the four directions
    { char: '東', meaning: 'east', on: ['トウ'], kun: ['ひがし'], emoji: '🌅', words: [['東', 'ひがし', 'east'], ['東京', 'とうきょう', 'Tokyo (eastern capital)'], ['東口', 'ひがしぐち', 'east exit']] },
    { char: '西', meaning: 'west', on: ['セイ', 'サイ'], kun: ['にし'], emoji: '🌇', words: [['西', 'にし', 'west'], ['東西', 'とうざい', 'east and west'], ['西口', 'にしぐち', 'west exit']] },
    { char: '南', meaning: 'south', on: ['ナン'], kun: ['みなみ'], emoji: '🌴', words: [['南', 'みなみ', 'south'], ['南北', 'なんぼく', 'north and south'], ['南口', 'みなみぐち', 'south exit']] },
    { char: '北', meaning: 'north', on: ['ホク'], kun: ['きた'], emoji: '🏔️', words: [['北', 'きた', 'north'], ['北口', 'きたぐち', 'north exit'], ['北海道', 'ほっかいどう', 'Hokkaido']] },
    // family
    { char: '父', meaning: 'father', on: ['フ'], kun: ['ちち'], emoji: '👨', words: [['父', 'ちち', '(my) father'], ['お父さん', 'おとうさん', 'father (polite)'], ['父母', 'ふぼ', 'father and mother']] },
    { char: '母', meaning: 'mother', on: ['ボ'], kun: ['はは'], emoji: '👩', words: [['母', 'はは', '(my) mother'], ['お母さん', 'おかあさん', 'mother (polite)'], ['母語', 'ぼご', 'mother tongue']] },
    { char: '兄', meaning: 'older brother', on: ['キョウ', 'ケイ'], kun: ['あに'], emoji: '👦', words: [['兄', 'あに', '(my) older brother'], ['お兄さん', 'おにいさん', 'older brother (polite)'], ['兄弟', 'きょうだい', 'siblings']] },
    { char: '弟', meaning: 'younger brother', on: ['ダイ', 'テイ', 'デ'], kun: ['おとうと'], emoji: '👶', words: [['弟', 'おとうと', 'younger brother'], ['兄弟', 'きょうだい', 'siblings'], ['弟子', 'でし', 'apprentice']] },
    { char: '姉', meaning: 'older sister', on: ['シ'], kun: ['あね'], emoji: '👧', words: [['姉', 'あね', '(my) older sister'], ['お姉さん', 'おねえさん', 'older sister (polite)'], ['姉妹', 'しまい', 'sisters']] },
    { char: '妹', meaning: 'younger sister', on: ['マイ'], kun: ['いもうと'], emoji: '🎀', words: [['妹', 'いもうと', 'younger sister'], ['姉妹', 'しまい', 'sisters']] },
    // years, weeks, hours
    { char: '年', meaning: 'year', on: ['ネン'], kun: ['とし'], emoji: '🎋', words: [['年', 'とし', 'year; age'], ['来年', 'らいねん', 'next year'], ['今年', 'ことし', 'this year (special reading)']] },
    { char: '週', meaning: 'week', on: ['シュウ'], kun: [], emoji: '📆', words: [['今週', 'こんしゅう', 'this week'], ['来週', 'らいしゅう', 'next week'], ['毎週', 'まいしゅう', 'every week']] },
    { char: '午', meaning: 'noon', on: ['ゴ'], kun: [], emoji: '🕛', words: [['午前', 'ごぜん', 'a.m.'], ['午後', 'ごご', 'p.m.'], ['正午', 'しょうご', 'noon']] },
    { char: '前', meaning: 'before, front', on: ['ゼン'], kun: ['まえ'], emoji: '⏮️', words: [['前', 'まえ', 'before; in front'], ['午前', 'ごぜん', 'a.m.'], ['名前', 'なまえ', 'name']] },
    { char: '後', meaning: 'after, behind', on: ['ゴ', 'コウ'], kun: ['あと', 'うしろ', 'のち'], emoji: '⏭️', words: [['後', 'あと', 'after; later'], ['後ろ', 'うしろ', 'behind'], ['午後', 'ごご', 'p.m.']] },
    { char: '毎', meaning: 'every', on: ['マイ'], kun: [], emoji: '🔁', words: [['毎日', 'まいにち', 'every day'], ['毎年', 'まいとし', 'every year'], ['毎朝', 'まいあさ', 'every morning']] },
    { char: '朝', meaning: 'morning', on: ['チョウ'], kun: ['あさ'], emoji: '🌞', words: [['朝', 'あさ', 'morning'], ['毎朝', 'まいあさ', 'every morning'], ['朝食', 'ちょうしょく', 'breakfast']] },
    { char: '夜', meaning: 'night', on: ['ヤ'], kun: ['よる', 'よ'], emoji: '🌙', words: [['夜', 'よる', 'night'], ['今夜', 'こんや', 'tonight'], ['夜中', 'よなか', 'the middle of the night']] },
    { char: '夕', meaning: 'evening', on: ['セキ'], kun: ['ゆう'], emoji: '🌆', words: [['夕方', 'ゆうがた', 'evening'], ['夕日', 'ゆうひ', 'the setting sun'], ['七夕', 'たなばた', 'the Star Festival (special reading)']] },
    { char: '方', meaning: 'direction, way, person', on: ['ホウ'], kun: ['かた'], emoji: '🧭', words: [['夕方', 'ゆうがた', 'evening'], ['方', 'かた', 'person (polite)'], ['方向', 'ほうこう', 'direction']] },
    // the kanji inside everyday verbs
    { char: '見', meaning: 'see', on: ['ケン'], kun: ['みる'], emoji: '👀', words: [['見る', 'みる', 'to see'], ['花見', 'はなみ', 'flower viewing'], ['見学', 'けんがく', 'a study visit']] },
    { char: '行', meaning: 'go; a line of text', on: ['コウ', 'ギョウ'], kun: ['いく', 'ゆく', 'おこなう'], emoji: '🚶', words: [['行く', 'いく', 'to go'], ['一行', 'いちぎょう', 'one line (of text)'], ['旅行', 'りょこう', 'a trip']] },
    { char: '来', meaning: 'come', on: ['ライ'], kun: ['くる'], emoji: '🏃', words: [['来る', 'くる', 'to come'], ['来年', 'らいねん', 'next year'], ['来週', 'らいしゅう', 'next week']] },
    { char: '食', meaning: 'eat, food', on: ['ショク'], kun: ['たべる'], emoji: '🍽️', words: [['食べる', 'たべる', 'to eat'], ['食事', 'しょくじ', 'a meal'], ['朝食', 'ちょうしょく', 'breakfast']] },
    { char: '飲', meaning: 'drink', on: ['イン'], kun: ['のむ'], emoji: '🍵', words: [['飲む', 'のむ', 'to drink'], ['飲み物', 'のみもの', 'a drink'], ['飲食', 'いんしょく', 'eating and drinking']] },
    { char: '書', meaning: 'write', on: ['ショ'], kun: ['かく'], emoji: '✍️', words: [['書く', 'かく', 'to write'], ['書道', 'しょどう', 'calligraphy'], ['辞書', 'じしょ', 'dictionary']] },
    { char: '話', meaning: 'talk, story', on: ['ワ'], kun: ['はなす', 'はなし'], emoji: '🗣️', words: [['話す', 'はなす', 'to speak'], ['話', 'はなし', 'a story; a talk'], ['電話', 'でんわ', 'telephone']] },
    { char: '読', meaning: 'read', on: ['ドク'], kun: ['よむ'], emoji: '📖', words: [['読む', 'よむ', 'to read'], ['音読み', 'おんよみ', 'on-reading'], ['読書', 'どくしょ', 'reading books']] },
    { char: '買', meaning: 'buy', on: ['バイ'], kun: ['かう'], emoji: '🛒', words: [['買う', 'かう', 'to buy'], ['買い物', 'かいもの', 'shopping'], ['売買', 'ばいばい', 'buying and selling']] },
    { char: '作', meaning: 'make', on: ['サク', 'サ'], kun: ['つくる'], emoji: '🔨', words: [['作る', 'つくる', 'to make'], ['作文', 'さくぶん', 'composition'], ['作家', 'さっか', 'writer']] },
    // studying and writing
    { char: '学', meaning: 'study, learning', on: ['ガク'], kun: ['まなぶ'], emoji: '🎓', words: [['学ぶ', 'まなぶ', 'to study'], ['学校', 'がっこう', 'school'], ['大学', 'だいがく', 'university']] },
    { char: '校', meaning: 'school', on: ['コウ'], kun: [], emoji: '🏫', words: [['学校', 'がっこう', 'school'], ['高校', 'こうこう', 'high school'], ['校長', 'こうちょう', 'head teacher']] },
    { char: '字', meaning: 'character, letter', on: ['ジ'], kun: [], emoji: '🔤', words: [['字', 'じ', 'character; handwriting'], ['漢字', 'かんじ', 'kanji'], ['名字', 'みょうじ', 'surname']] },
    { char: '漢', meaning: 'China (of old), Chinese', on: ['カン'], kun: [], emoji: '🀄', words: [['漢字', 'かんじ', 'kanji'], ['漢文', 'かんぶん', 'classical Chinese writing']] },
    { char: '語', meaning: 'word, language', on: ['ゴ'], kun: ['かたる'], emoji: '💬', words: [['日本語', 'にほんご', 'Japanese (language)'], ['英語', 'えいご', 'English'], ['語る', 'かたる', 'to tell (a story)']] },
    { char: '文', meaning: 'sentence, writing', on: ['ブン', 'モン'], kun: ['ふみ'], emoji: '📝', words: [['文', 'ぶん', 'sentence'], ['作文', 'さくぶん', 'composition'], ['文字', 'もじ', 'letter, character']] },
    { char: '名', meaning: 'name', on: ['メイ', 'ミョウ'], kun: ['な'], emoji: '🪪', words: [['名前', 'なまえ', 'name'], ['有名', 'ゆうめい', 'famous'], ['名字', 'みょうじ', 'surname']] },
    { char: '習', meaning: 'learn', on: ['シュウ'], kun: ['ならう'], emoji: '🧑‍🏫', words: [['習う', 'ならう', 'to learn'], ['練習', 'れんしゅう', 'practice'], ['学習', 'がくしゅう', 'study, learning']] },
    { char: '勉', meaning: 'effort', on: ['ベン'], kun: [], emoji: '💪', words: [['勉強', 'べんきょう', 'study']] },
    { char: '強', meaning: 'strong', on: ['キョウ', 'ゴウ'], kun: ['つよい'], emoji: '🏋️', words: [['強い', 'つよい', 'strong'], ['勉強', 'べんきょう', 'study'], ['強力', 'きょうりょく', 'powerful']] },
    { char: '道', meaning: 'road, way', on: ['ドウ'], kun: ['みち'], emoji: '🛤️', words: [['道', 'みち', 'road'], ['書道', 'しょどう', 'calligraphy'], ['北海道', 'ほっかいどう', 'Hokkaido']] },
    { char: '友', meaning: 'friend', on: ['ユウ'], kun: ['とも'], emoji: '🤝', words: [['友達', 'ともだち', 'friend'], ['友人', 'ゆうじん', 'friend (formal)'], ['親友', 'しんゆう', 'best friend']] },
    { char: '新', meaning: 'new', on: ['シン'], kun: ['あたらしい'], emoji: '✨', words: [['新しい', 'あたらしい', 'new'], ['新年', 'しんねん', 'New Year'], ['新聞', 'しんぶん', 'newspaper']] },
    { char: '音', meaning: 'sound', on: ['オン', 'イン'], kun: ['おと', 'ね'], emoji: '🎵', words: [['音', 'おと', 'sound'], ['音読み', 'おんよみ', 'on-reading'], ['音楽', 'おんがく', 'music']] },
    { char: '長', meaning: 'long; chief', on: ['チョウ'], kun: ['ながい'], emoji: '📏', words: [['長い', 'ながい', 'long'], ['校長', 'こうちょう', 'head teacher'], ['社長', 'しゃちょう', 'company president']] },
    { char: '高', meaning: 'tall, high', on: ['コウ'], kun: ['たかい'], emoji: '🗼', words: [['高い', 'たかい', 'tall; expensive'], ['高校', 'こうこう', 'high school'], ['最高', 'さいこう', 'the best']] },
    { char: '早', meaning: 'early', on: ['ソウ'], kun: ['はやい'], emoji: '🐓', words: [['早い', 'はやい', 'early'], ['早く', 'はやく', 'early; quickly'], ['早朝', 'そうちょう', 'early morning']] },
    { char: '何', meaning: 'what', on: ['カ'], kun: ['なに', 'なん'], emoji: '❓', words: [['何', 'なに', 'what'], ['何時', 'なんじ', 'what time'], ['何人', 'なんにん', 'how many people']] },
    { char: '歌', meaning: 'song', on: ['カ'], kun: ['うた', 'うたう'], emoji: '🎶', words: [['歌', 'うた', 'song'], ['歌う', 'うたう', 'to sing'], ['歌手', 'かしゅ', 'singer']] },
    { char: '紙', meaning: 'paper', on: ['シ'], kun: ['かみ'], emoji: '📜', words: [['紙', 'かみ', 'paper'], ['手紙', 'てがみ', 'letter (mail)'], ['和紙', 'わし', 'Japanese paper']] },
    // colours
    { char: '赤', meaning: 'red', on: ['セキ'], kun: ['あかい'], emoji: '🟥', words: [['赤い', 'あかい', 'red'], ['赤ちゃん', 'あかちゃん', 'baby'], ['赤道', 'せきどう', 'the equator']] },
    { char: '青', meaning: 'blue', on: ['セイ'], kun: ['あおい'], emoji: '🟦', words: [['青い', 'あおい', 'blue'], ['青空', 'あおぞら', 'blue sky'], ['青年', 'せいねん', 'young man']] },
    { char: '黒', meaning: 'black', on: ['コク'], kun: ['くろい'], emoji: '⬛', words: [['黒い', 'くろい', 'black'], ['黒板', 'こくばん', 'blackboard']] },
    { char: '色', meaning: 'colour', on: ['ショク', 'シキ'], kun: ['いろ'], emoji: '🎨', words: [['色', 'いろ', 'colour'], ['茶色', 'ちゃいろ', 'brown'], ['景色', 'けしき', 'scenery']] },
    // the temple in the snow
    { char: '雪', meaning: 'snow', on: ['セツ'], kun: ['ゆき'], emoji: '❄️', words: [['雪', 'ゆき', 'snow'], ['大雪', 'おおゆき', 'heavy snow'], ['雪だるま', 'ゆきだるま', 'snowman']] },
    { char: '寺', meaning: 'temple', on: ['ジ'], kun: ['てら'], emoji: '🛕', words: [['寺', 'てら', 'temple'], ['山寺', 'やまでら', 'mountain temple'], ['寺院', 'じいん', 'temple (formal)']] },
  ],

  grammar: [
    { id: 'kj-onyomi', region: 9, jp: '音読み', say: "on'yomi", en: 'a kanji’s Chinese-derived reading; written in katakana in dictionaries and used mostly in compounds', example: { jp: '学校（がっこう）、来年（らいねん）', en: 'school, next year: both read with on’yomi' } },
    { id: 'kj-kunyomi', region: 9, jp: '訓読み', say: "kun'yomi", en: 'a kanji’s native Japanese reading; used when the kanji stands alone or carries okurigana', example: { jp: '春（はる）、書く（かく）', en: 'spring, to write: both read with kun’yomi' } },
    { id: 'kj-okurigana', region: 9, jp: '送りがな', say: 'okurigana', en: 'the kana after a kanji stem; they carry the changing ending of verbs and adjectives', example: { jp: '書く → 書きます、新しい → 新しくない', en: 'write → writes (polite); new → not new' } },
    { id: 'kj-jukugo', region: 9, jp: '熟語', say: 'jukugo', en: 'a compound of two or more kanji; compounds usually take on’yomi', example: { jp: '春（はる）＋夏（なつ）… → 春夏秋冬（しゅんかしゅうとう）', en: 'spring, summer… → the four seasons' } },
    { id: 'kj-radical', region: 9, jp: '部首', say: 'bushu', en: 'a kanji’s radical (key part) hints at its meaning: 言 speech, 氵 water, 女 woman, 日 sun, 木 tree', example: { jp: '話・語・読 は ぜんぶ「言」', en: 'talk, language and read all hold 言 (speech)' } },
    { id: 'kj-rendaku', region: 9, jp: '連濁', say: 'rendaku', en: 'in a compound, the second part often gets voiced: か→が, て→で, そ→ぞ', example: { jp: '山（やま）＋寺（てら）→ 山寺（やまでら）', en: 'mountain + temple → mountain temple' } },
    { id: 'kj-sokuon', region: 9, jp: '促音化', say: 'sokuon-ka', en: 'in a compound a final く・つ sound can shrink into a small っ', example: { jp: '学（がく）＋校（こう）→ 学校（がっこう）', en: 'learning + school → school' } },
    { id: 'kj-jukujikun', region: 9, jp: '特別な読み', say: 'tokubetsu na yomi', en: 'some words are read as a whole, not kanji by kanji', example: { jp: '今年（ことし）、七夕（たなばた）、大人（おとな）', en: 'this year, the Star Festival, adult' } },
    { id: 'kj-stroke-order', region: 9, jp: '筆順', say: 'hitsujun', en: 'stroke order: top before bottom, left before right; a crossing horizontal usually comes before the vertical', example: { jp: '十：一 → 丨', en: 'ten: the horizontal first, then the vertical' } },
    { id: 'kj-stroke-count', region: 9, jp: '画数', say: 'kakusū', en: 'counting strokes: each separate pen movement is one stroke (a dictionary sorts kanji by it)', example: { jp: '雪 は 十一画', en: 'snow has eleven strokes' } },
    { id: 'kj-noma', region: 9, jp: '々', say: 'noma', en: 'the repeat mark: writes the same kanji again (often with a sound change)', example: { jp: '人々（ひとびと）、時々（ときどき）', en: 'people, sometimes' } },
    { id: 'kj-family', region: 9, jp: '父／お父さん', say: 'chichi / otōsan', en: 'humble words for your own family (父・母・兄・姉), polite お〜さん for other people’s family', example: { jp: 'わたしの 母は 先生です。あなたの お母さんは？', en: 'My mother is a teacher. And your mother?' } },
    { id: 'kj-time-ni', region: 9, jp: '来年・毎朝（に なし）', say: 'no ni after relative time', en: 'relative time words (今年, 来週, 毎朝) take no に; clock times and dates do (七時に)', example: { jp: '来年 寺へ 行きます。七時に おきます。', en: 'I’ll go to the temple next year. I get up at seven.' } },
  ],

  sentences: [
    { id: 'sn1', en: 'I study kanji every day.', tokens: ['毎日', '漢字', 'を', '勉強します'], distractors: ['が', '練習'], region: 9, hint: '毎日 needs no particle; what you study takes を.' },
    { id: 'sn2', en: 'My older sister is a teacher.', tokens: ['姉', 'は', '先生', 'です'], distractors: ['お姉さん', 'を'], region: 9, hint: 'Talking about your own sister to others, use the humble 姉 (あね).' },
    { id: 'sn3', en: 'I will go to the temple next year.', tokens: ['来年', '寺', 'に', '行きます'], alts: [['来年', '寺', 'へ', '行きます']], distractors: ['去年', 'を'], region: 9, hint: 'Relative time words like 来年 take no に; the destination takes に or へ.' },
    { id: 'sn4', en: 'Snow falls in winter.', tokens: ['冬', 'に', '雪', 'が', '降ります'], alts: [['冬', 'は', '雪', 'が', '降ります']], distractors: ['夏', 'を'], region: 9, hint: 'Seasons can take に (in winter); the snow that falls takes が.' },
    { id: 'sn5', en: 'The temple is north of the mountain.', tokens: ['寺', 'は', '山', 'の', '北', 'に', 'あります'], distractors: ['南', 'います'], region: 9, hint: 'X の 北 = north of X. Buildings use あります.' },
    { id: 'sn6', en: 'My younger brother practises calligraphy every week.', tokens: ['弟', 'は', '毎週', '書道', 'を', '練習します'], distractors: ['兄', 'に'], region: 9, hint: '弟 is a younger brother; 毎週 needs no particle.' },
    { id: 'sn7', en: 'I write my name in kanji.', tokens: ['漢字', 'で', '名前', 'を', '書きます'], alts: [['名前', 'を', '漢字', 'で', '書きます']], distractors: ['に', '読みます'], region: 9, hint: 'The means (in kanji) takes で; the thing written takes を.' },
    { id: 'sn8', en: 'In the morning I read the sutra.', tokens: ['朝', 'お経', 'を', '読みます'], distractors: ['に', '書きます'], region: 9, hint: '朝 is a relative time word: no に needed.' },
    { id: 'sn9', en: 'I learn kanji from the monk.', tokens: ['お坊さん', 'に', '漢字', 'を', '習います'], distractors: ['で', '教えます'], region: 9, hint: 'With 習う, the teacher takes に: お坊さんに 習います.' },
    { id: 'sn10', en: 'Winter holidays start next week.', tokens: ['冬休み', 'は', '来週', 'から', 'です'], distractors: ['去年', 'まで'], region: 9, hint: 'から = from (a starting point in time).' },
    { id: 'sn11', en: 'I drink tea in the afternoon.', tokens: ['午後', 'お茶', 'を', '飲みます'], alts: [['お茶', 'を', '午後', '飲みます']], distractors: ['午前', 'で'], region: 9, hint: '午後 = p.m. / afternoon. It needs no に here.' },
    { id: 'sn12', en: 'Every year we make a snowman.', tokens: ['毎年', '雪だるま', 'を', '作ります'], distractors: ['に', '見ます'], region: 9, hint: '毎年 takes no particle; what you make takes を.' },
    { id: 'sn13', en: 'The sound of the bell is beautiful.', tokens: ['鐘', 'の', '音', 'は', 'きれい', 'です'], distractors: ['が', '歌'], region: 9, hint: '鐘の音 = the bell’s sound; の links the two nouns.' },
  ],

  runes: [
    { id: 'sr1', jp: '春夏秋冬', reading: 'しゅんかしゅうとう', answer: 'The four seasons.', wrong: ['Spring has come at last.', 'Summer and autumn only.'], region: 9 },
    { id: 'sr2', jp: '東口は こちらです', reading: 'ひがしぐちは こちらです', answer: 'The east exit is this way.', wrong: ['The west exit is this way.', 'The east gate is closed.'], region: 9 },
    { id: 'sr3', jp: '午後三時に 鐘を つきます', reading: 'ごごさんじに かねを つきます', answer: 'We strike the bell at 3 p.m.', wrong: ['We strike the bell at 3 a.m.', 'The bell rang three times.'], region: 9 },
    { id: 'sr4', jp: 'わたしの 兄弟は 三人です', reading: 'わたしの きょうだいは さんにんです', answer: 'I have three siblings.', wrong: ['My older brother is three.', 'Three monks are my teachers.'], region: 9 },
    { id: 'sr5', jp: '毎年 冬に 雪だるまを 作ります', reading: 'まいとし ふゆに ゆきだるまを つくります', answer: 'Every winter we make a snowman.', wrong: ['Last winter we made a snowman.', 'The snowman melts every spring.'], region: 9 },
    { id: 'sr6', jp: '漢字の 音読みと 訓読み', reading: 'かんじの おんよみと くんよみ', answer: 'The on-readings and kun-readings of kanji.', wrong: ['The sounds and meanings of kana.', 'Reading kanji aloud and writing them.'], region: 9 },
    { id: 'sr7', jp: '北の 山寺で 書道を 習います', reading: 'きたの やまでらで しょどうを ならいます', answer: 'I learn calligraphy at the mountain temple in the north.', wrong: ['I teach calligraphy at the temple in the south.', 'I buy brushes at the northern market.'], region: 9 },
    { id: 'sr8', jp: '妹は 今年 七さいです', reading: 'いもうとは ことし ななさいです', answer: 'My younger sister is seven this year.', wrong: ['My older sister is seven this year.', 'My younger sister was seven last year.'], region: 9 },
    { id: 'sr9', jp: '来週の 午前に 新年の お経を 読みます', reading: 'らいしゅうの ごぜんに しんねんの おきょうを よみます', answer: 'Next week, in the morning, we read the New Year sutra.', wrong: ['This week, in the afternoon, we read the New Year sutra.', 'Next year we will write a new sutra.'], region: 9 },
  ],

  readings: {
    勉強します: 'べんきょうします',
    練習します: 'れんしゅうします',
    降ります: 'ふります',
    音: 'おと',
    教えます: 'おしえます',
    お茶: 'おちゃ',
    毎日: 'まいにち',
    朝: 'あさ',
    歌: 'うた',
  },

  npcs: [
    {
      id: 'kuu',
      name: 'Kuu the Young Monk',
      jp: 'わかい おぼうさんの くう',
      emoji: '🧑‍🦲',
      region: 9,
      personality: 'Earnest young monk who keeps the temple’s guest register. Writes every visitor’s name in his best brush hand, worries about getting stroke order wrong, and is secretly proud that his own monk name, 空, means “sky”.',
      politeness: 'polite',
      color: '#8fb8de',
      interests: ['calligraphy', 'kanji readings', 'the seasons at the temple', 'where travellers come from'],
      greeting: { jp: 'ようこそ、おまいりですか？', en: 'Welcome. Have you come to pray?' },
    },
  ],

  scenarios: [
    {
      id: 'snowtemple-register',
      npcId: 'kuu',
      region: 9,
      translations: 'hint',
      start: 'greet',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Kuu keeps the temple’s guest register. Every visitor must be written in, properly.',
        'He will ask where you came from (東西南北), what season it is, and about your family (兄 or お兄さん?).',
        'Then he tests your reading of a compound or two. Wrong answers cost a ❤️.',
      ],
      nodes: {
        greet: {
          id: 'greet',
          line: { jp: 'ようこそ、雪の 寺へ。ぼくは くうです。', en: 'Welcome to the Snowbound Temple. I’m Kuu.' },
          kana: 'ようこそ、ゆきの てらへ。ぼくは くうです。',
          wordIds: ['tera', 'yuki'],
          hint: 'Entering someone’s place, a polite greeting fits: こんにちは, or おじゃまします (“sorry to intrude”).',
          next: 'from',
          options: [
            { jp: 'おじゃまします。', en: 'Sorry to intrude. (said on entering)', correct: true, reply: { jp: 'どうぞ、どうぞ。くつの 雪を はらって くださいね。', en: 'Please, come in. Brush the snow off your shoes.' }, effects: { trust: 1 } },
            { jp: 'はじめまして。よろしく おねがいします。', en: 'Nice to meet you. Please treat me well.', correct: true, reply: { jp: 'こちらこそ、よろしく おねがいします。', en: 'The pleasure is mine.' } },
            { jp: 'おやすみなさい。', en: 'Good night.', correct: false, reply: { jp: 'まだ あさですよ。…ねむいんですか？', en: 'It’s still morning. …Are you sleepy?' }, note: 'おやすみなさい is for bedtime. On arriving, say こんにちは or おじゃまします.' },
          ],
        },
        from: {
          id: 'from',
          line: { jp: 'ちょうめんに 書きますね。どちらから 来ましたか？', en: 'I’ll write you into the register. Where have you come from?' },
          kana: 'ちょうめんに かきますね。どちらから きましたか？',
          wordIds: ['minami', 'kita'],
          hint: 'The Castle Town lies below the mountain, to the south: 南 (みなみ). “Came from” is 〜から 来ました.',
          next: 'season',
          options: [
            { jp: '南の 城下町から 来ました。', kana: 'みなみの じょうかまちから きました。', en: 'I came from the Castle Town to the south.', correct: true, wordIds: ['minami', 'kuru'], reply: { jp: '南から！ あの 長い さかを のぼって きたんですね。', en: 'From the south! You climbed that long slope.' }, effects: { trust: 1 } },
            { jp: '北の 城下町から 来ました。', kana: 'きたの じょうかまちから きました。', en: 'I came from the Castle Town to the north.', correct: false, wordIds: ['kita'], reply: { jp: '北？ 北には 雪と 山しか ありませんよ。', en: 'North? There’s nothing up north but snow and mountains.' }, note: '北 (きた) is north. The Castle Town is to the south: 南 (みなみ).' },
            { jp: '南の 城下町へ 行きます。', kana: 'みなみの じょうかまちへ いきます。', en: 'I’m going to the Castle Town to the south.', correct: false, wordIds: ['iku'], reply: { jp: 'えっ、もう かえるんですか？', en: 'What, you’re leaving already?' }, note: '〜へ 行きます means “go to”. Where you came from is 〜から 来ました.' },
          ],
        },
        season: {
          id: 'season',
          line: { jp: 'つぎは 日づけ。いまの 季節は？', en: 'Next, the date. What season is it now?' },
          kana: 'つぎは ひづけ。いまの きせつは？',
          wordIds: ['kisetsu', 'fuyu'],
          hint: 'Look outside: snow everywhere. Winter is 冬 (ふゆ).',
          next: 'family',
          options: [
            { jp: '冬です。', kana: 'ふゆです。', en: 'It’s winter.', correct: true, wordIds: ['fuyu'], reply: { jp: 'はい、冬です。ここは 一年の はんぶんが 冬ですけどね。', en: 'Yes, winter. Though here, half the year is winter.' } },
            { jp: '夏です。', kana: 'なつです。', en: 'It’s summer.', correct: false, wordIds: ['natsu'], reply: { jp: '夏！？ そとを 見て ください！', en: 'Summer?! Look outside!' }, note: '夏 (なつ) is summer. With all this snow, it’s 冬 (ふゆ), winter.' },
            { jp: '春です。', kana: 'はるです。', en: 'It’s spring.', correct: false, wordIds: ['haru'], reply: { jp: '春は まだまだ です。さくらも ねています。', en: 'Spring is a long way off. Even the cherry trees are asleep.' }, note: '春 (はる) is spring. Snow on the ground: 冬 (ふゆ).' },
          ],
        },
        family: {
          id: 'family',
          line: { jp: 'ごかぞくは？ 兄弟は いますか？', en: 'And your family? Do you have siblings?' },
          kana: 'ごかぞくは？ きょうだいは いますか？',
          wordIds: ['kazoku', 'kyoudai'],
          hint: 'Talking about your OWN family, use the humble words: 兄 (あに), 姉 (あね). People take います.',
          next: 'yomi',
          options: [
            { jp: 'はい、兄が います。', kana: 'はい、あにが います。', en: 'Yes, I have an older brother.', correct: true, wordIds: ['ani'], reply: { jp: 'いいですね。ぼくは 弟子ばかりの 寺で そだちました。', en: 'How nice. I grew up in a temple full of apprentices.' }, effects: { trust: 1 } },
            { jp: 'はい、お兄さんが います。', kana: 'はい、おにいさんが います。', en: 'Yes, I have an (honourable) older brother.', correct: false, wordIds: ['oniisan'], reply: { jp: 'じぶんの お兄さんに「お〜さん」？ ふふ、ていねいですね。', en: 'Calling your own brother “o-…-san”? Hehe, very polite.' }, note: 'お兄さん is for someone else’s brother (or calling to your own). Telling others about yours: 兄 (あに).' },
            { jp: 'はい、姉が あります。', kana: 'はい、あねが あります。', en: 'Yes, there is an older sister (as an object).', correct: false, wordIds: ['ane'], reply: { jp: 'お姉さんは「もの」じゃ ありませんよ！', en: 'Your sister isn’t a thing!' }, note: 'People and animals take います, not あります: 姉が います.' },
          ],
        },
        yomi: {
          id: 'yomi',
          line: { jp: 'さいごに、うらもんの ふだを 読んで ください。「北口」。', en: 'Last thing: read the sign on the back gate. “北口”.' },
          kana: 'さいごに、うらもんの ふだを よんで ください。きたぐち。',
          wordIds: ['kita', 'kuchi'],
          hint: 'Both halves keep their native (kun) readings here: きた + くち, and the second part gets voiced (rendaku): くち → ぐち.',
          next: 'write',
          options: [
            { jp: 'きたぐち', en: 'kitaguchi (north exit)', correct: true, wordIds: ['kita'], reply: { jp: 'せいかい！ くち が ぐち に なるのが ポイントです。', en: 'Correct! The trick is that くち becomes ぐち.' }, effects: { trust: 1 } },
            { jp: 'ほくこう', en: 'hokukō', correct: false, wordIds: ['kita'], reply: { jp: 'おしい… でも この ふだは 訓読みなんです。', en: 'Close… but this sign uses kun’yomi.' }, note: '北口 is read with kun’yomi: きた + くち, voiced to きたぐち. (ほく and こう are on’yomi.)' },
            { jp: 'きたくち', en: 'kitakuchi', correct: false, wordIds: ['kita'], reply: { jp: 'もう すこし！ くちが にごります。', en: 'Almost! The くち gets voiced.' }, note: 'Rendaku: in a compound the second part often voices. くち → ぐち: きたぐち.' },
          ],
        },
        write: {
          id: 'write',
          line: { jp: 'では、ちょうめんの この ことばを 読んで ください。「冬休み」。', en: 'Now read this word in the register: “冬休み”.' },
          kana: 'では、ちょうめんの この ことばを よんで ください。ふゆやすみ。',
          wordIds: ['fuyuyasumi'],
          hint: '冬 = ふゆ (winter), 休み = やすみ (rest, holiday).',
          next: 'bye',
          input: {
            accepted: ['ふゆやすみ', '冬休み'],
            model: '冬休み',
            modelKana: 'ふゆやすみ',
            wrongReply: { jp: 'ふゆ… なんでしょう？', en: 'Fuyu… what?' },
            wrongNote: '冬 (ふゆ, winter) + 休み (やすみ, holiday): ふゆやすみ, winter holidays.',
            reply: { jp: 'ふゆやすみ！ よく 読めました。', en: 'Fuyuyasumi! Well read.' },
          },
        },
        bye: { id: 'bye', line: { jp: 'ちょうめんに 書きました。どうぞ、ごゆっくり。', en: 'You’re in the register. Please, take your time here.' }, kana: 'ちょうめんに かきました。どうぞ、ごゆっくり。', end: true },
      },
    },
  ],
}

export const DATA: RegionData | null = PACK
