/**
 * Region 9 maps: the Snowbound Temple. The main grounds climb from the
 * mountain road in the south, through the sanmon gate and up the stone steps,
 * to a courtyard before the scriptorium; the bell tower stands to the east
 * beside the brush mound (筆塚) and a steaming spring-fed pond; the road west
 * leads down to the frozen lake, a path north to the ice cave, and a pass
 * through the cliffs in the north-east climbs on toward the clouds.
 *
 * Markers are Greek letters so they never collide with a legend.
 */
import type { Cell, MapSpec } from '../../world/types'

const SNOW: Record<string, Cell> = {
  '.': { g: 'snow' },
  P: { g: 'snow', o: 'snow-pine' },
  T: { g: 'snow', o: 'tree' },
  r: { g: 'snow', o: 'rock' },
  u: { g: 'snow', o: 'stump' },
  y: { g: 'snow', o: 'snowman' },
  i: { g: 'ice' },
  C: { g: 'snow', o: 'cliff' },
  '^': { g: 'snow', o: 'roof-red' },
  A: { g: 'snow', o: 'roof-red-edge' },
  '#': { g: 'snow', o: 'wall' },
  H: { g: 'snow', o: 'wall-window' },
  D: { g: 'snow', o: 'door' },
  Z: { g: 'snow', o: 'stone-wall' },
  L: { g: 'snow', o: 'lantern' },
  S: { g: 'snow', o: 'statue' },
  f: { g: 'snow', o: 'fence' },
}

export const SNOWTEMPLE: MapSpec = {
  id: 'snowtemple',
  name: 'The Snowbound Temple',
  jp: '雪の寺',
  region: 9,
  music: 'snowtemple',
  particles: 'sparkles',
  tint: 'rgba(170, 200, 255, 0.12)',
  bg: '#dfe9f5',
  rows: [
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP99PPPPPPPP',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP==PPPPPPPP',
    'PPCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC==CCCCCCPP',
    'PPCCCCCCCCCCCC66CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC==CCCCCCPP',
    'PPCCCCC.......==..................................==.CCCCCPP',
    'PP.τ..P.....P.κ=...........T....u........P..P.....2=...P..PP',
    'PPP.u...T.....==P...^^^^^^^^^^^^^^^^^^^^........P.==.μ....PP',
    'PP.iiii....P..==....^^^^^^^^^^^^^^^^^^^^....P..θ..==......PP',
    'PP.iiii.....Pr==....AAAAAAAAAAAAAAAAAAAAP.........==......PP',
    'PP.iiii...r...==.P..#H#H#H#H#55H#H#H#H#H...TP.....==....P.PP',
    'PP............==..nnnnnnnnυnnλ=nnnnnnnnnnn==========..P...PP',
    'PP.....P......==.ynNnnnnNnnnn==nnnnNnnnnNn....P...==P.....PP',
    'PP............==.Tnnnnnnnnnnn==nnnnnnnnnnn...^^^^^^^^.....PP',
    '7=3===============nnnnnnnnnnn==nnnnnnnnnnnPu.^^^^^^^^.....PP',
    '7=================nnnnnnβnnnn==nnnnnnnnnnn...AAAAAAAA.....PP',
    'PP.........y...u..nnnnnnnnnnn==nnnnnnnnnnn...###4####.....PP',
    'PP..^^^^^^^^^..r..nnnnnnnnnnnQQnnnnnnnnnnn.....Pχ.......T.PP',
    'PP..^^^^^^^^^P.P..nnnnnnnnnnn==nnnnnnnnnn=========........PP',
    'PP..AAAAAAAAA.....nnnnnnnnnnn==nnnnγnnnnn=..P.Py..........PP',
    'PP..#H#HDH#H#...P.nnnnnnnnnnn==nnοnnnnnnn=................PP',
    'PP........ε.......nnnnnnnnnnn==nnnnnnnnnn=..nSnSnSnSnS....PP',
    'PP.......P....P...nNnnnnnnnnn==nnnnnνnnnN=..nnnnnnnnnn....PP',
    'PP................nnnnnnnnnnn==nnnnnnnnnn====nnnnδnnnn.P..PP',
    'PP....P............P..PP.....==..........r..nnnnnnnnnn.P..PP',
    'PPr..........u.........P.....==..P.P.......πnnnnnnnnnnT...PP',
    'PP......Tr..====================......ω............P.....TPP',
    'PP.P........====================..........y..φ..r..P......PP',
    'PP....P.r...==....r............=T.P.......OOOOOO.......ξ..PP',
    'PP...y......==.α......η........=.......rOOOOOOOOOO....P...PP',
    'PP......P..P==.Py..P...........=.P..r...OOOOOOOOOOr....P..PP',
    'PP..........==..ι..............========.OOOOOOOOOO........PP',
    'PP.ZZZZZZZZLggLZZZZZZZZ............PP...OOOOOOOOOO.uσ.....PP',
    'PP..........==.......P.............P...rOOOOOOOOOO........PP',
    'PPfff.fff.L.==.Lψ......................rOOOOOOOOOOr.r....PPP',
    'PPfρ....fS..==..S.P...iiiiii.....P...P.T..OOOOOOP.........PP',
    'PPf....Pf.L.==TL...PP.iiiiii...u......PP.r..P.....PP......PP',
    'PPfP.ζ..fS..==..S..T..iiiiii..P.T...................iiiiP.PP',
    'PPf.....f.L.==.L...P.......r......T..y..............iiii..PP',
    'PPfffffff...1=.P........P......P........P.................PP',
    'PP..........==............................................PP',
    'PPPPPPPPPPPP==PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPP00PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
  ],
  legend: { ...SNOW, O: { g: 'onsen' }, g: { g: 'path', o: 'gate-open' } },
  spawn: 'west',
  inn: 'west',
  points: {
    '1': { name: 'west', dir: 'up' },
    '2': { name: 'east', dir: 'down' },
    '3': { name: 'lake', dir: 'right' },
    λ: { name: 'library', dir: 'down' },
    κ: { name: 'cave', dir: 'down' },
    χ: { name: 'bell', dir: 'down' },
  },
  exits: [
    { at: '0', to: '@prev', point: 'east' },
    { at: '9', to: '@next', point: 'west', tile: 'stairs-up' },
    { at: '7', to: 'snowtemple-lake', point: 'east' },
    { at: '6', to: 'snowtemple-cave', point: 'entrance', tile: 'cave' },
    { at: '5', to: 'snowtemple-library', point: 'door', tile: 'door' },
    { at: '4', to: 'snowtemple-bell', point: 'door', tile: 'door' },
  ],
  entities: [
    { at: 'α', id: 'st-sweeper', kind: 'activity', sprite: 'monk', dir: 'down', wander: 1, activities: ['r9-words-1'], name: { jp: 'ゆきかきの おぼうさん', en: 'Sweeper Monk' }, lines: [{ jp: 'はいても はいても、雪は ふる。春も 夏も 秋も、ここから 見て きたよ。', en: 'Sweep and sweep, and still the snow falls. I’ve watched spring, summer and autumn from this spot, too.' }] },
    { at: 'β', id: 'st-compass', kind: 'activity', tile: 'tablet', activities: ['r9-trace-1'], name: { jp: 'ほうがくの いし', en: 'Stone Compass' }, lines: [{ jp: 'たいらな いしに 東・西・南・北。字の ふちが こおっている。', en: 'A flat stone carved with east, west, south and north. The edges of the characters are iced over.' }] },
    { at: 'γ', id: 'st-pilgrims', kind: 'activity', sprite: 'villager-b', dir: 'left', wander: 1, activities: ['r9-words-2'], name: { jp: 'さんぱいの かぞく', en: 'Pilgrim Family' }, lines: [{ jp: 'かぞくで おまいりに 来たの。父も 母も、さむくて ふるえてるわ。', en: 'We came to pray as a family. My father and mother are shivering.' }] },
    { at: 'δ', id: 'st-fudezuka', kind: 'activity', tile: 'statue', activities: ['r9-trace-2'], name: { jp: 'ふでづか', en: 'Brush Mound' }, lines: [{ jp: 'つかいおえた ふでを ねむらせる、ふでの おはか。「ありがとう」と きざまれている。', en: 'A resting place for worn-out brushes. “Thank you” is carved on the stone.' }] },
    { at: 'ε', id: 'st-kuu', kind: 'activity', sprite: 'monk', dir: 'down', activities: ['r9-talk'], name: { jp: 'くう', en: 'Kuu' }, lines: [{ jp: 'ちょうめんに お名前を どうぞ。…あ、字が こおってる！', en: 'Please write your name in the register. …Ah, the ink has frozen!' }] },
    { at: 'ζ', id: 'st-kids', kind: 'activity', sprite: 'child', dir: 'right', wander: 1, activities: ['r9-defense'], name: { jp: 'ゆきがっせんの こども', en: 'Snowball Kids' }, lines: [{ jp: 'ゆきがっせん しよう！ 名前を いえない ゆきだまは、ぜんぶ あたるよ！', en: 'Snowball fight! Any snowball you can’t name hits you!' }] },
    { at: 'η', id: 'st-snowman', kind: 'activity', tile: 'snowman', activities: ['r9-cross'], name: { jp: 'ゆきの きょじん', en: 'Snow Giant' }, lines: [{ jp: 'おなかに ますめが かいてある。クロスワードだ！', en: 'A grid is drawn on its belly. A crossword!' }] },
    { at: 'θ', id: 'st-trial', kind: 'activity', tile: 'statue', activities: ['r9-mastery'], name: { jp: 'しれんの せきぞう', en: 'Trial Statue' }, lines: [{ jp: 'ろうそくが もえつきる まえに、文を くみたてよ。', en: 'Build your sentences before the candle burns down.' }] },
    { at: 'ι', id: 'st-sign-gate', kind: 'sign', tile: 'sign', name: { jp: 'さんもんの かんばん', en: 'Gate Sign' }, lines: [{ jp: '北：本どう（しゃきょうの へや）　東：かねつきどう　西：みずうみ', en: 'North: the main hall (the scriptorium). East: the bell tower. West: the lake.' }, { jp: '北西の こおりの あなには 入らないこと。', en: 'Do not enter the ice cave to the north-west.' }] },
    { at: 'μ', id: 'st-sign-pass', kind: 'sign', tile: 'sign', name: { jp: 'とうげの かんばん', en: 'Pass Sign' }, lines: [{ jp: 'この さき、雲の 上の みやこ。', en: 'Beyond here: the city above the clouds.' }] },
    { at: 'ν', id: 'st-cat', kind: 'npc', sprite: 'cat', wander: 2, name: { jp: 'てらねこ', en: 'Temple Cat' }, lines: [{ jp: 'にゃ。（こたつは どこ？ と いう かおを している）', en: 'Mew. (It has a “where is the kotatsu?” look on its face.)' }] },
    { at: 'ξ', id: 'st-fox', kind: 'npc', sprite: 'fox', wander: 2, name: { jp: 'ゆきぎつね', en: 'Snow Fox' }, lines: [{ jp: '…（雪の 上に、きれいな あしあとを 一行 のこしていく）', en: '…(It leaves a single neat line of pawprints across the snow.)' }] },
    { at: 'ο', id: 'st-pilgrim-father', kind: 'npc', sprite: 'villager-a', dir: 'right', wander: 1, name: { jp: 'さんぱいの おとうさん', en: 'Pilgrim Father' }, lines: [{ jp: 'まいとし かぞくで 来るんだ。でも、ことしは おみくじの 字が 読めなくてね。', en: 'We come as a family every year. But this year we can’t read the fortunes.' }, { jp: 'むすめが「父」と「母」の 字を ならったんだ。じまんの むすめだよ。', en: 'My daughter just learned the kanji for father and mother. I’m so proud.' }] },
    { at: 'π', id: 'st-big-snowman', kind: 'landmark', tile: 'snowman', word: 'yukidaruma', name: { jp: 'ふるい 雪だるま', en: 'Old Snow Giant' }, lines: [{ jp: '何年も とけない、ふしぎな 雪だるま。ちょっと さびしそう。', en: 'A strange snowman that hasn’t melted in years. It looks a little lonely.' }] },
    { at: 'ρ', id: 'st-chest-fort', kind: 'chest', tile: 'chest', chest: { item: 'herb', n: 2, shards: 20, lock: { answer: 'ゆきだるま', jp: 'ふたに「雪だるま」。よみを となえよ。', en: 'The lid bears 雪だるま. Chant its reading.' } } },
    { at: 'σ', id: 'st-chest-pond', kind: 'chest', tile: 'chest', chest: { item: 'ether', n: 2, shards: 25, lock: { answer: 'ふゆ', jp: 'ふたに「冬」。よみを となえよ。', en: 'The lid bears 冬. Chant its reading.' } } },
    { at: 'τ', id: 'st-chest-nook', kind: 'chest', tile: 'chest', chest: { item: 'charm', n: 1, shards: 30, lock: { answer: 'きた', jp: 'ふたに「北」。よみを となえよ。', en: 'The lid bears 北. Chant its reading.' } } },
    { at: 'υ', id: 'st-hall-plaque', kind: 'landmark', tile: 'sign', word: 'tera', name: { jp: '本どうの がく', en: 'Hall Plaque' }, lines: [{ jp: '大きな がく。「雪」と「寺」の 字が、こおりの 下で ねむっている。', en: 'A great plaque. The characters for snow and temple sleep beneath the ice.' }] },
    { at: 'φ', id: 'st-onsen', kind: 'landmark', tile: 'sign', name: { jp: 'ゆげの いけ', en: 'Steaming Pond' }, lines: [{ jp: 'おんせんの おゆが ながれこむ いけ。冬でも こおらない。', en: 'A pond fed by a hot spring. Even in winter, it never freezes.' }, { jp: 'たてふだ：「つららの ある ところでは、おゆの はなしを しないこと」', en: 'A notice: “Where icicles hang, do not talk about hot baths.”' }] },
    { at: 'ω', id: 'st-shoveler', kind: 'npc', sprite: 'monk', wander: 2, name: { jp: 'ゆきかきの でし', en: 'Shovelling Apprentice' }, lines: [{ jp: '朝から ずっと 雪かき。午後も 雪かき。毎日 雪かき！', en: 'Shovelling since morning. Shovelling in the afternoon. Shovelling every day!' }, { jp: '「弟子」の「弟」は おとうと。ぼくは みんなの おとうとって わけ。', en: 'The 弟 in 弟子 (apprentice) means little brother. So I’m everyone’s little brother.' }] },
    { at: 'ψ', id: 'st-jizo', kind: 'landmark', tile: 'statue', name: { jp: 'かさじぞう', en: 'Hatted Jizō' }, lines: [{ jp: 'だれかが じぞうに すげがさを かぶせて いった。…どこかで 聞いた 話だね。', en: 'Someone has put straw hats on the jizō statues. …That story sounds familiar.' }] },
  ],
}

export const SNOWTEMPLE_LIBRARY: MapSpec = {
  id: 'snowtemple-library',
  name: 'The Scriptorium',
  jp: 'しゃきょうの へや',
  region: 9,
  music: 'snowtemple',
  interior: true,
  particles: 'dust',
  bg: '#0d0c16',
  tint: 'rgba(160, 190, 255, 0.12)',
  rows: [
    '#######################',
    '#kkkkkkkHkHkHkHkkkkkkk#',
    '#wwεwwζwwtttttwwηwwθww#',
    '#wwwwwwwwttαttwwwwwwww#',
    '#wkkkkkwwtttttwwkkkkkw#',
    '#wwwwwwwwwwMwwwwwwwwξw#',
    '#NwwwwwwβwwMwwwwwwwwwN#',
    '#wkkkkkwwwwMwwwwkkkkkw#',
    '#wwwwwwwwwwMwwwwwwwwww#',
    '#NwwwwwwwwwMwwμwwwwwwN#',
    '#wkkkkkwwwwMwwwwkkkkkw#',
    '#wwwwwwwwwwMwwwwwwwwwι#',
    '#wttγttwwwwMwwwwttδttw#',
    '#νtttttwwww1wwwwtttttw#',
    '###########0###########',
  ],
  legend: { N: { g: 'wood-floor', o: 'chochin' } },
  spawn: 'door',
  points: { '1': { name: 'door', dir: 'up' } },
  exits: [{ at: '0', to: 'snowtemple', point: 'library', tile: 'carpet' }],
  entities: [
    { at: 'α', id: 'sl-abbot', kind: 'npc', sprite: 'monk', dir: 'down', name: { jp: 'ろうし', en: 'The Abbot' }, lines: [{ jp: '…わしの 名前… ふだが こおって、読めんのじゃ。', en: '…My name… the tag has frozen, and I can’t read it.' }] },
    { at: 'β', id: 'sl-scribe', kind: 'activity', sprite: 'monk', dir: 'right', activities: ['r9-words-4'], name: { jp: 'しゃきょうの かしら', en: 'Head Scribe' }, lines: [{ jp: '漢字、勉強、練習。ここでは ことばを 書いて まもるのです。', en: 'Kanji, study, practice. Here we guard words by writing them.' }] },
    { at: 'γ', id: 'sl-desk', kind: 'activity', tile: 'tablet', activities: ['r9-trace-3'], name: { jp: 'かきものづくえ', en: 'Writing Desk' }, lines: [{ jp: 'すずりと ふでが ならんでいる。お手本の 字だけ、こおっていない。', en: 'Inkstone and brushes, neatly set out. Only the model characters have escaped the ice.' }] },
    { at: 'δ', id: 'sl-copytable', kind: 'activity', tile: 'sign', activities: ['r9-forge'], name: { jp: 'しゃきょうの つくえ', en: 'Copying Table' }, lines: [{ jp: 'お経を うつす つくえ。きれぎれの ことばを 文に もどそう。', en: 'The table where sutras are copied. Put the broken words back into sentences.' }] },
    { at: 'ε', id: 'sl-scroll-haru', kind: 'landmark', tile: 'sign', name: { jp: '春の かけじく', en: 'Spring Scroll' }, lines: [{ jp: 'さくらの え。字が こおっている：「春」。', en: 'A painting of cherry blossom. Its character is frozen: 春.' }] },
    { at: 'ζ', id: 'sl-scroll-natsu', kind: 'landmark', tile: 'sign', name: { jp: '夏の かけじく', en: 'Summer Scroll' }, lines: [{ jp: 'ほたるの え。字が こおっている：「夏」。', en: 'A painting of fireflies. Its character is frozen: 夏.' }] },
    { at: 'η', id: 'sl-scroll-aki', kind: 'landmark', tile: 'sign', name: { jp: '秋の かけじく', en: 'Autumn Scroll' }, lines: [{ jp: 'もみじの え。字が こおっている：「秋」。', en: 'A painting of maple leaves. Its character is frozen: 秋.' }] },
    { at: 'θ', id: 'sl-scroll-fuyu', kind: 'landmark', tile: 'sign', name: { jp: 'からの かけじく', en: 'Empty Hook' }, lines: [{ jp: 'かけじくを かける くぎ。なにも かかっていない。', en: 'A hook for a hanging scroll. Nothing hangs on it.' }] },
    { at: 'ι', id: 'fk9-shoji', kind: 'landmark', tile: 'wall-window', name: { jp: 'やぶれた しょうじ', en: 'Torn Screen' }, lines: [{ jp: 'あなだらけの しょうじ。…あなの むこうで、なにかが まばたきした。', en: 'A paper screen full of holes. …Something blinked behind one of them.' }] },
    { at: 'μ', id: 'sl-copyist', kind: 'npc', sprite: 'monk', wander: 1, name: { jp: 'しゃきょうの おぼうさん', en: 'Copying Monk' }, lines: [{ jp: '一行 書いては、こおる。また 一行 書いては、こおる…', en: 'I write one line, and it freezes. I write another line, and it freezes…' }, { jp: '音読みと 訓読み、どちらで 読むか。それが いつも むずかしい。', en: 'On-reading or kun-reading? That’s always the hard part.' }] },
    { at: 'ν', id: 'sl-chest', kind: 'chest', tile: 'chest', chest: { item: 'ether', n: 2, shards: 25, lock: { answer: 'かんじ', jp: 'ふたに「漢字」。よみを となえよ。', en: 'The lid bears 漢字. Chant its reading.' } } },
    { at: 'ξ', id: 'sl-paper', kind: 'landmark', tile: 'crate', name: { jp: 'わしの たな', en: 'Washi Shelf' }, lines: [{ jp: 'まっしろな わしが つまれている。', en: 'Stacks of pure white washi paper.' }] },
  ],
}

export const SNOWTEMPLE_BELL: MapSpec = {
  id: 'snowtemple-bell',
  name: 'The Bell Tower',
  jp: 'かねつきどう',
  region: 9,
  music: 'snowtemple',
  interior: true,
  particles: 'dust',
  bg: '#0b0d14',
  tint: 'rgba(255, 210, 150, 0.1)',
  rows: [
    '###############',
    '#HHHHHHHHHHHHH#',
    '#nnnnnnnnnnγnn#',
    '#nNnnMMMMMnnNn#',
    '#nnnnMMαMMnnnn#',
    '#nnnnMMMMMnnnn#',
    '#nnnnMMMMMnnnn#',
    '#nnβnnnnnnnnnn#',
    '#nnnnnnnnnnnδn#',
    '#nNnnnnnnnnnNn#',
    '#nnnnnnnnnnnnx#',
    '#xnnnnn1nnnnne#',
    '#######0#######',
  ],
  legend: { x: { g: 'stone-floor', o: 'crate' }, e: { g: 'stone-floor', o: 'barrel' } },
  spawn: 'door',
  points: { '1': { name: 'door', dir: 'up' } },
  exits: [{ at: '0', to: 'snowtemple', point: 'bell', tile: 'door' }],
  entities: [
    { at: 'α', id: 'sb-bell', kind: 'activity', tile: 'shrine-bell', activities: ['r9-listen'], name: { jp: 'おおがね', en: 'Great Bell' }, lines: [{ jp: '大きな かね。ひょうめんに「鐘」の 字。こだまに ことばが まじっている。', en: 'A huge bell with 鐘 cast on its side. Words seem to ride its echo.' }] },
    { at: 'β', id: 'sb-genta', kind: 'activity', sprite: 'monk', dir: 'right', activities: ['r9-words-3'], name: { jp: 'げんた', en: 'Genta' }, lines: [{ jp: 'わっはっは！ わしは かねつきの げんた。午前も 午後も、ときを ならすのが しごとじゃ！', en: 'Wahaha! I’m Genta the bell-keeper. Morning and afternoon, I ring out the hours!' }] },
    { at: 'γ', id: 'sb-calendar', kind: 'landmark', tile: 'sign', word: 'toshi', name: { jp: 'こよみ', en: 'Temple Calendar' }, lines: [{ jp: '一年の こよみ。今年、来年、毎年の ぎょうじが 書いてある。', en: 'The calendar for the year: this year’s, next year’s and every year’s ceremonies.' }, { jp: '「十二月三十一日：じょやの かね（百八かい）」', en: '“December 31st: the New Year’s Eve bell (108 strikes).”' }] },
    { at: 'δ', id: 'sb-chest', kind: 'chest', tile: 'chest', chest: { item: 'charm', n: 1, shards: 25, lock: { answer: 'かね', jp: 'ふたに「鐘」。よみを となえよ。', en: 'The lid bears 鐘. Chant its reading.' } } },
  ],
}

export const SNOWTEMPLE_LAKE: MapSpec = {
  id: 'snowtemple-lake',
  name: 'The Frozen Lake',
  jp: 'こおりの みずうみ',
  region: 9,
  music: 'snowtemple',
  particles: 'sparkles',
  tint: 'rgba(150, 190, 255, 0.14)',
  bg: '#dfe9f5',
  rows: [
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PP..........P..P...P....P..............P..PP',
    'PP...........WWWWWWWWWWWWWW.........PP....PP',
    'PP........WWWWWWWWWWWWWWWWWWWW.....PP.....PP',
    'PP........WWWWWWWWWWWWWWWWWWWW....P....P..PP',
    'PP..P....iiiiWWWWWWWWWWWWWWiiii.....P.....PP',
    'PP.....iiiiiiiiiiiiiiiiiiiiiiiiii..P^^^^^.PP',
    'PP.P..iiiiiiiiiiiiiiiiiiiiiiiiiiii..^^^^^.PP',
    'PP..y.iiiiiiiiiiiiiiiiiiiiiiiiiiiiPPAAAAAPPP',
    'PP...iiiiiiiiiiiiiiiiiiiiiiiiiiiiii.#H#H#.PP',
    'PP...iiiiiiiiiiiiiiiiiiiiii~iiiiiii..δ...PPP',
    'PP...iiiiiiiiiiiiiiiiiiiiiiiiiiiiii.P.P.η.PP',
    'PP...iiiiiiiii~iiiiiiiiiiiiiiiiiiiiP.....rPP',
    'PP.P.iiiiiiiiiiiiiiiiiiiiiiiii===========1=0',
    'PP...iiiiiiiiiiiiiiiiiiiiiiiii=============0',
    'PP....iiiiiiiiiiiiiiii~αiiiiiiiiiiP.=....PPP',
    'PPPP..iiiii~iiiiiiiiiiiiiiiiiiiεii..=P....PP',
    'PP..P..iiiiiiiiiiiiiiiiiiiiiiiiii...=.....PP',
    'PP.P.....iiiiiiiiiiiiiiiiiiiiii.....=.....PP',
    'PP...P....iiiiiiiγiiiiiiiiiiii.P..θ.=P....PP',
    'PP.nnnn......iiiiiiiiiiiiii.........=.....PP',
    'PP.nβnn.P...P.P...P.P........P.r....=..P.PPP',
    'PP.nnnn..ζP...........PP....PP....P.=.....PP',
    'PPP..P..=============================.....PP',
    'PP.........r....P...............yP......P.PP',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP',
  ],
  legend: { ...SNOW },
  spawn: 'east',
  points: { '1': { name: 'east', dir: 'left' } },
  exits: [{ at: '0', to: 'snowtemple', point: 'lake' }],
  entities: [
    { at: 'α', id: 'lk-fisher', kind: 'activity', sprite: 'villager-a', dir: 'left', activities: ['r9-speed'], name: { jp: 'あなづりの りょうし', en: 'Ice Fisher' }, lines: [{ jp: 'こおりに あなを あけて、わかさぎを つるんだ。はやく 読まないと にげるぞ！', en: 'Cut a hole in the ice and fish for smelt. Read fast, or they get away!' }] },
    { at: 'β', id: 'lk-stele', kind: 'activity', tile: 'tablet', activities: ['r9-runes'], name: { jp: 'みずうみの いしぶみ', en: 'Lakeside Stele' }, lines: [{ jp: 'こけと 雪に おおわれた いしぶみ。漢字の ことばが ならんでいる。', en: 'A stone stele under moss and snow, carved with kanji compounds.' }] },
    { at: 'γ', id: 'lk-ice-slate', kind: 'activity', tile: 'tablet', activities: ['r9-trace-4'], name: { jp: 'こおりの ばん', en: 'Ice Slate' }, lines: [{ jp: 'つるつるの こおり。ぼうで 字を かけそうだ。', en: 'Smooth, clear ice. You could scratch characters into it with a stick.' }] },
    { at: 'δ', id: 'fk9-tsurara', kind: 'npc', sprite: 'villager-b', dir: 'down', name: { jp: 'しろい きものの ひと', en: 'Woman in White' }, lines: [{ jp: '…のきの つららが、きれいでしょう？', en: '…The icicles on the eaves are beautiful, aren’t they?' }] },
    { at: 'ε', id: 'lk-thin-ice', kind: 'landmark', tile: 'sign', word: 'koori', name: { jp: 'うすごおりの ふだ', en: 'Thin-Ice Sign' }, lines: [{ jp: '「こおりが うすい。ちゅうい！」', en: '“Thin ice. Careful!”' }] },
    { at: 'ζ', id: 'lk-chest', kind: 'chest', tile: 'chest', chest: { item: 'herb', n: 3, shards: 20, lock: { answer: 'こおり', jp: 'ふたに「氷」。よみを となえよ。', en: 'The lid bears 氷. Chant its reading.' } } },
    { at: 'η', id: 'lk-hut-sign', kind: 'sign', tile: 'sign', name: { jp: 'こやの ひょうさつ', en: 'Hut Nameplate' }, lines: [{ jp: '名字だけが のこっている。名前の ところは、こおりで 見えない。', en: 'Only the surname remains. Where the given name was, there is only ice.' }] },
    { at: 'θ', id: 'lk-heron-kid', kind: 'npc', sprite: 'child', wander: 2, name: { jp: 'スケートの こ', en: 'Skating Kid' }, lines: [{ jp: '見て！ こおりの 上で「北」って 字を すべったんだ！', en: 'Look! I skated the kanji for north on the ice!' }, { jp: 'ひがしに すべって、にしに すべって… めが まわる〜', en: 'Skate east, skate west… I’m dizzy~' }] },
  ],
}

export const SNOWTEMPLE_CAVE: MapSpec = {
  id: 'snowtemple-cave',
  name: 'The Ice Cave',
  jp: 'こおりの あな',
  region: 9,
  music: 'snowtemple',
  interior: true,
  particles: 'sparkles',
  bg: '#05070f',
  tint: 'rgba(120, 170, 255, 0.2)',
  rows: [
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    'CCCCCCCCCCCC........CCCCCCCCCCCC',
    'CCCCCCCCC..............CCCCCCCCC',
    'CCCCCCC..ε...,,,,,,......CCCCCCC',
    'CCCCCC.......,,,α,,.......CCCCCC',
    'CCCCC.....R..,,,,,,..R.....CCCCC',
    'CCCC........................CCCC',
    'CCCC..WW....................CCCC',
    'CCC..WWWW..................δ.CCC',
    'CCC..WWWW...............R....CCC',
    'CCC..WWWW....................CCC',
    'CCC..WWWW....................CCC',
    'CCC.....................γ....CCC',
    'CCC...β......................CCC',
    'CCCC.....R............R.....CCCC',
    'CCCC........................CCCC',
    'CCCCC.......R......R.......CCCCC',
    'CCCCCC....................CCCCCC',
    'CCCCCCC..................CCCCCCC',
    'CCCCCCCCC..............CCCCCCCCC',
    'CCCCCCCCCCCC....1...CCCCCCCCCCCC',
    'CCCCCCCCCCCCCC....CCCCCCCCCCCCCC',
    'CCCCCCCCCCCCCC..00CCCCCCCCCCCCCC',
  ],
  legend: { '.': { g: 'ice' }, ',': { g: 'snow' }, C: { g: 'stone-floor', o: 'cliff' }, R: { g: 'ice', o: 'boulder' } },
  spawn: 'entrance',
  points: { '1': { name: 'entrance', dir: 'up' } },
  exits: [{ at: '0', to: 'snowtemple', point: 'cave' }],
  entities: [
    { at: 'α', id: 'sc-yukionna', kind: 'boss', sprite: 'yuki-onna', activities: ['r9-boss'], name: { jp: 'ゆきおんな', en: 'Yuki-onna' }, lines: [{ jp: '…しずかに。字は、もう いらない。', en: '…Hush. There is no more need for writing.' }] },
    { at: 'β', id: 'sc-icewall', kind: 'activity', tile: 'tablet', activities: ['r9-recall'], name: { jp: 'こおりの かべ', en: 'Frozen Wall' }, lines: [{ jp: 'あつい こおりの 中に、漢字が とじこめられている。おもいだして、書きだそう。', en: 'Kanji are trapped deep in the ice. Remember them, and write them out.' }] },
    { at: 'γ', id: 'sc-mirror', kind: 'activity', tile: 'tablet', activities: ['r9-mastery-2'], name: { jp: 'こおりの かがみ', en: 'Ice Mirror' }, lines: [{ jp: 'よみがなの ない 字だけが うつる かがみ。', en: 'A mirror that shows only characters, never their readings.' }] },
    { at: 'δ', id: 'sc-chest', kind: 'chest', tile: 'chest', chest: { item: 'ether', n: 3, shards: 40, lock: { answer: 'しんしん', jp: 'ふたに「雪が しんしんと ふる」。さいごの ことばを となえよ。', en: 'The lid reads: 雪が しんしんと ふる. Chant the word for how it falls.' } } },
    { at: 'ε', id: 'sc-frozen-names', kind: 'landmark', tile: 'rock', word: 'koori', name: { jp: 'こおった 名前', en: 'Frozen Names' }, lines: [{ jp: 'こおりの 中に、たくさんの 名前が ねむっている。寺の みんなの 名前だ。', en: 'Many names sleep inside the ice: the names of everyone at the temple.' }] },
  ],
}

export const MAPS: MapSpec[] = [SNOWTEMPLE, SNOWTEMPLE_LIBRARY, SNOWTEMPLE_BELL, SNOWTEMPLE_LAKE, SNOWTEMPLE_CAVE]
