import type { Locus } from '../types'

/**
 * Room 9 of the memory palace: the Snowbound Temple.
 *
 * Route: up the stone steps to the sweeper monk at the gate, into the
 * courtyard to the stone compass, east past the old snow giant and the snow
 * child by the steaming pond, back to the pilgrim family, down to the
 * snowball fort, east to the brush mound, west to the temple office, then
 * into the bell tower (the bell-keeper, the great bell), the scriptorium (the
 * abbot, the head scribe, the writing desk, the copying table, the watching
 * screen), out to the frozen lake (the ice fisher, the stele, the icicle hut).
 *
 * Kanji memories use the shape of the character and a CAPS sound hook for
 * its readings (kun'yomi first, then the on'yomi).
 */
const m = (item: string, story: string, image: string) => ({ item, story, image })

export const ROOM: Locus[] = [
  {
    id: 'p9-sweeper',
    room: 9,
    map: 'snowtemple',
    anchor: 'st-sweeper',
    name: { jp: 'ゆきかきの おぼうさん', en: 'Sweeper Monk' },
    emoji: '🧹',
    memories: [
      m('w:haru', 'The sweeper monk brushes away a patch of snow and spring bursts out of it: blossom, birdsong, and a HARE called ROO hopping in the thaw, crying "HA-ROO! Spring!"', 'snow is brushed aside and spring bursts out: blossom, birdsong, and a HARE called ROO hopping in the thaw, crying "HA-ROO! Spring!"'),
      m('w:natsu', 'One more stroke of the broom and it is blazing summer at the gate: cicadas scream and squirrels pelt the old monk with sun-baked NUTS, "NAT-SU-mmer!", until he sweats through his robe.', 'it is suddenly blazing summer: cicadas scream and squirrels pelt you with sun-baked NUTS, "NAT-SU-mmer!", until you sweat through your sleeves'),
      m('w:aki', 'The broom stirs up a whirl of red maple leaves. The sweeper rubs his back and groans "AH, KEE... so achy," raking autumn into a heap by the gate.', 'a whirl of red maple leaves blows in and an old man rubs his back, groaning "AH, KEE... so achy" as he rakes autumn into a heap'),
      m('w:fuyu', 'Then winter slams back. A gust blows snow into the sweeper’s face and he sputters "FOO! YOU!" at the sky, his beard frozen white.', 'a gust of winter blasts snow into an old man’s face and he sputters "FOO! YOU!" at the sky, his beard frozen white'),
      m('w:kisetsu', 'Four keys hang on the sweeper’s broom: blossom, sun, leaf and snowflake. Turning one KEY SETS YOU in that season of the year, "KEY-SETS-YOU".', 'four keys dangle on a broom (blossom, sun, leaf, snowflake), and turning one KEY SETS YOU in that season of the year: "KEY-SETS-YOU"'),
      m('j:春', 'Carved on the gatepost: three planks stacked over a person spreading their arms, all sitting on a little sun. The sun warms them till they sprout SHOOts (SHUN). The HARE called ROO nibbles them: HA-ROO, spring.', 'three planks stacked over a person spreading their arms, all sitting on a little sun; it warms them till they sprout SHOOts (SHUN), and a HARE called ROO nibbles them: spring'),
      m('j:夏', 'The sweeper points at another carving: a head under a flat hat, dragging two slow feet through the heat. It pants "NAT-SU-mmer!" and gasps a sweaty "KA!": summer.', 'a head under a flat hat, dragging two slow feet through the heat: summer. It pants "NAT-SU-mmer!" and gasps a sweaty "KA!"'),
      m('j:秋', 'By the gate a rice stalk stands beside a little bonfire: harvest time, stubble burning, autumn. The sweeper warms his ACHY back, "AH, KEE", and shouts "SHOO!" (SHUU) at the sparks.', 'a rice stalk stands beside a bonfire: harvest, stubble burning, autumn. An old man warms his ACHY back, "AH, KEE", and shouts "SHOO!" at the sparks'),
      m('j:冬', 'The last carving: a slow, dragging figure with two drops of ice under it. Winter, when even walking freezes. It sputters "FOO! YOU!" and hops about on frozen TOEs (TOU).', 'a slow, dragging figure with two drops of ice under it: winter, when even walking freezes. It sputters "FOO! YOU!" and hops about on frozen TOEs'),
    ],
  },
  {
    id: 'p9-compass',
    room: 9,
    map: 'snowtemple',
    anchor: 'st-compass',
    name: { jp: 'ほうがくの いし', en: 'Stone Compass' },
    emoji: '🧭',
    memories: [
      m('w:higashi', 'The eastern point of the compass glows. A swordsman stands on it at dawn: HE GASHES the sky open with one stroke and the sun spills out, "HEE-GA-SHEE!"', 'a swordsman faces the dawn: HE GASHES the sky open with one stroke and the sun spills out where it rises, in the east, "HEE-GA-SHEE!"'),
      m('w:nishi', 'On the western point a dancer bends her KNEE at sunset. SHE bows to the sun as it sinks behind the compass, whispering "NEE-SHEE".', 'at sunset a dancer bends her KNEE and SHE bows to the sun as it sinks in the west, whispering "NEE-SHEE"'),
      m('w:minami', 'The southern point is strangely warm. A tanned surfer lies on it shouting "MEE NAH-MEE!", riding warm waves that lap out of the stone.', 'a tanned surfer waves from the warm south, shouting "MEE NAH-MEE!", riding warm waves while palm trees sway behind him'),
      m('w:kita', 'The northern point is crusted with frost. A polar bear sits on it rocking out on a frosty KEY-TAR, howling icy solos: "KEE-TAH!"', 'a polar bear rocks out on a frosty KEY-TAR in the far north, howling icy solos, "KEE-TAH!", while the aurora flickers overhead'),
      m('j:東', 'The east mark on the compass: a sun tangled in the branches of a tree, rising. HE GASHES it free, "HEE-GA-SHEE", and it TOE-steps (TOU) up over the trunk.', 'a sun tangled in the branches of a tree, rising in the east; HE GASHES it free, "HEE-GA-SHEE", and it TOE-steps up over the trunk'),
      m('j:西', 'The west mark: a lidded box with two little legs inside, like a nest where birds roost at sunset. The dancer bends her KNEE and SHE says goodnight, "NEE-SHEE"; the birds SAY "SEI".', 'a lidded box with two little legs inside, a nest where birds roost at sunset; a dancer bends her KNEE and SHE says goodnight, "NEE-SHEE", and the birds SAY "SEI"'),
      m('j:南', 'The south mark looks like a beach tent with a cross on its roof and a little fan inside. The surfer naps under it, "MEE NAH-MEE", while his NAN (NAN) brings him flatbread.', 'a beach tent with a cross on its roof and a little fan inside, on the warm southern sand; a surfer naps under it, "MEE NAH-MEE", while his NAN brings him bread'),
      m('j:北', 'The north mark: two figures sitting back to back, turned away from the freezing wind, shivering the HOKEY-pokey (HOKU) while the bear plays its KEY-TAR, "KEE-TAH".', 'two figures sit back to back, turned away from the freezing north wind, shivering the HOKEY-pokey while a bear plays a KEY-TAR, "KEE-TAH"'),
      m('j:方', 'The compass needle is a little figure with a flat cap and one long arm pointing the way. "HOH! This direction!" it cries (HOU), and it CUTS A path (KATA) through the snow toward it.', 'a little figure with a flat cap and one long arm points the way, crying "HOH! this direction!", and CUTS A path through the snow toward it'),
    ],
  },
  {
    id: 'p9-snowgiant',
    room: 9,
    map: 'snowtemple',
    anchor: 'st-big-snowman',
    name: { jp: 'ふるい 雪だるま', en: 'Old Snow Giant' },
    emoji: '☃️',
    memories: [
      m('w:yukidaruma', 'Up close the old giant is a round, red-faced Daruma doll made of rolled snow, its coal eyes rolling. YOU KEY it in the belly, "YOO-KEE DA-ROO-MA!", and it wobbles but never falls.', 'a round, red-faced Daruma doll made of rolled snow, coal eyes rolling; YOU KEY it in the belly, "YOO-KEE DA-ROO-MA!", and it wobbles but never falls'),
      m('w:ooyuki', 'Heavy snow keeps piling on the giant until only its nose pokes out. It groans "OH, YOU KEY-ding me! OH-YUKI!" as the drift climbs higher.', 'heavy snow piles higher and higher on a buried statue until only its nose shows; it groans "OH, YOU KEY-ding me!", "OH-YUKI!"'),
      m('w:koori', 'The giant’s carrot nose has frozen into a solid CORE of ice, "KOH-REE", hard as a pebble and cold enough to crack your teeth.', 'a carrot nose frozen into a solid CORE of ice, "KOH-REE," hard as stone and cold enough to crack your teeth'),
      m('w:fuyuyasumi', 'Kids hang a banner on the giant, throw down their school bags and grab sledges: "FOO! YOU! YA, SUE ME, it’s the winter holidays!" No lessons till spring.', 'kids throw down their school bags and grab sledges, yelling "FOO! YOU! YA, SUE ME, it’s the winter holidays!" — no lessons till spring'),
      m('j:雪', 'Someone has drawn on the giant’s chest: rain falling into a hand that sweeps it up like a broom. Rain you can sweep is snow. YOU KEY it into a ball, and it SETS hard, "SETSU!"', 'rain falls into a hand that sweeps it up like a broom: rain you can sweep is snow. YOU KEY it into a ball, and it SETS hard, "SETSU!"'),
      m('j:夕', 'Behind the giant a thin crescent moon, only half risen, peeps over the hills: evening. It calls "YOU!" (YUU) to everyone still out playing, and says "SAY, KEY?" (SEKI) for the door.', 'a thin crescent moon, only half risen, peeps over the hills: evening has come. It calls "YOU!" to everyone still out playing'),
      m('w:yuugata', 'The giant’s shadow stretches long across the snow and your phone buzzes: "YOU GOT A curfew, it’s evening!" The lanterns flicker on one by one.', 'the sky turns orange and your phone buzzes: "YOU GOT A curfew, it’s evening!" — the shadows stretch long and the lanterns flicker on'),
    ],
  },
  {
    id: 'p9-yuki',
    room: 9,
    map: 'snowtemple',
    anchor: 'st-yuki',
    name: { jp: 'ゆきんこ', en: 'The Snow Child' },
    emoji: '❄️',
    memories: [
      m('w:shinshin', 'Yuki holds a finger to her lips. Snow falls so thickly it makes no sound at all, only your SHINS, SHIN-SHIN, pushing through deep powder: a hushed, full quiet.', 'snow falls so thick and silent that the only sound is your SHINS, SHIN-SHIN, pushing through deep powder: a hushed, full quiet'),
      m('j:夜', 'Yuki traces the kanji for night in the snow: a person tucked under a roof while the moon slips in beside them. "YO, ROO, go to sleep," says the moon, and the person YAwns (YA).', 'a person tucked under a roof while the moon slips in beside them: night. "YO, ROO, go to sleep," says the moon, and they YAwn'),
      m('j:朝', 'Yuki giggles at the kanji for morning: a sun rising between two sprouts of grass while the pale moon still hangs beside it. "AH, SAH!" she stretches, and calls "CHOW time!" (CHOU).', 'a sun rises between two sprouts of grass while the pale moon still hangs beside it: morning. "AH, SAH!" you stretch, and someone calls "CHOW time!"'),
      m('w:maiasa', 'Every single morning Yuki sweeps the snow off the pond stones and sings the same little song: "MY AH-SAH, MY AH-SAH!"', 'every single morning a little girl sweeps the steps and sings "MY AH-SAH, MY AH-SAH!", the same song, day after day'),
      m('j:早', 'Yuki draws the sun sitting just one stick-length above the ground: early. A rooster on her head crows "HAH-YAY! SO early!" (SOU) before anyone else is awake.', 'the sun sits just one stick-length above the ground: early. A rooster crows "HAH-YAY! SO early!" before anyone else is awake'),
    ],
  },
  {
    id: 'p9-pilgrims',
    room: 9,
    map: 'snowtemple',
    anchor: 'st-pilgrims',
    name: { jp: 'さんぱいの かぞく', en: 'Pilgrim Family' },
    emoji: '👪',
    memories: [
      m('w:chichi', 'The pilgrim girl bows and humbly introduces her own dad: "my father, CHEE-CHEE," while he grins with CHEESE stuck in his beard.', 'a girl bows and humbly introduces her own dad, "my father: CHEE-CHEE," while he grins with CHEESE stuck in his beard'),
      m('w:haha', 'Then she humbly introduces her own mum, who can’t stop laughing at everything, even the snow: "my mother, HA-HA!"', 'a girl humbly introduces her own mum, who can’t stop laughing at everything, even the snow: "my mother, HA-HA!"'),
      m('w:otousan', 'The pilgrim mother politely asks after your dad: "your OH-TOE-SAN?" Somewhere far away a man stands on his TOEs to wave back.', 'someone politely asks after your dad, bowing: "your OH-TOE-SAN?", and far away a man stands on his TOEs to wave back'),
      m('w:okaasan', 'The pilgrim boy shouts across the courtyard: "OH, KAH-SAN! the CAR is stuck in the snow!" and his mum comes running with a shovel.', 'a boy shouts politely across the snow: "OH, KAH-SAN! the CAR is stuck!" and his mum comes running with a shovel'),
      m('w:kazoku', 'The whole pilgrim family pulls out KAZOOs and plays in a row, father, mother and kids: the KAZOO-KOO family band.', 'a whole family plays KAZOOs in a row, father, mother and kids, the KAZOO-KOO family band, all humming the same tune'),
      m('w:ryoushin', 'Both parents link arms and twirl in the snow at a ROYAL SHIN-dig, "RYO-SHIN!", while their kids cheer for the two of them.', 'both parents link arms and twirl at a ROYAL SHIN-dig, "RYO-SHIN!", while the kids cheer for the two of them'),
      m('j:父', 'The pilgrim dad crosses two sticks into an X, with two flicks of sawdust flying above: a father chopping wood. "CHEE-CHEE," he grins, puffing "FOO!" (FU).', 'a dad crosses two sticks into an X, with two flicks of sawdust flying above: chopping wood. "CHEE-CHEE," he grins, puffing "FOO!"'),
      m('j:母', 'The pilgrim mum folds into the kanji for mother: a kneeling woman’s shape in a box, with two dots for nursing her baby. She laughs "HA-HA!" and BOws (BO).', 'a kneeling woman’s shape folded into a box, with two dots for nursing her baby: mother. She laughs "HA-HA!" and BOws'),
      m('g:kj-family', 'The pilgrim girl talks about her own dad HUMBLY to you, but calls your dad with honour-SAN. HUMBLE words for your own family, polite SAN words for everyone else’s.', 'a girl talks about her own dad humbly, but adds honour-SAN for someone else’s dad: HUMBLE words for your own family, polite SAN words for others’'),
    ],
  },
  {
    id: 'p9-fort',
    room: 9,
    map: 'snowtemple',
    anchor: 'st-kids',
    name: { jp: 'ゆきの とりで', en: 'Snowball Fort' },
    emoji: '🏰',
    memories: [
      m('w:ani', 'Your older brother is captain of the fort, crouched behind the snow wall like a boss. A snowball smacks his kneecap: "AH, KNEE!"', 'your older brother crouches behind a snow wall, the big boss, and yelps "AH, KNEE!" when a snowball smacks his kneecap'),
      m('w:oniisan', 'The younger kids politely call the captain "OH-NEE-SAN", and a little ONI horn pokes out of his woolly hat.', 'everyone politely calls the big boy "OH-NEE-SAN", and a little ONI horn pokes out of his woolly hat'),
      m('w:ane', 'Your older sister lobs the biggest snowball over the fort wall and taunts "AH, NEH! too slow!", always a step ahead of you.', 'your older sister lobs the biggest snowball and taunts "AH, NEH! too slow!", always a step ahead of you'),
      m('w:oneesan', 'The little kids in the fort bow and call her "OH-NEH-SAN", offering her the roundest snowballs as if she were a queen.', 'little kids bow and call the big girl "OH-NEH-SAN", offering her the roundest snowballs as if she were a queen'),
      m('w:otouto', 'Your little brother waddles out of the fort in a bucket helmet, "OH, TOE-TOE!", and trips over his own TOEs into the snow.', 'a little brother waddles out in a bucket helmet, "OH, TOE-TOE!", and trips over his own TOEs into the snow'),
      m('w:imouto', 'Your little sister rolls the tiniest snowball in the fort, stamps her boot and squeaks "EE-MOH-TOH!": the youngest and bossiest of all.', 'a little sister rolls the tiniest snowball, stamps her boot and squeaks "EE-MOH-TOH!", the youngest and bossiest of all'),
      m('j:兄', 'Over the fort walks a big mouth on two legs, bossing everyone about: the older brother. "AH, KNEE!" he yelps, then fires orders, "KYOH! KYOH!" (KYOU).', 'a big mouth walking on two legs, bossing everyone about: the older brother. "AH, KNEE!" he yelps, then fires orders, "KYOH! KYOH!"'),
      m('j:弟', 'In the fort lies a tiny bow wrapped in string with two horns poking up: little brother’s toy. He trips on it, "OH, TOE-TOE!", and DIves (DAI) into the snow.', 'a tiny bow wrapped in string with two horns poking up: a little brother’s toy. He trips on it, "OH, TOE-TOE!", and DIves into the snow'),
      m('j:姉', 'Beside the fort a woman stands at a market stall: big sister selling snowballs, shouting "AH, NEH!" at customers. SHE (SHI) is the boss.', 'a woman stands beside a market stall: big sister running the shop, shouting "AH, NEH!" at customers. SHE is the boss'),
    ],
  },
  {
    id: 'p9-fudezuka',
    room: 9,
    map: 'snowtemple',
    anchor: 'st-fudezuka',
    name: { jp: 'ふでづか', en: 'Brush Mound' },
    emoji: '🪦',
    memories: [
      m('j:妹', 'On the mound a girl stands beside a sapling that has not yet grown up: little sister. She squeaks "EE-MOH-TOH!" and points at the brushes: "MY (MAI) turn!"', 'a girl beside a sapling that has not yet grown up: little sister. She squeaks "EE-MOH-TOH!" and points: "MY turn!"'),
      m('w:kyoudai', 'A pack of siblings crowds round the mound playing dice, brothers and sisters together, yelling "KYO, DIE!" each time the DICE land.', 'a pack of siblings, brothers and sisters, crowd round a game, yelling "KYO, DIE!" each time the DICE land, all squabbling and all family'),
      m('w:deshi', 'A young apprentice kneels before the mound to thank his master’s old brush, humbly setting down a DISH of rice: "DEH-SHEE".', 'a young apprentice kneels before his master and humbly sets down a DISH, "DEH-SHEE", hoping to be taught'),
      m('g:kj-stroke-order', 'Every stone on the mound was carved in order: TOP before bottom, LEFT before right, the crossing horizontal before the vertical. Carve one out of order and the stone cracks.', 'a mason carves a character stroke by stroke: TOP before bottom, LEFT before right, horizontal before the vertical it crosses; carve out of order and the stone cracks'),
      m('g:kj-stroke-count', 'Each buried brush has a notch on its handle for every STROKE it wrote, and the mound keeper COUNTS them like tally marks: snow has eleven.', 'a brush handle has a notch for every separate pen movement, and someone COUNTS the STROKES like tally marks: snow has eleven'),
      m('j:紙', 'Silk threads are pressed beside a hooked spoon on the mound until the fibres turn flat and white: paper. It beckons "COME-EE!" (kami) and SHE (SHI) writes a thank-you on it.', 'silk threads are pressed beside a hooked spoon until the fibres turn flat and white: paper. It beckons "COME-EE!" and SHE writes a letter on it'),
      m('j:友', 'Carved on the mound: two hands, one reaching over the other, clasped tight. Friends. "TOH-MOH-dachi, YOU (YUU) and me!" they promise.', 'two hands, one reaching over the other, clasp tight: friends. "TOH-MOH-dachi, YOU and me!" they promise'),
    ],
  },
  {
    id: 'p9-office',
    room: 9,
    map: 'snowtemple',
    anchor: 'st-kuu',
    name: { jp: 'てらの じむしょ', en: 'Temple Office' },
    emoji: '📒',
    memories: [
      m('w:toshi', 'Kuu flips his calendar over a whole year and a birthday cake pops out of the register. "TOE-SHE!" cries the old woman blowing out the candles, a year older.', 'a calendar flips over a whole year and a birthday cake pops up; "TOE-SHE!" says the old woman blowing out the candles, a year older'),
      m('w:kotoshi', 'Kuu wears a brand-new COAT with this year’s date stitched on the collar: "COAT-O-SHE!" he says, wearing this year proudly. Not read piece by piece, but as a whole.', 'a brand-new COAT with this year’s date stitched on the collar: "COAT-O-SHE!" you say, wearing this year proudly'),
      m('w:kyonen', 'A gust slams the office door and a CYCLONE, "KYOH-NEN!", rips last year’s page off Kuu’s calendar and carries it away over the roofs.', 'a calendar page rips off and blows away in a CYCLONE, "KYOH-NEN!", carrying all of last year with it'),
      m('w:rainen', 'Kuu writes next year’s plans in the register and it starts to RAIN indoors, "RAI-NEN!", smudging everything he meant to do next year.', 'you write a plan on next year’s page and it starts to RAIN, "RAI-NEN!", smudging everything you meant to do next year'),
      m('w:maitoshi', 'Every year the same goose waddles into the office and pecks Kuu’s foot: "MY TOE! SHE did it again!" Every year without fail.', 'every single year the same goose waddles in and pecks your foot: "MY TOE! SHE did it again!", every year without fail'),
      m('w:shinnen', 'A pine-and-bamboo decoration hangs on the office door, and a NINja leaps out of it kicking SHINS, "SHIN-NEN!", shouting Happy New Year.', 'a pine-and-bamboo decoration hangs on a door and a NINja leaps out kicking SHINS, "SHIN-NEN!", shouting Happy New Year'),
      m('j:年', 'On Kuu’s calendar a farmer shoulders a sheaf of grain on a long pole: one harvest, one year gone. He counts, "TOE-SHE... NEN, NEN, NINE!" (NEN).', 'a farmer shoulders a sheaf of grain on a long pole: one harvest, one year gone. He counts years, "TOE-SHE... NEN, NEN, NINE!"'),
      m('j:毎', 'In the office a mother puts on the very same little hat on top of her head every single day, and every time she sighs "MY, MY!" (MAI).', 'a mother puts on the very same little hat on top of her head every single day, and every time she sighs "MY, MY!"'),
      m('g:kj-time-ni', 'Kuu pins CLOCK times to his register with a NEEdle: seven o’clock, NI. But RELATIVE time words like next year or every morning float free with no pin.', 'clock times are pinned down with a NEEdle, "NI", but RELATIVE time words like this year or every morning float free with no pin at all'),
    ],
  },
  {
    id: 'p9-genta',
    room: 9,
    map: 'snowtemple-bell',
    anchor: 'sb-genta',
    name: { jp: 'かねつきの げんた', en: 'Bell Keeper' },
    emoji: '🧘',
    memories: [
      m('w:konshuu', 'Genta’s chore list for this week is an ice-cream CONE stuffed in a SHOE, "CON-SHOO!". Lick it before the week runs out.', 'an ice-cream CONE stuffed in a SHOE, "CON-SHOO!", is this week’s chore list: lick it before the week runs out'),
      m('w:raishuu', 'Genta fills a SHOE with RICE for next week, "RAI-SHOO!", and leaves it by the bell to deal with later.', 'someone fills a SHOE with RICE for next week, "RAI-SHOO!", and leaves it by the door to deal with later'),
      m('w:maishuu', 'Every single week Genta stomps around the tower bellowing "MY SHOE!", because it has gone missing yet again.', 'every single week a big man stomps about bellowing "MY SHOE!", because it has gone missing yet again'),
      m('w:kongetsu', 'On this month’s page of Genta’s calendar a giant ice-cream CONE GETS YOU, "KON-GETSU!", melting all over the moon.', 'a giant ice-cream CONE GETS YOU on this month’s calendar page, "KON-GETSU!", melting all over the moon'),
      m('w:raigetsu', 'Genta turns to next month and a sack of RICE topples off the page and GETS YOU, "RAI-GETSU!", burying you in grains.', 'a sack of RICE topples off next month’s calendar page and GETS YOU, "RAI-GETSU!", burying you in grains'),
      m('w:obousan', 'Genta, a shaven-headed monk in black robes, toots an OBOE instead of chanting, "OH-BOH-SAN!", while the temple cat covers its ears.', 'a shaven-headed monk in black robes toots an OBOE instead of chanting, "OH-BOH-SAN!", while a cat covers its ears'),
      m('j:週', 'Genta paces a full lap around the tower on the road radical, round and round: one lap, one week. Each lap he loses a SHOE, "SHUU!"', 'a walker paces a full lap around a walled square, a loop on the move: one week. Each lap he loses a SHOE, "SHUU!"'),
      m('j:来', 'Genta’s little potted tree waves its arms like someone beckoning: come here! It calls "KOO-ROO!" and sprouts ears of RYE (RAI).', 'a little tree waves its arms like someone beckoning: come here! It calls "KOO-ROO!" and sprouts ears of RYE (RAI)'),
    ],
  },
  {
    id: 'p9-bell',
    room: 9,
    map: 'snowtemple-bell',
    anchor: 'sb-bell',
    name: { jp: 'おおがね', en: 'Great Bell' },
    emoji: '🔔',
    memories: [
      m('w:kane', 'Genta swings a CANE into the great bell, "KAH-NEH!", and the BONG rolls out over the snowy mountains.', 'a huge bronze bell hangs from a beam and someone swings a CANE into it: "KAH-NEH!", and the BONG rolls over the mountains'),
      m('w:gozen', 'The bell rings before noon and the monks GO to ZEN meditation, "GO-ZEN!", the whole morning spent sitting still beneath it.', 'before noon a bell rings out and the monks GO to ZEN meditation, "GO-ZEN!", the whole morning spent sitting still'),
      m('w:gogo', 'After lunch the bell clangs and Genta yells "GO-GO!": afternoon, back to work, everyone grumbling up from their naps.', 'after lunch a whistle blows "GO-GO!": afternoon, back to work, everyone grumbling up from their naps'),
      m('w:mae-before', 'You step to the front of the queue at the bell and someone yells "MY, EH? I was here before you!" Standing in front, the one who came before.', 'you step to the front of the line and someone yells "MY, EH? I was here before you!" — standing in front, the one who came before'),
      m('j:午', 'On the bell’s side, a cow that has lost its horn stands at the top of the sky at midday: noon exactly. Everyone shouts "GO!" (GO) for lunch.', 'a cow that has lost its horn stands at the top of the sky at midday, noon exactly, and everyone shouts "GO!" for lunch'),
      m('j:前', 'Cast on the bell: a boat with a knife on its prow cutting forward, always in front. "MY, EH? I’m first!" and the ZEN monks wave from its bow.', 'a boat with a knife on its prow cuts forward through the waves, always in front: "MY, EH? I’m first!" and the ZEN monks wave from its bow'),
      m('j:後', 'Behind the bell someone shuffles on slow feet, trailing a short thread, falling behind and arriving after everyone: "AH, TOE!" they stub a foot and GO last.', 'someone shuffles along on slow feet, trailing a short thread, falling behind and arriving after everyone: "AH, TOE!", they stub their foot and GO last'),
      m('j:音', 'Someone STANDS on top of the sun and sings so loudly that the sound makes the bell hum: "OH-TOE!", and the volume is turned ON.', 'someone STANDS on top of the sun and sings so loudly that the sound rings across the sky: "OH-TOE!", and the volume is turned ON'),
    ],
  },
  {
    id: 'p9-abbot',
    room: 9,
    map: 'snowtemple-library',
    anchor: 'sl-abbot',
    name: { jp: 'ろうしの ざ', en: 'Abbot’s Dais' },
    emoji: '🪷',
    memories: [
      m('w:okyou', 'On his dais the old abbot chants from an accordion-folded scroll, rocking slowly, "OH-KYOH, OH-KYOH", each line a bead on his prayer beads.', 'an old monk chants from an accordion-folded scroll, rocking slowly, "OH-KYOH, OH-KYOH", each line a bead on his prayer beads'),
      m('j:寺', 'Above the dais a hand measures the ground inch by inch and lays a foundation stone: a temple. "TEH-RAH!" it announces, and "GEE (JI), it took ages".', 'a hand measures the ground inch by inch and lays a foundation stone: a temple, "TEH-RAH!" "GEE, it took ages"'),
      m('j:名', 'The abbot explains: in the dark evening no one can see faces, so a mouth calls out each name: "NAH-mae? MAY (MEI) I have your name?"', 'in the dark evening no one can see faces, so a mouth calls out each name: "NAH-mae? MAY I have your name?"'),
      m('w:myouji', 'A cat in a tiny monk’s robe introduces itself to the abbot family-name first: "MEOW-JEE, that is my surname", and stamps its paw print in the register.', 'a cat in a tiny suit introduces itself family-name first: "MEOW-JEE, that is my surname", and stamps its paw print'),
      m('g:kj-noma', 'The abbot’s scribe refuses to write the same kanji twice in a row: "NO, MA’AM," he says, and draws a little REPEAT mark instead.', 'a scribe refuses to write the same kanji twice in a row: "NO, MA’AM," he says, and draws a little REPEAT mark instead, so people people becomes hito-bito'),
      m('j:長', 'The abbot’s hair flows down to his feet, long, long: he is the chief. "NAH, GUY, that’s long!" "CHOW (CHOU) time, chief!"', 'an old man with long, long hair flowing down to his feet: long, and chief of his village. "NAH, GUY, that’s long!" "CHOW time, chief!"'),
      m('j:高', 'From the dais you see a tall pagoda, roof stacked on roof, high above the temple: "TAH-KAI!" you gasp, "COH (KOU), it’s high!"', 'a tall tower with roof stacked on roof stands high above the town: "TAH-KAI!" you gasp at the top, "COH, it’s high!"'),
    ],
  },
  {
    id: 'p9-scribe',
    room: 9,
    map: 'snowtemple-library',
    anchor: 'sl-scribe',
    name: { jp: 'しゃきょうの かしら', en: 'Head Scribe' },
    emoji: '🖋️',
    memories: [
      m('w:kanji', 'The head scribe shows you a mountain of characters from old China, each a little picture. "CAN, GEE?" you ask, "learn all these?" Yes, you CAN.', 'a mountain of Chinese characters, each a little picture: "CAN, GEE?" you ask, "learn all these?", and the answer is yes, you CAN'),
      m('w:ji-letter', 'The scribe squints at one scrawled character in your notebook: "GEE, what a character!", and corrects a single letter of your handwriting.', 'someone squints at a single scrawled written character: "GEE, what a character!", and corrects one letter of your handwriting'),
      m('j:漢', 'The scribe’s favourite kanji: a great river flows on the left, and beside it stands a scholar of old China, singing "CAN!" (KAN) as he floats characters east to Japan.', 'a great river flows on the left and beside it stands a scholar of old China, singing "CAN, GEE!" as he floats characters east to Japan'),
      m('j:字', 'Under the scriptorium roof a child sits learning letters one by one, squealing "GEE!" (JI) at each new character it writes.', 'a child sits under a roof learning letters one by one, squealing "GEE!" at each new character it writes'),
      m('w:benkyou', 'The scribe makes you study so hard your pencil BENDS, "BEN-KYOH!", books piled to the rafters, studying all night.', 'a student studies so hard that their pencil BENDS, "BEN-KYOH!", books piled to the ceiling, studying all night'),
      m('w:renshuu', 'You write the same stroke a hundred times while a WREN hopping in a SHOE pecks at every mistake: "REN-SHOO!", practice, practice.', 'you repeat the same exercise a hundred times while a WREN hopping in a SHOE pecks at every mistake: "REN-SHOO!", practice, practice'),
      m('j:勉', 'The scribe shows the kanji of effort: a rabbit straining with all its POWER to pull free of a trap, legs BENDing: "BEN!"', 'a rabbit strains with all its POWER to pull free, legs BENDing: "BEN!", pure effort, then flops down exhausted'),
      m('j:強', 'Over the scribe’s desk hangs a bow strong enough to shoot a giant beetle: "TSOO-YOI! strong!" It twangs "KYOH!" (KYOU) and the bug flies off.', 'a bow strong enough to shoot a giant beetle: "TSOO-YOI! strong!" It twangs "KYOH!" and the bug flies off'),
      m('j:習', 'A white chick on the scribe’s shelf flaps its wings again and again, learning to fly: "NAH-RAH-OOH!", until its mother SHOOs (SHUU) it off.', 'a white chick flaps its wings again and again, learning to fly: "NAH-RAH-OOH!", until its mother SHOOs it off the branch'),
    ],
  },
  {
    id: 'p9-desk',
    room: 9,
    map: 'snowtemple-library',
    anchor: 'sl-desk',
    name: { jp: 'かきものづくえ', en: 'Writing Desk' },
    emoji: '✍️',
    memories: [
      m('w:narau', 'At the desk an old teacher guides your hand on the brush. You learn from her, saying "NAH-RAH-OOH!" each time she corrects a stroke.', 'an old teacher guides your hand on the brush and you learn from her, saying "NAH-RAH-OOH!" each time she corrects a stroke'),
      m('w:manabu', 'At the next desk a MAN in A BOOTH studies by candlelight, "MAH-NAH-BOO", taking notes until he has mastered the whole book.', 'a MAN in A BOOTH studies by candlelight, "MAH-NAH-BOO", taking notes until he has mastered the whole book'),
      m('j:学', 'On the desk a child sits under a roof with three sparks of knowledge fizzing above: learning. It gasps "GAH-KOO!" (GAKU) at every new idea.', 'a child under a roof with three sparks of knowledge fizzing above: learning. It gasps "GAH-KOO!" at every new idea'),
      m('j:校', 'A tiny wooden schoolhouse sits on the desk beside a crossroads where children cross paths and mix: school. Its bell goes "KOH!" (KOU).', 'a wooden schoolhouse beside a crossroads where children cross paths and mix: school. The bell goes "KOH!"'),
      m('w:shodou', 'The master at the desk dips a huge brush and SHOWS the WAY: "SHOH-DOH!", one bold stroke of calligraphy across white paper.', 'a master dips a huge brush and SHOWS the WAY: "SHOH-DOH!", one bold stroke of calligraphy across white paper'),
      m('j:書', 'A hand grips an upright brush over the desk and writes: "KAH-KOO!" it scratches, SHOWing (SHO) off each stroke.', 'a hand grips an upright brush with its bristles over a page and writes: "KAH-KOO!" it scratches, SHOWing off each stroke'),
      m('j:道', 'Across the desk a head with a tuft of hair walks along the road radical: a path, a way. It goes "ME-CHEE" and "DOH!" (DOU) when it takes a wrong turn.', 'a head with a tuft of hair walks along a road: a path, a way. It goes "ME-CHEE" and "DOH!" when it takes a wrong turn'),
      m('w:sakubun', 'You stuff your whole composition into a SACK and carry it to the desk as a BOON for the teacher: "SAH-KOO-BOON!", a full essay to read.', 'you stuff your whole composition into a SACK and bring it as a BOON to the teacher: "SAH-KOO-BOON!", a full essay to read'),
      m('j:作', 'A person bends over the desk with a saw-toothed tool, making something: "TSOO-KOO-ROO!", sweeping the shavings into a SACK (SAKU).', 'a person bends over a workbench with a saw-toothed tool, making something: "TSOO-KOO-ROO!", sweeping the shavings into a SACK'),
    ],
  },
  {
    id: 'p9-copy',
    room: 9,
    map: 'snowtemple-library',
    anchor: 'sl-copytable',
    name: { jp: 'しゃきょうの つくえ', en: 'Copying Table' },
    emoji: '📜',
    memories: [
      m('w:bun-sentence', 'On the copying table a whole sentence, subject, particles and verb, is wrapped up in a single steamed BUN: "BOON!", first word to full stop.', 'a whole sentence, subject, particles and verb, is wrapped up in a single steamed BUN, "BOON!", from the first word to the final full stop'),
      m('j:文', 'A figure with a crossed pattern tattooed on his chest leans over the table: patterns that turned into writing. "BOON!" (BUN) he flexes, and a MONK (MON) copies it.', 'a figure with a crossed pattern tattooed across his chest, patterns that turned into writing: "BOON!", he flexes, and a MONK copies it'),
      m('w:ichigyou', 'You copy just one line of the sutra and your nose starts to ITCH: "ITCHY GYOH!" you sneeze, smudging the single line.', 'you copy just one line of text and your nose starts to ITCH; "ITCHY GYOH!" you sneeze, smudging the single line'),
      m('j:行', 'The table is a crossroads seen from above where travellers go: "EE-KOO!" they set off. And a line of text marches along it, "GYOH!" (GYOU).', 'a crossroads seen from above where travellers go: "EE-KOO!" they set off; and a line of text marches along it, "GYOH!"'),
      m('w:onyomi', 'A lamp marked China flicks ON beside each kanji on the table and its imported sound lights up: "ON-YOH-MEE", the reading borrowed from Chinese.', 'a lamp marked China flicks ON beside a kanji and its imported sound lights up: "ON-YOH-MEE", the reading borrowed from Chinese'),
      m('w:kunyomi', 'A COON from the local woods climbs onto the table and reads each kanji in its own homegrown Japanese way: "KOON-YOH-MEE", the native reading.', 'a COON from the local woods reads the kanji in its own homegrown Japanese way: "KOON-YOH-MEE", the native reading'),
      m('g:kj-onyomi', 'On the table, kanji pair up into COMPOUNDS and flick the ON switch: the Chinese-born sound lights up, so school is read gak-kou, the ON way.', 'kanji pair up into COMPOUNDS and flick the ON switch: the Chinese-born sound lights up, so two kanji side by side are usually read the ON way'),
      m('g:kj-kunyomi', 'A kanji standing ALONE at the edge of the table, or trailing little kana tails, speaks its native KOON reading: spring alone is haru.', 'a kanji standing ALONE, or trailing little kana tails, speaks its native Japanese KOON reading, the one used for words on their own'),
      m('g:kj-okurigana', 'On the table a kanji stem stands firm like an OAK while its little kana TAIL wags and changes, write to writes: "OH-KOO-REE-GAH-NAH".', 'a kanji stem stands firm like an OAK while its little kana TAIL changes shape, wagging from one ending to the next: OH-KOO-REE-GAH-NAH'),
    ],
  },
  {
    id: 'p9-shoji',
    room: 9,
    map: 'snowtemple-library',
    anchor: 'fk9-shoji',
    name: { jp: 'もくもくれんの しょうじ', en: 'Watching Screen' },
    emoji: '👁️',
    memories: [
      m('j:見', 'One of the eyes in the torn screen grows two legs and strolls out, staring at everything: "MEE-ROO!", and KEN (KEN), the eye, sees it all.', 'a big eye grows two legs and strolls about staring at everything: "MEE-ROO!", and KEN, the eye, sees it all'),
      m('j:読', 'The eyes in the screen read a market seller’s sign: speech on the left, the seller on the right, read out loud. "YOH-MOO!", "DOC (DOKU), read it to me!"', 'speech on the left, a market seller on the right: reading the seller’s sign out loud. "YOH-MOO!", "DOC, read it to me!"'),
      m('j:話', 'Through a hole in the screen a word bubble pops out next to a waggling tongue: talking. "HAH-NAH-SOO!" it chatters, "WAH (WA), let me tell you a story!"', 'a word bubble next to a waggling tongue: talking. "HAH-NAH-SOO!" it chatters, "WAH, let me tell you a story!"'),
      m('j:語', 'A speech bubble beside the word for "me" sticks to the screen: my own language. "GO (GO) on," the eyes urge, "say it in your language!"', 'a speech bubble beside the word "me": my own language. "GO on," it urges, "say it in your language!"'),
      m('g:kj-radical', 'Every eye in the screen ignores the whole kanji and peers at its key piece first, the RADICAL: speech means talk, water means wet, tree means wood.', 'a detective with a magnifying glass ignores the whole kanji and peers at its key piece, the RADICAL: speech means talk, water means wet, tree means wood'),
      m('j:何', 'A person behind the screen holds up a sign with a hook on it and shrugs: "NAH-NEE? what?", pointing at a passing CAR (KA).', 'a person holds a sign with a hook on it and shrugs: "NAH-NEE? what?", pointing at a passing CAR'),
    ],
  },
  {
    id: 'p9-fisher',
    room: 9,
    map: 'snowtemple-lake',
    anchor: 'lk-fisher',
    name: { jp: 'あなづりの りょうし', en: 'Ice Fisher' },
    emoji: '🎣',
    memories: [
      m('j:食', 'The fisher lifts the lid off a steaming pot of his catch: eating. "TAH-BEH-ROO!" he digs in. SHOCK (SHOKU)-ingly delicious!', 'a lid lifts off a steaming pot of good food: eating. "TAH-BEH-ROO!" you dig in. SHOCK-ingly delicious!'),
      m('j:飲', 'Beside the ice hole the fisher opens his mouth wide, as if yawning, over a bowl of hot sake: drinking. "NOH-MOO!" he gulps, and the warmth goes IN (IN).', 'a wide-open, yawning mouth next to a bowl: drinking. "NOH-MOO!" you gulp, and the warm drink goes IN'),
      m('j:買', 'The fisher’s net scoops up a shell coin from the ice hole: catching things with money, buying. "KAH-OOH," he pays, and BUYs (BAI) a bag of bait.', 'a net scoops up a shell coin: catching things with money, buying. "KAH-OOH," you pay, and BUY a bag of bait'),
      m('j:新', 'The fisher splits a standing tree with an axe for a new rod, and the fresh wood gleams: "AH-TAH-RAH-SHEE!", new. A splinter scrapes his SHIN (SHIN).', 'a standing tree is split by an axe and its fresh, new wood gleams: "AH-TAH-RAH-SHEE!", and a splinter scrapes your SHIN'),
      m('g:kj-jukugo', 'The fisher hauls up two kanji fish hooked TOGETHER on one line, a COMPOUND catch, and together they speak in their ON voice: "JOO-KOO-GO!"', 'two kanji fish come up hooked TOGETHER on one line, a COMPOUND catch, and together they speak in their ON voice: "JOO-KOO-GO!"'),
    ],
  },
  {
    id: 'p9-stele',
    room: 9,
    map: 'snowtemple-lake',
    anchor: 'lk-stele',
    name: { jp: 'みずうみの いしぶみ', en: 'Lakeside Stele' },
    emoji: '🪨',
    memories: [
      m('g:kj-rendaku', 'Carved on the stele: mountain plus temple. When the two words join hands, the second one’s first sound gets two little voice dots: tera becomes dera. "REN-DAH-KOO!" it rumbles deeper.', 'two words join hands and the second one’s first sound gets two little voice dots: t becomes D, k becomes G. "REN-DAH-KOO!", it rumbles deeper'),
      m('g:kj-sokuon', 'Another stele: learning plus school. The two squeeze together and the first one’s ending shrinks to a tiny GULP, a small tsu: gaku plus kou becomes GAK-KOU.', 'two kanji squeeze together and the first one’s ending shrinks to a tiny GULP, a small tsu: gaku plus kou becomes GAK-KOU, "SOH-KOO-ON"'),
      m('g:kj-jukujikun', 'One stele refuses to be read kanji by kanji: it must be read as a WHOLE, like a nickname. This year is KOTOSHI, the Star Festival is TANABATA.', 'some words refuse to be read kanji by kanji and must be read as a WHOLE, like a nickname: this year is KOTOSHI, the Star Festival is TANABATA'),
      m('j:歌', 'On the stele, two stacked open-mouth signs sit beside a wide singing mouth: a song. "OOH-TAH!" you sing across the ice, and the crows join in, "KAH!" (KA).', 'two stacked open-mouth signs beside a wide singing mouth: a song. "OOH-TAH!" you sing, and the crows join in, "KAH!"'),
    ],
  },
  {
    id: 'p9-tsurara',
    room: 9,
    map: 'snowtemple-lake',
    anchor: 'fk9-tsurara',
    name: { jp: 'つららの こや', en: 'Icicle Hut' },
    emoji: '🧊',
    memories: [
      m('j:赤', 'In the hut’s hearth, flames roar beneath a lump of earth until it glows red: "AH-KAI!", red-hot. "SAY, KEY?" (SEKI) asks the woman in white, backing away from it.', 'flames roar beneath a lump of earth until it glows red: "AH-KAI!", red-hot; "SAY, KEY?" you ask, too hot to touch'),
      m('j:青', 'An icicle on the hut’s eaves catches a sprout growing over the moon, and everything turns the blue-green of new leaves and moonlit sky: "AH-OY!", "SAY (SEI), it’s blue!"', 'a sprout grows over the moon and everything turns the blue-green of new leaves and moonlit sky: "AH-OY!", "SAY, it’s blue!"'),
      m('j:黒', 'The hut sits over a smoky fire until it is covered in soot: black. "COO, ROY!" you cough, smeared in COKE (KOKU) dust.', 'a village sits over a smoky fire until it is covered in soot: black. "COO, ROY!" you cough, smeared in COKE dust'),
      m('j:色', 'Under the icicles a figure crouches over a coiled snake whose scales flash every colour: "EE-ROH!", a rainbow of hues, SHOCKing (SHOKU) pink to blue.', 'a figure crouches over a coiled snake whose scales flash every colour: "EE-ROH!", a rainbow of hues, SHOCKing pink to blue'),
    ],
  },
]
