/**
 * Region 9 pixel art: a young monk in black robes under a wide straw kasa,
 * a little snow child in a straw cape (mino), a snow wolf and Yuki-onna.
 * Palette characters are raster.LEGEND's (t/T straw, n/N night robes,
 * p paper, w white, i ice, C foam, m mist, S stone shade).
 */
import type { RegionSprites } from '../types'

const E16 = '................'
/** Pad a half-map to 32 rows (content placed from `top`). */
function rows32(top: number, body: string[]): string[] {
  const out: string[] = []
  for (let i = 0; i < top; i++) out.push(E16)
  out.push(...body)
  while (out.length < 32) out.push(E16)
  return out.slice(0, 32)
}

export const SPRITES: RegionSprites = {
  characters: {
    monk: {
      legRows: [14, 14],
      down: [
        '................',
        '.......tt.......',
        '.....tttttt.....',
        '...tttttttttt...',
        '.TTTTTTTTTTTTTT.',
        '....ffffffff....',
        '....fkffffkf....',
        '....fkffffkf....',
        '....hffffffh....',
        '....nnwwwwnn....',
        '...nnnnwwnnnN...',
        '..fnnnnnnnnnNf..',
        '...nnnnnnnnnN...',
        '...nnnn..nnnN...',
        '....pp..........',
        '................',
      ],
      up: [
        '................',
        '.......tt.......',
        '.....tttttt.....',
        '...tttttttttt...',
        '.TTTTTTTTTTTTTT.',
        '....FFFFFFFF....',
        '....FFFFFFFF....',
        '....FFFFFFFF....',
        '.....FFFFFF.....',
        '....nnnnnnnn....',
        '...nnnnnnnnnN...',
        '..fnnnnnnnnnNf..',
        '...nnnnnnnnnN...',
        '...nnnn..nnnN...',
        '....pp..........',
        '................',
      ],
      side: [
        '................',
        '......tt........',
        '....tttttt......',
        '..tttttttttt....',
        'TTTTTTTTTTTTTT..',
        '.....Ffffff.....',
        '.....Ffffkf.....',
        '.....Ffffkf.....',
        '.....Fffhff.....',
        '.....nnwwn......',
        '....nnnnwn......',
        '....nnnnnfn.....',
        '....nnnnnn......',
        '....nnn.nnn.....',
        '....pp...pp.....',
        '................',
      ],
    },
    snowchild: {
      span: [4, 11],
      down: [
        '................',
        '................',
        '.......tt.......',
        '.....tttttt.....',
        '....tTTTTTTt....',
        '....tiwwwwit....',
        '....tfkffkft....',
        '....tfkffkft....',
        '....thffffht....',
        '...tTttFFttTt...',
        '..tTtTtttTtTtt..',
        '..TtTtTtTtTtTT..',
        '...TtTtTtTtTT...',
        '......p..p......',
        '......T.........',
        '................',
      ],
      up: [
        '................',
        '................',
        '.......tt.......',
        '.....tttttt.....',
        '....tTTTTTTt....',
        '....tttttttt....',
        '....tTtttTtt....',
        '....tttttttt....',
        '....tTttTttt....',
        '...tTtTtTtTtT...',
        '..tTtTtttTtTtt..',
        '..TtTtTtTtTtTT..',
        '...TtTtTtTtTT...',
        '......p..p......',
        '......T.........',
        '................',
      ],
      side: [
        '................',
        '................',
        '.......tt.......',
        '.....tttttt.....',
        '....tTTTTTTt....',
        '....ttTiwwww....',
        '....ttTffkf.....',
        '....ttTffkf.....',
        '....ttTfhff.....',
        '...tTtTtfft.....',
        '..tTtTtTtTt.....',
        '..TtTtTtTtT.....',
        '...TtTtTtT......',
        '.....p...p......',
        '.....T...T......',
        '................',
      ],
    },
  },
  enemies: {
    'snow-wolf': {
      sym: true,
      shade: 'm',
      anim: 'squash',
      pivot: 30,
      rows: rows32(2, [
        '..m.............',
        '..mm............',
        '..mSm...........',
        '..mSSm..........',
        '..mSSmm.........',
        '..mmmmmmmmmmmmmm',
        '.mmmmmmmmmmmmmmm',
        '.mmmmmmmmmmmmmmm',
        '.mmmmwwmmmmmmmmm',
        '.mmmwiikmmmmmmmm',
        '.mmmmwwmmmmmmmww',
        '..mmmmmmmmmmmwww',
        '..mmmmmmmmmmwwww',
        '...mmmmmmmmwwwwk',
        '...mmmmmmmmwwwkk',
        '....mmmmmmmmwwww',
        '.....mmmmmmmmwwV',
        '....mmmmmmmmmmww',
        '...mmwmmmwmmmmww',
        '..mmwmmmwmmmwmww',
        '..mmmmmmmmmmmmmw',
        '..mmmmmmmmmmmmmm',
        '...mmmmmmmmmmmmm',
        '...mmmmmmmmmmmmm',
        '...mmmmmmmmmmmmm',
        '....mmmm..mmmmmm',
        '....mmmm...mmmm.',
        '....mmmm...mmmm.',
        '...wwwww..wwwww.',
      ]),
      patch: [{ x: 5, y: 11, rows: ['w'] }],
      frame1: [
        { x: 13, y: 21, rows: ['.CC.', 'C..C'], sym: false },
        { x: 2, y: 2, rows: ['.m', 'mm'] },
      ],
    },
    'yuki-onna': {
      sym: true,
      shade: 'w',
      anim: 'bob',
      rows: rows32(1, [
        '..........nnnnnn',
        '........nnnnnnnn',
        '.......nnnnnnnnn',
        '......nnnnnnnnnn',
        '......nnnnnnpppp',
        '.....nnnnnnppppp',
        '.....nnnnnpppppp',
        '.....nnnnnpikppp',
        '.....nnnnnpppppp',
        '.....nnnnnpppppp',
        '.....nnnnnnppppV',
        '....nnnnnnnnpppp',
        '....nnnnnnnnwwww',
        '....nnnnnnnwwwiw',
        '...nnnnnnnwwwiww',
        '...nnnnnnwwwwwiw',
        '...nnnnnwwwwwwbb',
        '..nnnnnwwwwwwbbb',
        '..nnnnnwwwwwwbbb',
        '..nnnnwwwwwwwwww',
        '..nnnwwwwwwwwwiw',
        '..nnnwwwwwwwwiww',
        '..nnwwwwwwwwwwww',
        '...nwwwwwwwwwwww',
        '...wwwwwwwwwwwww',
        '..iwwwwwwwwwwwww',
        '.iiwwwwwwwwwwwww',
        'iiiiwwwwwwwwwwww',
        '.iiiiiiwwwwwwwww',
        '..i.iiiiiwwiiiii',
        '.....i..i..i..i.',
      ]),
      patch: [{ x: 1, y: 6, rows: ['C.', '.w'], sym: false }],
      frame1: [
        { x: 28, y: 9, rows: ['.C', 'w.'], sym: false },
        { x: 3, y: 15, rows: ['.n', 'nn', 'n.'] },
      ],
    },
  },
}
