/**
 * Region 10 — 雲の都, the Cloud Capital. A city of palaces floating above
 * the weather, reached by a rainbow bridge: the last stop before the Tower.
 * Here the learner's grammar grows into real N4 sentences: the plain and
 * ない forms, comparisons, the potential, three kinds of "if", reasons,
 * opinions, plans, duty and guesses about tomorrow's weather.
 *
 * Words: weather and sky, verbs of the mind, feelings and abstract nouns,
 * and the little words of comparing and guessing (もっと, 一番, たぶん…).
 */
import type { RegionData } from '../types'

export const DATA: RegionData = {
  region: {
    id: 10,
    name: 'The Cloud Capital',
    jp: '雲の都',
    reading: 'くものみやこ',
    tagline: 'Above the weather, every thought becomes a sentence.',
    teaches: ['Plain and ない forms', 'Comparisons, “can” and three kinds of “if”', 'Reasons, opinions, plans and guesses'],
    color: '#9b8cf2',
    emoji: '☁️',
    pos: { x: 68, y: 20 },
    map: 'clouds',
  },

  words: [
    // ── Reading the Sky: weather words
    ['tenki', '天気', 'てんき', 'weather', 'noun', '🌤️', { element: 'wind' }],
    ['hare', '晴れ', 'はれ', 'clear weather', 'noun', '☀️', { alt: ['sunny weather', 'sunny', 'fine weather', 'clear skies'], element: 'light' }],
    ['kumori', '曇り', 'くもり', 'cloudy weather', 'noun', '🌥️', { alt: ['cloudy', 'overcast'], element: 'wind' }],
    ['kaminari', '雷', 'かみなり', 'thunder', 'noun', '⚡', { alt: ['thunderbolt', 'thunderstorm'], element: 'light' }],
    ['inazuma', '稲妻', 'いなずま', 'lightning', 'noun', '🌩️', { alt: ['lightning flash', 'lightning bolt'], element: 'light' }],
    ['niji', '虹', 'にじ', 'rainbow', 'noun', '🌈', { element: 'light' }],
    ['arashi', '嵐', 'あらし', 'storm', 'noun', '🌪️', { alt: ['tempest'], element: 'wind' }],
    ['kiri', '霧', 'きり', 'fog', 'noun', '🌫️', { alt: ['mist'], element: 'water' }],
    ['ten', '天', 'てん', 'heaven', 'noun', '🌌', { alt: ['the heavens', 'the sky above'], element: 'light' }],
    ['tenki-yohou', '天気予報', 'てんきよほう', 'weather forecast', 'noun', '📻', { alt: ['forecast'] }],
    ['hareru', '晴れる', 'はれる', 'clear up', 'verb', '🌞', { masu: '晴れます', alt: ['to clear up', 'be sunny', 'become sunny'] }],
    ['furu', '降る', 'ふる', 'fall (rain, snow)', 'verb', '🌧️', { masu: '降ります', alt: ['to fall', 'fall', 'to rain', 'come down'] }],
    ['fuku', '吹く', 'ふく', 'blow (wind)', 'verb', '🌬️', { masu: '吹きます', alt: ['to blow', 'blow'] }],
    ['oto', '音', 'おと', 'sound', 'noun', '🔊', { alt: ['noise'] }],
    ['taiko', '太鼓', 'たいこ', 'drum', 'noun', '🥁', { alt: ['taiko drum', 'Japanese drum'] }],

    // ── Verbs of the Mind: thinking, knowing, deciding
    ['omou', '思う', 'おもう', 'think', 'verb', '💭', { masu: '思います', alt: ['to think', 'feel', 'believe (think)'] }],
    ['kangaeru', '考える', 'かんがえる', 'consider', 'verb', '🤔', { masu: '考えます', alt: ['to consider', 'think about', 'ponder', 'think over'] }],
    ['kimeru', '決める', 'きめる', 'decide', 'verb', '⚖️', { masu: '決めます', alt: ['to decide', 'choose (decide)', 'settle'] }],
    ['kuraberu', '比べる', 'くらべる', 'compare', 'verb', '📊', { masu: '比べます', alt: ['to compare'] }],
    ['shiru', '知る', 'しる', 'get to know', 'verb', '💡', { masu: '知ります', alt: ['to know', 'know', 'learn of', 'find out'] }],
    ['wakaru', '分かる', 'わかる', 'understand', 'verb', '🧠', { masu: '分かります', alt: ['to understand', 'get it', 'know'] }],
    ['dekiru', 'できる', 'できる', 'can do', 'verb', '💪', { masu: 'できます', alt: ['be able to', 'can', 'be possible'] }],
    ['wasureru', '忘れる', 'わすれる', 'forget', 'verb', '🫥', { masu: '忘れます', alt: ['to forget'] }],
    ['oboeru', '覚える', 'おぼえる', 'remember', 'verb', '📝', { masu: '覚えます', alt: ['to remember', 'memorise', 'memorize', 'learn by heart'] }],
    ['shinjiru', '信じる', 'しんじる', 'believe', 'verb', '🙏', { masu: '信じます', alt: ['to believe', 'trust', 'believe in'] }],
    ['naru', 'なる', 'なる', 'become', 'verb', '🦋', { masu: 'なります', alt: ['to become', 'turn into', 'get'] }],
    ['hajimeru', '始める', 'はじめる', 'begin', 'verb', '🏁', { masu: '始めます', alt: ['to begin', 'start', 'to start'] }],
    ['tsuzukeru', '続ける', 'つづける', 'continue', 'verb', '🔁', { masu: '続けます', alt: ['to continue', 'keep on', 'keep going'] }],
    ['erabu', '選ぶ', 'えらぶ', 'choose', 'verb', '👆', { masu: '選びます', alt: ['to choose', 'pick', 'select'] }],

    // ── Feelings and Meanings: how it feels, what it means
    ['tanoshii', '楽しい', 'たのしい', 'fun', 'i-adj', '🎉', { alt: ['enjoyable', 'pleasant'] }],
    ['ureshii', 'うれしい', 'うれしい', 'glad', 'i-adj', '😊', { alt: ['happy', 'joyful', 'delighted'] }],
    ['kanashii', '悲しい', 'かなしい', 'sad', 'i-adj', '😢', { alt: ['sorrowful'] }],
    ['sabishii', '寂しい', 'さびしい', 'lonely', 'i-adj', '🥺', { alt: ['lonesome'] }],
    ['kimochi', '気持ち', 'きもち', 'feeling', 'noun', '💗', { alt: ['feelings', 'mood'] }],
    ['imi', '意味', 'いみ', 'meaning', 'noun', '📖', { alt: ['sense'] }],
    ['riyuu', '理由', 'りゆう', 'reason', 'noun', '❓', { alt: ['cause', 'why'] }],
    ['yakusoku', '約束', 'やくそく', 'promise', 'noun', '🤞', { alt: ['appointment', 'vow'] }],
    ['mirai', '未来', 'みらい', 'future', 'noun', '🔮', { alt: ['the future'] }],
    ['kotae', '答え', 'こたえ', 'answer', 'noun', '✅', { alt: ['reply', 'solution'] }],
    ['shitsumon', '質問', 'しつもん', 'question', 'noun', '🙋', { alt: ['a question'] }],
    ['iken', '意見', 'いけん', 'opinion', 'noun', '🗣️', { alt: ['view', 'idea'] }],
    ['yuuki', '勇気', 'ゆうき', 'courage', 'noun', '🦁', { alt: ['bravery'] }],
    ['omoide', '思い出', 'おもいで', 'memory', 'noun', '📷', { alt: ['memories', 'keepsake', 'recollection'] }],
    ['fushigi', '不思議', 'ふしぎ', 'mysterious', 'na-adj', '🌀', { alt: ['strange', 'wondrous', 'mystery'] }],

    // ── More, Most, Maybe: comparing and guessing
    ['motto', 'もっと', 'もっと', 'more', 'adverb', '➕', { alt: ['even more'] }],
    ['ichiban', '一番', 'いちばん', 'the most', 'adverb', '🥇', { alt: ['number one', 'best', 'first', 'most'] }],
    ['zutto', 'ずっと', 'ずっと', 'much more', 'adverb', '↔️', { alt: ['all along', 'the whole time', 'far more', 'always'] }],
    ['hou', 'ほう', 'ほう', 'side (in comparisons)', 'noun', '⚖️', { alt: ['side', 'direction', 'the one that'] }],
    ['onaji', '同じ', 'おなじ', 'same', 'expression', '🟰', { alt: ['the same', 'identical'] }],
    ['chigau', '違う', 'ちがう', 'differ', 'verb', '🙅', { masu: '違います', alt: ['to differ', 'be different', 'be wrong'] }],
    ['kitto', 'きっと', 'きっと', 'surely', 'adverb', '✨', { alt: ['certainly', 'without fail', 'definitely'] }],
    ['tabun', 'たぶん', 'たぶん', 'probably', 'adverb', '🤷', { alt: ['perhaps', 'maybe'] }],
    ['dandan', 'だんだん', 'だんだん', 'gradually', 'adverb', '📈', { alt: ['little by little', 'step by step'] }],
    ['yatto', 'やっと', 'やっと', 'at last', 'adverb', '🏁', { alt: ['finally', 'at long last'] }],
    ['sugu', 'すぐ', 'すぐ', 'right away', 'adverb', '⏩', { alt: ['soon', 'at once', 'immediately'] }],
    ['hontou', '本当', 'ほんとう', 'truth', 'noun', '💯', { alt: ['really', 'true', 'reality'] }],
  ],

  grammar: [
    { id: 'plain-form', region: 10, jp: '〜る・〜う（じしょけい）', say: 'jisho-kei', en: 'plain (dictionary) form: casual “do”, and the form other grammar is built on', example: { jp: 'わたしは 毎日 本を よむ。', en: 'I read books every day. (casual)' } },
    { id: 'nai-form', region: 10, jp: '〜ない', say: 'nai', en: 'plain “don’t”: よむ→よまない, たべる→たべない, する→しない, くる→こない', example: { jp: 'きょうは 雨が ふらない。', en: 'It won’t rain today.' } },
    { id: 'yori-hou', region: 10, jp: 'Bより Aのほうが〜', say: 'yori … no hō ga', en: 'comparing two: A is more ~ than B', example: { jp: '雨より 雪の ほうが 好きです。', en: 'I like snow more than rain.' } },
    { id: 'naka-de-ichiban', region: 10, jp: '〜の中で Aが いちばん〜', say: 'no naka de … ichiban', en: 'among a group, A is the most ~', example: { jp: '天気の 中で 晴れが いちばん 好きです。', en: 'Of all weather, I like clear skies best.' } },
    { id: 'potential', region: 10, jp: '〜られる・〜える', say: 'rareru / eru', en: 'can do (potential): たべる→たべられる, よむ→よめる, する→できる', example: { jp: 'この 字が よめますか。', en: 'Can you read this character?' } },
    { id: 'koto-ga-dekiru', region: 10, jp: '〜ことが できる', say: 'koto ga dekiru', en: 'can ~: dictionary form + ことが できる', example: { jp: 'てんにんは 雲の 上を あるく ことが できます。', en: 'Celestial maidens can walk on the clouds.' } },
    { id: 'tara', region: 10, jp: '〜たら', say: 'tara', en: 'if / once ~ happens (た-form + ら), then…', example: { jp: '晴れたら、山へ 行きましょう。', en: 'If it clears up, let’s go to the mountain.' } },
    { id: 'ba', region: 10, jp: '〜ば', say: 'ba', en: 'if ~ (condition): よむ→よめば, たべる→たべれば, ない→なければ', example: { jp: '毎日 よめば、おぼえます。', en: 'If you read every day, you’ll remember.' } },
    { id: 'to-whenever', region: 10, jp: '〜と（じょうけん）', say: 'to', en: 'whenever A happens, B naturally follows (dictionary form + と)', example: { jp: '風が ふくと、雲が うごきます。', en: 'When the wind blows, the clouds move.' } },
    { id: 'kara-because', region: 10, jp: '〜から', say: 'kara', en: 'because ~ (the reason comes first, then から)', example: { jp: '雨だから、行きません。', en: 'It’s raining, so I won’t go.' } },
    { id: 'to-omou', region: 10, jp: '〜と おもう', say: 'to omou', en: 'I think that ~ (plain form + と おもう)', example: { jp: 'あしたは 晴れると おもいます。', en: 'I think it will be sunny tomorrow.' } },
    { id: 'tsumori', region: 10, jp: '〜つもり', say: 'tsumori', en: 'I plan / intend to ~ (dictionary form + つもり)', example: { jp: 'あした 山に 行く つもりです。', en: 'I plan to go to the mountain tomorrow.' } },
    { id: 'nakereba-naranai', region: 10, jp: '〜なければ ならない', say: 'nakereba naranai', en: 'must ~ (ない-form: ない→なければ ならない)', example: { jp: 'もう かえらなければ なりません。', en: 'I have to go home now.' } },
    { id: 'kamoshirenai', region: 10, jp: '〜かもしれない', say: 'kamo shirenai', en: 'might ~ / maybe (a real possibility, not sure)', example: { jp: 'あしたは 雨かもしれません。', en: 'It might rain tomorrow.' } },
    { id: 'deshou', region: 10, jp: '〜でしょう', say: 'deshō', en: 'probably ~ (forecasts and confident guesses)', example: { jp: 'あしたは 雪でしょう。', en: 'It will probably snow tomorrow.' } },
  ],

  sentences: [
    { id: 'cl1', en: 'Thunder is louder than rain.', tokens: ['雨', 'より', '雷', 'の', 'ほう', 'が', 'うるさい', 'です'], distractors: ['を', 'いちばん'], region: 10, hint: 'B より A の ほうが ~: the thing that wins the comparison takes の ほうが.' },
    { id: 'cl2', en: 'Of all weather, I like clear skies best.', tokens: ['天気', 'の', '中', 'で', '晴れ', 'が', '一番', '好き', 'です'], distractors: ['より', 'を'], region: 10, hint: '~の 中で marks the group; the winner takes が, then 一番.' },
    { id: 'cl3', en: 'I think it will be sunny tomorrow.', tokens: ['明日', 'は', '晴れる', 'と', '思います'], distractors: ['を', '晴れます'], region: 10, hint: 'と 思います follows the plain form: 晴れる, not 晴れます.' },
    { id: 'cl4', en: 'I can read this kanji.', tokens: ['この', '漢字', 'が', '読めます'], distractors: ['で', '読みます'], region: 10, hint: 'The potential form 読める (can read) usually marks its object with が.' },
    { id: 'cl5', en: 'If it clears up, let’s go to the mountain.', tokens: ['晴れたら', '山', 'に', '行きましょう'], alts: [['晴れたら', '山', 'へ', '行きましょう']], distractors: ['を', '晴れて'], region: 10, hint: '〜たら: once it has cleared up, then… The condition comes first.' },
    { id: 'cl6', en: 'If you read every day, you will remember.', tokens: ['毎日', '読めば', '覚えます'], distractors: ['を', '忘れます'], region: 10, hint: '〜ば: よむ → よめば (“if you read”).' },
    { id: 'cl7', en: 'When the wind blows, the clouds move.', tokens: ['風', 'が', '吹く', 'と', '雲', 'が', '動きます'], distractors: ['を', '吹いて'], region: 10, hint: 'Dictionary form + と: whenever A happens, B follows.' },
    { id: 'cl8', en: 'It’s raining, so I won’t go.', tokens: ['雨', 'だ', 'から', '行きません'], distractors: ['の', '行きます'], region: 10, hint: 'The reason comes first, then から: 雨だから.' },
    { id: 'cl9', en: 'I plan to cross the rainbow bridge.', tokens: ['虹', 'の', '橋', 'を', '渡る', 'つもり', 'です'], distractors: ['に', '渡ります'], region: 10, hint: 'つもり follows the dictionary form: 渡る つもり.' },
    { id: 'cl10', en: 'I have to go home.', tokens: ['家', 'に', '帰らなければ', 'なりません'], alts: [['家', 'へ', '帰らなければ', 'なりません']], distractors: ['帰らない', 'を'], region: 10, hint: 'かえらない → かえらなければ なりません: “must go home”.' },
    { id: 'cl11', en: 'It might rain tomorrow.', tokens: ['明日', 'は', '雨', 'が', '降る', 'かもしれません'], distractors: ['降ります', 'を'], region: 10, hint: 'かもしれません follows the plain form: 降る かもしれません.' },
    { id: 'cl12', en: 'It will probably snow tomorrow.', tokens: ['明日', 'は', '雪', 'でしょう'], distractors: ['ましょう', 'を'], region: 10, hint: 'でしょう makes a forecast: probably. ましょう means “let’s”.' },
    { id: 'cl13', en: 'I don’t understand the meaning.', tokens: ['意味', 'が', '分からない'], distractors: ['を', '分かる'], region: 10, hint: '分かる takes が, and its ない-form is 分からない.' },
    { id: 'cl14', en: 'I can speak Japanese.', tokens: ['日本語', 'を', '話す', 'こと', 'が', 'できます'], distractors: ['に', '話します'], region: 10, hint: 'Dictionary form + ことが できます = can do: 話す ことが できます.' },
  ],

  runes: [
    { id: 'cl-r1', jp: '明日は晴れるでしょう', reading: 'あしたははれるでしょう', answer: 'It will probably be sunny tomorrow.', wrong: ['It was sunny yesterday.', 'Let’s go out when it is sunny.'], region: 10 },
    { id: 'cl-r2', jp: '雨より雪のほうが好きです', reading: 'あめよりゆきのほうがすきです', answer: 'I like snow more than rain.', wrong: ['I like rain more than snow.', 'I like neither rain nor snow.'], region: 10 },
    { id: 'cl-r3', jp: '三つの中でこれが一番大きいです', reading: 'みっつのなかでこれがいちばんおおきいです', answer: 'Of the three, this one is the biggest.', wrong: ['This one is bigger than those three.', 'There are three big ones inside.'], region: 10 },
    { id: 'cl-r4', jp: 'この漢字が読めますか', reading: 'このかんじがよめますか', answer: 'Can you read this kanji?', wrong: ['Did you read this kanji?', 'Please write this kanji.'], region: 10 },
    { id: 'cl-r5', jp: '雷がなったら、家に帰ります', reading: 'かみなりがなったら、いえにかえります', answer: 'If thunder rolls, I’ll go home.', wrong: ['I went home because of the thunder.', 'The thunder came to my house.'], region: 10 },
    { id: 'cl-r6', jp: 'もう帰らなければなりません', reading: 'もうかえらなければなりません', answer: 'I have to go home now.', wrong: ['I don’t want to go home yet.', 'I already went home.'], region: 10 },
    { id: 'cl-r7', jp: '明日は雨かもしれません', reading: 'あしたはあめかもしれません', answer: 'It might rain tomorrow.', wrong: ['It will definitely rain tomorrow.', 'It did not rain today.'], region: 10 },
    { id: 'cl-r8', jp: '明日、山に行くつもりです', reading: 'あした、やまにいくつもりです', answer: 'I plan to go to the mountain tomorrow.', wrong: ['I went to the mountain yesterday.', 'I can’t go to the mountain tomorrow.'], region: 10 },
    { id: 'cl-r9', jp: '風が強いから、船は出ません', reading: 'かぜがつよいから、ふねはでません', answer: 'The wind is strong, so the ship won’t sail.', wrong: ['The ship sails because the wind is strong.', 'The wind stopped, so the ship left.'], region: 10 },
  ],

  readings: {
    雷: 'かみなり',
    漢字: 'かんじ',
    読めます: 'よめます',
    読みます: 'よみます',
    晴れたら: 'はれたら',
    晴れて: 'はれて',
    行きましょう: 'いきましょう',
    毎日: 'まいにち',
    読めば: 'よめば',
    覚えます: 'おぼえます',
    忘れます: 'わすれます',
    吹いて: 'ふいて',
    動きます: 'うごきます',
    行きません: 'いきません',
    行きます: 'いきます',
    渡ります: 'わたります',
    帰らなければ: 'かえらなければ',
    帰らない: 'かえらない',
    家: 'いえ',
    分からない: 'わからない',
  },

  npcs: [
    {
      id: 'forecaster',
      name: 'Shigure the Weather-Reader',
      jp: '天気よみの シグレ',
      emoji: '🌦️',
      region: 10,
      personality: 'Earnest young weather-reader of the Cloud Capital who writes the daily forecast on a great paper kite. Precise, a little anxious, and proud of never once being wrong (she has been wrong many times). Raijin’s drumming keeps shattering her sentences mid-forecast.',
      politeness: 'polite',
      color: '#9b8cf2',
      interests: ['tomorrow’s weather', 'clouds', 'rainbows', 'why the drums are so loud'],
      greeting: { jp: 'こんにちは！ あしたの 天気、しりたいですか？', en: 'Hello! Want to know tomorrow’s weather?' },
    },
  ],

  scenarios: [
    {
      id: 'clouds-forecast',
      npcId: 'forecaster',
      region: 10,
      translations: 'always',
      start: 'greet',
      hearts: 4,
      startTrust: 2,
      trustMax: 6,
      intro: [
        'Every time Raijin’s drums boom, Shigure’s weather forecast shatters halfway through a sentence.',
        'Help her finish them: でしょう (probably), かもしれない (might), と思う (I think), から (because), 〜たら (if / once).',
        'Pick the reply that completes the thought. Wrong answers cost a ❤️.',
      ],
      nodes: {
        greet: {
          id: 'greet',
          line: { jp: 'あ、たびの かた！ わたしは 天気よみの シグレです。', en: 'Oh, a traveller! I’m Shigure, the weather-reader.' },
          wordIds: ['tenki'],
          next: 'forecast',
          options: [
            { jp: 'はじめまして。よろしく おねがいします。', en: 'Nice to meet you.', correct: true, reply: { jp: 'こちらこそ！ ていねいな かたですね。', en: 'Likewise! How polite of you.' }, effects: { trust: 1 } },
            { jp: 'こんにちは。', en: 'Hello.', correct: true, reply: { jp: 'こんにちは！', en: 'Hello!' } },
            { jp: 'いただきます。', en: 'Thanks for the meal.', correct: false, reply: { jp: 'え？ ごはんは ありませんよ…', en: 'Huh? There’s no food here…' }, note: 'いただきます is said before eating. To greet someone you are meeting: はじめまして or こんにちは.' },
          ],
        },
        forecast: {
          id: 'forecast',
          line: { jp: 'たいこの 音で、よほうが こわれました。「あしたは 晴れる…」 つぎは？', en: 'The drums broke my forecast. “Tomorrow it will clear up…” What comes next?' },
          wordIds: ['tenki-yohou', 'hareru', 'taiko'],
          hint: 'A forecast is a confident guess: 〜でしょう (probably).',
          next: 'maybe',
          options: [
            { jp: '…でしょう。', en: '…probably.', correct: true, reply: { jp: '「あしたは 晴れるでしょう」！ そう、それです！', en: '“It will probably clear up tomorrow”! Yes, that’s it!' }, effects: { trust: 1 } },
            { jp: '…ましょう。', en: '…let’s!', correct: false, reply: { jp: '「晴れましょう」？ 空に おねがいしても…', en: '“Let’s clear up”? Asking the sky nicely won’t…' }, note: 'ましょう means “let’s”. A forecast uses でしょう: 晴れるでしょう.' },
            { jp: '…ください。', en: '…please.', correct: false, reply: { jp: 'それは おねがいです。よほうでは ありません。', en: 'That’s a wish, not a forecast.' }, note: 'ください is a request. For a forecast, use でしょう.' },
          ],
        },
        maybe: {
          id: 'maybe',
          line: { jp: 'でも にしの 雲が へんです。「雨が ふる…」 まだ わかりません。', en: 'But the clouds in the west look odd. “It will rain…” I’m not sure yet.' }, kana: 'でも にしの くもが へんです。あめが ふる… まだ わかりません。',
          wordIds: ['furu', 'ame', 'mada'],
          hint: 'Not sure? 〜かもしれません (might).',
          next: 'think',
          options: [
            { jp: '…かもしれません。', en: '…it might.', correct: true, reply: { jp: '「雨が ふるかもしれません」。うん、しょうじきな よほうです。', en: '“It might rain.” Mm, an honest forecast.' }, effects: { trust: 1 } },
            { jp: '…つもりです。', en: '…it intends to.', correct: false, reply: { jp: '雲に つもりは ありません！ …たぶん。', en: 'Clouds don’t have plans! …Probably.' }, note: 'つもり is for your own plans. For “it might rain”: ふるかもしれません.' },
            { jp: '…ません。', en: '…it won’t.', correct: false, reply: { jp: 'それだと、はんたいの いみに なります。', en: 'That says the opposite.' }, note: 'ふりません means “won’t fall”. To say “might”, add かもしれません.' },
          ],
        },
        think: {
          id: 'think',
          line: { jp: 'あなたは どう 思いますか。あしたは さむいですか。', en: 'What do you think? Will it be cold tomorrow?' }, kana: 'あなたは どう おもいますか。あしたは さむいですか。',
          wordIds: ['omou'],
          hint: 'Plain form + と 思います: さむいと 思います.',
          next: 'why',
          options: [
            { jp: 'さむいと 思います。', kana: 'さむいと おもいます。', en: 'I think it will be cold.', correct: true, wordIds: ['omou'], reply: { jp: 'わたしも そう 思います！', en: 'I think so too!' }, effects: { trust: 1 } },
            { jp: 'さむいです 思います。', kana: 'さむいです おもいます。', en: '(It is cold I think.)', correct: false, wordIds: ['omou'], reply: { jp: 'と が きえて しまいました！', en: 'Your と got blown away!' }, note: 'You need と before 思います: さむいと 思います.' },
            { jp: 'さむいを 思います。', kana: 'さむいを おもいます。', en: '(I think cold-object.)', correct: false, wordIds: ['omou'], reply: { jp: 'を では ありません。と です。', en: 'Not を — と.' }, note: 'What you think is quoted with と: さむいと 思います.' },
          ],
        },
        why: {
          id: 'why',
          line: { jp: 'あれ、どうして かさを もって いるんですか。', en: 'Oh, why are you carrying an umbrella?' },
          wordIds: ['kasa', 'riyuu'],
          hint: 'Give the reason first, then から: …かもしれないからです.',
          next: 'if',
          options: [
            { jp: '雨が ふるかもしれないからです。', kana: 'あめが ふるかもしれないからです。', en: 'Because it might rain.', correct: true, wordIds: ['furu'], reply: { jp: 'なるほど！ わたしの よほうを 信じて いるんですね。', en: 'I see! You trust my forecast.' }, effects: { trust: 1 } },
            { jp: '雨から ふります。', kana: 'あめから ふります。', en: '(It falls from rain.)', correct: false, reply: { jp: '雨から なにが ふるんですか？', en: 'What falls out of the rain?' }, note: 'から for a reason goes after the whole reason: 雨が ふるかもしれないから.' },
            { jp: 'かさが すきですから かもしれません。', en: '(Because I like umbrellas might.)', correct: false, reply: { jp: 'ん？ ちょっと こんがらがって いますね。', en: 'Hm? That’s got a bit tangled.' }, note: 'Put かもしれない inside the reason, then から: ふるかもしれないから.' },
          ],
        },
        if: {
          id: 'if',
          line: { jp: 'もし あした 晴れたら、なにを しますか。', en: 'If it clears up tomorrow, what will you do?' }, kana: 'もし あした はれたら、なにを しますか。',
          wordIds: ['hareru'],
          hint: 'Start with 晴れたら, then what you will do.',
          next: 'final',
          options: [
            { jp: '晴れたら、にじを 見に 行きます。', kana: 'はれたら、にじを みに いきます。', en: 'If it clears up, I’ll go and see the rainbow.', correct: true, wordIds: ['niji'], reply: { jp: 'すてき！ 雨の あとの にじは、雲の都の じまんです。', en: 'Lovely! A rainbow after rain is the Cloud Capital’s pride.' }, effects: { trust: 1 } },
            { jp: '晴れるたら、にじを 見に 行きます。', kana: 'はれるたら、にじを みに いきます。', en: '(If it clears-up-ra…)', correct: false, reply: { jp: '「晴れるたら」？ 「晴れたら」ですよ。', en: '“Hareru-tara”? It’s “haretara”.' }, note: '〜たら is built on the た-form: 晴れた → 晴れたら.' },
            { jp: '晴れたら、きのう にじを 見ました。', kana: 'はれたら、きのう にじを みました。', en: '(If it clears up, I saw a rainbow yesterday.)', correct: false, reply: { jp: 'あしたの はなしで、きのう？ じかんが こんがらがって います！', en: 'Tomorrow… and yesterday? Time is all tangled!' }, note: 'A 〜たら “if” points to the future here, so the result is future too: 行きます.' },
          ],
        },
        final: {
          id: 'final',
          line: { jp: 'さいごに、あしたの よほうを ひとつ。雪が たぶん ふります。よほうらしく いって ください！', en: 'Last one: tomorrow, snow will probably fall. Say it like a real forecast!' }, kana: 'さいごに、あしたの よほうを ひとつ。ゆきが たぶん ふります。よほうらしく いって ください！',
          wordIds: ['yuki', 'tabun'],
          hint: 'あしたは ゆきでしょう。',
          next: 'bye',
          input: {
            accepted: ['あしたはゆきでしょう', '明日は雪でしょう', 'あしたは雪でしょう', '明日はゆきでしょう', 'あしたはゆきがふるでしょう', '明日は雪が降るでしょう', 'あしたは雪がふるでしょう', 'あしたはたぶんゆきでしょう', 'あしたはたぶん雪でしょう'],
            model: '明日は雪でしょう',
            modelKana: 'あしたは ゆきでしょう',
            wrongReply: { jp: 'う〜ん、まだ よほうらしく ないですね。', en: 'Hmm, that doesn’t sound like a forecast yet.' },
            wrongNote: 'Topic, weather, then でしょう: あしたは ゆきでしょう.',
            reply: { jp: 'かんぺき！ これで よほうが 書けます！', en: 'Perfect! Now I can write my forecast!' },
          },
        },
        bye: { id: 'bye', line: { jp: 'ありがとう ございました！ あしたも 天気を 見に きて くださいね。', en: 'Thank you so much! Come and check the weather again tomorrow.' }, kana: 'ありがとう ございました！ あしたも てんきを みに きて くださいね。', end: true },
      },
    },
  ],
}
