import type { Locus } from '../types'

/**
 * Room 10: the Cloud Capital. Off the rainbow bridge at the west gate (the
 * rainbow pillar, then Amane), up to the weather-readers' terrace (the
 * forecast kite, the cloud pen), across to the star observatory (the great
 * telescope, the scholar, the star-chart table), over to the thunder-drum
 * hall (the lightning rod, then the great drum inside), down to the market
 * plaza (wind chimes, the candy seller, the sign-painter) and finally down
 * the stair into the sky garden (the old plum, the shrine of learning).
 */
export const ROOM: Locus[] = [
  {
    id: 'p10-pillar',
    room: 10,
    map: 'clouds',
    anchor: 'c-rainbow',
    name: { jp: 'にじの はしら', en: 'Rainbow Pillar' },
    emoji: '🌈',
    memories: [
      { item: 'w:niji', story: 'A white horse trots off the rainbow bridge and kneels at the pillar: KNEE, GEE-up! Out of its bent knee springs a brand-new rainbow, arching away over the sky.', image: 'a white horse kneels — KNEE, GEE-up! — and out of its bent knee springs a brand-new rainbow, arching away across the sky' },
      { item: 'w:hare', story: 'The clouds round the pillar tear open and a single sunbeam strikes your face. “HA! A RAY!” shouts a child. Clear weather, blue to the edges, not a cloud left.', image: 'the clouds tear open and a single sunbeam strikes your face while a child shouts “HA! A RAY!” — clear weather, blue to the edges' },
      { item: 'w:hareru', story: 'A grey sky hangs on the pillar like a wet blanket. A kangaroo yanks it away — HA, RAY, ROO! — and the whole sky clears up in one bounce.', image: 'a kangaroo yanks a grey sky down like a wet blanket — HA, RAY, ROO! — and everything clears up in a single bounce' },
      { item: 'w:ten', story: 'Ten angels sit in a row on top of the pillar, counting out loud — “…eight, nine, TEN!” — and on TEN the gate of heaven swings open above them in gold.', image: 'ten angels sit in a row counting aloud, and on “TEN!” the gate of heaven swings open above them in gold' },
      { item: 'w:arashi', story: 'A storm whirls round the pillar and everyone it touches breaks out in red spots. “AH, RASH, EE!” they yell, scratching, while the gale howls overhead.', image: 'a storm whirls past and everyone it touches breaks out in red spots, yelling “AH, RASH, EE!” and scratching while the gale howls' },
    ],
  },
  {
    id: 'p10-gate',
    room: 10,
    map: 'clouds',
    anchor: 'c-amane',
    name: { jp: 'にしの もん', en: 'West Gate' },
    emoji: '⛩️',
    memories: [
      { item: 'w:kimochi', story: 'Amane hands you a KEY made of MOCHI. Bite it and you taste exactly how you feel: sweet when happy, salty when sad. It is a feeling you can eat.', image: 'someone hands you a KEY made of MOCHI, and when you bite it you taste exactly how you feel — sweet when happy, salty when sad' },
      { item: 'w:ureshii', story: 'Amane opens a present and gasps “OOH, RESH-EE!” — inside is fresh sushi shaped like a heart. She spins so happily that her feather shawl lifts her off the ground. Glad, glad, glad.', image: 'a girl opens a present, gasps “OOH, RESH-EE!” at fresh heart-shaped sushi, and spins so happily that she floats off the ground — glad, glad, glad' },
      { item: 'w:sabishii', story: 'One small bee sits alone on the gatepost. “SAH… BEE… SHE is all by herself,” sighs Amane. The bee hums a tiny lonely tune that nobody answers.', image: 'one small bee sits all alone on a post — “SAH… BEE… SHE is all by herself” — humming a tiny lonely tune that nobody answers' },
      { item: 'w:kanashii', story: 'A traveller drops a CAN of NASHI pears off the rainbow bridge. It tumbles into the sky, gone forever. He sits down at the gate and cries big sad tears.', image: 'a traveller drops a CAN of NASHI pears into the open sky, watches it vanish forever, and sits down crying big sad tears' },
      { item: 'w:tanoshii', story: 'Amane lies on a cloud getting a golden TAN. “TAN, OH, SHE is having SO much fun!” cry the gate guards as she giggles and waves her toes in the sunshine.', image: 'a girl lies on a cloud getting a golden TAN — “TAN, OH, SHE is having so much fun!” — giggling and waving her toes in the sun' },
    ],
  },
  {
    id: 'p10-kite',
    room: 10,
    map: 'clouds',
    anchor: 'c-kite',
    name: { jp: 'よほうの たこ', en: 'Forecast Kite' },
    emoji: '🪁',
    memories: [
      { item: 'w:tenki', story: 'Ten silver KEYS dangle from the kite’s tail. Turn one and it rains, another and it snows, another and the sun comes out. TEN KEYS for all the weather.', image: 'a ring of TEN silver KEYS dangles in the air, and each one you turn changes the weather — rain, snow, sunshine — all the weather in one hand' },
      { item: 'w:tenki-yohou', story: 'A pirate parrot perches on the kite, jangling ten keys and squawking “TEN KEY, YO-HO!” Then it reads out tomorrow’s weather forecast in a booming pirate voice.', image: 'a pirate parrot jangles ten keys and squawks “TEN KEY, YO-HO!” before reading out tomorrow’s weather forecast in a booming pirate voice' },
      { item: 'w:kumori', story: 'Pigeons crowd the kite string, cooing “COO… MORE-EE!” Each coo puffs out another grey cloud until the sky is thick and overcast. Cloudy weather, courtesy of pigeons.', image: 'pigeons crowd a string, cooing “COO… MORE-EE!” and every coo puffs out another grey cloud until the sky is thick and overcast' },
      { item: 'w:kiri', story: 'Shigure slices the morning fog with a cheese knife: it is thick and white as KIRI cream cheese. She spreads a slice of fog on her toast and can’t see her plate.', image: 'a girl slices morning fog with a cheese knife — thick and white as KIRI cream cheese — and spreads it on toast until she can’t see her plate' },
      { item: 'w:furu', story: 'A FOOLish kangaroo — the FOO-ROO — stands under the kite with its mouth open as rain and snow fall straight down into it. Whatever falls from the sky, it swallows.', image: 'a foolish kangaroo, the FOO-ROO, stands with its mouth open while rain and snow fall straight down into it' },
      { item: 'g:deshou', story: 'Shigure squints at the sky and announces “DAY, SHOW… sun!” with a shrug that means “probably.” Bolt this onto the end of a forecast and it becomes a confident guess.', image: 'a weather girl squints upward, announces “DAY, SHOW… sun!” and shrugs: tacked onto a sentence, this makes it a confident guess, “probably”' },
      { item: 'g:kamoshirenai', story: 'The kite tugs east, then west. “Maybe she CAME… OH, SHE RAN… EYE don’t know!” mutters Shigure. Put it after a plain verb or noun: “might”.', image: 'a kite tugs east, then west, while someone mutters “maybe she CAME… OH, SHE RAN… EYE don’t know!” — after a plain verb or noun, it means “might”' },
    ],
  },
  {
    id: 'p10-pen',
    room: 10,
    map: 'clouds',
    anchor: 'c-shepherd',
    name: { jp: '雲の かこい', en: 'Cloud Pen' },
    emoji: '🐑',
    memories: [
      { item: 'w:fuku', story: 'Sorata puffs out his cheeks and blows — FOO! — and a cuckoo shoots out of a cloud-sheep going “KOO!” The wind blows the whole flock round the pen.', image: 'a boy puffs his cheeks and blows — FOO! — and a cuckoo shoots out of a fluffy sheep going “KOO!” as the wind blows the flock away' },
      { item: 'g:to-whenever', story: 'Every time a cloud-sheep steps on Sorata’s TOE, it rains. TOE, then rain. TOE, then rain. Whenever the first thing happens, the second always follows.', image: 'every time a sheep steps on a boy’s TOE it rains — TOE, then rain, TOE, then rain — whenever the first thing happens, the second always follows' },
      { item: 'w:dandan', story: 'A shepherd called DAN climbs a staircase of clouds one step at a time: “DAN… DAN… DAN…” Little by little, gradually, he gets higher than the pen.', image: 'a shepherd called DAN climbs a staircase of clouds one step at a time — “DAN… DAN… DAN…” — little by little, gradually higher' },
      { item: 'w:sugu', story: 'A cloud-sheep sits on SUE’s lunch. “SUE, GO!” yells Sorata, and SUE goes right away, immediately, before the sheep can eat the rice balls.', image: 'a sheep sits on a girl’s lunch and someone yells “SUE, GO!” so she goes right away, immediately, before it eats her rice balls' },
    ],
  },
  {
    id: 'p10-telescope',
    room: 10,
    map: 'clouds-observatory',
    anchor: 'co-telescope',
    name: { jp: 'おおぼうえんきょう', en: 'Great Telescope' },
    emoji: '🔭',
    memories: [
      { item: 'w:mirai', story: 'You look through the telescope and see ME eating RYE bread, grey-haired, a hundred years from now. MEE-RYE: it only ever shows the future.', image: 'you peer through a lens and see ME eating RYE bread, grey-haired, a hundred years from now — MEE-RYE — it only shows the future' },
      { item: 'w:fushigi', story: 'A strange egg floats out of the eyepiece, goes FOOSH, and hatches a little SHE-GEE ghost that glows every colour at once. Nobody can explain it. How mysterious.', image: 'a strange egg floats up, goes FOOSH, and hatches a little SHE-GEE ghost glowing every colour at once — nobody can explain it, how mysterious' },
      { item: 'w:shiru', story: 'SHE spots a ROO on the moon through the lens: SHE ROO! Now she knows. Once you’ve seen it, you can never un-know that there’s a kangaroo up there.', image: 'a girl peers up — SHE spots a ROO on the moon — SHE ROO! — and now she knows, and can never un-know, that there is a kangaroo up there' },
      { item: 'w:wakaru', story: 'The apprentice stares at a star map for an hour, then slaps the telescope: “WACK-A-ROO! I get it!” The whole sky suddenly makes sense. Understood.', image: 'an apprentice stares at a star map for an hour, then slaps the brass and shouts “WACK-A-ROO! I get it!” as the whole sky suddenly makes sense' },
      { item: 'w:imi', story: '“What is the meaning of ME?” asks a star, pointing at itself. “EE… ME?” The telescope zooms in until you see the answer written in its light.', image: 'a little star points at itself and asks “EE… ME? what is the meaning of me?” and the answer appears written in its light' },
      { item: 'g:potential', story: 'A RARE ROO peers through the telescope: “I CAN see Mars! I CAN read the stars!” Tack its RARE-ROO ending onto a verb and you CAN do it.', image: 'a RARE ROO hops up and boasts “I CAN see Mars, I CAN read the stars!” — tack its RARE-ROO ending onto a verb and you CAN do it' },
    ],
  },
  {
    id: 'p10-scholar',
    room: 10,
    map: 'clouds-observatory',
    anchor: 'co-hakase',
    name: { jp: 'はかせの つくえ', en: 'Scholar’s Desk' },
    emoji: '📜',
    memories: [
      { item: 'w:omou', story: 'The scholar strokes his long beard: “OH… MOE? I think… yes, I think it is Moe the comet.” A little thought-bubble pops out of his ear.', image: 'an old scholar strokes his long beard and murmurs “OH… MOE? I think… yes, I think it is Moe the comet,” a thought-bubble popping from his ear' },
      { item: 'w:kangaeru', story: 'A tin-CAN GUY sits on the scholar’s desk with his chin on his hand, considering a puzzle so hard that steam puffs out: CAN-GUY-AIR-ROO, thinking it over and over.', image: 'a tin-CAN GUY sits with his chin on his hand considering a puzzle so hard that steam puffs out — CAN-GUY-AIR-ROO — thinking it over and over' },
      { item: 'w:iken', story: '“EE, KEN, what’s your opinion?” asks the scholar. Ken the owl clears his throat and gives a long view on the weather, with charts.', image: 'someone asks “EE, KEN, what’s your opinion?” and Ken the owl clears his throat and gives a long view on the weather, with charts' },
      { item: 'w:shitsumon', story: 'SHE’S TSU-MON the moth, and she has a question. She hops on the desk, raises one tiny leg and asks: “Why do stars twinkle?”', image: 'a moth named TSU-MON — SHE’S got a question — raises one tiny leg and asks politely: “why do stars twinkle?”' },
      { item: 'w:kotae', story: 'The answer to the moth’s question is hidden under the scholar’s COAT. “EYE it!” he says, lifting the COAT, and there it is, written in chalk: COAT-EYE.', image: 'an old man lifts his COAT and says “EYE it!” — COAT-EYE — and there underneath is the answer, written in chalk' },
      { item: 'w:riyuu', story: '“The REason the comet came back,” says the scholar, poking your chest, “is YOU.” REE-YOU. Every reason in his notebook ends with your name.', image: 'an old scholar pokes your chest — “the REason it all happened is YOU” — REE-YOU — and every reason in his notebook ends with your name' },
      { item: 'g:to-omou', story: 'The scholar stubs his TOE and says “OH, MOW…” — “I think it will rain.” Quote your plain-form thought, add TOE, then OH-MOW: “I think that…”', image: 'an old man stubs his TOE and says “OH, MOW… I think it will rain”: a plain-form thought, then TOE, then OH-MOW, means “I think that…”' },
      { item: 'g:kara-because', story: 'The scholar is late. “My CAR, RAH, broke!” — the reason first, then CAR-RAH, then what happened: “because the car broke, I am late.”', image: 'a late scholar puffs “my CAR, RAH, broke!” — say the reason first, then CAR-RAH, then what happened: “because the car broke, I’m late”' },
    ],
  },
  {
    id: 'p10-chart',
    room: 10,
    map: 'clouds-observatory',
    anchor: 'co-chart',
    name: { jp: 'せいずの つくえ', en: 'Star-Chart Table' },
    emoji: '🗺️',
    memories: [
      { item: 'w:kuraberu', story: 'A COOL BEAR and a ROO stand on the star chart while the apprentice measures them side by side. COO-RA-BEAR-ROO: she compares them, ear to ear.', image: 'a COOL BEAR and a ROO stand side by side while someone measures them ear to ear — COO-RA-BEAR-ROO — comparing them' },
      { item: 'w:onaji', story: '“OH, NAH, GEE!” Two identical stars sit on the chart, the same size, the same shine, the same wink. Even the scholar can’t tell which is which.', image: 'two stars sit side by side — “OH, NAH, GEE!” — the same size, the same shine, the same wink, and nobody can tell which is which' },
      { item: 'w:chigau', story: 'The apprentice puts cheese where the moon should be. “CHEE-GOW! That’s wrong!” snaps the scholar. It looks different, so it is different.', image: 'someone puts cheese where the moon should be and an old man snaps “CHEE-GOW! that’s wrong!” — it looks different, so it is different' },
      { item: 'w:hou', story: 'A garden HOE lies across the chart, pointing at one of two stars. “That one, the HOE’s side, is brighter.” In comparisons, this word marks the winning side.', image: 'a garden HOE lies across two stars, pointing at one: “that one, the HOE’s side, is brighter” — in comparisons, this marks the winning side' },
      { item: 'w:ichiban', story: 'An ITCHY BAND of stars plays on the chart, scratching between notes, and wins first prize: a gold medal. Number one. The very best and the most.', image: 'an ITCHY BAND of stars scratches between notes and still wins first prize, a gold medal: number one, the very best, the most' },
      { item: 'w:motto', story: 'The scholar’s family MOTTO is carved round the table: “MORE!” Every time you read it, he adds another star. More, more, even more.', image: 'a family MOTTO is carved in gold letters: “MORE!” — and every time you read it, someone adds another star: more, more, even more' },
      { item: 'w:zutto', story: 'A giant ZOO TOE has been sticking out from under the chart all along, the whole time, for ages. ZOO-TOE: and it is much, much bigger than yours.', image: 'a giant ZOO TOE has been sticking out from under the table all along, the whole time — ZOO-TOE — and it is much, much bigger than yours' },
      { item: 'g:yori-hou', story: 'Two comets race. “Than the one of YORE, the HOE side is faster!” The loser goes before YORE; the winner takes the HOE side.', image: 'two comets race and a judge shouts “than the one of YORE, the HOE side is faster!” — the loser sits before YORE, the winner takes the HOE side' },
      { item: 'g:naka-de-ichiban', story: 'The scholar KNOCKS on a box of planets: “KNOCK-A-DAY! Among all these, the ITCHY BAND one is the biggest!” Among a group, one is the most.', image: 'someone KNOCKS on a box of planets — “KNOCK-A-DAY! among all of these, the ITCHY BAND one is the biggest!” — among a group, one is the most' },
    ],
  },
  {
    id: 'p10-rod',
    room: 10,
    map: 'clouds',
    anchor: 'c-rod',
    name: { jp: 'ひらいしん', en: 'Lightning Rod' },
    emoji: '⚡',
    memories: [
      { item: 'w:kaminari', story: 'A canary in a frilly camisole — the CAMI-NARY — clings to the metal pillar and shrieks every time the thunder booms. It is the loudest bird in the sky.', image: 'a canary in a frilly camisole, the CAMI-NARY, clings to a metal pole and shrieks every time the thunder booms overhead' },
      { item: 'w:inazuma', story: 'A bolt ZOOMS down and hits the metal pillar with a white crack: “EE, NAH, ZOOM-AH!” For a second you can see your own bones. Lightning!', image: 'a white bolt ZOOMS down with a crack — “EE, NAH, ZOOM-AH!” — and for one second you can see your own bones: lightning' },
      { item: 'w:oto', story: 'You stub your toe on the pillar: “OH, TOE!” The sound echoes off every cloud in the city and comes back three times louder. What a sound.', image: 'you stub your toe and yell “OH, TOE!” and the sound echoes off every cloud and comes back three times louder' },
      { item: 'w:taiko', story: 'A drum wearing a necktie rolls up the path: TIE-KOH. Raijin’s drumsticks bounce on it — DON! DON! — and the tie flaps with every beat.', image: 'a drum wearing a necktie rolls up — TIE-KOH — and two drumsticks bounce on it, DON! DON!, the tie flapping with every beat' },
    ],
  },
  {
    id: 'p10-drum',
    room: 10,
    map: 'clouds-hall',
    anchor: 'ch-drum',
    name: { jp: 'おおだいこ', en: 'Great Drum' },
    emoji: '🥁',
    memories: [
      { item: 'g:plain-form', story: 'A dusty DICTIONARY sits on the drum, open to the plain form of every verb. “GEE, SHOW me!” says the drummer, and it shows the casual form everything else is built on.', image: 'a dusty DICTIONARY opens to the plain form of every verb — “GEE, SHOW me!” — the casual form all the other grammar is built on' },
      { item: 'g:nai-form', story: 'A horse refuses to beat the drum: “NAY! NIGH!” it neighs, shaking its mane. Turn the verb’s last sound to -a and add NIGH: “don’t.”', image: 'a horse refuses to beat a drum — “NAY! NIGH!” — shaking its mane: change the verb’s last sound to -a and add NIGH to say “don’t”' },
      { item: 'w:naru', story: 'A fat drumstick slowly becomes NARROW, then NARROWER, until it turns into a flute. NAH-ROO: one thing becoming something else before your eyes.', image: 'a fat drumstick slowly becomes NARROW, then narrower, until it turns into a flute — NAH-ROO — one thing becoming something else before your eyes' },
      { item: 'w:hajimeru', story: '“HA! GEE! MAY-ROO… begin!” shouts the drummer, and a kangaroo called May starts hopping on the great drum. The first beat — the start of the song.', image: 'someone shouts “HA! GEE! MAY-ROO… begin!” and a kangaroo called May starts hopping on a drum: the first beat, the start of the song' },
      { item: 'w:tsuzukeru', story: 'The ZOO KEEPER ROO keeps drumming… and keeps drumming… and keeps drumming. TSU-ZOO-KEH-ROO. He just won’t stop: he continues all night long.', image: 'the ZOO KEEPER ROO keeps drumming, and keeps drumming — TSU-ZOO-KEH-ROO — he continues all night long and won’t stop' },
      { item: 'w:yuuki', story: '“YOU, KEY!” says Amane, pressing a golden key into your hand. It unlocks the courage inside you, and your knees stop shaking in front of the thunder god.', image: 'someone presses a golden key into your hand — “YOU, KEY!” — and it unlocks the courage inside you so your knees stop shaking' },
    ],
  },
  {
    id: 'p10-chimes',
    room: 10,
    map: 'clouds',
    anchor: 'c-chimes',
    name: { jp: 'ふうりんの あずまや', en: 'Wind-Chime Pavilion' },
    emoji: '🎐',
    memories: [
      { item: 'w:kitto', story: 'Each wind chime hangs from a little first-aid KIT for your TOE. KIT-TOE: rub it on a stubbed toe and it will surely, certainly stop hurting.', image: 'a first-aid KIT for your TOE hangs off a string — KIT-TOE — rub it on a stubbed toe and it will surely, certainly stop hurting' },
      { item: 'w:tabun', story: 'The chimes clink “TA… BOON?” Is this breeze a boon? Probably. Maybe. Perhaps. The chimes never say yes for sure.', image: 'chimes clink “TA… BOON?” — is this breeze a boon? probably, maybe, perhaps — they never say yes for sure' },
      { item: 'w:hontou', story: 'An HONEST TOE pokes out of a sandal under the chimes and swears: “HONEST, TOE: it’s the truth!” It cannot tell a lie. Really, truly.', image: 'an HONEST TOE pokes out of a sandal and swears “HONEST, TOE: it’s the truth!” — it can’t tell a lie, really, truly' },
      { item: 'w:yatto', story: 'A tiny YACHT finally sails out of the clouds and bumps into the chimes. “At last!” cry the crowd. “YACHT-OH! It took forever.”', image: 'a tiny YACHT finally sails out of the clouds and bumps into you — “YACHT-OH! at last!” — it took forever' },
    ],
  },
  {
    id: 'p10-candy',
    room: 10,
    map: 'clouds',
    anchor: 'c-candy',
    name: { jp: '雲がしの みせ', en: 'Candy Stall' },
    emoji: '🍭',
    memories: [
      { item: 'w:erabu', story: 'Momo holds up two cloud candies shaped like ghosts. “Which ERA, BOO? Old ghost or new ghost?” You have to choose one. You pick the new one.', image: 'someone holds up two ghost-shaped sweets — “which ERA, BOO? old ghost or new ghost?” — and you have to choose, pick, select one' },
      { item: 'w:kimeru', story: 'Momo decides the price by tossing a KEY at a dartboard MARE: KEY-MARE-ROO. Wherever the key lands, the matter is settled. Decided!', image: 'a seller tosses a KEY at a dartboard shaped like a MARE — KEY-MARE-ROO — and wherever it lands, the matter is settled: decided!' },
      { item: 'w:dekiru', story: 'A kangaroo stands on a DECK of cloud candy and juggles seven sweets: “DECK-EE-ROO! I CAN do it!” Momo claps. Able to do anything.', image: 'a kangaroo stands on a DECK of sweets juggling seven at once — “DECK-EE-ROO! I CAN do it!” — able to do anything' },
      { item: 'g:koto-ga-dekiru', story: 'A ROO plays a KOTO harp on the DECK of the stall: “KOTO GA DECK-ROO!” Dictionary form, then this phrase: “I can play.” The crowd throws coins.', image: 'a ROO plucks a KOTO harp on a wooden DECK — “KOTO GA DECK-ROO!” — after the dictionary form, the phrase means “I can”' },
    ],
  },
  {
    id: 'p10-painter',
    room: 10,
    map: 'clouds',
    anchor: 'c-painter',
    name: { jp: 'かんばんやの はしご', en: 'Sign-Painter’s Ladder' },
    emoji: '🪜',
    memories: [
      { item: 'g:tara', story: 'Gen paints the last stroke and a trumpet blasts “TA-RAH!” Once that happens, the shop opens. Hook TA-RAH onto a past verb: once/if it happens, then…', image: 'a painter finishes the last stroke and a trumpet blasts “TA-RAH!” — hook it onto a past verb: once, or if, that happens, then…' },
      { item: 'g:ba', story: 'A sheep on the ladder bleats “BAA… IF you give me grass, I’ll get down.” Change the verb’s last sound to -e and add BAA: “if”.', image: 'a sheep on a ladder bleats “BAA… IF you give me grass, I’ll come down” — change the verb’s last sound to -e and add BAA for “if”' },
      { item: 'g:tsumori', story: 'A SUMO wrestler climbs Gen’s ladder with a paintbrush: “SUMO-REE plans to paint the sky!” Dictionary form + SUMO-REE: “I intend to.”', image: 'a SUMO wrestler climbs a ladder with a paintbrush, announcing “SUMO-REE plans to paint the sky!” — dictionary form + SUMO-REE: “I intend to”' },
      { item: 'g:nakereba-naranai', story: 'A NACHO REBEL hangs off the ladder yelling “NAH-KEH-REBA, NAH-RAH-NIGH!” You must come down! You have to! Turn the “don’t” form into this to mean “must”.', image: 'a NACHO REBEL dangles off a ladder yelling “NAH-KEH-REBA, NAH-RAH-NIGH!” — you must, you have to: the “don’t” form turned into “must”' },
    ],
  },
  {
    id: 'p10-plum',
    room: 10,
    map: 'clouds-garden',
    anchor: 'cg-plum',
    name: { jp: 'ふるい うめの 木', en: 'Old Plum Tree' },
    emoji: '🌸',
    memories: [
      { item: 'w:omoide', story: 'The old plum smells of OH-MOE-EE-DAY: Grandma Moe’s birthday, years ago. One sniff of the blossom and the whole memory comes back, cake and all.', image: 'one sniff of plum blossom — OH, MOE, EE, DAY! — and a whole memory of Grandma Moe’s birthday comes back, cake and all' },
      { item: 'w:yakusoku', story: 'A YAK, SO COOL in sunglasses, hooks his little finger round a plum branch: “YAK-SO-KOO. I promise I’ll come back next spring.” A promise.', image: 'a YAK, SO COOL in sunglasses, hooks his little finger round a branch — “YAK-SO-KOO, I promise I’ll come back next spring”' },
      { item: 'w:shinjiru', story: 'A SHIN-GUARDED ROO kneels before the plum and believes, truly believes, that it will fly. SHIN-GEE-ROO. And the next morning, it does.', image: 'a ROO in SHIN-GUARDS kneels and believes, truly believes, that it will fly — SHIN-GEE-ROO — and the next morning it does' },
    ],
  },
  {
    id: 'p10-tenjin',
    room: 10,
    map: 'clouds-garden',
    anchor: 'cg-shrine',
    name: { jp: 'てんじんさまの ほこら', en: 'Shrine of Tenjin' },
    emoji: '📚',
    memories: [
      { item: 'w:oboeru', story: 'A student bows to the god of learning — “OH, BOW, AIR, ROO!” — and every word she bows to sticks in her head for good. Remembered, memorised.', image: 'a student bows deeply — “OH, BOW, AIR, ROO!” — and every word she bows to sticks in her head for good: remembered, memorised' },
      { item: 'w:wasureru', story: '“I WAS SURE… ROO… what was I saying?” A kangaroo leans on the plum tree and forgets mid-sentence. It has forgotten its own name.', image: 'a kangaroo leans on a tree — “I WAS SURE… ROO… what was I saying?” — and forgets in mid-sentence, even its own name' },
    ],
  },
]
