import type { RegionSprites } from '../types'

/**
 * Pixel art for the Cloud Capital: Amane and the celestial maidens (tennin,
 * with a floating feather shawl, the hagoromo, looping round them), the old
 * sky-scholar (tall cap, long white beard, a rolled star chart), the raijū
 * thunder beast, and Raijin with his ring of drums.
 *
 * Slots follow the human convention: 1 cloth, 2 cloth shade, 3 trim, 4 cloth
 * light, 5 hair, 6 hair shade, 7 legs, 8 shoes.
 */
export const SPRITES: RegionSprites = {
  characters: {
    tennin: {
      slots: { 1: 'sakura', 2: 'lilac', 3: 'gold', 4: 'paper', 5: 'night', 6: 'navy', 7: 'navy', 8: 'woodDark' },
      legRows: [14, 14],
      sideSpan: [2, 12],
    down: [
      '................',
      '....55....55....',
      '....555yy555....',
      '....55555556....',
      '...5555555556...',
      '...55ffffff56...',
      '...5fkffffkf6...',
      '...5fkffffkf6...',
      '...5hffffffh6...',
      'jj.5pww33wwp6.jj',
      '.jjpww1111wwPjj.',
      '..jjw111111wjj..',
      '...jjw1111wjj...',
      '...4UUUUUUUU2...',
      '....ww..........',
      '................',
    ],
    up: [
      '................',
      '....55....55....',
      '....555yy555....',
      '....55555556....',
      '...5555555556...',
      '...5555555556...',
      '...5555555556...',
      '...5555555556...',
      '...5555555556...',
      'jj.p55555556P.jj',
      '.jjpw555556wPjj.',
      '..jjww5556wwjj..',
      '...jjwwwwwwjj...',
      '...4UUUUUUUU2...',
      '....ww..........',
      '................',
    ],
    side: [
      '................',
      '.....55.........',
      '....555yy.......',
      '....5555556.....',
      '...555555556....',
      '...5556ffffff...',
      '...556Ffffkff...',
      '...556Ffffkff...',
      '...556ffffhf....',
      '.jj.56pww3wP....',
      '..jj56pw11wPjj..',
      '...jjj5w11w.jjj.',
      '.....jjw11wjj...',
      '....4UUUUU2.....',
      '....ww...ww.....',
      '................',
    ],
    },
    scholar: {
      slots: { 1: 'navy', 2: 'night', 4: 'dusk', 5: 'night', 6: 'navy', 7: 'navy', 8: 'woodDark' },
      legRows: [14, 14],
      sideSpan: [2, 10],
    down: [
      '......nnnn......',
      '......nyyn......',
      '.....nnnnnn.....',
      '.....ffffff.....',
      '....fffffffF....',
      '...mwwffffwwm...',
      '...mfkffffkfm...',
      '...mfwwwwwwfm...',
      '....wwwwwwww....',
      '...41wwwwww12pp.',
      '...411wwww112fp.',
      '...41y1ww1112.p.',
      '...4111w11y12.p.',
      '...4111111112...',
      '....OO........y.',
      '................',
    ],
    up: [
      '......nnnn......',
      '......nnnn......',
      '.....nnnnnn.....',
      '.....mmmmmm.....',
      '....mmmmmmmm....',
      '...mmmmmmmmmm...',
      '...mmmmmmmmmm...',
      '...mmmmmmmmmm...',
      '....mmmmmmmm....',
      '.pp4111111112...',
      '.pf4111y11112...',
      '.p.4111111112...',
      '.p.41y1111112...',
      '...4111111y12...',
      '....OO..........',
      '................',
    ],
    side: [
      '.......nnnn.....',
      '.......nyyn.....',
      '......nnnnnn....',
      '.....fffff......',
      '....ffffffF.....',
      '...mmmfffwwf....',
      '...mmmFffkff....',
      '...mmmffwwwww...',
      '....mmmwwwwww...',
      '....4111wwwww...',
      '....41111ffpp...',
      '....41y111..p...',
      '...4111111..p...',
      '...41111y1..p...',
      '....OO...OO.....',
      '................',
    ],
    },
  },
  enemies: {
    raiju: {
      anim: 'bob',
      shade: 'bc',
      rows: [
        '................................',
        '................................',
        '........dd............dd........',
        '........dd............dd........',
        '.........Ud..........dU......y.l',
        '.........Ud..y.ll.y..dU.......l.',
        '.........Udl.bbbbbb.ldU.....y...',
        '.........UddbbbbbbbbddU......l..',
        '..........ddbbbbbbbbdd........l.',
        '.........bbbbbbbbbbbbbb......y.l',
        '.........lbyyybbbbyyybl.......l.',
        '.........bbykybbbbykybb.....y...',
        '........lbbykybbbbykybbl.....l..',
        '.........bbbbbbbbbbbbbb.......l.',
        '.......l.bbbbbbNNbbbbbb.l...y...',
        '.........bbbbkkkkkkbbbb......l..',
        '........ybbbbbwbbwbbbbby....l...',
        '........bbbbbbbbbbbbbbbb...y....',
        '......lbbbbbbbbccbbbbbbbbly.....',
        '.......bbbbbccccccccbbbbby......',
        '.......bbbbccccccccccbbbb.......',
        '.......bbbccccccccccccbbb.......',
        '.......bbbccccccccccccbbb.......',
        '.......bbbccccccccccccbbb.......',
        '........bbccccccccccccbb........',
        '........bbbccccccccccbbb........',
        '.........bbbccccccccbbb.........',
        '........bbbbbbbccbbbbbbb........',
        '........bbbbb..bb..bbbbb........',
        '.........wbw........wbw.........',
        '................................',
        '................................',
      ],
    },
    raijin: {
      anim: 'bob',
      shade: 'vV',
      rows: [
        '.........oyyo......oyyo.........',
        '.........pyyyoOOOOoyyyp.........',
        '...o.....PyVyo....oyVyP.....o...',
        '...L...OOoPyo......oyPoOO...L...',
        '..oLLoOOn.Pnnnn..nnnnP.nOOoLLo..',
        '..oyLyo..nnPnnnnnnnnPnn..oyLyo..',
        '..yyLyonnnnnnnnnnnnnnnnnnoyLyy..',
        '..oyLL.nnnnnvvvvvvvvnnnnn.LLyo..',
        '..OooL.nnnnnnvvvvvvnnnnnn.LooO..',
        '..O.vvvnnnnvwkvvvvkwvnnnnvvv.O..',
        '.oO..vvvnnvvvvvvvvvvvvnnvvv..Oo.',
        'oyoo...vvnnvVvvvvvvVvnnvv...ooyo',
        'yyyo...vvnnvwwwwwwwwvnnvv...oyyy',
        'yVVo....vvvnvvvvvvvvnvvv....oVVy',
        'oyoo....vvvvvvvvvvvvvvvv....ooyo',
        '.o......vvvvvvvvvvvvvvvv......o.',
        '.........vvvvVVVVVVvvvv.........',
        '..........vvvvvvvvvvvv..........',
        '..........vvvvvvvvvvvv..........',
        '...........vvVVVVVVvv...........',
        '...........vVVVVVVVVv...........',
        '............VVVVVVVV............',
        '..........ykyyykkyyyky..........',
        '..........yyykyyyykyyy..........',
        '..........ykyyyyyyyyky..........',
        '..........yyyykyykyyyy..........',
        '............vv....vv............',
        '...........vv......vv...........',
        '....mmmm...vv......vv...mmmm....',
        '..wwwwww..vv........vv..wwwwww..',
        '..wwwwwwVVVV........VVVVwwwwww..',
        '................................',
      ],
    },
  },
}
