/**
 * Walking characters, 16×16, authored as palette maps (see raster.LEGEND).
 * Each has `down`, `up` and `side` (facing right; left is mirrored). The
 * second walk frame is derived (legs swapped) unless given explicitly.
 * Digits are per-character colour slots. The ink outline is added
 * automatically around the silhouette.
 *
 * Human slot convention: 1 cloth, 2 cloth shade, 3 trim, 4 cloth light,
 * 5 hair, 6 hair shade, 7 legs, 8 shoes.
 */
import type { Slots } from '../raster'

export interface CharDef {
  down: string[]
  up: string[]
  side: string[]
  /** Explicit second frames (otherwise derived). */
  down1?: string[]
  up1?: string[]
  side1?: string[]
  slots?: Slots
  /** Leg rows mirrored for the 2nd down/up frame, and the column span. */
  legRows?: [number, number]
  span?: [number, number]
  /** Column span used to gather the legs for the side "passing" frame. */
  sideSpan?: [number, number]
  /** Floating sprite: frame 1 bobs up a pixel instead of walking. */
  float?: boolean
  /** Characters of flat colours to auto-shade (top-left light). */
  shade?: string
}

const HUMAN: Slots = { 5: 'night', 6: 'navy', 7: 'navy', 8: 'woodDark' }

export const CHARACTERS: Record<string, CharDef> = {
  mage: {
    legRows: [14, 14],
    span: [3, 12],
    sideSpan: [2, 12],
    down: [
      '................',
      '.........41.....',
      '........4112.ly.',
      '.......41112.yy.',
      '......411112..o.',
      '.....33333332.o.',
      '..441111111112o.',
      '...OFFFFFFFFO.o.',
      '...OfkffffkfO.o.',
      '...OfkffffkfO.o.',
      '....hffffffh..o.',
      '...4133333312fo.',
      '..f4111331112.o.',
      '...4333333332.o.',
      '....OO........o.',
      '................',
    ],
    up: [
      '................',
      '.....41.........',
      '.ly.4112........',
      '.yy.41112.......',
      '.o..411112......',
      '.o.33333333.....',
      '.o411111111112..',
      '.o.OOOOOOOOOO...',
      '.o.OOOOOOOOOO...',
      '.o.OOOOOOOOOO...',
      '.o..OOOOOOOO....',
      '.of4111111112...',
      '.o.4111111112f..',
      '.o.4333333332...',
      '.o..OO..........',
      '................',
    ],
    side: [
      '................',
      '....41..........',
      '....4112.....ly.',
      '.....41112...yy.',
      '.....411112...o.',
      '....333333332.o.',
      '.4411111111112o.',
      '...OOOOFFFFF..o.',
      '...OOOFffkff..o.',
      '...OOOFffkff..o.',
      '....OOfffhf...o.',
      '....411111133fo.',
      '....411111132.o.',
      '...4333333332.o.',
      '....OO...OO...o.',
      '................',
    ],
  },

  fude: {
    float: true,
    down: [
      '................',
      '.......LO.......',
      '.......LOv......',
      '.......LO.v.....',
      '......yyye......',
      '.....pwwppP.....',
      '....pwwpppPP....',
      '....pwkppwkP....',
      '....pkkppkkP....',
      '....hpppppHP....',
      '....PppppPPP....',
      '.....PnnnnP.....',
      '......nnNN......',
      '.......Nk.......',
      '........k.......',
      '................',
    ],
    up: [
      '................',
      '.......LO.......',
      '......vLO.......',
      '.....v.LO.......',
      '......yyye......',
      '.....pwwppP.....',
      '....pwppppPP....',
      '....pppppppP....',
      '....pppppppP....',
      '....pppppppP....',
      '....PppppPPP....',
      '.....PnnnnP.....',
      '......nnNN......',
      '.......Nk.......',
      '.......k........',
      '................',
    ],
    side: [
      '................',
      '.......LO.......',
      '.......LOv......',
      '.......LO.v.....',
      '......yyye......',
      '.....pwwppP.....',
      '....pwwpppPP....',
      '....pppppwkP....',
      '....pppppkkP....',
      '....pppppphP....',
      '....PpppppPP....',
      '...nPPPPPP......',
      '..nnnnn.........',
      '.nNk............',
      '.k..............',
      '................',
    ],
  },

  merchant: {
    slots: { ...HUMAN, 1: 'wood', 2: 'woodDark', 4: 'woodLight' },
    down: [
      '................',
      '.....555555.....',
      '....55555555....',
      '...5555555556...',
      '...ppppppppppv..',
      '...5ffffffff6...',
      '...5fkffffkf6...',
      '...ffkffffkfF...',
      '....hffFFffh....',
      '...41pppppp12...',
      '..f41pppppp12f..',
      '..F41PPPPPP12F..',
      '...41pppppp12...',
      '.....77..77.....',
      '.....88.........',
      '................',
    ],
    up: [
      '................',
      '.....555555.....',
      '....55555555....',
      '...5555555556...',
      '...pppppppppp...',
      '...5555vv5556...',
      '...5555vv5566...',
      '...F55555566F...',
      '....FFFFFFFF....',
      '...41p1111p12...',
      '..f411pppp112f..',
      '..F4111111112F..',
      '...4111111112...',
      '.....77..77.....',
      '.....88.........',
      '................',
    ],
    side: [
      '................',
      '.....55555......',
      '....5555555.....',
      '...555555555....',
      '..vppppppppp....',
      '..v5556ffffff...',
      '...556Ffffkff...',
      '...556Ffffkff...',
      '....56fffhff....',
      '....41111pp.....',
      '....4111fpp.....',
      '....41111pP.....',
      '....41111pp.....',
      '....77...77.....',
      '....88...88.....',
      '................',
    ],
  },

  guard: {
    slots: HUMAN,
    sideSpan: [2, 11],
    down: [
      '..............w.',
      '......dddN....m.',
      '....ddNyyNNN..m.',
      '..ddddNNNNNNNNo.',
      '...nnnnnnnnnn.o.',
      '...5ffffffff5.o.',
      '...5fkffffkf5.o.',
      '...ffkffffkfF.o.',
      '....hffffffh..o.',
      '...svvvvvvVVsfo.',
      '..fsvyyyyyyVs.o.',
      '...svvvvvvVVs.o.',
      '....nNnNnNnN..o.',
      '.....77..77...o.',
      '.....88.......o.',
      '................',
    ],
    up: [
      '.w..............',
      '.m....dddN......',
      '.m..ddNNNNNN....',
      '.oddddNNNNNNNN..',
      '.o.nnnnnnnnnn...',
      '.o.5555555555...',
      '.o.5555555555...',
      '.o.F55555555F...',
      '.o..FFFFFFFF....',
      '.ofsvvvvvvVVs...',
      '.o.svvvvvvVVsf..',
      '.o.sVVVVVVVVs...',
      '.o..nNnNnNnN....',
      '.o...77..77.....',
      '.o...88.........',
      '................',
    ],
    side: [
      '.............w..',
      '.....dddN....m..',
      '...ddNNNNN...m..',
      '.dddddNNNNNNNo..',
      '..nnnnnnnnnn.o..',
      '...5556fffff.o..',
      '...556Fffkff.o..',
      '...556Fffkff.o..',
      '....56ffhff..o..',
      '....svvvvVsffo..',
      '....svyyyyVs.o..',
      '....svvvvVVs.o..',
      '.....nNnNnN..o..',
      '....77...77..o..',
      '....88...88..o..',
      '................',
    ],
  },

  priest: {
    slots: HUMAN,
    legRows: [14, 14],
    down: [
      '................',
      '.......dn.......',
      '......dnnnn.....',
      '....5dnnnnn5....',
      '...5555555556...',
      '...55ffffff56...',
      '...5fkffffkf6...',
      '...ffkffffkfF...',
      '....hffffffh....',
      '...pwwwPPwwwP...',
      '..pwwwfoofwwPP..',
      '..pwwwwoowwwPP..',
      '...Cccccccccb...',
      '...Cccb..cccb...',
      '....ww..........',
      '................',
    ],
    up: [
      '................',
      '.......dn.......',
      '......dnnnn.....',
      '....5dnnnnn5....',
      '...5555555556...',
      '...5555555556...',
      '...5555555556...',
      '...F55555566F...',
      '....FFFFFFFF....',
      '...pwwwwwwwwP...',
      '..pwwwwwwwwwPP..',
      '..pwwwwwwwwwPP..',
      '...Cccccccccb...',
      '...Cccb..cccb...',
      '....ww..........',
      '................',
    ],
    side: [
      '................',
      '.......dn.......',
      '.....dnnnn......',
      '....dnnnnn5.....',
      '...555555555....',
      '...5556ffffff...',
      '...556Ffffkff...',
      '...556Ffffkff...',
      '....56fffhff....',
      '....pwwwwwP.....',
      '...pwwwwfoP.....',
      '...pwwwwwoP.....',
      '....Cccccb......',
      '....Ccb.ccb.....',
      '....ww...ww.....',
      '................',
    ],
  },

  king: {
    slots: { ...HUMAN, 5: 'mist', 6: 'stone' },
    legRows: [14, 14],
    down: [
      '................',
      '....y..yy..y....',
      '....yyvyyvyy....',
      '....lyyyyyye....',
      '...5555555556...',
      '...5ffffffff6...',
      '...5fkffffkf6...',
      '...5fkffffkf6...',
      '...ffmmmmmmfF...',
      '....mmmmmmmm....',
      '..wkwmmmmmmwkw..',
      '..VvvvvmmvvvvV..',
      '..VvvvvyyvvvvV..',
      '...wwkwwwwkww...',
      '....OO..........',
      '................',
    ],
    up: [
      '................',
      '....y..yy..y....',
      '....yyyyyyyy....',
      '....lyyyyyye....',
      '...5555555556...',
      '...5555555556...',
      '...5555555556...',
      '...5555555566...',
      '...F55555566F...',
      '..wkwwwwwwwkww..',
      '..VvvvvvvvvvvV..',
      '..VvvvvvvvvvvV..',
      '..VvvvvvvvvvvV..',
      '...wwkwwwwkww...',
      '....OO..........',
      '................',
    ],
    side: [
      '................',
      '.....y.y.y......',
      '.....yyvyy......',
      '.....lyyye......',
      '...555555555....',
      '...5556ffffff...',
      '...556Ffffkff...',
      '...556Ffffkff...',
      '...556fffmmmm...',
      '....5mmmmmmm....',
      '..wkwwVvmmmm....',
      '..VVvvvvvmm.....',
      '..VVvvvvvvy.....',
      '..VVwwkwwkw.....',
      '....OO...OO.....',
      '................',
    ],
  },

  elder: {
    slots: { ...HUMAN, 1: 'dusk', 2: 'navy', 4: 'stone' },
    legRows: [14, 14],
    sideSpan: [2, 10],
    down: [
      '................',
      '................',
      '.....ffffff.....',
      '....fffffffF....',
      '...mfffffffFm...',
      '...mwwffffwwm...',
      '...mfkffffkfm...',
      '...mfwwwwwwfm...',
      '....wwwwwwww....',
      '...41wwwwww12oo.',
      '...411wwww112fo.',
      '...4111ww1112.o.',
      '...4111111112.o.',
      '...4111111112.o.',
      '....OO........o.',
      '................',
    ],
    up: [
      '................',
      '................',
      '.....ffffff.....',
      '....fffffffF....',
      '...mfffffffFm...',
      '...mmfffffFmm...',
      '...mmmmmmmmmm...',
      '...mmmmmmmmmm...',
      '....mmmmmmmm....',
      '.oo4111111112...',
      '.of4111111112...',
      '.o.4111111112...',
      '.o.4111111112...',
      '.o.4111111112...',
      '.o..OO..........',
      '................',
    ],
    side: [
      '................',
      '................',
      '.....fffff......',
      '....ffffffF.....',
      '...mfffffffF....',
      '...mmmfffwwf....',
      '...mmmFffkff....',
      '...mmmffwwwww...',
      '....mmmwwwwww...',
      '....4111wwwww...',
      '....41111ffoo...',
      '....411111..o...',
      '...4111111..o...',
      '...4111111..o...',
      '....OO...OO.o...',
      '................',
    ],
  },

  innkeeper: {
    legRows: [14, 14],
    down: [
      '................',
      '......nnnn......',
      '....nnnnnnnnv...',
      '...nnnnnnnnnn...',
      '...ndnnnnnnnn...',
      '...nnffffffnn...',
      '...nfkffffkfn...',
      '...ffkffffkfF...',
      '....hffffffh....',
      '...hhpffffphH...',
      '..fhhhhpphhhHf..',
      '...yyyyvvyyye...',
      '...hhhhhhhhhH...',
      '....hhhhhhhH....',
      '.....ww.........',
      '................',
    ],
    up: [
      '................',
      '......nnnn......',
      '....nnnnnnnnv...',
      '...nnnnnnnnnn...',
      '...ndnnnnnnnn...',
      '...nnnnnnnnnn...',
      '...nnnnnnnnnN...',
      '...FnnnnnnnnF...',
      '....FFFFFFFF....',
      '...hhhhhhhhhH...',
      '..fhhhhhhhhhHf..',
      '...yyyyyyyyye...',
      '...hhhyyyyhhH...',
      '....hhhhhhhH....',
      '.....ww.........',
      '................',
    ],
    side: [
      '................',
      '.....nnn........',
      '....nnnnnnv.....',
      '...nnnnnnnnn....',
      '...ndnnnnnnnn...',
      '...nnnnffffff...',
      '...nnnFfffkff...',
      '...nnnFfffkff...',
      '....nnfffhff....',
      '.....hhhhpH.....',
      '.....hhhfhH.....',
      '....yyyyyye.....',
      '.....hhhhhH.....',
      '.....hhhhhH.....',
      '.....ww..ww.....',
      '................',
    ],
  },

  jailer: {
    down: [
      '................',
      '.....dddNNN.....',
      '....ddNNNNNN....',
      '...dNNNNNNNNN...',
      '...nnnnnnnnnnNn.',
      '...fkkffffkkF...',
      '...ffkffffkfF...',
      '...ffffkkfffF...',
      '....FsFsFsFF....',
      '..fooommmmoooF..',
      '..fooommmmoooF..',
      '..FOOOyyOOOOOF..',
      '...SSSySSSSSS...',
      '....SSS..SSS....',
      '....OOO.........',
      '................',
    ],
    up: [
      '................',
      '.....dddNNN.....',
      '....ddNNNNNN....',
      '...dNNNNNNNNN...',
      '...nnnnnnnnnnNn.',
      '...NNNNNNNNNN...',
      '...NNNNNNNNNN...',
      '...FNNNNNNNNF...',
      '....FFFFFFFF....',
      '..fooooooooooF..',
      '..fooooooooooF..',
      '..FOOOOOOOOOOF..',
      '...SSSSSSSSSS...',
      '....SSS..SSS....',
      '....OOO.........',
      '................',
    ],
    side: [
      '................',
      '.....dddNN......',
      '....ddNNNNN.....',
      '...dNNNNNNNN....',
      '.nNnnnnnnnnn....',
      '...NNNffkkff....',
      '...NNFfffkff....',
      '...NNfffffFF....',
      '....NFsFsFF.....',
      '....oooommmm....',
      '....ooffmmmm....',
      '....OOOOyOOO....',
      '....SSSSySSS....',
      '....SSS..SSS....',
      '....OOO..OOO....',
      '................',
    ],
  },

  'villager-a': {
    slots: HUMAN,
    down: [
      '................',
      '......aaLL......',
      '....aaaLLLLo....',
      '..aaaLLLLLLLLo..',
      '...oooooooooo...',
      '...5ffffffff5...',
      '...5fkffffkf5...',
      '...ffkffffkfF...',
      '....hffffffh....',
      '...bdddffdddN...',
      '...fbddddddNf...',
      '...FOOOOOOOOF...',
      '....bddddddN....',
      '.....NN..NN.....',
      '.....LL.........',
      '................',
    ],
    up: [
      '................',
      '......aaLL......',
      '....aaaLLLLo....',
      '..aaaLLLLLLLLo..',
      '...oooooooooo...',
      '...5555555555...',
      '...5555555555...',
      '...F55555555F...',
      '....FFFFFFFF....',
      '...bddddddddN...',
      '...fbddddddNf...',
      '...FOOOOOOOOF...',
      '....bddddddN....',
      '.....NN..NN.....',
      '.....LL.........',
      '................',
    ],
    side: [
      '................',
      '.....aaLL.......',
      '...aaaLLLLo.....',
      '.aaaLLLLLLLLLo..',
      '..ooooooooooo...',
      '...5556fffff....',
      '...556Fffkff....',
      '...556Fffkff....',
      '....56ffhff.....',
      '.....bddddN.....',
      '.....bdfddN.....',
      '.....OOOOOO.....',
      '.....bddddN.....',
      '....NN...NN.....',
      '....LL...LL.....',
      '................',
    ],
  },

  'villager-b': {
    down: [
      '................',
      '.....CCcccc.....',
      '....Cccccccb....',
      '...Cccccccccb...',
      '...OObbbbbbOO...',
      '...OOffffffOO...',
      '...Ofkffffkfo...',
      '...ffkffffkfF...',
      '....hffffffh....',
      '...rgpffffpgG...',
      '..frgggppgggGf..',
      '...vvvvvvvvvV...',
      '...rggggggggG...',
      '....rggggggG....',
      '.....ww.........',
      '................',
    ],
    up: [
      '................',
      '.....CCcccc.....',
      '....Cccccccb....',
      '...Cccccccccb...',
      '...cccccccccb...',
      '...OOOOccOOOO...',
      '...OOOOccOOOO...',
      '...FOOOOOOOOF...',
      '....FFFFFFFF....',
      '...rggggggggG...',
      '..frggggggggGf..',
      '...vvvvvvvvvV...',
      '...rggvvvvggG...',
      '....rggggggG....',
      '.....ww.........',
      '................',
    ],
    side: [
      '................',
      '.....CCccc......',
      '....Cccccccb....',
      '...Cccccccccb...',
      '..cbbbbbbbOO....',
      '...OOOOffffff...',
      '...OOOFfffkff...',
      '...OOOFfffkff...',
      '....OOfffhff....',
      '.....rgggpG.....',
      '.....rggfgG.....',
      '....vvvvvvV.....',
      '.....rggggG.....',
      '.....rggggG.....',
      '.....ww..ww.....',
      '................',
    ],
  },

  child: {
    span: [4, 11],
    down: [
      '................',
      '................',
      '........O.......',
      '.....OOOOOO.....',
      '....OOOOOOOO....',
      '....OOffffOO....',
      '....fkffffkf....',
      '....fkffffkf....',
      '....hffffffh....',
      '.....FffffF.....',
      '.....yeppeV.....',
      '....fyeeeeVf....',
      '.....NNNNNN.....',
      '......f..f......',
      '......O.........',
      '................',
    ],
    up: [
      '................',
      '................',
      '........O.......',
      '.....OOOOOO.....',
      '....OOOOOOOO....',
      '....OOOOOOOO....',
      '....OOOOOOOO....',
      '....fOOOOOOf....',
      '.....OOOOOO.....',
      '.....FFFFFF.....',
      '.....yeeeeV.....',
      '....fyeeeeVf....',
      '.....NNNNNN.....',
      '......f..f......',
      '......O.........',
      '................',
    ],
    side: [
      '................',
      '................',
      '.......O........',
      '.....OOOOO......',
      '....OOOOOOO.....',
      '....OOOfffff....',
      '....OOFffkff....',
      '....OOFffkff....',
      '....Offfhff.....',
      '......ffff......',
      '......yeeV......',
      '......yefV......',
      '......NNNN......',
      '.....f...f......',
      '.....O...O......',
      '................',
    ],
  },

  // Animals: slot 1 fur (auto-shaded), 2 belly/muzzle, 3 ear/nose, 4 eyes,
  // 5 tail tip. Built from one quadruped template, varied by tail and ears.
  cat: animal('cat', { 1: 'stone', 2: 'paper', 3: 'sakuraDark', 4: 'gold', 5: 'stone' }),
  dog: animal('dog', { 1: 'woodLight', 2: 'paper', 3: 'ink', 4: 'ink', 5: 'paper' }),
  fox: animal('fox', { 1: 'orange', 2: 'paper', 3: 'crimson', 4: 'ink', 5: 'white' }),
}

type Kind = 'cat' | 'dog' | 'fox'

function put(rows: string[], x: number, y: number, m: string[]) {
  const out = rows.map((r) => r.split(''))
  m.forEach((r, j) => [...r].forEach((ch, i) => ch !== ' ' && out[y + j] && (out[y + j][x + i] = ch)))
  return out.map((r) => r.join(''))
}

function animal(kind: Kind, slots: Slots): CharDef {
  const blank = '................'
  const down = [
    blank,
    blank,
    blank,
    '...1........1...',
    '...13......31...',
    '...1111111111...',
    '..111111111111..',
    '..114k1111k411..',
    '..111223322111..',
    '...1122222211...',
    '....11111111....',
    '....11111111....',
    '.....22..22.....',
    '.....22.........',
    blank,
    blank,
  ]
  const up = [
    blank,
    blank,
    blank,
    '...1........1...',
    '...11......11...',
    '...1111111111...',
    '..111111111111..',
    '..111111111111..',
    '..111111111111..',
    '....11111111....',
    '...1111111111...',
    '...1111111111...',
    '.....11..11.....',
    '.....11.........',
    blank,
    blank,
  ]
  const side = [
    blank,
    blank,
    blank,
    blank,
    '..........1..1..',
    '.........131131.',
    '.........111111.',
    '.........11k111.',
    '.........111223.',
    '...11111111122..',
    '...11111111111..',
    '...11122222211..',
    '...1..1...1..1..',
    '...1..1...1..1..',
    blank,
    blank,
  ]
  let side1 = [...side.slice(0, 12), '....1.1...1.1...', '....1.1...1.1...', blank, blank]
  let d = down
  let u = up
  let sd = side
  if (kind === 'cat') {
    sd = put(sd, 1, 4, ['1 ', '1 ', ' 1', ' 1', ' 1'])
    side1 = put(side1, 1, 3, [' 1', '1 ', '1 ', ' 1', ' 1', ' 1'])
    d = put(d, 13, 8, [' 1', '1 ', '1 '])
    u = put(u, 7, 12, ['11', '11', ' 1'])
  } else if (kind === 'dog') {
    sd = put(sd, 1, 6, [' 111', ' 1 1', '  11'])
    side1 = put(side1, 1, 5, ['  1 ', ' 111', ' 1 1', '  11'])
    sd = put(sd, 9, 8, ['1112223'.slice(0, 6)])
    side1 = put(side1, 9, 8, ['111222'])
    d = put(d, 2, 5, ['  2      2  '])
    d = put(d, 12, 8, [' 11', '1 1', ' 1 '])
    u = put(u, 6, 11, [' 1111 ', ' 1  1 ', '  11  '])
  } else {
    // kitsune: long bushy tail with a white tip, markings under the eyes
    sd = put(sd, 0, 6, ['  11', ' 111', '5111', '511 '])
    side1 = put(side1, 0, 5, [' 5  ', '5111', ' 111', '  11'])
    d = put(d, 2, 8, ['  3      3 '])
    d = put(d, 12, 7, ['  11', ' 111', ' 111', '  15'])
    u = put(u, 9, 10, [' 11', '111', '111', '15 '])
  }
  return { slots, shade: '1', legRows: [12, 13], span: [3, 12], down: d, up: u, side: sd, side1 }
}
