import type { Img, Slots } from '../raster'
import { buildDragon } from './dragon'

export type Anim = 'squash' | 'bob' | 'flicker'

export interface Patch {
  x: number
  y: number
  rows: string[]
  /** Also apply mirrored on the other half (for symmetric sprites). */
  sym?: boolean
}

export interface EnemyDef {
  w?: number
  h?: number
  /** Pixel map; when `sym`, each row is the left half and is mirrored. */
  rows?: string[]
  sym?: boolean
  slots?: Slots
  shade?: string
  patch?: Patch[]
  frame1?: Patch[]
  anim: Anim | Anim[]
  pivot?: number
  /** Procedural base image (used by the dragon). */
  build?: (frame: number) => Img
}


const E16 = '................'
/** Pad a half-map to 32 rows (content placed from `top`). */
function rows32(top: number, body: string[]): string[] {
  const out: string[] = []
  for (let i = 0; i < top; i++) out.push(E16)
  out.push(...body)
  while (out.length < 32) out.push(E16)
  return out.slice(0, 32)
}

const SLIME_BODY = [
  '...............r',
  '..............rr',
  '.............rrr',
  '............rrrr',
  '..........rrrrrr',
  '.........rrrrrrr',
  '........rrrrrrrr',
  '.......rrrrrrrrr',
  '......rrrrrrrrrr',
  '.....rrrrrrrrrrr',
  '.....rrrrrrrrrrr',
  '....rrrrrrrrrrrr',
  '....rrrrkkrrrrrr',
  '...rrrrkkkkrrrrr',
  '...rrrrkkkkrrrrr',
  '...rrrrkkkkrrrrr',
  '..rrrrrrkkrrrrrr',
  '..rrrrrrrrrrrrrr',
  '..rrrrrhrrrrkrrr',
  '.rrrrrrrrrrrrkVV',
  '.rrrrrrrrrrrrrkk',
  '.rrrrrrrrrrrrrrr',
  '.rrrrrrrrrrrrrrr',
  '.rrrrrrrrrrrrrrr',
  '..rrrrrrrrrrrrrr',
  '....rrrrrrrrrrrr',
]

export const ENEMIES: Record<string, EnemyDef> = {
  slime: {
    sym: true,
    shade: 'r',
    anim: 'squash',
    pivot: 28,
    rows: rows32(5, SLIME_BODY),
    patch: [
      { x: 8, y: 18, rows: ['w.'], sym: false },
      { x: 22, y: 18, rows: ['w'] },
      { x: 8, y: 11, rows: ['..R', '.RR', 'Rw.', 'R..'] },
    ],
  },

  'ice-slime': {
    sym: true,
    shade: 'i',
    anim: 'squash',
    pivot: 28,
    rows: rows32(1, [
      '...............C',
      '...............C',
      '..............Ci',
      '..........C...Ci',
      '..........Ci..Ci',
      '.........Cii.Cii',
      '.........Ciiiiii',
      '........iiiiiiii',
      '.......iiiiiiiii',
      '.......iiiiiiiii',
      '......iiiiiiiiii',
      '.....iiiiiiiiiii',
      '.....iiiiiiiiiii',
      '....iiiiiiiiiiii',
      '....iiiNiiiiiiii',
      '....iiiiNNiiiiii',
      '...iiiiNNNNiiiii',
      '...iiiiNNNNiiiii',
      '...iiiiiNNiiiiii',
      '..iiiiiiiiiiiiii',
      '..iiiiiciiiiiiii',
      '..iiiiiiiiiiiiii',
      '.iiiiiiiiiiiiNNN',
      '.iiiiiiiiiiiNiii',
      '.iiiiiiiiiiiiiii',
      '.iiiiiiiiiiiiiii',
      '.iiiiiiiiiiiiiii',
      '..iiiiiiiiiiiiii',
      '....iiiiiiiiiiii',
    ]),
    patch: [
      { x: 8, y: 17, rows: ['w'] },
      { x: 22, y: 17, rows: ['w'] },
      { x: 9, y: 11, rows: ['.w', 'ww', 'w.'] },
      { x: 4, y: 26, rows: ['w'] },
    ],
  },

  imp: {
    sym: true,
    shade: 'up',
    anim: 'bob',
    rows: rows32(2, [
      '........p.......',
      '........pp......',
      '.........pp.....',
      '.........ppuuuuu',
      '..d.......puuuuu',
      '..dd.....uuuuuuu',
      '..dNd...uuuuuuuu',
      '.dNNNd..unuuuuuu',
      '.dNNNNduuunnuuuu',
      '.dNNNNNuullkuuuu',
      '.dNNNNNuulllUuuu',
      '.dNNNNNNuuuuuuuu',
      '.dNN.NNNuuukkkkk',
      '..N..N.N.uukwVVV',
      '.....N....uukkkk',
      '...........uuuuu',
      '............uuuu',
      '..........uuuUUU',
      '.........uu.uuUU',
      '........uu..uuUU',
      '........pp..uuUU',
      '............uuUU',
      '............uuu.',
      '...........uuu..',
      '...........uu...',
      '...........uu...',
      '..........ppp...',
    ]),
    patch: [{ x: 19, y: 20, rows: ['...uu', '....u', '....u', '...uV', '..VVV', '...V.'] }],
    frame1: [
      { x: 1, y: 6, rows: ['_d.', 'dd.', 'dNd'], sym: true },
      { x: 1, y: 16, rows: ['..N..N.', '.......'], sym: true },
    ],
  },

  bat: {
    sym: true,
    shade: 'du',
    anim: 'bob',
    rows: rows32(4, [
      '...........d....',
      '...........dd...',
      '..........dhd...',
      '..........dddd..',
      '..n.......dddddd',
      '..nn.....ddddddd',
      '..nun....ddddddd',
      '.nuuun..dddldddd',
      '.nuuuun.ddllkddd',
      '.nuuuuunddddddkk',
      'nuuuuuuunddddkwk',
      'nuuuuuuuuuddddkk',
      'nuuunuuuunuddddd',
      '.nun.nuun.nudddd',
      '.n...n.n...udddd',
      '.......n....dddd',
      '............dd.d',
      '............y..y',
    ]),
    frame1: [
      {
        x: 0,
        y: 8,
        rows: [
          '_______........',
          '_______........',
          '_______........',
          '________.......',
          '________.......',
          '.nnn_____......',
          'nuuun____......',
          'nuuuunnnn......',
          'nuuuuuuuun.....',
          '.nuuuuuuun.....',
          '..nuuunuuu.....',
          '...n..nun......',
          '........n......',
        ],
        sym: true,
      },
    ],
  },

  mushroom: {
    sym: true,
    shade: 'vp',
    anim: 'squash',
    pivot: 27,
    rows: rows32(3, [
      '..........vvvvpp',
      '.......vvvvvvvpp',
      '.....vvvvpppvvvv',
      '....vvvvpppppvvv',
      '...vvvvvvpppvvvv',
      '..vvvvvvvvvvvvvv',
      '..vvppvvvvvvvvvv',
      '.vvvppvvvvvvvvvv',
      '.vvvvvvvvvvvvvvv',
      '.vvvvvvvvvvvvvvv',
      '..VVVVVVVVVVVVVV',
      '....PaPaPaPaPaPa',
      '..........pppppp',
      '.........ppppppp',
      '.........ppkpppp',
      '.........ppkpppp',
      '.........phppppk',
      '.......pp.pppppp',
      '.......pp.pppppp',
      '..........pppppp',
      '..........pppppp',
      '..........pppppp',
      '.........oooo...',
      '........ooooo...',
    ]),
  },

  kappa: {
    sym: true,
    shade: 'ga',
    anim: 'squash',
    pivot: 26,
    rows: rows32(2, [
      '...........mmmmm',
      '.........mmccccc',
      '........GGmmmmmm',
      '.......GGGGGGGGG',
      '......GGgGGgGGgG',
      '......gggggggggg',
      '.....ggwwwwggggg',
      '.....gwwwkkggggg',
      '.....gwwwkkggggg',
      '.....ggwwwwggyyy',
      '......ggggggyyyy',
      '......gggggggeee',
      '.......ggggggggg',
      '.........ggggggg',
      '.....oo..ggggggg',
      '....ooogggggaaaa',
      '....oogggggaaaaa',
      '....ogggg.gaLLLL',
      '....oggg..gaaaaa',
      '....oggg..gaLLLL',
      '...gGgG...gaaaaa',
      '...g.g....ggaaaa',
      '..........gggggg',
      '..........ggg...',
      '..........ggg...',
      '.........gGgG...',
      '........gGgGg...',
    ]),
    patch: [{ x: 13, y: 3, rows: ['.C'] }],
  },

  tanuki: {
    sym: true,
    shade: 'oa',
    anim: 'squash',
    pivot: 27,
    rows: rows32(3, [
      '........oo......',
      '........oOoo....',
      '........oOoooooo',
      '.......ooooooooo',
      '......oooooooooo',
      '......oooooooooo',
      '.....oOOOOOooooo',
      '.....OOOkwOOpppp',
      '.....OOOkkOppppk',
      '.....oOOOOpppppp',
      '......ooooppppkp',
      '.......ooooppppk',
      '........oooooooo',
      '.......ooooooooo',
      '......oooooaaaaa',
      '.....ooooaaaaaaa',
      '....oooo.aaaaaaa',
      '...ooooOaaaaaaaa',
      '...OOOo.aaaaaaaa',
      '.....oooaaaaaaaa',
      '.....oooaaaaaaaa',
      '.....ooooaaaaaaa',
      '......oooooaaaaa',
      '.......ooooooooo',
      '.......OOOO.....',
      '......OOOOO.....',
    ]),
    patch: [
      { x: 13, y: 0, rows: ['..rr..', '.rRrr.', 'rrgrrr', '.rrg..', '...g..'] },
      { x: 24, y: 17, rows: ['..ooo.', '.ooooo', 'oOOOoo', 'ooooOo', 'oOOOoo', 'oooooo', '.OOOoo', '.ooooo', '..ooo.'] },
    ],
  },

  golem: {
    sym: true,
    shade: 's',
    anim: ['squash', 'flicker'],
    pivot: 24,
    rows: rows32(2, [
      '...........gggss',
      '..........ssssss',
      '..........ssSSss',
      '..........ssllss',
      '..........ssssss',
      '..........sssSSS',
      '...ggsss...sssss',
      '..gggsssssssssss',
      '.sssssssssssssss',
      '.sssssSsssssssss',
      '.ssssss.sssssssj',
      '.ssssss.sssssjjj',
      '.sSssss.sssssssj',
      '.ssssss.sssssssj',
      '.ssssss.ssssjjjj',
      '.ssSsss.ssssssss',
      '.ssssss..sssssss',
      '.ssssss..sssssss',
      '.sssssss.sssssss',
      '.sssssss.sssssss',
      '.sSsssss..ssssss',
      '..ssssS...ssssss',
      '.........sssss..',
      '.........sssss..',
      '.........sssss..',
      '........ssssss..',
      '........ssssss..',
    ]),
  },

  wisp: {
    sym: true,
    shade: 'c',
    anim: 'bob',
    rows: rows32(3, [
      '...............c',
      '...............c',
      '..........c...cc',
      '..........cc.cci',
      '.........ccccci.',
      '........cccccici',
      '.......ccccciiii',
      '......cccccciiii',
      '......ccccciiiii',
      '.....cccccciiiii',
      '.....ccccciiiiii',
      '.....cccciNNiiii',
      '.....cccciNNiiii',
      '.....cccciiiiiiC',
      '.....ccccciiiiCw',
      '......ccccciiCww',
      '......ccccccCCCw',
      '.......ccccccccc',
      '........cccccccc',
      '..........cccccc',
      '............cccc',
    ]),
    patch: [
      { x: 10, y: 14, rows: ['w'] },
      { x: 20, y: 23, rows: ['cc...', '.ccc.', '..cc.', '...c.', '..c..'] },
      { x: 9, y: 11, rows: ['.w', 'w.'] },
    ],
    frame1: [
      { x: 9, y: 3, rows: ['.c....c.', 'cc...cc.', 'c...c...'], sym: true },
      { x: 20, y: 23, rows: ['_c...', '..cc.', '...cc', '...c.', '...c.'] },
    ],
  },

  kitsune: {
    sym: true,
    shade: 'yp',
    anim: 'squash',
    pivot: 25,
    rows: rows32(1, [
      '................',
      '................',
      '.....pp....y....',
      '....pppp...yy...',
      '....pppp...yvy..',
      '....yyyy...yvvyy',
      '...yyyye..yyyyyy',
      '...yyyye..yyyyyy',
      '...yyyye.yyyyyyy',
      '.pp.yyyye.yvvyyy',
      'ppp.yyyye.ykkyyy',
      'pppy.yyyye.yyppp',
      '.yyy.yyyye.ypppk',
      '.yyyy.yyyye.pppp',
      '..yyy.yyyyy.yppp',
      '..yyyy.yyyyyyppp',
      '...yyyy.yyyyyppp',
      '....yyyy.yyyyppp',
      '.....yyyyyyyyypp',
      '......yyyyyyyypp',
      '........yyyyyyyp',
      '.........yyyyyyy',
      '..........yyyyyy',
      '..........yyyyyy',
      '..........yyy..y',
      '..........yyy...',
      '.........ppp....',
      '.........ppp....',
    ]),
    patch: [
      { x: 1, y: 24, rows: ['.c.', 'cic', 'iwi', 'cic', '.c.'] },
      { x: 28, y: 22, rows: ['.c.', 'cic', 'iwi', 'cic', '.c.'] },
    ],
    frame1: [
      { x: 1, y: 24, rows: ['.c.', 'cwc', 'cic', '.c.', '...'] },
      { x: 28, y: 22, rows: ['...', '.c.', 'cwc', 'cic', '.c.'] },
    ],
  },

  harpy: {
    sym: true,
    shade: 'ufV',
    anim: 'bob',
    rows: rows32(2, [
      '...........VVVVV',
      '.........VVVVVVV',
      '.u......VVVVVVVV',
      '.uu.....VVffffff',
      '.uUu...VVfffffff',
      '.uUuu..VVffkffff',
      '.uUuuu.VVffkffff',
      '.uUuuuuVVfhfffff',
      '.uUuuuuuVVffffff',
      '.uuuuuuuuVVfffff',
      '.uuuuuuuuuuVffff',
      '.uuuuuuuuuuuuuuu',
      '..uu.uuuuuuuuuuu',
      '..u..uu.uuuuuuuu',
      '.....u..uuuuuuuu',
      '........uuuuUUUU',
      '.........uuuUUUU',
      '.........uuuuUUU',
      '..........uuuuuu',
      '..........uuuuuu',
      '...........uuuuu',
      '...........uu.uu',
      '...........yy...',
      '...........yy...',
      '..........y.y.y.',
      '..........y.y.y.',
    ]),
    frame1: [
      {
        x: 0,
        y: 4,
        rows: [
          '________',
          '________',
          '________',
          '________',
          '________',
          '_______.',
          '_______.',
          '_______.',
          '........',
          '........',
          '........',
          '........',
          'uuuu.uuu',
          'uUuu.uuu',
          '.uuu.u..',
          '.u...u..',
          '........',
        ],
        sym: true,
      },
    ],
  },

  treant: {
    sym: true,
    shade: 'ro',
    anim: 'squash',
    pivot: 21,
    rows: rows32(1, [
      '..........rrrrrr',
      '......rrr.rrrrrr',
      '....rrrrrrrrrrrr',
      '...rrrrrrrrgrrrr',
      '..rrrrrrggrrrrrr',
      '.rrrrrrrrrrrrrrr',
      '.rrrrgggrrrrrrrr',
      '.rrrrrrrrrrrggrr',
      '.rrrrrrrrrrrrrrr',
      '..rrrgrrrrrrrrrr',
      '...rrrr.rrrroooo',
      '....rr.....ooooo',
      '.oo........ooooo',
      '..oo......oooooo',
      '...ooo...ooooooo',
      '.....ooooooOOOoo',
      '.......oooOlOooo',
      '........oooooooo',
      '........oooOOOOO',
      '........ooOkkkkk',
      '........oooOOOOO',
      '........oooooOoo',
      '.......ooOooooOo',
      '......oooooooooo',
      '.....oooOoooooOo',
      '....ooo.oooooooo',
      '...ooo..ooo..ooo',
      '..ooo..ooo...ooo',
      '.ooo...oo.....oo',
    ]),
    patch: [{ x: 1, y: 11, rows: ['rr', 'rR'] }, { x: 29, y: 11, rows: ['rr', 'rR'] }],
  },

  tengu: {
    sym: true,
    shade: 'vpd',
    anim: 'bob',
    rows: rows32(2, [
      '..............nn',
      '.............nnn',
      '..d......mmvvvvv',
      '..dd....mmvvvvvv',
      '.dddd..mmvvvvvvv',
      '.ddddd.mvwwvvvvv',
      '.dddddmmvvvwwvve',
      '.ddddddmvvlkvvve',
      '.ddddddmvvvvvvve',
      '.ddddddmvvvvvvve',
      '.ddddddmppvvvvve',
      '.dddddd.pppvvvve',
      '..ddddd.pppppppe',
      '..ddddd..ppppppe',
      '..dddd....pppppe',
      '..dddd.pppppppp.',
      '..ddd.ppppVVpppp',
      '..ddd.pppppVVppp',
      '...dd.pppppppVVp',
      '...d..ppppppppVV',
      '......vv.ppppppp',
      '.........ppppppp',
      '.........NNNNNNN',
      '.........NNN..NN',
      '.........NNN....',
      '.........NNN....',
      '........oooo....',
      '..........o.....',
    ]),
    patch: [
      { x: 16, y: 9, rows: ['V'] },
      { x: 16, y: 10, rows: ['V'] },
      { x: 16, y: 11, rows: ['V'] },
      { x: 16, y: 12, rows: ['V'] },
      { x: 16, y: 13, rows: ['V'] },
      { x: 16, y: 14, rows: ['V'] },
      { x: 15, y: 15, rows: ['eV'] },
      { x: 15, y: 16, rows: ['ee'] },
      { x: 24, y: 12, rows: ['..rrr.', '.rrRrr', 'rrrgrr', 'rrgrrr', '.rgrr.', '..oo..', '..o...', '.vv...'] },
    ],
  },

  oni: {
    sym: true,
    shade: 'vyp',
    anim: 'squash',
    pivot: 24,
    rows: rows32(1, [
      '.....p..........',
      '.....pp....n..n.',
      '......pp..nnn.nn',
      '.......ppnnnnnnn',
      '......nnnpnnnnnn',
      '......nnvvvvvvvv',
      '......nvvvvvvvvv',
      '......nvnnvvvvvv',
      '......nvvvnnvvvv',
      '......nvvllkvvvv',
      '......nvvlllvvvv',
      '......nvvwvvvvvV',
      '......nvvwkkkkkk',
      '......nvvvkkkkkk',
      '.......vvvvvvvvv',
      '....vvvvvvvvvvvv',
      '...vvvvvvvvvvvvv',
      '..vvvvvvvvvvvvvv',
      '..vvvvv.vvvvvvvv',
      '.vvvvv..vvvvvvvv',
      '.vvvvv..vvvvVvvv',
      '.vvvv...yykyykyy',
      '.vvvv...ykyykyyk',
      '.vvvv...yykyykyy',
      '.vvvv....ykyykyy',
      '.........vvvv...',
      '.........vvvv...',
      '........vvvvv...',
      '........VVVVV...',
    ]),
    patch: [
      { x: 11, y: 14, rows: ['w.w.w'] },
      { x: 17, y: 14, rows: ['w.w.w'.split('').reverse().join('')] },
      {
        x: 26,
        y: 2,
        rows: [
          '.mm.',
          'mSSm',
          'SmSS',
          'SSmS',
          'mSSS',
          'SSmS',
          'SmSS',
          'SSSm',
          'mSSS',
          'SSmS',
          'SSSS',
          '.SS.',
          '.oo.',
          '.oo.',
          'vOOv',
          'vvvv',
          '.oo.',
          '.oo.',
        ],
      },
    ],
  },

  skeleton: {
    sym: true,
    shade: 'pV',
    anim: 'bob',
    rows: rows32(1, [
      '.....y..........',
      '.....yy.........',
      '......yy........',
      '.......yyyyyyyyy',
      '........NNNNNNNN',
      '.......NNdNNdNNN',
      '......NNNNNNNNNN',
      '....VVNNNNNNNNNN',
      '....VVVNpppppppp',
      '.....VVppppppppp',
      '.....VVpkkkppppp',
      '......Vpkxkppppk',
      '......Vpkkkppppp',
      '.......ppppppppp',
      '.......pkpkpkpkp',
      '........pppppppp',
      '...VVVVV..pppppp',
      '...VVVVVVVVVVVVV',
      '...yyyyyVVVVVVVV',
      '...VVVVVVyyyyyyy',
      '...yyyyyVVVVVVVV',
      '...VVVVVVVVVVVVV',
      '....pp..yyyyyyyy',
      '....pp..VVVVVVVV',
      '....pp..VVyVVyVV',
      '...ppp..VVyVVyVV',
      '.........ppp....',
      '.........pp.....',
      '.........pp.....',
      '........NNN.....',
    ]),
    patch: [
      {
        x: 26,
        y: 3,
        rows: ['..w', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', '.wm', 'yyyy', '.n.', '.n.', '.n.', '.p.'].map((r) => r.padEnd(4, '.')),
      },
    ],
    frame1: [{ x: 9, y: 11, rows: ['x'] }, { x: 22, y: 11, rows: ['x'] }],
  },

  dragon: {
    w: 64,
    h: 64,
    anim: [],
    build: (f) => buildDragon(f),
  },
}
