/** 16×16 item & UI icons (flat colours, auto-shaded and outlined). */
import type { Slots } from '../raster'

export interface IconDef {
  rows: string[]
  slots?: Slots
  shade?: string
}

const HEART = (c: string, hi: string) => [
  '................',
  '................',
  '................',
  '...cccc..cccc...',
  '..cccccccccccc..',
  '.cchhcccccccccc.',
  '.chhccccccccccc.',
  '.cccccccccccccc.',
  '.cccccccccccccc.',
  '..cccccccccccc..',
  '...cccccccccc...',
  '....cccccccc....',
  '.....cccccc.....',
  '......cccc......',
  '.......cc.......',
  '................',
].map((r) => r.replace(/c/g, c).replace(/h/g, hi))

const STAR = (c: string, hi: string) => [
  '................',
  '.......cc.......',
  '.......cc.......',
  '......cccc......',
  '......chcc......',
  '.ccccchcccccccc.',
  '.cccchcccccccc..',
  '..cccccccccccc..',
  '...cccccccccc...',
  '....cccccccc....',
  '....cccccccc....',
  '...ccccc.cccc...',
  '...cccc...ccc...',
  '..ccc......ccc..',
  '..cc........cc..',
  '................',
].map((r) => r.replace(/c/g, c).replace(/h/g, hi))

export const ICONS: Record<string, IconDef> = {
  herb: {
    shade: 'r',
    rows: [
      '................',
      '..........rr....',
      '.........rrrr...',
      '........rrrRr...',
      '..rr....rrRrr...',
      '.rrrr..rrRrr....',
      '.rrRrr.rRrr.....',
      '..rrRrrgrr......',
      '...rrrgr........',
      '......g.rrr.....',
      '.....g.rrRrr....',
      '....g.rrRrrr....',
      '...g...rrrr.....',
      '..g.............',
      '..g.............',
      '................',
    ],
  },
  ether: {
    shade: 'bL',
    rows: [
      '................',
      '......LLL.......',
      '......oLo.......',
      '......mpm.......',
      '......mpm.......',
      '.....mpppm......',
      '....mbbbbbm.....',
      '...mbbCbbbbm....',
      '...mbCbbbbbm....',
      '...mbbbbbbbm....',
      '...mbbbbbbbm....',
      '...mbbbbbbbm....',
      '....mbbbbbm.....',
      '.....mmmmm......',
      '................',
      '................',
    ],
  },
  smoke: {
    shade: 'sm',
    rows: [
      '................',
      '..........mm....',
      '.........mmmm...',
      '..........mm.l..',
      '.........e..l...',
      '........e.......',
      '.....ssse.......',
      '...sssssss......',
      '..sssmssssss....',
      '..ssmsssssss....',
      '.ssssssssssss...',
      '.ssssssssssss...',
      '.ssssssssssss...',
      '..ssssssssss....',
      '...ssssssss.....',
      '................',
    ],
  },
  charm: {
    shade: 'v',
    rows: [
      '................',
      '.......yy.......',
      '......y..y......',
      '......y..y......',
      '....vvvyyvvv....',
      '....vvvvvvvv....',
      '....vvyyyyvv....',
      '....vvyvvyvv....',
      '....vvyyyyvv....',
      '....vvvvvvvv....',
      '....vvvvvvvv....',
      '....vvyvvyvv....',
      '....vvvyyvvv....',
      '....vvvvvvvv....',
      '.....vvvvvv.....',
      '................',
    ],
  },
  scroll: {
    shade: 'p',
    rows: [
      '................',
      '................',
      '..oo........oo..',
      '.oLOppppppppOOo.',
      '..LOppppppppOO..',
      '..LOpkkppkkpOO..',
      '..LOppppppppOO..',
      '..LOpkpkkkppOO..',
      '..LOppppppppOO..',
      '..LOpkkkpkppOO..',
      '..LOppppppppOO..',
      '..LOppppppppOO..',
      '.oLOppppppppOOo.',
      '..oo........oo..',
      '................',
      '................',
    ],
  },
  key: {
    shade: 'y',
    rows: [
      '................',
      '................',
      '....yyyy........',
      '...yyyyyy.......',
      '..yyy..yyy......',
      '..yy....yy......',
      '..yyy..yyy......',
      '...yyyyyyy......',
      '....yyyyyyy.....',
      '.........yyy....',
      '..........yyy...',
      '.........yyyyy..',
      '..........yy.y..',
      '...........y....',
      '................',
      '................',
    ],
  },
  shard: {
    shade: 'uU',
    rows: [
      '................',
      '.......U........',
      '......UUu.......',
      '......UwUu......',
      '.....UUwUuu.....',
      '.....UUwUuu.....',
      '....UUUwUuuu....',
      '....UUUUUuuu....',
      '....UUUUUuuu....',
      '....UUUUUuuu....',
      '.....UUUUuu.....',
      '.....UUUUuu.....',
      '......UUuu......',
      '......UUu.......',
      '.......U........',
      '................',
    ],
  },
  heart: { shade: 'v', rows: HEART('v', 'p') },
  'heart-empty': { shade: 'N', rows: HEART('N', 'd') },
  star: { shade: 'y', rows: STAR('y', 'l') },
  'star-empty': { shade: 'N', rows: STAR('N', 'd') },
  lock: {
    shade: 'ys',
    rows: [
      '................',
      '.....ssssss.....',
      '....ss....ss....',
      '....s......s....',
      '....s......s....',
      '....s......s....',
      '..yyyyyyyyyyyy..',
      '..yyyyyyyyyyyy..',
      '..yyyyykkyyyyy..',
      '..yyyyykkyyyyy..',
      '..yyyyyykyyyyy..',
      '..yyyyyykyyyyy..',
      '..yyyyyyyyyyyy..',
      '..yyyyyyyyyyyy..',
      '................',
      '................',
    ],
  },
  sword: {
    shade: 'm',
    rows: [
      '................',
      '............wm..',
      '...........wmm..',
      '..........wmm...',
      '.........wmm....',
      '........wmm.....',
      '.......wmm......',
      '......wmm.......',
      '..y..wmm........',
      '...ywmm.........',
      '....ym..........',
      '...nny..........',
      '..nn..y.........',
      '.nn.............',
      '.y..............',
      '................',
    ],
  },
  staff: {
    shade: 'oU',
    rows: [
      '................',
      '...........UU...',
      '..........UwUU..',
      '..........UUUU..',
      '.........oUUU...',
      '........o.o.....',
      '.......oo.......',
      '......oo........',
      '.....oo.........',
      '....oo..........',
      '...oo...........',
      '..oo............',
      '.oo.............',
      '................',
      '................',
      '................',
    ],
  },
  book: {
    shade: 'V',
    rows: [
      '................',
      '................',
      '...VVVVVVVVVV...',
      '..VVVVVVVVVVVp..',
      '..VVyyyyyyVVVp..',
      '..VVyVVVVyVVVp..',
      '..VVyyyyyyVVVp..',
      '..VVVVVVVVVVVp..',
      '..VVVVyyVVVVVp..',
      '..VVVyVVyVVVVp..',
      '..VVVVyyVVVVVp..',
      '..VVVVVVVVVVVp..',
      '..VVVVVVVVVVPp..',
      '...ppppppppppp..',
      '................',
      '................',
    ],
  },
  chest: {
    shade: 'oy',
    rows: [
      '................',
      '................',
      '................',
      '....oooooooo....',
      '..oooooooooooo..',
      '.yooooooooooooy.',
      '.yooooooooooooy.',
      '.yyyyyyyyyyyyyy.',
      '.yoooookkoooooy.',
      '.yoooooyyoooooy.',
      '.yooooooooooooy.',
      '.yooooooooooooy.',
      '.yyyyyyyyyyyyyy.',
      '................',
      '................',
      '................',
    ],
  },
  'chest-open': {
    shade: 'oy',
    rows: [
      '................',
      '..oooooooooooo..',
      '.yooooooooooooy.',
      '.yooooooooooooy.',
      '.yyyyyyyyyyyyyy.',
      '.yOOOlyOlOOOOOy.',
      '.yOOlyyylOOOOOy.',
      '.yyyyyyyyyyyyyy.',
      '.yooooooooooooy.',
      '.yooooooooooooy.',
      '.yooooooooooooy.',
      '.yooooooooooooy.',
      '.yyyyyyyyyyyyyy.',
      '................',
      '................',
      '................',
    ],
  },
  exclaim: {
    shade: 'y',
    rows: [
      '................',
      '......yyyy......',
      '......yyyy......',
      '......yyyy......',
      '......yyyy......',
      '......yyyy......',
      '.......yy.......',
      '.......yy.......',
      '.......yy.......',
      '................',
      '......yyyy......',
      '......yyyy......',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  question: {
    shade: 'p',
    rows: [
      '................',
      '.....pppppp.....',
      '....pppppppp....',
      '....ppp..ppp....',
      '.........ppp....',
      '........ppp.....',
      '.......ppp......',
      '.......pp.......',
      '.......pp.......',
      '................',
      '.......pp.......',
      '.......pp.......',
      '................',
      '................',
      '................',
      '................',
    ],
  },
}
